### ISSUE TITLE
Invalid json in e??j

### ISSUE THREAD

**Issue by quim0** [radare/radare2#10003]
### Work environment

```
$ r2 -v
radare2 2.6.0-git 18056 @ darwin-x86-64 git.2.5.0-166-g78ce646cf
commit: 78ce646cf6186410b9d6750e7861dfd9dd004e07 build: 2018-05-02__20:38:37
```

### Expected behavior
Be able to parse the json output.

### Actual behavior
Raises an invalid \escape exception.

### Steps to reproduce the behavior
```
>>> import r2pipe
>>> r = r2pipe.open('-')
>>> r.cmdj('e??j')
r2pipe.cmdj.Error: Invalid \escape: line 1 column 10502 (char 10501)
>>> import re; re.findall('\\\\x[a-zA-Z0-9]{2}', r.cmd('e??j'))
['\\xd0', '\\xd9', '\\x94', '\\x7f', '\\x7f']
```

As you can see there're some `\\xff`  scape characters, and according to [this](https://stackoverflow.com/a/4296045) it must be `\u00ff` if we want the unicode character, or `\\\\xff` if we want the `\\xff`.

```
>>> json.loads('{"a": "\\x27"}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 8 (char 7)
>>> json.loads('{"a": "\\u0027"}')
{'a': "'"}
>>> json.loads('{"a": "\\\\x27"}')
{'a': '\\x27'}
```

**Comment by quim0** [comment]
Problem seems to be here:
https://github.com/radare/radare2/blob/0036b2cae832696793593117c0724d277a459174/libr/util/str.c#L1106
But this function is used in other places, so idk how to approach this, as it may break other stuff.
