### ISSUE TITLE
r2pm install of r2frida failure

### ISSUE THREAD

**Issue by cryptax** [radare/radare2#10627]
Hi,
Not entirely sure whether I should report this to frida or to radare2 ;) But I wasn't able to install the r2frida plugin on my OS.

This is what `r2pm -i r2frida` reports:

Thanks!

```
make io_frida.so
make[1]: Entering directory '/home/axelle/.local/share/radare2/r2pm/git/r2frida'
npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 

> r2frida-agent@2.6.0 prepublish /home/axelle/.local/share/radare2/r2pm/git/r2frida
> npm run build


> r2frida-agent@2.6.0 build /home/axelle/.local/share/radare2/r2pm/git/r2frida
> frida-compile src/agent -o src/_agent.js

/home/axelle/.local/share/radare2/r2pm/git/r2frida/node_modules/frida-compile/index.js:113
    updateWatchedFiles(new Set([...watched, ...files]));
                                ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/axelle/.local/share/radare2/r2pm/git/r2frida/node_modules/frida-compile/bin/compile.js:5:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-122-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! r2frida-agent@2.6.0 build: `frida-compile src/agent -o src/_agent.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the r2frida-agent@2.6.0 build script 'frida-compile src/agent -o src/_agent.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the r2frida-agent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     frida-compile src/agent -o src/_agent.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs r2frida-agent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls r2frida-agent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/axelle/.local/share/radare2/r2pm/git/r2frida/npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm ERR! Linux 4.4.0-122-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! r2frida-agent@2.6.0 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the r2frida-agent@2.6.0 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the r2frida-agent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs r2frida-agent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls r2frida-agent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/axelle/.local/share/radare2/r2pm/git/r2frida/npm-debug.log
Makefile:144: recipe for target 'node_modules' failed
make[1]: *** [node_modules] Error 1
make[1]: Leaving directory '/home/axelle/.local/share/radare2/r2pm/git/r2frida'
Makefile:96: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: Build failed
```

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux Mint 18.3 x86 64 (NB. this distro also relies on Ubuntu xenial)
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18693 @ linux-x86-64 git.2.6.9-31-ga566e7a commit: a566e7af99c4b5a0833615f16f0841aab2a342bb build: 2018-07-05__09:05:15 |

### Expected behavior

Install r2frida plugin

### Actual behavior

Failed to install plugin

### Steps to reproduce the behavior 

1. Update r2
2. r2pm init
3. r2pm -i r2frida

**Comment by radare** [comment]
Node4 is not even LTS. You may upgrade it :)

**Comment by cryptax** [comment]
That solves it indeed. Thanks. :+1:
