### ISSUE TITLE
Arrow keys segfault

### ISSUE THREAD

**Issue by 0xAC44** [radare/radare2#10831]
OS: antergos, 64 bit
Just built r2 from git and installed it in my home.

```
radare2 2.8.0-git 1 @ linux-x86-64 git.2.8.0-git
commit: 3e55b5f57d3d8eb2c38e681f125e7b9517191fde build: 2018-07-27__15:30:14
```

https://asciinema.org/a/RArS1ijt5Ul0Vzo7gPYdNJJGE

Just opening /bin/ls and then pressing up makes r2 segfault.
It seems r2 is segfaulting at dietline.c:256 with line->sdbshell_hist being null. That's as far as I've got.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007f56f7185749 in r_line_set_hist_callback (line=0x7f56f73989a0 <r_line_instance>, up=0x7f56f718575e <cmd_history_up>, down=0x7f56f7185868 <cmd_history_down>)
    at dietline.c:256
256		line->sdbshell_hist_iter = r_list_head (line->sdbshell_hist);
(gdb) bt
#0  0x00007f56f7185749 in r_line_set_hist_callback (line=0x7f56f73989a0 <r_line_instance>, up=0x7f56f718575e <cmd_history_up>, down=0x7f56f7185868 <cmd_history_down>)
    at dietline.c:256
#1  0x00007f56f7185b8f in r_line_hist_up () at dietline.c:329
#2  0x00007f56f71871dd in r_line_readline_cb (cb=0x0, user=0x0) at dietline.c:1283
#3  0x00007f56f71866a3 in r_line_readline () at dietline.c:563
#4  0x00007f56f785348f in r_core_fgets (buf=0x7ffc38f8e870 "", len=4096) at core.c:1593
#5  0x00007f56f7189c09 in r_cons_fgets (buf=0x7ffc38f8e870 "", len=4096, argc=0, argv=0x0) at input.c:226
#6  0x00007f56f7856e6b in r_core_prompt (r=0x55ec601f7580 <r>, sync=0) at core.c:2433
#7  0x000055ec5fff4573 in main (argc=2, argv=0x7ffc38f8fc78, envp=0x7ffc38f8fc90) at radare2.c:1370
```

**Comment by cyanpencil** [comment]
@0xAC44 thank you for the report.

I believe this was fixed by https://github.com/radare/radare2/pull/10829.

Please update to the latest git master (it was merged a few hours ago) and tell us if you still get the problem.

**Comment by 0xAC44** [comment]
Yes, latest master works for me.
