### ISSUE TITLE
segfault problems in latest git version

### ISSUE THREAD

**Issue by jstucke** [radare/radare2#10855]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux Mint 19 Tara, x86_64
| File format of the file you reverse (mandatory)      | ELF 64-bit LSB executable
| Architecture/bits of the file (mandatory)            | x86-64, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18955 @ linux-x86-64 git.2.7.0-176-gd98c5b908 commit: d98c5b908078bccd59005e2f1be4532d940d5079 build: 2018-07-30__09:22:14

### Problem Description
Since updating to the newest version, running analyses (`aaa`) on certain files produces a segfault (on most files it still runs fine; the problems seem to be limited to x64 files):
```bash
[0x00402700]> aaa
[ WARNING : block size exceeding max block size at 0x00411e87
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x00412c8a
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0041341e
[+] Try changing it with e anal.bb.maxsize
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[fish: “r2 dropbear_x86_64-linux-gnu_gc…” terminated by signal SIGSEGV (Address boundary error)
```

This does not happen in the previously used version (radare2 2.8.0-git 18738 @ linux-x86-64 git.2.7.0-62-g9e4039ccc commit: 9e4039ccc320c612a56a5c42f30ee862995e39c0 build: 2018-07-17__09:18:15 (the block size warnings also occur though))

#### gdb Trace

```bash
(gdb) run
Starting program: /usr/bin/r2 -c aaaa dropbear_x86_64_-O0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[ WARNING : block size exceeding max block size at 0x00411e87
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x00412c8a
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0041341e
[+] Try changing it with e anal.bb.maxsize
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[ ] Type matching analysis for all functions (afta)
Program received signal SIGSEGV, Segmentation fault.
__strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120	../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x00007ffff3e17de9 in sdb_array_contains (s=0x5555606f0470, 
    key=0x7ffff406d380 <Key.4289+3840> "27584.reg.write", val=0x0, cas=0x0) at array.c:505
#2  0x00007ffff7b57bec in type_pos_hit (anal=0x5555557ea140, trace=0x5555606f0470, in_stack=false, 
    idx=27584, size=88, place=0x0) at anal_tp.c:49
#3  0x00007ffff7b5897e in type_match (core=0x55555575e1c0 <r>, addr=4304454, 
    fcn_name=0x555560d48010 "fprintf", baddr=4304368, cc=0x5555557da510 "amd64", prev_idx=27564, 
    userfnc=false, caddr=4203344) at anal_tp.c:265
#4  0x00007ffff7b595cb in r_core_anal_type_match (core=0x55555575e1c0 <r>, fcn=0x5555576d2d40)
    at anal_tp.c:433
#5  0x00007ffff7a6caea in type_cmd (core=0x55555575e1c0 <r>, input=0x555559d85213 "a") at cmd_anal.c:685
#6  0x00007ffff7a7320b in cmd_anal_fcn (core=0x55555575e1c0 <r>, input=0x555559d85211 "fta")
    at cmd_anal.c:2330
#7  0x00007ffff7a84f99 in cmd_anal (data=0x55555575e1c0 <r>, input=0x555559d85211 "fta")
    at cmd_anal.c:7102
#8  0x00007ffff7b1348c in r_cmd_call (cmd=0x55555585de50, input=0x555559d85210 "afta") at cmd_api.c:237
#9  0x00007ffff7ac976f in r_core_cmd_subst_i (core=0x55555575e1c0 <r>, cmd=0x555559d85210 "afta", 
    colon=0x0, tmpseek=0x7fffffffd2b6) at cmd.c:2911
#10 0x00007ffff7ac62d0 in r_core_cmd_subst (core=0x55555575e1c0 <r>, cmd=0x555559d85210 "afta")
    at cmd.c:1940
#11 0x00007ffff7acbeca in r_core_cmd (core=0x55555575e1c0 <r>, cstr=0x7ffff7b78a57 "afta", log=0)
    at cmd.c:3615
#12 0x00007ffff7acc61f in r_core_cmd0 (user=0x55555575e1c0 <r>, cmd=0x7ffff7b78a57 "afta") at cmd.c:3779
#13 0x00007ffff7a84041 in cmd_anal_all (core=0x55555575e1c0 <r>, input=0x555555c8c1a2 "aa")
    at cmd_anal.c:6831
#14 0x00007ffff7a85113 in cmd_anal (data=0x55555575e1c0 <r>, input=0x555555c8c1a1 "aaa")
    at cmd_anal.c:7150
#15 0x00007ffff7b1348c in r_cmd_call (cmd=0x55555585de50, input=0x555555c8c1a0 "aaaa") at cmd_api.c:237
#16 0x00007ffff7ac976f in r_core_cmd_subst_i (core=0x55555575e1c0 <r>, cmd=0x555555c8c1a0 "aaaa", 
    colon=0x0, tmpseek=0x7fffffffd906) at cmd.c:2911
#17 0x00007ffff7ac62d0 in r_core_cmd_subst (core=0x55555575e1c0 <r>, cmd=0x555555c8c1a0 "aaaa")
    at cmd.c:1940
#18 0x00007ffff7acbeca in r_core_cmd (core=0x55555575e1c0 <r>, cstr=0x7fffffffe1bf "aaaa", log=0)
    at cmd.c:3615
#19 0x0000555555558023 in run_commands (cmds=0x5555557c0260, files=0x5555557c02c0, quiet=false)
    at radare2.c:367
#20 0x000055555555b2d8 in main (argc=4, argv=0x7fffffffde18, envp=0x7fffffffde40) at radare2.c:1318
```

### File for Reproducing the Error 

[binary.zip](https://github.com/radare/radare2/files/2240235/binary.zip)

**Comment by radare** [comment]
thats a null deref. ill fix that in sdb. 1m

**Comment by radare** [comment]
please confirm the fix in master

**Comment by jstucke** [comment]
I can confirm that the error seems to be gone now. Thank you very much!
