### ISSUE TITLE
One more googlefuzz crash

### ISSUE THREAD

**Issue by radare** [radare/radare2#11235]
[clusterfuzz-testcase-minimized-ia_fuzz-5730103170957312.dms.zip](https://github.com/radare/radare2/files/2320828/clusterfuzz-testcase-minimized-ia_fuzz-5730103170957312.dms.zip)

**Comment by radare** [comment]
```
INFO: Loaded 1 PC tables (155456 PCs): 155456 [0x2503170,0x2762570),
--
  | /mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_radare2_7c098d5bc2bf0d73a75b53c6781baceb06a49745/revisions/ia_fuzz: Running 1 inputs 100 time(s) each.
  | Running: /2775204d3fb7fcf6a14f63e3a9512f0651f196d9f3cb193291b8abf615fuzz-0
  | =================================================================
  | ==1==ERROR: AddressSanitizer: SEGV on unknown address 0x61910000fbff (pc 0x000000fddeb0 bp 0x7ffd513b3bf0 sp 0x7ffd513b3b40 T0)
  | ==1==The signal is caused by a READ memory access.
  | SCARINESS: 20 (wild-addr-read)
  | #0 0xfddeaf in r_bin_mdmp_init_directory_entry radare2/libr/bin/format/mdmp/mdmp.c:479:21
  | #1 0xfdb934 in r_bin_mdmp_init_directory radare2/libr/bin/format/mdmp/mdmp.c:663:4
  | #2 0xfdad63 in r_bin_mdmp_init radare2/libr/bin/format/mdmp/mdmp.c:787:7
  | #3 0xfdab06 in r_bin_mdmp_new_buf radare2/libr/bin/format/mdmp/mdmp.c:833:7
  | #4 0xfd61b2 in load_bytes radare2/libr/bin/p/bin_mdmp.c:196:13
  | #5 0xef300e in r_bin_object_new radare2/libr/bin/obj.c:58:16
  | #6 0xeedb92 in r_bin_file_new_from_bytes radare2/libr/bin/bfile.c:515:6
  | #7 0xed30dd in r_bin_load_io2 radare2/libr/bin/bin.c:485:13
  | #8 0xed2ac1 in r_bin_load_io radare2/libr/bin/bin.c:42:12
  | #9 0x635bb5 in cmd_open_bin radare2/libr/core/cmd_open.c:305:6

```
