### ISSUE TITLE
Segmentation fault in wasm (aaaa)

### ISSUE THREAD

**Issue by oddcoder** [radare/radare2#11275]
# Segmentation fault in wasm (aaaa)

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                        | gentoo x64
| File format of the file you reverse (mandatory)      | wasm
| Architecture/bits of the file (mandatory)            | wasm
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19237 @ linux-x86-64 git.2.8.0-226-ge2df259a8 commit: e2df259a8ecd6570cb72b7ddf47df36f0a5f715c build: 2018-08-27__12:31:45

### Expected behavior

Analysis and clean exit

### Actual behavior

Segmentation fault on exit

### Steps to reproduce the behavior 

```
 r2 -N test.wasm
err: beach type entries
[0x000000bb]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ] 
[Value from 0x00000000 to 0x00000fdd
aav: 0x00000000-0x00000fdd in 0x0-0xfdd
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Type matching analysis for all functions (afta)
[x] Emulate code to find computed references (aae)
[x] Analyze consecutive function (aat)
[0x000000bb]> q
[1]    1120 segmentation fault  r2 -N test.wasm
```

Here few extra notes:
- `aa` doens't crash
-  `aaa` doesn't crash either: however `aaa` results in this issue https://github.com/radare/radare2/issues/11134
- `aaa;aae;aat` which is supposed to be equivalent to `aaaa` doesn't crash either.

The binary file: [test.wasm.zip](https://github.com/radare/radare2/files/2323751/test.wasm.zip)

#### stack trace:
```
[#0] 0x7ffff63afd93 → Name: cs_close(handle=0x7ffff6aa3f60 <handle>)
[#1] 0x7ffff6341cb5 → Name: fini(p=0x0)
[#2] 0x7ffff635e239 → Name: r_anal_plugin_free(p=0x7ffff6a0b900 <r_anal_plugin_x86_cs>)
[#3] 0x7ffff3dbb0ce → Name: r_list_delete(list=0x55555582b740, iter=0x5555558336c0)
[#4] 0x7ffff3dbaf9e → Name: r_list_purge(list=0x55555582b740)
[#5] 0x7ffff3dbafea → Name: r_list_free(list=0x55555582b740)
[#6] 0x7ffff635e2c4 → Name: r_anal_free(a=0x5555557ea6a0)
[#7] 0x7ffff7a2e9db → Name: r_core_fini(c=0x55555575e580 <r>)
[#8] 0x55555555bcd9 → Name: main(argc=0x2, argv=0x7fffffffdaa8, envp=0x7fffffffdac0)
```

**Comment by radare** [comment]
can you build with asan and paste the log?

**Comment by oddcoder** [comment]
```
➜  wasm r2 test.wasm
err: beach type entries
[0x000000bb]> aaaa
[Couldn't read buffer starting with sym. and entry0 (aa)
Couldn't read buffer
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ] 
[Value from 0x00000000 to 0x00000fdd
aav: 0x00000000-0x00000fdd in 0x0-0xfdd
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Type matching analysis for all functions (afta)
[=================================================================
==3297==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f418173f820 at pc 0x7f4180b295d3 bp 0x7ffcbc6de8b0 sp 0x7ffcbc6de8a0
WRITE of size 8 at 0x7f418173f820 thread T0
    #0 0x7f4180b295d2 in wasm_op /home/oddcoder/projects/radare2/libr/..//libr/anal/p/anal_wasm.c:117
    #1 0x7f4180b5aae8 in r_anal_op /home/oddcoder/projects/radare2/libr/anal/op.c:154
    #2 0x7f4182dd00fb in r_core_anal_esil /home/oddcoder/projects/radare2/libr/core/canal.c:4026
    #3 0x7f4182c78858 in cmd_anal_all /home/oddcoder/projects/radare2/libr/core/cmd_anal.c:7136
    #4 0x7f4182c7a218 in cmd_anal /home/oddcoder/projects/radare2/libr/core/cmd_anal.c:7411
    #5 0x7f4182dab062 in r_cmd_call /home/oddcoder/projects/radare2/libr/core/cmd_api.c:237
    #6 0x7f4182d05e4d in r_core_cmd_subst_i /home/oddcoder/projects/radare2/libr/core/cmd.c:2857
    #7 0x7f4182cff279 in r_core_cmd_subst /home/oddcoder/projects/radare2/libr/core/cmd.c:1930
    #8 0x7f4182d0b9fa in r_core_cmd /home/oddcoder/projects/radare2/libr/core/cmd.c:3605
    #9 0x7f4182d0c717 in r_core_cmd0 /home/oddcoder/projects/radare2/libr/core/cmd.c:3769
    #10 0x7f4182c78363 in cmd_anal_all /home/oddcoder/projects/radare2/libr/core/cmd_anal.c:7081
    #11 0x7f4182c7a218 in cmd_anal /home/oddcoder/projects/radare2/libr/core/cmd_anal.c:7411
    #12 0x7f4182dab062 in r_cmd_call /home/oddcoder/projects/radare2/libr/core/cmd_api.c:237
    #13 0x7f4182d06580 in r_core_cmd_subst_i /home/oddcoder/projects/radare2/libr/core/cmd.c:2901
    #14 0x7f4182cff279 in r_core_cmd_subst /home/oddcoder/projects/radare2/libr/core/cmd.c:1930
    #15 0x7f4182d0b9fa in r_core_cmd /home/oddcoder/projects/radare2/libr/core/cmd.c:3605
    #16 0x7f4182bc3cec in r_core_prompt_exec /home/oddcoder/projects/radare2/libr/core/core.c:2511
    #17 0x564f8bdbe3ae in main /home/oddcoder/projects/radare2/binr/radare2/radare2.c:1396
    #18 0x7f417ce8ef09 in __libc_start_main (/lib64/libc.so.6+0x20f09)
    #19 0x564f8bdb7199 in _start (/home/oddcoder/projects/radare2/binr/radare2/radare2+0x7199)

0x7f418173f820 is located 0 bytes to the right of global variable 'wasm_stack' defined in '/home/oddcoder/projects/radare2/libr/..//libr/anal/p/anal_wasm.c:17:3' (0x7f418173e020) of size 6144
0x7f418173f820 is located 32 bytes to the left of global variable 'wasm_stack_ptr' defined in '/home/oddcoder/projects/radare2/libr/..//libr/anal/p/anal_wasm.c:18:5' (0x7f418173f840) of size 4
SUMMARY: AddressSanitizer: global-buffer-overflow /home/oddcoder/projects/radare2/libr/..//libr/anal/p/anal_wasm.c:117 in wasm_op
Shadow bytes around the buggy address:
  0x0fe8b02dfeb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe8b02dfec0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe8b02dfed0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe8b02dfee0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe8b02dfef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe8b02dff00: 00 00 00 00[f9]f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fe8b02dff10: 04 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 f9 f9 f9
  0x0fe8b02dff20: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe8b02dff30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe8b02dff40: 00 00 00 00 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0fe8b02dff50: 00 00 00 00 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3297==ABORTING
```

**Comment by wargio** [comment]
i'll fix this tonight

**Comment by wargio** [comment]
@devnexen i'll fix it in a few mins.

**Comment by devnexen** [comment]
Alright :-)
