### ISSUE TITLE
Memory leaks in the metainformation handling (comments/reflines) upon exit.

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#11493]
```
==1275892==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2248 byte(s) in 10 object(s) allocated from:
    #0 0x7fef5e306e50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x7fef4e1b7785 in sdb_decode /home/akochkov/radare/radare2/shlr/sdb/src/base64.c:101
    #2 0x7fef5725f5c3 in r_meta_get_string /home/akochkov/radare/radare2/libr/anal/meta.c:185
    #3 0x7fef5d1443db in ds_show_comments_right /home/akochkov/radare/radare2/libr/core/disasm.c:1836
    #4 0x7fef5d179820 in r_core_print_disasm /home/akochkov/radare/radare2/libr/core/disasm.c:4708
    #5 0x7fef5cee21ea in cmd_print /home/akochkov/radare/radare2/libr/core/cmd_print.c:4591
    #6 0x7fef5d09703b in r_cmd_call /home/akochkov/radare/radare2/libr/core/cmd_api.c:237
    #7 0x7fef5cf583bd in r_core_cmd_subst_i /home/akochkov/radare/radare2/libr/core/cmd.c:2922
    #8 0x7fef5cf4adb4 in r_core_cmd_subst /home/akochkov/radare/radare2/libr/core/cmd.c:1934
    #9 0x7fef5cf62711 in r_core_cmd /home/akochkov/radare/radare2/libr/core/cmd.c:3626
    #10 0x7fef5cf63a45 in r_core_cmd0 /home/akochkov/radare/radare2/libr/core/cmd.c:3790
    #11 0x7fef5cfdae6d in visual_refresh /home/akochkov/radare/radare2/libr/core/visual.c:3155
    #12 0x7fef5cfddbaa in r_core_visual /home/akochkov/radare/radare2/libr/core/visual.c:3329
    #13 0x7fef5cf44d0d in cmd_visual /home/akochkov/radare/radare2/libr/core/cmd.c:1296
    #14 0x7fef5d09703b in r_cmd_call /home/akochkov/radare/radare2/libr/core/cmd_api.c:237
    #15 0x7fef5cf583bd in r_core_cmd_subst_i /home/akochkov/radare/radare2/libr/core/cmd.c:2922
    #16 0x7fef5cf4adb4 in r_core_cmd_subst /home/akochkov/radare/radare2/libr/core/cmd.c:1934
    #17 0x7fef5cf62711 in r_core_cmd /home/akochkov/radare/radare2/libr/core/cmd.c:3626
    #18 0x7fef5cd05aff in r_core_prompt_exec /home/akochkov/radare/radare2/libr/core/core.c:2568
    #19 0x560050fe87be in main /home/akochkov/radare/radare2/binr/radare2/radare2.c:1432
    #20 0x7fef4c7b211a in __libc_start_main (/lib64/libc.so.6+0x2311a)

Direct leak of 616 byte(s) in 4 object(s) allocated from:
    #0 0x7fef5e306e50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x7fef4e1b7785 in sdb_decode /home/akochkov/radare/radare2/shlr/sdb/src/base64.c:101
    #2 0x7fef572619f0 in r_meta_deserialize_val /home/akochkov/radare/radare2/libr/anal/meta.c:346
    #3 0x7fef57262844 in r_meta_find /home/akochkov/radare/radare2/libr/anal/meta.c:425
    #4 0x7fef57268c90 in r_anal_reflines_get /home/akochkov/radare/radare2/libr/anal/reflines.c:120
    #5 0x7fef5d12daba in ds_reflines_init /home/akochkov/radare/radare2/libr/core/disasm.c:791
    #6 0x7fef5d1763bf in r_core_print_disasm /home/akochkov/radare/radare2/libr/core/disasm.c:4595
    #7 0x7fef5cee21ea in cmd_print /home/akochkov/radare/radare2/libr/core/cmd_print.c:4591
    #8 0x7fef5d09703b in r_cmd_call /home/akochkov/radare/radare2/libr/core/cmd_api.c:237
    #9 0x7fef5cf583bd in r_core_cmd_subst_i /home/akochkov/radare/radare2/libr/core/cmd.c:2922
    #10 0x7fef5cf4adb4 in r_core_cmd_subst /home/akochkov/radare/radare2/libr/core/cmd.c:1934
    #11 0x7fef5cf62711 in r_core_cmd /home/akochkov/radare/radare2/libr/core/cmd.c:3626
    #12 0x7fef5cf63a45 in r_core_cmd0 /home/akochkov/radare/radare2/libr/core/cmd.c:3790
    #13 0x7fef5cfdae6d in visual_refresh /home/akochkov/radare/radare2/libr/core/visual.c:3155
    #14 0x7fef5cfddbaa in r_core_visual /home/akochkov/radare/radare2/libr/core/visual.c:3329
    #15 0x7fef5cf44d0d in cmd_visual /home/akochkov/radare/radare2/libr/core/cmd.c:1296
    #16 0x7fef5d09703b in r_cmd_call /home/akochkov/radare/radare2/libr/core/cmd_api.c:237
    #17 0x7fef5cf583bd in r_core_cmd_subst_i /home/akochkov/radare/radare2/libr/core/cmd.c:2922
    #18 0x7fef5cf4adb4 in r_core_cmd_subst /home/akochkov/radare/radare2/libr/core/cmd.c:1934
    #19 0x7fef5cf62711 in r_core_cmd /home/akochkov/radare/radare2/libr/core/cmd.c:3626
    #20 0x7fef5cd05aff in r_core_prompt_exec /home/akochkov/radare/radare2/libr/core/core.c:2568
    #21 0x560050fe87be in main /home/akochkov/radare/radare2/binr/radare2/radare2.c:1432
    #22 0x7fef4c7b211a in __libc_start_main (/lib64/libc.so.6+0x2311a)

Direct leak of 456 byte(s) in 3 object(s) allocated from:
    #0 0x7fef5e306e50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x7fef4e1b7785 in sdb_decode /home/akochkov/radare/radare2/shlr/sdb/src/base64.c:101
    #2 0x7fef572619f0 in r_meta_deserialize_val /home/akochkov/radare/radare2/libr/anal/meta.c:346
    #3 0x7fef57262844 in r_meta_find /home/akochkov/radare/radare2/libr/anal/meta.c:425
    #4 0x7fef57268c90 in r_anal_reflines_get /home/akochkov/radare/radare2/libr/anal/reflines.c:120
    #5 0x7fef5d12de09 in ds_reflines_init /home/akochkov/radare/radare2/libr/core/disasm.c:794
    #6 0x7fef5d1763bf in r_core_print_disasm /home/akochkov/radare/radare2/libr/core/disasm.c:4595
    #7 0x7fef5cee21ea in cmd_print /home/akochkov/radare/radare2/libr/core/cmd_print.c:4591
    #8 0x7fef5d09703b in r_cmd_call /home/akochkov/radare/radare2/libr/core/cmd_api.c:237
    #9 0x7fef5cf583bd in r_core_cmd_subst_i /home/akochkov/radare/radare2/libr/core/cmd.c:2922
    #10 0x7fef5cf4adb4 in r_core_cmd_subst /home/akochkov/radare/radare2/libr/core/cmd.c:1934
    #11 0x7fef5cf62711 in r_core_cmd /home/akochkov/radare/radare2/libr/core/cmd.c:3626
    #12 0x7fef5cf63a45 in r_core_cmd0 /home/akochkov/radare/radare2/libr/core/cmd.c:3790
    #13 0x7fef5cfdae6d in visual_refresh /home/akochkov/radare/radare2/libr/core/visual.c:3155
    #14 0x7fef5cfddbaa in r_core_visual /home/akochkov/radare/radare2/libr/core/visual.c:3329
    #15 0x7fef5cf44d0d in cmd_visual /home/akochkov/radare/radare2/libr/core/cmd.c:1296
    #16 0x7fef5d09703b in r_cmd_call /home/akochkov/radare/radare2/libr/core/cmd_api.c:237
    #17 0x7fef5cf583bd in r_core_cmd_subst_i /home/akochkov/radare/radare2/libr/core/cmd.c:2922
    #18 0x7fef5cf4adb4 in r_core_cmd_subst /home/akochkov/radare/radare2/libr/core/cmd.c:1934
    #19 0x7fef5cf62711 in r_core_cmd /home/akochkov/radare/radare2/libr/core/cmd.c:3626
    #20 0x7fef5cd05aff in r_core_prompt_exec /home/akochkov/radare/radare2/libr/core/core.c:2568
    #21 0x560050fe87be in main /home/akochkov/radare/radare2/binr/radare2/radare2.c:1432
    #22 0x7fef4c7b211a in __libc_start_main (/lib64/libc.so.6+0x2311a)

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x7fef5e253320 in strdup (/lib64/libasan.so.5+0x3b320)
    #1 0x7fef5ce0535a in setFunctionName /home/akochkov/radare/radare2/libr/core/cmd_anal.c:2103
    #2 0x7fef5ce0cecc in cmd_anal_fcn /home/akochkov/radare/radare2/libr/core/cmd_anal.c:2704
    #3 0x7fef5ce53686 in cmd_anal /home/akochkov/radare/radare2/libr/core/cmd_anal.c:7393
    #4 0x7fef5d09703b in r_cmd_call /home/akochkov/radare/radare2/libr/core/cmd_api.c:237
    #5 0x7fef5cf583bd in r_core_cmd_subst_i /home/akochkov/radare/radare2/libr/core/cmd.c:2922
    #6 0x7fef5cf4adb4 in r_core_cmd_subst /home/akochkov/radare/radare2/libr/core/cmd.c:1934
    #7 0x7fef5cf62711 in r_core_cmd /home/akochkov/radare/radare2/libr/core/cmd.c:3626
    #8 0x7fef5cf639b9 in r_core_cmdf /home/akochkov/radare/radare2/libr/core/cmd.c:3784
    #9 0x7fef5d0d25df in r_core_anal_all /home/akochkov/radare/radare2/libr/core/canal.c:3208
    #10 0x7fef5ce4eda5 in cmd_anal_all /home/akochkov/radare/radare2/libr/core/cmd_anal.c:7023
    #11 0x7fef5ce53b50 in cmd_anal /home/akochkov/radare/radare2/libr/core/cmd_anal.c:7441
    #12 0x7fef5d09703b in r_cmd_call /home/akochkov/radare/radare2/libr/core/cmd_api.c:237
    #13 0x7fef5cf583bd in r_core_cmd_subst_i /home/akochkov/radare/radare2/libr/core/cmd.c:2922
    #14 0x7fef5cf4adb4 in r_core_cmd_subst /home/akochkov/radare/radare2/libr/core/cmd.c:1934
    #15 0x7fef5cf62711 in r_core_cmd /home/akochkov/radare/radare2/libr/core/cmd.c:3626
    #16 0x7fef5cd05aff in r_core_prompt_exec /home/akochkov/radare/radare2/libr/core/core.c:2568
    #17 0x560050fe87be in main /home/akochkov/radare/radare2/binr/radare2/radare2.c:1432
    #18 0x7fef4c7b211a in __libc_start_main (/lib64/libc.so.6+0x2311a)

SUMMARY: AddressSanitizer: 3327 byte(s) leaked in 18 allocation(s).
```

**Comment by radare** [comment]
pleae update, line numbers doesnt match

**Comment by dav1901** [comment]
I believe those were fixed in 
https://github.com/radare/radare2/commit/f7be81edbbeaf99862d5e552398d6a91630cc2a9#diff-7b45b46dd8a84a924b91f34c2b1e6309
 https://github.com/radare/radare2/commit/8c521e8bf1c8b4accbf558b6ed06b510b09aa5c7#diff-b29aa2f07bcaeba1c57e637fab81237d
https://github.com/radare/radare2/commit/2b055189918296d93512449d3a459967bd2a6bf5#diff-9a7bcc9d9f9b6439c4d8b9301f1d46cc
