### ISSUE TITLE
Memory Leak in rabin -H

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#11692]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19569 @ linux-x86-64 git.2.9.0-240-g2582b36a7 commit: 2582b36a77b7b754000b071fe1f15fc4797d28e3 build: 2018-09-29__15:43:50

### Expected behavior
No memory leak

### Actual behavior
Memory leak

### Steps to reproduce the behavior 
- Compile r2 with ASAN/LeakSanitizer
- Run `rabin2 -H test_file` where `test_file` is simply a blank file

```
$ ASAN_OPTIONS=detect_odr_violation=0 rabin2 -H blerg

=================================================================
==42476==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x56098bb3d308 in calloc (/home/angr/opt/radare2/binr/rabin2/rabin2+0xe4308)
    #1 0x7fb6327002e9 in r_bin_load_io2 /home/angr/opt/radare2/libr/bin/bin.c:441:15
    #2 0x7fb6326ffef1 in r_bin_load_io /home/angr/opt/radare2/libr/bin/bin.c:42:12
    #3 0x7fb63270173b in r_bin_load /home/angr/opt/radare2/libr/bin/bin.c:261:9
    #4 0x7fb632722c89 in r_bin_open /home/angr/opt/radare2/libr/bin/open.c:32:6
    #5 0x56098bb77ffb in main /home/angr/opt/radare2/binr/rabin2/rabin2.c:1014:7
    #6 0x7fb6309c1b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).
```

Note: This leak happens with other examples as well, this is just the easiest to reproduce, for example:

```
=================================================================
==42618==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32768 byte(s) in 1 object(s) allocated from:
    #0 0x55b34234c308 in calloc (/home/angr/opt/radare2/binr/rabin2/rabin2+0xe4308)
    #1 0x7ff690f972e9 in r_bin_load_io2 /home/angr/opt/radare2/libr/bin/bin.c:441:15
    #2 0x7ff690f96ef1 in r_bin_load_io /home/angr/opt/radare2/libr/bin/bin.c:42:12
    #3 0x7ff690f9873b in r_bin_load /home/angr/opt/radare2/libr/bin/bin.c:261:9
    #4 0x7ff690fb9c89 in r_bin_open /home/angr/opt/radare2/libr/bin/open.c:32:6
    #5 0x55b342386ffb in main /home/angr/opt/radare2/binr/rabin2/rabin2.c:1014:7
    #6 0x7ff68f258b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: 32768 byte(s) leaked in 1 allocation(s).
```

**Comment by bannsec** [comment]
Believe this ticket was resolved with the merge. Will open new ticket if i discover more memory leaks.
