### ISSUE TITLE
Segfault in idpi

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#11807]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX 64 bits
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86 32bits
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19909 @ darwin-x86-64 git.2.9.0-356-g33dab09e2 commit: 33dab09e2062d0ec964ad6c61b0bf550ebcabcb4 build: 2018-10-13__19:37:56

### Steps to reproduce the behavior 

- Get binary: [msvcrt40.dll.zip](https://github.com/radare/radare2/files/2475819/msvcrt40.dll.zip)
- `idpd` to get the PDB
- `idpi` get segfault

```
[0x78080000]> idpi
pdb/tpi.c:1537:8: runtime error: member access within misaligned address 0x60b0000399c2 for type 'SCString', which requires 8 byte alignment
0x60b0000399c2: note: pointer points here
 00 00  00 00 be be be be be be  be be be be be be be be  be be be be be be be be  be be be be be be
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1537:8 in
pdb/tpi.c:1537:8: runtime error: store to misaligned address 0x60b0000399ca for type 'char *', which requires 8 byte alignment
0x60b0000399ca: note: pointer points here
 be be  be be be be be be be be  be be be be be be be be  be be be be be be be be  be be 00 00 00 00
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1537:8 in
pdb/tpi.c:1518:8: runtime error: member access within misaligned address 0x60b0000399c2 for type 'SCString', which requires 8 byte alignment
0x60b0000399c2: note: pointer points here
 00 00  00 00 be be be be be be  be be 00 00 00 00 00 00  00 00 be be be be be be  be be be be be be
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1518:8 in
pdb/tpi.c:1518:8: runtime error: store to misaligned address 0x60b0000399c2 for type 'unsigned int', which requires 8 byte alignment
0x60b0000399c2: note: pointer points here
 00 00  00 00 be be be be be be  be be 00 00 00 00 00 00  00 00 be be be be be be  be be be be be be
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1518:8 in
pdb/tpi.c:1519:8: runtime error: member access within misaligned address 0x60b0000399c2 for type 'SCString', which requires 8 byte alignment
0x60b0000399c2: note: pointer points here
 00 00  00 00 4a 00 00 00 be be  be be 00 00 00 00 00 00  00 00 be be be be be be  be be be be be be
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1519:8 in
pdb/tpi.c:1519:8: runtime error: store to misaligned address 0x60b0000399ca for type 'char *', which requires 8 byte alignment
0x60b0000399ca: note: pointer points here
 be be  be be 00 00 00 00 00 00  00 00 be be be be be be  be be be be be be be be  be be 00 00 00 00
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1519:8 in
pdb/tpi.c:1520:13: runtime error: member access within misaligned address 0x60b0000399c2 for type 'SCString', which requires 8 byte alignment
0x60b0000399c2: note: pointer points here
 00 00  00 00 4a 00 00 00 be be  be be f0 7e 01 00 70 60  00 00 be be be be be be  be be be be be be
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1520:13 in
pdb/tpi.c:1520:13: runtime error: load of misaligned address 0x60b0000399ca for type 'char *', which requires 8 byte alignment
0x60b0000399ca: note: pointer points here
 be be  be be f0 7e 01 00 70 60  00 00 be be be be be be  be be be be be be be be  be be 00 00 00 00
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1520:13 in
pdb/tpi.c:1523:16: runtime error: member access within misaligned address 0x60b0000399c2 for type 'SCString', which requires 8 byte alignment
0x60b0000399c2: note: pointer points here
 00 00  00 00 4a 00 00 00 be be  be be f0 7e 01 00 70 60  00 00 be be be be be be  be be be be be be
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1523:16 in
pdb/tpi.c:1523:16: runtime error: load of misaligned address 0x60b0000399ca for type 'char *', which requires 8 byte alignment
0x60b0000399ca: note: pointer points here
 be be  be be f0 7e 01 00 70 60  00 00 be be be be be be  be be be be be be be be  be be 00 00 00 00
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/tpi.c:1523:16 in
pdb/pdb.c:1116:7: runtime error: member access within misaligned address 0xbebebebebebebebe for type 'RList' (aka 'struct r_list_t'), which requires 8 byte alignment
0xbebebebebebebebe: note: pointer points here
<memory cannot be printed>
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/pdb.c:1116:7 in
pdb/pdb.c:1116:7: runtime error: load of misaligned address 0xbebebebebebebebe for type 'RListIter *' (aka 'struct r_list_iter_t *'), which requires 8 byte alignment
0xbebebebebebebebe: note: pointer points here
<memory cannot be printed>
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior pdb/pdb.c:1116:7 in
AddressSanitizer:DEADLYSIGNAL
=================================================================
==90343==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010c8e29c6 bp 0x7ffee4eb6110 sp 0x7ffee4eb5cc0 T0)
==90343==The signal is caused by a READ memory access.
==90343==Hint: address points to the zero page.
    #0 0x10c8e29c5 in print_gvars pdb.c:1116
    #1 0x10b353de8 in r_core_pdb_info cbin.c:1023
    #2 0x10af47102 in cmd_info .cmd_info.c:643
    #3 0x10b3d2d94 in r_cmd_call cmd_api.c:239
    #4 0x10aff63f0 in r_core_cmd_subst_i cmd.c:2928
    #5 0x10aec0171 in r_core_cmd_subst cmd.c:1936
    #6 0x10aea8169 in r_core_cmd cmd.c:3648
    #7 0x10ae3fac4 in r_core_prompt_exec core.c:2632
    #8 0x10ad5015b in main radare2.c:1442
    #9 0x7fff55913014 in start (libdyld.dylib:x86_64+0x1014)

==90343==Register values:
rax = 0x0000100000000000  rbx = 0x00007ffee4eb61c0  rcx = 0x17d7d7d7d7d7d7d7  rdx = 0x0000000000000040
rdi = 0x0000000000000000  rsi = 0x00000001124e5588  rbp = 0x00007ffee4eb6110  rsp = 0x00007ffee4eb5cc0
 r8 = 0x0000000000000000   r9 = 0x000000000000ef4b  r10 = 0x00007fff55a6378a  r11 = 0x0000000000000202
r12 = 0x000000010b7413a7  r13 = 0x00007ffee4eb8680  r14 = 0x00007ffee4eb6140  r15 = 0x000000010afe3600
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV pdb.c:1116 in print_gvars
==90343==ABORTING
```

**Comment by Maijin** [comment]
The segfault is fixed but the idpi doesn't print anything?

**Comment by radare** [comment]
didnt we had tests?

**Comment by Maijin** [comment]
we have a lot of tests for pdb but looks like for this case there is none, not sure also what to expect though.
