### ISSUE TITLE
Last 5 clusterfuzz reproducers

### ISSUE THREAD

**Issue by radare** [radare/radare2#12134]
* [clusterfuzz-2018-11-12.zip](https://github.com/radare/radare2/files/2572662/clusterfuzz-2018-11-12.zip)

**Comment by radare** [comment]
only 1 left:

```
$ r2 clusterfuzz-testcase-minimized-ia_fuzz-5664529107648512.dms
[ERROR] Number of streams = 38161477 is greater than is supportable by bin size
[WARN] Invalid or unsupported enumeration encountered 64
=================================================================
==7929==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6190000b99b4 at pc 0x00010c857490 bp 0x7ffee4c2bdf0 sp 0x7ffee4c2bde8
READ of size 8 at 0x6190000b99b4 thread T0
    #0 0x10c85748f in r_bin_mdmp_init_pe_bins mdmp.c:821
    #1 0x10c85367b in r_bin_mdmp_init mdmp.c:885
    #2 0x10c8530a7 in r_bin_mdmp_new_buf mdmp.c:927
    #3 0x10c83f724 in load_buffer bin_mdmp.c:212
    #4 0x10c46e5a1 in r_bin_object_new obj.c:165
    #5 0x10c45a42a in r_bin_file_new_from_bytes bfile.c:396
    #6 0x10c401da0 in r_bin_open_io bin.c:415
    #7 0x10b470e82 in r_core_file_do_load_for_io_plugin cfile.c:382
    #8 0x10b466004 in r_core_bin_load cfile.c:540
    #9 0x10afd8a76 in main (r2:x86_64+0x100008a76)
    #10 0x7fff663ca08c in start (libdyld.dylib:x86_64+0x1708c)

0x6190000b99b4 is located 48 bytes to the right of 1028-byte region [0x6190000b9580,0x6190000b9984)
allocated by thread T0 here:
    #0 0x1152e7f53 in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x56f53)
    #1 0x110fe5f3e in r_buf_set_bytes buf.c:347
    #2 0x10c853078 in r_bin_mdmp_new_buf mdmp.c:922
    #3 0x10c83f724 in load_buffer bin_mdmp.c:212
    #4 0x10c46e5a1 in r_bin_object_new obj.c:165
    #5 0x10c45a42a in r_bin_file_new_from_bytes bfile.c:396
    #6 0x10c401da0 in r_bin_open_io bin.c:415
    #7 0x10b470e82 in r_core_file_do_load_for_io_plugin cfile.c:382
    #8 0x10b466004 in r_core_bin_load cfile.c:540
    #9 0x10afd8a76 in main (r2:x86_64+0x100008a76)
    #10 0x7fff663ca08c in start (libdyld.dylib:x86_64+0x1708c)

SUMMARY: AddressSanitizer: heap-buffer-overflow mdmp.c:821 in r_bin_mdmp_init_pe_bins
Shadow bytes around the buggy address:
  0x1c32000172e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c32000172f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c3200017300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c3200017310: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c3200017320: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1c3200017330: 04 fa fa fa fa fa[fa]fa fa fa fa fa fa fa fa fa
  0x1c3200017340: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c3200017350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c3200017360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c3200017370: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c3200017380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==7929==ABORTING
Abort trap: 6
```

**Comment by radare** [comment]
Fixed all those
