### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow WRITE of size 8 format/mach0/mach0.c:1922:16

### ISSUE THREAD

**Issue by revskills** [radare/radare2#12384]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | GNU/Linux Gentoo x86_64
| File format of the file you reverse (mandatory)      |  Mach-O
| Architecture/bits of the file (mandatory)            | arm
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.1 20364 @ linux-x86-64 git.3.1.1 commit: b143e1b1b5622ef2f41a90f4c0f7ed4c477caf40 build: 2018-12-03__10:20:55

### Actual behavior
```
==3303==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200002a870 at pc 0x7f39ca7b6304 bp 0x7ffd67cdb6f0 sp 0x7ffd67cdb6e8
WRITE of size 8 at 0x60200002a870 thread T0
    #0 0x7f39ca7b6303 in parse_import_ptr /home/rs/dev/radare2/libr/..//libr/bin/p/../format/mach0/mach0.c:1922:16
    #1 0x7f39ca7b4e7b in get_relocs /home/rs/dev/radare2/libr/..//libr/bin/p/../format/mach0/mach0.c:2210:8
    #2 0x7f39ca790d35 in relocs /home/rs/dev/radare2/libr/..//libr/bin/p/bin_mach0.c:477:17
    #3 0x7f39ca4f9e8a in r_bin_object_set_items /home/rs/dev/radare2/libr/bin/obj.c:354:16
    #4 0x7f39ca4f4b2f in r_bin_object_new /home/rs/dev/radare2/libr/bin/obj.c:223:2
    #5 0x7f39ca4dfedf in r_bin_file_new_from_bytes /home/rs/dev/radare2/libr/bin/bfile.c:396:18
    #6 0x7f39ca48aee7 in r_bin_open_io /home/rs/dev/radare2/libr/bin/bin.c:420:13
    #7 0x7f39cc740aa3 in r_core_file_do_load_for_io_plugin /home/rs/dev/radare2/libr/core/cfile.c:382:7
    #8 0x7f39cc73632c in r_core_bin_load /home/rs/dev/radare2/libr/core/cfile.c:540:4
    #9 0x55ed6a6d4240 in main /home/rs/dev/radare2/binr/radare2/radare2.c:1145:15
    #10 0x7f39be630ae6 in __libc_start_main (/lib64/libc.so.6+0x21ae6)
    #11 0x55ed6a5fb749 in _start (/home/rs/dev/radare2/binr/radare2/radare2+0x2a749)

0x60200002a871 is located 0 bytes to the right of 1-byte region [0x60200002a870,0x60200002a871)
allocated by thread T0 here:
    #0 0x55ed6a69e7e3 in malloc (/home/rs/dev/radare2/binr/radare2/radare2+0xcd7e3)
    #1 0x7f39ca7b4af1 in get_relocs /home/rs/dev/radare2/libr/..//libr/bin/p/../format/mach0/mach0.c:2206:18
    #2 0x7f39ca790d35 in relocs /home/rs/dev/radare2/libr/..//libr/bin/p/bin_mach0.c:477:17
    #3 0x7f39ca4f9e8a in r_bin_object_set_items /home/rs/dev/radare2/libr/bin/obj.c:354:16
    #4 0x7f39ca4f4b2f in r_bin_object_new /home/rs/dev/radare2/libr/bin/obj.c:223:2
    #5 0x7f39ca4dfedf in r_bin_file_new_from_bytes /home/rs/dev/radare2/libr/bin/bfile.c:396:18
    #6 0x7f39ca48aee7 in r_bin_open_io /home/rs/dev/radare2/libr/bin/bin.c:420:13
    #7 0x7f39cc740aa3 in r_core_file_do_load_for_io_plugin /home/rs/dev/radare2/libr/core/cfile.c:382:7
    #8 0x7f39cc73632c in r_core_bin_load /home/rs/dev/radare2/libr/core/cfile.c:540:4
    #9 0x55ed6a6d4240 in main /home/rs/dev/radare2/binr/radare2/radare2.c:1145:15
    #10 0x7f39be630ae6 in __libc_start_main (/lib64/libc.so.6+0x21ae6)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/rs/dev/radare2/libr/..//libr/bin/p/../format/mach0/mach0.c:1922:16 in parse_import_ptr
Shadow bytes around the buggy address:
  0x0c047fffd4b0: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fd
  0x0c047fffd4c0: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fa
  0x0c047fffd4d0: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fd
  0x0c047fffd4e0: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fd
  0x0c047fffd4f0: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fd
=>0x0c047fffd500: fa fa fd fa fa fa fd fd fa fa fd fa fa fa[01]fa
  0x0c047fffd510: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffd520: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffd530: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffd540: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffd550: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3303==ABORTING


```

### Steps to reproduce the behavior 
[crash.gz](https://github.com/radare/radare2/files/2639246/crash.gz)

```
$ r2 crash
```

**Comment by radare** [comment]
Thanks!
