### ISSUE TITLE
Utf8 issue

### ISSUE THREAD

**Issue by Zurich1994** [radare/radare2#12525]
I use python 3.6.5 in linux os, and the version of r2pipe is 1.2.0, when i run r2.cmd("i"), it returns error, like this:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/r2pipe/open_base.py", line 197, in cmd
    res = self._cmd(cmd, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/r2pipe/open_sync.py", line 125, in _cm
    return out.decode('utf8')

Then, i use the radare2(3.1.0) to check it , i found there are some strange chars in the attribute of "dgb_file", it cause the decode("utf8") returns error. So i just modified the open_sync.py on line 125, like this : result.decode("utf","ignore"). Everything is ok.

**Comment by radare** [comment]
this is not a bug in r2
