### ISSUE TITLE
UB in DEX because of RBufGetAt

### ISSUE THREAD

**Issue by radare** [radare/radare2#12662]
in p/bin_dex.c
```c
 339         const ut8 *p4 = r_buf_get_at (binfile->buf, debug_info_off, NULL);
 340         const ut8 *p4_end = p4 + binfile->buf->length - debug_info_off;
```

sample from  clusterfuzz:

[clusterfuzz-testcase-minimized-ia_fuzz-5741698980773888.dms.zip](https://github.com/radare/radare2/files/2729490/clusterfuzz-testcase-minimized-ia_fuzz-5741698980773888.dms.zip)

asan error:

```
$ r2 clusterfuzz-testcase-minimized-ia_fuzz-5741698980773888.dms
/Users/pancake/prg/radare2/libr/..//libr/bin/p/bin_dex.c:1536:36: runtime error: pointer index expression with base 0x000000004420 overflowed to 0xfffffffffffffd64
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/pancake/prg/radare2/libr/..//libr/bin/p/bin_dex.c:1536:36 in
/Users/pancake/prg/radare2/libr/..//libr/bin/p/bin_dex.c:340:48: runtime error: pointer index expression with base 0x000000004420 overflowed to 0xffffffffff00441a
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/pancake/prg/radare2/libr/..//libr/bin/p/bin_dex.c:340:48 in
=================================================================
==51840==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62900000e622 at pc 0x000107df4ea9 bp 0x7ffee93fd640 sp 0x7ffee93fd638
READ of size 1 at 0x62900000e622 thread T0
    #0 0x107df4ea8 in r_read_le32 r_endian.h:176
    #1 0x107e197ce in dex_method_signature2 bin_dex.c:306
    #2 0x107e0ebc4 in dex_parse_debug_item bin_dex.c:374
    #3 0x107e0cc6a in parse_dex_class_method bin_dex.c:1363
    #4 0x107dff4b8 in parse_class bin_dex.c:1562
    #5 0x107df811d in dex_loadcode bin_dex.c:1661
    #6 0x107de4e95 in entries bin_dex.c:1799
    #7 0x107d1b4d3 in r_bin_object_set_items obj.c:311
    #8 0x107d1927b in r_bin_object_new obj.c:223
    #9 0x107d0373e in r_bin_file_new_from_bytes bfile.c:460
    #10 0x107caba80 in r_bin_open_io bin.c:410
    #11 0x106ca56f2 in r_core_file_do_load_for_io_plugin cfile.c:380
    #12 0x106c9a874 in r_core_bin_load cfile.c:538
    #13 0x1068029dc in main (r2:x86_64+0x1000089dc)
    #14 0x7fff5fbb9ed8 in start (libdyld.dylib:x86_64+0x16ed8)

0x62900000e622 is located 1 bytes to the right of 17441-byte region [0x62900000a200,0x62900000e621)
allocated by thread T0 here:
    #0 0x111024f53 in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x56f53)
    #1 0x11092783e in r_buf_set_bytes buf.c:535
    #2 0x107e1e927 in r_bin_dex_new_buf dex.c:30
    #3 0x107de44c0 in load_buffer bin_dex.c:731
    #4 0x107d1791b in r_bin_object_new obj.c:164
    #5 0x107d0373e in r_bin_file_new_from_bytes bfile.c:460
    #6 0x107caba80 in r_bin_open_io bin.c:410
    #7 0x106ca56f2 in r_core_file_do_load_for_io_plugin cfile.c:380
    #8 0x106c9a874 in r_core_bin_load cfile.c:538
    #9 0x1068029dc in main (r2:x86_64+0x1000089dc)
    #10 0x7fff5fbb9ed8 in start (libdyld.dylib:x86_64+0x16ed8)

SUMMARY: AddressSanitizer: heap-buffer-overflow r_endian.h:176 in r_read_le32
Shadow bytes around the buggy address:
  0x1c5200001c70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c5200001c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c5200001c90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c5200001ca0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c5200001cb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1c5200001cc0: 00 00 00 00[01]fa fa fa fa fa fa fa fa fa fa fa
  0x1c5200001cd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c5200001ce0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c5200001cf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c5200001d00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c5200001d10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==51840==ABORTING
Abort trap: 6
```

**Comment by radare** [comment]
fixed

**Comment by attritionorg** [comment]
@radare Can you link to the fixing commit please?

**Comment by radare** [comment]
It was fixed with another sample

**Comment by radare** [comment]
thank you microsoft for not allowing me to reply images in gh via mail

![image1](https://user-images.githubusercontent.com/917142/53946722-a0612700-40c4-11e9-85d4-eed5c6c5b5d7.jpeg)
