### ISSUE TITLE
ASAN leaks found in linux with r2 -d ls

### ISSUE THREAD

**Issue by radare** [radare/radare2#13147]
```
Module version mismatch /home/pancake/.local/share/radare2/plugins/asm_au.so (3.0.0-git) vs (3.3.0-git)
Module version mismatch /home/pancake/.local/share/radare2/plugins/core_au.so (3.0.0-git) vs (3.3.0-git)
Module version mismatch /home/pancake/.local/share/radare2/plugins/anal_au.so (3.0.0-git) vs (3.3.0-git)
r_config_set: variable 'asm.shortcut' not found
Process with PID 18931 started...
= attach 18931 18931
bin.baddr 0x559357486000
Using 0x559357486000
asm.bits 64
[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001s[?1000h[?1001r[?1000l[?1049l[?47l8Do you want to quit? (Y/n) 
Do you want to kill the process? (Y/n) 

=================================================================
==18929==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6144 byte(s) in 192 object(s) allocated from:
    #0 0x7f46eb701231 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x7f46e8785eef in read_ht_rel /home/pancake/prg/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1281
    #2 0x7f46e8786df6 in rel_cache_new /home/pancake/prg/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1342
    #3 0x7f46e878a212 in get_import_addr /home/pancake/prg/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1635
    #4 0x7f46e87a52d2 in Elf64__r_bin_elf_get_symbols_imports /home/pancake/prg/radare2/libr/..//libr/bin/p/../format/elf/elf.c:3345
    #5 0x7f46e87a8cd5 in Elf64_r_bin_elf_get_imports /home/pancake/prg/radare2/libr/..//libr/bin/p/../format/elf/elf.c:3479
    #6 0x7f46e8758dc9 in imports /home/pancake/prg/radare2/libr/..//libr/bin/p/bin_elf.inc:525
    #7 0x7f46e8638177 in r_bin_object_set_items /home/pancake/prg/radare2/libr/bin/obj.c:350
    #8 0x7f46e86354b8 in r_bin_object_new /home/pancake/prg/radare2/libr/bin/obj.c:239
    #9 0x7f46e862bc36 in r_bin_file_new_from_bytes /home/pancake/prg/radare2/libr/bin/bfile.c:469
    #10 0x7f46e85f4a1c in r_bin_open_io /home/pancake/prg/radare2/libr/bin/bin.c:407
    #11 0x7f46e85f0ed6 in r_bin_open /home/pancake/prg/radare2/libr/bin/bin.c:215
    #12 0x7f46ea6739d4 in r_core_file_do_load_for_debug /home/pancake/prg/radare2/libr/core/cfile.c:319
    #13 0x7f46ea6769ad in r_core_bin_load /home/pancake/prg/radare2/libr/core/cfile.c:536
    #14 0x5572eb270c25 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1228
    #15 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 2261 byte(s) in 7 object(s) allocated from:
    #0 0x7f46eb701231 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x7f46ddd1b7c5 in r_file_slurp /home/pancake/prg/radare2/libr/util/file.c:357
    #2 0x7f46e7d1e705 in linux_info p/native/linux/linux_debug.c:516
    #3 0x7f46e7d0e81e in r_debug_native_info p/debug_native.c:306
    #4 0x7f46e7cc0d9c in r_debug_info /home/pancake/prg/radare2/libr/debug/debug.c:23
    #5 0x7f46ea48e6ac in cmd_debug /home/pancake/prg/radare2/libr/core/cmd_debug.c:4681
    #6 0x7f46ea7b171d in r_cmd_call /home/pancake/prg/radare2/libr/core/cmd_api.c:235
    #7 0x7f46ea65e224 in r_core_cmd_subst_i /home/pancake/prg/radare2/libr/core/cmd.c:3012
    #8 0x7f46ea650b75 in r_core_cmd_subst /home/pancake/prg/radare2/libr/core/cmd.c:2021
    #9 0x7f46ea668341 in r_core_cmd /home/pancake/prg/radare2/libr/core/cmd.c:3746
    #10 0x7f46ea66969d in r_core_cmd0 /home/pancake/prg/radare2/libr/core/cmd.c:3911
    #11 0x7f46ea6edbc2 in visual_refresh /home/pancake/prg/radare2/libr/core/visual.c:3864
    #12 0x7f46ea6f0ef2 in r_core_visual /home/pancake/prg/radare2/libr/core/visual.c:4059
    #13 0x7f46ea64ad29 in cmd_visual /home/pancake/prg/radare2/libr/core/cmd.c:1389
    #14 0x7f46ea7b171d in r_cmd_call /home/pancake/prg/radare2/libr/core/cmd_api.c:235
    #15 0x7f46ea65e224 in r_core_cmd_subst_i /home/pancake/prg/radare2/libr/core/cmd.c:3012
    #16 0x7f46ea650b75 in r_core_cmd_subst /home/pancake/prg/radare2/libr/core/cmd.c:2021
    #17 0x7f46ea668341 in r_core_cmd /home/pancake/prg/radare2/libr/core/cmd.c:3746
    #18 0x7f46ea3ebd83 in r_core_prompt_exec /home/pancake/prg/radare2/libr/core/core.c:2749
    #19 0x5572eb273630 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1486
    #20 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f46eb701231 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x7f46ddd42489 in r_list_new /home/pancake/prg/radare2/libr/util/list.c:171
    #2 0x7f46ddd424be in r_list_newf /home/pancake/prg/radare2/libr/util/list.c:180
    #3 0x7f46ea7802a4 in bin_sections /home/pancake/prg/radare2/libr/core/cbin.c:2451
    #4 0x7f46ea78e57e in r_core_bin_info /home/pancake/prg/radare2/libr/core/cbin.c:3661
    #5 0x7f46ea75e211 in r_core_bin_set_env /home/pancake/prg/radare2/libr/core/cbin.c:133
    #6 0x7f46ea673d97 in r_core_file_do_load_for_debug /home/pancake/prg/radare2/libr/core/cfile.c:342
    #7 0x7f46ea6769ad in r_core_bin_load /home/pancake/prg/radare2/libr/core/cfile.c:536
    #8 0x5572eb270c25 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1228
    #9 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f46eb701231 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x7f46ddd42489 in r_list_new /home/pancake/prg/radare2/libr/util/list.c:171
    #2 0x7f46ddd424be in r_list_newf /home/pancake/prg/radare2/libr/util/list.c:180
    #3 0x7f46ea7802a4 in bin_sections /home/pancake/prg/radare2/libr/core/cbin.c:2451
    #4 0x7f46ea78e5ba in r_core_bin_info /home/pancake/prg/radare2/libr/core/cbin.c:3664
    #5 0x7f46ea75e211 in r_core_bin_set_env /home/pancake/prg/radare2/libr/core/cbin.c:133
    #6 0x7f46ea673d97 in r_core_file_do_load_for_debug /home/pancake/prg/radare2/libr/core/cfile.c:342
    #7 0x7f46ea6769ad in r_core_bin_load /home/pancake/prg/radare2/libr/core/cfile.c:536
    #8 0x5572eb270c25 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1228
    #9 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 14 byte(s) in 1 object(s) allocated from:
    #0 0x7f46eb649f01 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:405
    #1 0x7f46ddd29a67 in r_sys_getenv /home/pancake/prg/radare2/libr/util/sys.c:447
    #2 0x7f46ea6ae335 in r_core_config_init /home/pancake/prg/radare2/libr/core/cconfig.c:2964
    #3 0x7f46ea3e6d65 in r_core_init /home/pancake/prg/radare2/libr/core/core.c:2468
    #4 0x5572eb26b782 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:536
    #5 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7f46eb649f01 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:405
    #1 0x7f46ddcf883f in r_str_new /home/pancake/prg/radare2/libr/util/str.c:683
    #2 0x7f46ddcf8dfb in r_str_newf /home/pancake/prg/radare2/libr/util/str.c:745
    #3 0x7f46e33e556d in __system p/io_ptrace.c:286
    #4 0x7f46e340fc1f in r_io_system /home/pancake/prg/radare2/libr/io/io.c:413
    #5 0x7f46e7cc9236 in r_debug_select /home/pancake/prg/radare2/libr/debug/debug.c:594
    #6 0x7f46ea419cc5 in cmd_debug_pid /home/pancake/prg/radare2/libr/core/cmd_debug.c:1076
    #7 0x7f46ea48e224 in cmd_debug /home/pancake/prg/radare2/libr/core/cmd_debug.c:4654
    #8 0x7f46ea7b171d in r_cmd_call /home/pancake/prg/radare2/libr/core/cmd_api.c:235
    #9 0x7f46ea65e224 in r_core_cmd_subst_i /home/pancake/prg/radare2/libr/core/cmd.c:3012
    #10 0x7f46ea650b75 in r_core_cmd_subst /home/pancake/prg/radare2/libr/core/cmd.c:2021
    #11 0x7f46ea668341 in r_core_cmd /home/pancake/prg/radare2/libr/core/cmd.c:3746
    #12 0x7f46ea6695fa in r_core_cmdf /home/pancake/prg/radare2/libr/core/cmd.c:3905
    #13 0x7f46ea6f20bf in r_core_setup_debugger /home/pancake/prg/radare2/libr/core/cio.c:22
    #14 0x5572eb27213e in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1314
    #15 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7f46eb649f01 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:405
    #1 0x7f46ddcf883f in r_str_new /home/pancake/prg/radare2/libr/util/str.c:683
    #2 0x7f46ddcf8dfb in r_str_newf /home/pancake/prg/radare2/libr/util/str.c:745
    #3 0x7f46e33e556d in __system p/io_ptrace.c:286
    #4 0x7f46e340fc1f in r_io_system /home/pancake/prg/radare2/libr/io/io.c:413
    #5 0x7f46e7cc9236 in r_debug_select /home/pancake/prg/radare2/libr/debug/debug.c:594
    #6 0x7f46ea6917fc in cb_cfgdebug /home/pancake/prg/radare2/libr/core/cconfig.c:1004
    #7 0x7f46e959b691 in r_config_set_i /home/pancake/prg/radare2/libr/config/config.c:587
    #8 0x7f46ea6f1f7c in r_core_setup_debugger /home/pancake/prg/radare2/libr/core/cio.c:12
    #9 0x5572eb27213e in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1314
    #10 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7f46eb649f01 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:405
    #1 0x7f46ddcf883f in r_str_new /home/pancake/prg/radare2/libr/util/str.c:683
    #2 0x7f46ddcf8dfb in r_str_newf /home/pancake/prg/radare2/libr/util/str.c:745
    #3 0x7f46e33e556d in __system p/io_ptrace.c:286
    #4 0x7f46e340fc1f in r_io_system /home/pancake/prg/radare2/libr/io/io.c:413
    #5 0x7f46e7cc9236 in r_debug_select /home/pancake/prg/radare2/libr/debug/debug.c:594
    #6 0x7f46e7cc65fd in r_debug_attach /home/pancake/prg/radare2/libr/debug/debug.c:433
    #7 0x7f46e7cd4b83 in r_debug_get_baddr /home/pancake/prg/radare2/libr/debug/debug.c:1641
    #8 0x5572eb2709ec in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1219
    #9 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7f46eb649f01 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:405
    #1 0x7f46ddcf883f in r_str_new /home/pancake/prg/radare2/libr/util/str.c:683
    #2 0x7f46ddcf8dfb in r_str_newf /home/pancake/prg/radare2/libr/util/str.c:745
    #3 0x7f46e33e556d in __system p/io_ptrace.c:286
    #4 0x7f46e340fc1f in r_io_system /home/pancake/prg/radare2/libr/io/io.c:413
    #5 0x7f46e7cc9236 in r_debug_select /home/pancake/prg/radare2/libr/debug/debug.c:594
    #6 0x7f46ea673849 in r_core_file_do_load_for_debug /home/pancake/prg/radare2/libr/core/cfile.c:304
    #7 0x7f46ea6769ad in r_core_bin_load /home/pancake/prg/radare2/libr/core/cfile.c:536
    #8 0x5572eb270c25 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1228
    #9 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7f46eb649f01 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:405
    #1 0x7f46ddcf883f in r_str_new /home/pancake/prg/radare2/libr/util/str.c:683
    #2 0x7f46ddcf8dfb in r_str_newf /home/pancake/prg/radare2/libr/util/str.c:745
    #3 0x7f46e33e556d in __system p/io_ptrace.c:286
    #4 0x7f46e340fc1f in r_io_system /home/pancake/prg/radare2/libr/io/io.c:413
    #5 0x7f46e7cc9236 in r_debug_select /home/pancake/prg/radare2/libr/debug/debug.c:594
    #6 0x7f46e7cd4ba6 in r_debug_get_baddr /home/pancake/prg/radare2/libr/debug/debug.c:1648
    #7 0x5572eb2709ec in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1219
    #8 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x7f46eb649f01 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:405
    #1 0x5572eb26cf07 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:793
    #2 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Indirect leak of 96 byte(s) in 4 object(s) allocated from:
    #0 0x7f46eb701019 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x7f46ddd4262f in r_list_append /home/pancake/prg/radare2/libr/util/list.c:201
    #2 0x7f46ea782693 in bin_sections /home/pancake/prg/radare2/libr/core/cbin.c:2574
    #3 0x7f46ea78e5ba in r_core_bin_info /home/pancake/prg/radare2/libr/core/cbin.c:3664
    #4 0x7f46ea75e211 in r_core_bin_set_env /home/pancake/prg/radare2/libr/core/cbin.c:133
    #5 0x7f46ea673d97 in r_core_file_do_load_for_debug /home/pancake/prg/radare2/libr/core/cfile.c:342
    #6 0x7f46ea6769ad in r_core_bin_load /home/pancake/prg/radare2/libr/core/cfile.c:536
    #7 0x5572eb270c25 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1228
    #8 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

Indirect leak of 96 byte(s) in 4 object(s) allocated from:
    #0 0x7f46eb701019 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x7f46ea782483 in bin_sections /home/pancake/prg/radare2/libr/core/cbin.c:2565
    #2 0x7f46ea78e5ba in r_core_bin_info /home/pancake/prg/radare2/libr/core/cbin.c:3664
    #3 0x7f46ea75e211 in r_core_bin_set_env /home/pancake/prg/radare2/libr/core/cbin.c:133
    #4 0x7f46ea673d97 in r_core_file_do_load_for_debug /home/pancake/prg/radare2/libr/core/cfile.c:342
    #5 0x7f46ea6769ad in r_core_bin_load /home/pancake/prg/radare2/libr/core/cfile.c:536
    #6 0x5572eb270c25 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:1228
    #7 0x7f46dcc9f222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

SUMMARY: AddressSanitizer: 8708 byte(s) leaked in 216 allocation(s).

```

**Comment by radare** [comment]
lot of thing shave changed in here and we are consstantly fixing memleaks, crashess, when we found them. closing
