### ISSUE TITLE
pv pV

### ISSUE THREAD

**Issue by radare** [radare/radare2#14165]
* [x] Make pv accept an argument (pv 32 -> shows nothing)
* [ ] Implement pv* ... how may this work? maybe as oneline instead of many :?
* [x] Fix pv crash (with no args it reads one by away)
* [ ] Fix pvj 32/pv2j 32 - only 1 value is shown, that must be an array of 32 values
* [x] Implement pV must work like pD vs pd, this is, if we do pV2 32, it should show the 2 byte values that fit in 32 bits, instead of 32 values of 2 bytes

**Comment by radare** [comment]
Also fix this crash:

```
[0x00000000]> pv
=================================================================
==46818==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000dcb53 at pc 0x000107c2ff0a bp 0x7ffeeca6f9b0 sp 0x7ffeeca6f9a8
READ of size 1 at 0x6020000dcb53 thread T0
    #0 0x107c2ff09 in cmd_print_pv cmd_print.c:2828
    #1 0x1079fcd40 in cmd_print cmd_print.c:4654
    #2 0x107edd7a5 in r_cmd_call cmd_api.c:244
    #3 0x107a88ef8 in r_core_cmd_subst_i cmd.c:3276
    #4 0x107942e0f in r_core_cmd_subst cmd.c:2172
    #5 0x107928bf8 in r_core_cmd cmd.c:4111
    #6 0x1078c4ff4 in r_core_prompt_exec core.c:2812
    #7 0x10d524adc in r_main_radare2 radare2.c:1473
    #8 0x103183cd1 in main radare2.c:48
    #9 0x7fff76b053d4 in start (libdyld.dylib:x86_64+0x163d4)

0x6020000dcb53 is located 0 bytes to the right of 3-byte region [0x6020000dcb50,0x6020000dcb53)
allocated by thread T0 here:
    #0 0x10d67210c in wrap_strdup (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x5610c)
    #1 0x107940f55 in r_core_cmd_subst cmd.c:2101
    #2 0x107928bf8 in r_core_cmd cmd.c:4111
    #3 0x1078c4ff4 in r_core_prompt_exec core.c:2812
    #4 0x10d524adc in r_main_radare2 radare2.c:1473
    #5 0x103183cd1 in main radare2.c:48
    #6 0x7fff76b053d4 in start (libdyld.dylib:x86_64+0x163d4)

SUMMARY: AddressSanitizer: heap-buffer-overflow cmd_print.c:2828 in cmd_print_pv
Shadow bytes around the buggy address:
  0x1c040001b910: fa fa 04 fa fa fa 04 fa fa fa 03 fa fa fa 04 fa
  0x1c040001b920: fa fa 03 fa fa fa 04 fa fa fa 03 fa fa fa 04 fa
  0x1c040001b930: fa fa 05 fa fa fa 04 fa fa fa 04 fa fa fa 03 fa
  0x1c040001b940: fa fa 02 fa fa fa 03 fa fa fa 04 fa fa fa 04 fa
  0x1c040001b950: fa fa 04 fa fa fa 03 fa fa fa fd fa fa fa fd fa
=>0x1c040001b960: fa fa 03 fa fa fa 03 fa fa fa[03]fa fa fa 01 fa
  0x1c040001b970: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c040001b980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c040001b990: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c040001b9a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c040001b9b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==46818==ABORTING
Abort trap: 6
$
```

**Comment by radare** [comment]
i fixed the crash, will do this pr later today. tired of watiing

**Comment by XVilka** [comment]
Will need tests
