### ISSUE TITLE
Heap out of bounds read in r_read_le32() (wasm_dis:641 - WASM_OP_F32CONST)

### ISSUE THREAD

**Issue by pventuzelo** [radare/radare2#14233]
Same kind of bug than #14228.
But on `case WASM_OP_F32CONST` this time

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04 x64
| File format of the file you reverse (mandatory)      | WASM
| Architecture/bits of the file (mandatory)            | WASM
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 21948 @ linux-x86-64 git.3.5.1-165-gd2f6640c5 commit: d2f6640c5b3d223282f92b0b2b2cbe2db530d1e8 build: 2019-06-06__07:31:23

### Expected behavior

Disassembly of file or error message.

### Actual behavior

Heap out of bounds read in ASAN build.

### Steps to reproduce the behavior 
- Download: [r2_hoobr_wasm_r_read_le32_641.zip](https://github.com/radare/radare2/files/3260165/r2_hoobr_wasm_r_read_le32_641.zip)

- Run: `r2 -A r2_hoobr_wasm_r_read_le32_641`

### Additional Logs, screenshots, source-code,  configuration dump, ...

ASAN report:
```
==8864==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61100004dbc0 at pc 0x7f8eda74c513 bp 0x7ffdf7ead5c0 sp 0x7ffdf7ead5b0
READ of size 1 at 0x61100004dbc0 thread T0
    #0 0x7f8eda74c512 in r_read_le32 XYZ/radare2/libr/include/r_endian.h:176
    #1 0x7f8eda74c674 in r_read_at_le32 XYZ/radare2/libr/include/r_endian.h:185
    #2 0x7f8eda74ed80 in wasm_dis XYZ/radare2/libr/..//libr/anal/p/../../asm/arch/wasm/wasm.c:641
    #3 0x7f8eda750556 in wasm_op XYZ/radare2/libr/..//libr/anal/p/anal_wasm.c:79
    #4 0x7f8eda797c56 in r_anal_op XYZ/radare2/libr/anal/op.c:153
    #5 0x7f8ede95693b in r_core_anal_search_xrefs XYZ/radare2/libr/core/canal.c:3680
    #6 0x7f8ede711319 in r_core_anal_refs XYZ/radare2/libr/core/cmd_anal.c:7641
    #7 0x7f8ede7177ae in cmd_anal_all XYZ/radare2/libr/core/cmd_anal.c:8212
    #8 0x7f8ede71ecdd in cmd_anal XYZ/radare2/libr/core/cmd_anal.c:9051
    #9 0x7f8ede9213c5 in r_cmd_call XYZ/radare2/libr/core/cmd_api.c:244
    #10 0x7f8ede808ce7 in r_core_cmd_subst_i XYZ/radare2/libr/core/cmd.c:3276
    #11 0x7f8ede7fd1ed in r_core_cmd_subst XYZ/radare2/libr/core/cmd.c:2172
    #12 0x7f8ede812076 in r_core_cmd XYZ/radare2/libr/core/cmd.c:4111
    #13 0x7f8ede81315a in r_core_cmd0 XYZ/radare2/libr/core/cmd.c:4276
    #14 0x7f8ee634bb6d in r_main_radare2 XYZ/radare2/libr/main/radare2.c:1391
    #15 0x5559b6685829 in main XYZ/radare2/binr/radare2/radare2.c:48
    #16 0x7f8ee51e3b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #17 0x5559b6685729 in _start (XYZ/radare2/binr/radare2/radare2+0x729)

0x61100004dbc0 is located 0 bytes to the right of 256-byte region [0x61100004dac0,0x61100004dbc0)
allocated by thread T0 here:
    #0 0x7f8ee6700b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7f8ede956481 in r_core_anal_search_xrefs XYZ/radare2/libr/core/canal.c:3647
    #2 0x7f8ede711319 in r_core_anal_refs XYZ/radare2/libr/core/cmd_anal.c:7641
    #3 0x7f8ede7177ae in cmd_anal_all XYZ/radare2/libr/core/cmd_anal.c:8212
    #4 0x7f8ede71ecdd in cmd_anal XYZ/radare2/libr/core/cmd_anal.c:9051
    #5 0x7f8ede9213c5 in r_cmd_call XYZ/radare2/libr/core/cmd_api.c:244
    #6 0x7f8ede808ce7 in r_core_cmd_subst_i XYZ/radare2/libr/core/cmd.c:3276
    #7 0x7f8ede7fd1ed in r_core_cmd_subst XYZ/radare2/libr/core/cmd.c:2172
    #8 0x7f8ede812076 in r_core_cmd XYZ/radare2/libr/core/cmd.c:4111
    #9 0x7f8ede81315a in r_core_cmd0 XYZ/radare2/libr/core/cmd.c:4276
    #10 0x7f8ee634bb6d in r_main_radare2 XYZ/radare2/libr/main/radare2.c:1391
    #11 0x5559b6685829 in main XYZ/radare2/binr/radare2/radare2.c:48
    #12 0x7f8ee51e3b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: heap-buffer-overflow XYZ/radare2/libr/include/r_endian.h:176 in r_read_le32
Shadow bytes around the buggy address:
  0x0c2280001b20: fd fd fd fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2280001b30: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2280001b40: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa
  0x0c2280001b50: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c2280001b60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c2280001b70: 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa
  0x0c2280001b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2280001b90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2280001ba0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c2280001bb0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2280001bc0: fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==8864==ABORTING
```

**Comment by radare** [comment]
The fix was easy 9ad57021d941be0385b1b430e31b60cc97a6e92b

Do you want to try to fix those easy issues before reporting the  crash next time? its usually 1-2 lines of C, that 1 byte oobread issue which may lead on UB on non-asan builds should be easy to spot and fix by hand in the other instructions

**Comment by pventuzelo** [comment]
Yes sure, i can try to provide patch(pull request) next time if i found new bugs in the future ;)

**Comment by radare** [comment]
reporting the crashes is fine :) i fix them asap, but i just want to flatten the  introduction  to new contributors so i can focus on more important things than fixing simple bugs.

thanks!
