### ISSUE TITLE
Wrong backtrace using dbt

### ISSUE THREAD

**Issue by iGr33k** [radare/radare2#14986]
This is related to https://github.com/radare/radare2/issues/8823#issue-273307071

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Manjaro x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            |  x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.8.0 22671 @ linux-x86-64                                      git.3.8.0-23-g5bb241711  commit: ```5bb241711983c5d8b548c7980058f1dda67fb5d6``` build: 2019-09-08__00:58:25

### Expected behavior
`dbt` in r2 shows the same backtrace addresses as `bt` in gdb.

#### gdb's `bt` output:
`#0  0x0000000000400810 in pwnme ()`
`#1  0x41415041414f4141 in ?? ()`
`#2  0x0000000000400051 in ?? ()`
`#3  0x00007ffff7df6ee3 in __libc_start_main () from /usr/lib/libc.so.6`
`#4  0x0000000000400679 in _start ()`
#### r2's `dbt` output:
`0  0x00400810 sp: 0x00000000 0    [??]  rip `
`1  0x7f8c418d8ee3 sp: 0x7ffd602ff8a8 16   [??]  rsi+1071295618 `
`2  0x7f8c41ac08a1 sp: 0x7ffd602ff938 144  [??]  map.usr_lib_ld_2.29.so.r_x+59553 `
`3  0x00400679 sp: 0x7ffd602ff968 48   [??]  entry0+41 `

After crashing program with cyclic pattern in gdb, bt shows address which can be used to calculate offset. In r2 that cant be done.
`pxq @rsp` shows the string with pattern.

#### in r2:
- open binary with `r2 -R stdin=./test.txt -d ret2win`
- `dc`
- `dbt`
#### in gdb:
- open binary `gdb ret2win`
- `r < test.txt`
- `bt`
### Additional Logs, screenshots, source-code,  configuration dump, ...

[ret2win.zip](https://github.com/radare/radare2/files/3587096/ret2win.zip)

**Comment by abcSup** [comment]
> gdb's bt output:
> ```
> #0 0x0000000000400810 in pwnme ()
> #1 0x41415041414f4141 in ?? ()
> #2 0x0000000000400051 in ?? ()
> #3 0x00007ffff7df6ee3 in __libc_start_main () from /usr/lib/libc.so.6
> #4 0x0000000000400679 in _start ()
> ```
I actually looked into this weeks ago and was researching on how `gdb` is able to keep track of the stack frames. It turned out that `gdb` does not actively keep track of the stack frames during execution and the backtrace is generated on requests. I also asked in their irc and was told that `gdb` should not be able to resolve the stack frames past `#1 0x41415041414f4141 in ?? ()` because the base stack pointer is already corrupted. But, what you are expecting is right. `r2` should at least output the corrupted return address.

What `r2` does in default (`fuzzy`) is going through the stack frames beginning from `esp/rsp` and searching for values for that look like addresses pointing to somewhere in executable memory maps, so it skips the corrupted return address in this case.

Currently, there are `fuzzy` and `anal` types of backtrace analysis in native Linux debugger, which can be set with `e dbg.btalgo`. I will try fixing the `anal` backtrace analysis because that seems to be the best way to resolve the stack frames for now. Backtrace analysis could definitely be improved with `DWARF` infos in future.
