### ISSUE TITLE
PDB crashes

### ISSUE THREAD

**Issue by radare** [radare/radare2#1631]
I have fuzzed a bit with asan and tried rabin2 -P. i fixed 2 bugs but asan fails to run on test.pdb
to build with asan just execute the sys/asan.sh script.

```
$ rabin2 -P test.pdb 
=================================================================
==22048==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200001cb7a at pc 0x7fced4025339 bp 0x7fffa1821e00 sp 0x7fffa1821df0
READ of size 1 at 0x60200001cb7a thread T0
    #0 0x7fced4025338 in parse_lf_arglist pdb/tpi.c:2032
    #1 0x7fced4027ac5 in parse_tpi_stypes pdb/tpi.c:2193
    #2 0x7fced4028131 in parse_tpi_stream pdb/tpi.c:2246
    #3 0x7fced402b7ff in pdb_read_root pdb/pdb.c:328
    #4 0x7fced402c408 in pdb7_parse pdb/pdb.c:459
    #5 0x7fced469b308 in bin_pdb /home/pancake/prg/radare2/libr/core/bin.c:476
    #6 0x7fced46a30b4 in r_core_bin_info /home/pancake/prg/radare2/libr/core/bin.c:1337
    #7 0x405be2 in main /home/pancake/prg/radare2/binr/rabin2/rabin2.c:687
    #8 0x7fced349b03f in __libc_start_main (/usr/lib/libc.so.6+0x2003f)
    #9 0x401ca8 (/home/pancake/prg/radare2/binr/rabin2/rabin2+0x401ca8)

0x60200001cb7a is located 11424613120106 bytes to the right of global variable '' from '' (0x4a5c00001220) of size 12506944766192
ASAN:SIGSEGV
==22048==AddressSanitizer: while reporting a bug found another one.Ignoring.

```

**Comment by radare** [comment]
Can anyone confirm? we have already fixed some of those issues

**Comment by radare** [comment]
Cant reproduce anymore
