### ISSUE TITLE
[zzuf] more afi/afo 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#1994]
morrn,

*32bit*

zzuf -s 0:1000000 -c -C 0 -q -T 5 -M 100 r2 -qc "afi;afo sym.main" ./a.out.bak 2>log

```
Warning: read (sym)
Warning: read (sym)
Invalid phdr.filesz value 0x401040
Invalid phdr.filesz value 0x400200
Invalid phdr.filesz value 0x400000
Invalid phdr.filesz value 0x600900
Invalid phdr.filesz value 0x600918
Invalid phdr.filesz value 0x40021c
Invalid phdr.filesz value 0x4007d4
Warning: read (sym)
Error reading r_offset
Error reading r_offset
*** glibc detected *** r2: malloc(): memory corruption: 0x0975aa40 ***

Program terminated with signal 6, Aborted.
#0  0xb76f2424 in __kernel_vsyscall ()
(gdb) bt
#0  0xb76f2424 in __kernel_vsyscall ()
#1  0xb6873661 in *__GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#2  0xb6876a92 in *__GI_abort () at abort.c:92
#3  0xb68afba5 in __libc_message (do_abort=2, fmt=0xb698a970 "*** glibc detected *** %s: %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:189
#4  0xb68b9c91 in malloc_printerr (action=<optimized out>, str=0x6 <Address 0x6 out of bounds>, ptr=0x90f7a40) at malloc.c:6312
#5  0xb68bca74 in _int_malloc (av=<optimized out>, bytes=<optimized out>) at malloc.c:4425
#6  0xb68bde1b in __libc_calloc (n=1, elem_size=40) at malloc.c:4094
#7  0xb7545e11 in reloc_convert (bin=0x90e5fc8, rel=0x90f7908, GOT=6294264) at /home/zlul/radare2/libr/..//libr/bin/p/bin_elf.c:369
#8  0xb75468c9 in relocs (arch=0x90e07f0) at /home/zlul/radare2/libr/..//libr/bin/p/bin_elf.c:487
#9  0xb75269b5 in r_bin_object_set_items (binfile=0x90e07f0, o=0x90e5e88) at bin.c:383
#10 0xb75283da in r_bin_object_new (binfile=0x90e07f0, plugin=0x90ae6c8, baseaddr=0, loadaddr=0, offset=0, sz=8473) at bin.c:872
#11 0xb7528a71 in r_bin_file_new_from_bytes (bin=0x90aa730, file=0x90e7aa0 "fu.684", bytes=0x90de6d0 "\177ELF\002\001\001", sz=8473, file_sz=8473, rawstr=0, baseaddr=0, loadaddr=0, fd=6, pluginname=0x0,
    xtrname=0x0, offset=0) at bin.c:983
#12 0xb75276bd in r_bin_load_io_at_offset_as_sz (bin=0x90aa730, desc=0x90de628, baseaddr=0, loadaddr=0, xtr_idx=0, offset=0, name=0x0, sz=8473) at bin.c:584
#13 0xb7527786 in r_bin_load_io_at_offset_as (bin=0x90aa730, desc=0x90de628, baseaddr=0, loadaddr=0, xtr_idx=0, offset=0, name=0x0) at bin.c:599
#14 0xb752712f in r_bin_load_io (bin=0x90aa730, desc=0x90de628, baseaddr=0, loadaddr=0, xtr_idx=0) at bin.c:498
#15 0xb7667ce8 in r_core_file_do_load_for_io_plugin (r=0x804e4c0, baseaddr=0, loadaddr=0) at file.c:340
#16 0xb76680f3 in r_core_bin_load (r=0x804e4c0, filenameuri=0x90e7aa0 "fu.684", baddr=0) at file.c:472
#17 0x0804bc23 in main (argc=2, argv=0xbf909c54, envp=0xbf909c60) at radare2.c:532
(gdb) i r
eax            0x0      0
ecx            0x4bda   19418
edx            0x6      6
ebx            0x4bda   19418
esp            0xbf908924       0xbf908924
ebp            0xbf90893c       0xbf90893c
esi            0x0      0
edi            0xb69a9ff4       -1231380492
eip            0xb76f2424       0xb76f2424 <__kernel_vsyscall+16>
eflags         0x200202 [ IF ID ]
cs             0x73     115
ss             0x7b     123
ds             0x7b     123
es             0x7b     123
fs             0x0      0
gs             0x33     51
```

fuzzed_file: (base64)
http://sprunge.us/UhNZ

r2 -v
radare2 0.9.9-git @ linux-little-x86-32 git.0.9.8-546-g9681c6f
commit: 9681c6fcf789c363121786ffbc5d925d7cae9d35 build: 2015-01-25

Greetings
--zlul

**Comment by zonkzonk** [comment]
==19516== Memcheck, a memory error detector
==19516== Copyright (C) 2002-2011, and GNU GPL'd, by Julian Seward et al.
==19516== Using Valgrind-3.7.0 and LibVEX; rerun with -h for copyright info
==19516== Command: r2 fu.684 fuzzed_file
==19516== Parent PID: 15887
==19516== 
==19516== Invalid write of size 4
==19516==    at 0x4197EDA: Elf64_r_bin_elf_read_reloc (elf.c:885)
==19516==    by 0x4198222: Elf64_r_bin_elf_get_relocs (elf.c:951)
==19516==    by 0x4193882: relocs (bin_elf.c:484)
==19516==    by 0x41739B4: r_bin_object_set_items (bin.c:383)
==19516==    by 0x41753D9: r_bin_object_new (bin.c:872)
==19516==    by 0x4175A70: r_bin_file_new_from_bytes (bin.c:983)
==19516==    by 0x41746BC: r_bin_load_io_at_offset_as_sz (bin.c:584)
==19516==    by 0x4174785: r_bin_load_io_at_offset_as (bin.c:599)
==19516==    by 0x417412E: r_bin_load_io (bin.c:498)
==19516==    by 0x409FCE7: r_core_file_do_load_for_io_plugin (file.c:340)
==19516==    by 0x40A00F2: r_core_bin_load (file.c:472)
==19516==    by 0x804BC22: main (radare2.c:532)
==19516==  Address 0x501731c is 8 bytes after a block of size 308 alloc'd
==19516==    at 0x4026A68: calloc (vg_replace_malloc.c:566)
==19516==    by 0x4197FD4: Elf64_r_bin_elf_get_relocs (elf.c:914)
==19516==    by 0x4193882: relocs (bin_elf.c:484)
==19516==    by 0x41739B4: r_bin_object_set_items (bin.c:383)
==19516==    by 0x41753D9: r_bin_object_new (bin.c:872)
==19516==    by 0x4175A70: r_bin_file_new_from_bytes (bin.c:983)
==19516==    by 0x41746BC: r_bin_load_io_at_offset_as_sz (bin.c:584)
==19516==    by 0x4174785: r_bin_load_io_at_offset_as (bin.c:599)
==19516==    by 0x417412E: r_bin_load_io (bin.c:498)
==19516==    by 0x409FCE7: r_core_file_do_load_for_io_plugin (file.c:340)
==19516==    by 0x40A00F2: r_core_bin_load (file.c:472)
==19516==    by 0x804BC22: main (radare2.c:532)
==19516== 
==19516== Invalid write of size 4
==19516==    at 0x4197EE6: Elf64_r_bin_elf_read_reloc (elf.c:886)
==19516==    by 0x4198222: Elf64_r_bin_elf_get_relocs (elf.c:951)
==19516==    by 0x4193882: relocs (bin_elf.c:484)
==19516==    by 0x41739B4: r_bin_object_set_items (bin.c:383)
==19516==    by 0x41753D9: r_bin_object_new (bin.c:872)
==19516==    by 0x4175A70: r_bin_file_new_from_bytes (bin.c:983)
==19516==    by 0x41746BC: r_bin_load_io_at_offset_as_sz (bin.c:584)
==19516==    by 0x4174785: r_bin_load_io_at_offset_as (bin.c:599)
==19516==    by 0x417412E: r_bin_load_io (bin.c:498)
==19516==    by 0x409FCE7: r_core_file_do_load_for_io_plugin (file.c:340)
==19516==    by 0x40A00F2: r_core_bin_load (file.c:472)
==19516==    by 0x804BC22: main (radare2.c:532)
==19516==  Address 0x5017328 is not stack'd, malloc'd or (recently) free'd
==19516== 
==19516== Invalid write of size 4
==19516==    at 0x4197EE9: Elf64_r_bin_elf_read_reloc (elf.c:886)
==19516==    by 0x4198222: Elf64_r_bin_elf_get_relocs (elf.c:951)
==19516==    by 0x4193882: relocs (bin_elf.c:484)
==19516==    by 0x41739B4: r_bin_object_set_items (bin.c:383)
:
