### ISSUE TITLE
[zzuf] sig11  0x00007f2c9548b5e6 in r_uleb128

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2000]
morn,

```
,r2 fuzzed-file.sig11.18053 
Warning: read (sym)
Warning: read (sym)
Warning: read (libs)
Warning: read (sym)
Warning: read (sym)
Ignore section with invalid shsize
DWARF: Unexpected pointer size: 9
Segmentation fault


Core was generated by `r2 fuzzed-file.sig11.18053'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2c9548b5e6 in r_uleb128 (data=0x1 <error: Cannot access memory at address 0x1>, datalen=65535, v=0x7fff868f0238) at uleb128.c:18
18                      if (*data) {
(gdb) bt
#0  0x00007f2c9548b5e6 in r_uleb128 (data=0x1 <error: Cannot access memory at address 0x1>, datalen=65535, v=0x7fff868f0238) at uleb128.c:18
#1  0x00007f2c98131111 in r_bin_dwarf_parse_comp_unit (s=0x116dfc0, obuf=0x11868ab "", cu=0x11868e0, da=0x1185f40, offset=0, 
    debug_str=0x11867f0 "long long int", debug_str_len=168) at dwarf.c:1273
#2  0x00007f2c981316fc in r_bin_dwarf_parse_info_raw (s=0x116dfc0, da=0x1185f40, obuf=0x11868a0 ",", len=48, debug_str=0x11867f0 "long long int", 
    debug_str_len=168, mode=2) at dwarf.c:1358
#3  0x00007f2c98131c64 in r_bin_dwarf_parse_info (da=0x1185f40, a=0x1122210, mode=2) at dwarf.c:1483
#4  0x00007f2c98ca3bf9 in bin_dwarf (core=0x606c00 <r>, mode=2) at bin.c:435
#5  0x00007f2c98ca7d0f in r_core_bin_info (core=0x606c00 <r>, action=4095, mode=2, va=1, filter=0x0, loadaddr=0, chksum=0x0) at bin.c:1482
#6  0x00007f2c98ca268b in r_core_bin_set_env (r=0x606c00 <r>, binfile=0x116dd00) at bin.c:94
#7  0x00007f2c98c8fca1 in r_core_file_do_load_for_io_plugin (r=0x606c00 <r>, baseaddr=0, loadaddr=0) at file.c:346
#8  0x00007f2c98c90057 in r_core_bin_load (r=0x606c00 <r>, filenameuri=0x11528f0 "fuzzed-file.sig11.18053", baddr=0) at file.c:473
#9  0x0000000000404254 in main (argc=2, argv=0x7fff868f0d78, envp=0x7fff868f0d90) at radare2.c:532
(gdb) 
```

fuuzzed_file:
http://sprunge.us/DVWf

r2 -v
radare2 0.9.9-git @ linux-little-x86-64 git.0.9.8-564-gead2bdc
commit: ead2bdcf50fa15bcc9bd38fd86ddb01e11c480f2 build: 2015-01-28

Greetings
--zlul

**Comment by crowell** [comment]
I have a fix, one minute :+1:

**Comment by radare** [comment]
I also had a fix, but valgrind showed me i was wrong with some oob reads more. Pla verify with valgrind before pushing :)
