### ISSUE TITLE
[zzuf] signal 11 0x00007f4903d3a5fc in relocs

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2011]
morn,

```
,r2 fuzzed_file.191277 
Warning: read (dyn)
Warning: read (dyn)
Warning: index out of strtab range
Ignore section with invalid shsize
Segmentation fault (core dumped)

Core was generated by `r2 fuzzed_file.191277'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4903d3a5fc in relocs (arch=0x2437cd0) at /home/zlul/src/radare2/libr/..//libr/bin/p/bin_elf.c:486
486                     for (i = 0; !relocs[i].last; i++) {
(gdb) bt
#0  0x00007f4903d3a5fc in relocs (arch=0x2437cd0) at /home/zlul/src/radare2/libr/..//libr/bin/p/bin_elf.c:486
#1  0x00007f4903d199cd in r_bin_object_set_items (binfile=0x2437cd0, o=0x24348d0) at bin.c:383
#2  0x00007f4903d1b2a8 in r_bin_object_new (binfile=0x2437cd0, plugin=0x23f1100, baseaddr=0, loadaddr=0, offset=0, sz=8473) a
#3  0x00007f4903d1b88a in r_bin_file_new_from_bytes (bin=0x23ec2d0, file=0x2438210 "fuzzed_file.191277", bytes=0x242d250 "\17
    sz=8473, file_sz=8473, rawstr=0, baseaddr=0, loadaddr=0, fd=6, pluginname=0x0, xtrname=0x0, offset=0) at bin.c:996
#4  0x00007f4903d1a618 in r_bin_load_io_at_offset_as_sz (bin=0x23ec2d0, desc=0x2437bd0, baseaddr=0, loadaddr=0, xtr_idx=0, of
    at bin.c:594
#5  0x00007f4903d1a6bd in r_bin_load_io_at_offset_as (bin=0x23ec2d0, desc=0x2437bd0, baseaddr=0, loadaddr=0, xtr_idx=0, offse
#6  0x00007f4903d1a0df in r_bin_load_io (bin=0x23ec2d0, desc=0x2437bd0, baseaddr=0, loadaddr=0, xtr_idx=0) at bin.c:498
#7  0x00007f4904880f4b in r_core_file_do_load_for_io_plugin (r=0x607980 <r>, baseaddr=0, loadaddr=0) at file.c:342
#8  0x00007f4904881335 in r_core_bin_load (r=0x607980 <r>, filenameuri=0x2438210 "fuzzed_file.191277", baddr=0) at file.c:474
#9  0x00000000004042a8 in main (argc=2, argv=0x7fff19a50c68, envp=0x7fff19a50c80) at radare2.c:534
```
fuzzed_file (b64):
http://sprunge.us/SSSG

r2 -v
8c1cdc205283373503ec3aaddedb3bd5ef3c19b6

Greetings
--zlul

**Comment by zonkzonk** [comment]
also crashes valgrind:

==11646== Memcheck, a memory error detector
==11646== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==11646== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==11646== Command: r2 fuzzed_file.191277
==11646== Parent PID: 515
==11646== 
==11646== Invalid write of size 4
==11646==    at 0x5BBCCF7: Elf64_r_bin_elf_get_relocs (elf.c:977)
==11646==    by 0x5BB8577: relocs (bin_elf.c:484)
==11646==    by 0x5B979CC: r_bin_object_set_items (bin.c:383)
==11646==    by 0x5B992A7: r_bin_object_new (bin.c:885)
==11646==    by 0x5B99889: r_bin_file_new_from_bytes (bin.c:996)
==11646==    by 0x5B98617: r_bin_load_io_at_offset_as_sz (bin.c:594)
==11646==    by 0x5B986BC: r_bin_load_io_at_offset_as (bin.c:612)
==11646==    by 0x5B980DE: r_bin_load_io (bin.c:498)
==11646==    by 0x50A65D3: r_core_file_do_load_for_io_plugin (file.c:342)
==11646==    by 0x50A69BD: r_core_bin_load (file.c:474)
==11646==    by 0x4042A7: main (radare2.c:534)
==11646==  Address 0x992c91c is 20 bytes before an unallocated block of size 2,651,824 in arena "client"
==11646== 
--11646-- VALGRIND INTERNAL ERROR: Valgrind received a signal 11 (SIGSEGV) - exiting
--11646-- si_code=1;  Faulting address: 0x10992C910;  sp: 0x802b9ddb0

valgrind: the 'impossible' happened:
   Killed by fatal signal

host stacktrace:
==11646==    at 0x380B4191: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==11646==    by 0x380B63B3: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==11646==    by 0x38076EA4: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==11646==    by 0x380771F2: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==11646==    by 0x380FAEFA: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==11646==    by 0x38109F90: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable
==11646==    at 0x4C2C080: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11646==    by 0x5BB7A66: reloc_convert (bin_elf.c:369)
==11646==    by 0x5BB85D0: relocs (bin_elf.c:487)
==11646==    by 0x5B979CC: r_bin_object_set_items (bin.c:383)
==11646==    by 0x5B992A7: r_bin_object_new (bin.c:885)
==11646==    by 0x5B99889: r_bin_file_new_from_bytes (bin.c:996)
==11646==    by 0x5B98617: r_bin_load_io_at_offset_as_sz (bin.c:594)
==11646==    by 0x5B986BC: r_bin_load_io_at_offset_as (bin.c:612)
==11646==    by 0x5B980DE: r_bin_load_io (bin.c:498)
==11646==    by 0x50A65D3: r_core_file_do_load_for_io_plugin (file.c:342)
==11646==    by 0x50A69BD: r_core_bin_load (file.c:474)
==11646==    by 0x4042A7: main (radare2.c:534)


Note: see also the FAQ in the source distribution.
It contains workarounds to several common problems.
In particular, if Valgrind aborted or crashed after
identifying problems in your program, there's a good chance
that fixing those problems will prevent Valgrind aborting or
crashing, especially if it happened in m_mallocfree.c.

If that doesn't help, please report this bug to: www.valgrind.org

In the bug report, send all the above text, the valgrind
version, and what OS and version you are using.  Thanks.
