### ISSUE TITLE
pDj high load + segfault

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2102]
morn

```
[0x00400610]> af
[0x00400610]> pDj
Segmentation fault (core dumped)
```

,r2 -v
radare2 0.9.9-git 7117 @ linux-little-x86-64 git.0.9.8-769-g87ae355
commit: 87ae355a3afbcb3513dd5b5e663f39fce6d55f63 build: 2015-02-16

Greetings
--zlul

**Comment by zonkzonk** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00Program received signal SIGSEGV, Segmentation fault.
0x00007ffff39f2559 in __memcpy_sse2_unaligned () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff39f2559 in __memcpy_sse2_unaligned () from /usr/lib/libc.so.6
#1  0x00007ffff729ece0 in r_cons_memcat (str=0x7ffff79c18da ",\"size\":1,\"type\":\"invalid\"}", len=27) at cons.c:527
#2  0x00007ffff729edb9 in r_cons_strcat (str=0x7ffff79c18da ",\"size\":1,\"type\":\"invalid\"}") at cons.c:547
#3  0x00007ffff729ec0e in r_cons_printf (format=0x7ffff79c18da ",\"size\":1,\"type\":\"invalid\"}") at cons.c:510
#4  0x00007ffff7999230 in r_core_print_disasm_json (core=0x607980 <r>, addr=4212927, 
    buf=0x6700e0 "1\355I\211\321^H\211\342H\203\344\360PTI\307\300@\"A", nb_bytes=0, nb_opcodes=0) at disasm.c:2453
#5  0x00007ffff794a35c in cmd_pDj (core=0x607980 <r>, arg=0x682803 "") at cmd_print.c:16
#6  0x00007ffff795041a in cmd_print (data=0x607980 <r>, input=0x682801 "Dj") at cmd_print.c:1516
#7  0x00007ffff798100c in r_cmd_call (cmd=0x6ab510, input=0x682800 "pDj") at cmd_api.c:179
#8  0x00007ffff795f618 in r_core_cmd_subst_i (core=0x607980 <r>, cmd=0x682800 "pDj", colon=0x0) at cmd.c:1437
#9  0x00007ffff795dd33 in r_core_cmd_subst (core=0x607980 <r>, cmd=0x682800 "pDj") at cmd.c:981
#10 0x00007ffff7960002 in r_core_cmd (core=0x607980 <r>, cstr=0x6d7680 "pDj", log=1) at cmd.c:1628
#11 0x00007ffff7925cd4 in r_core_prompt_exec (r=0x607980 <r>) at core.c:1015
#12 0x0000000000404f79 in main (argc=2, argv=0x7fffffffebc8, envp=0x7fffffffebe0) at radare2.c:742
007ffff39f2559 in __memcpy_sse2_unaligned () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff39f2559 in __memcpy_sse2_unaligned () from /usr/lib/libc.so.6
#1  0x00007ffff729ece0 in r_cons_memcat (str=0x7ffff79c18da ",\"size\":1,\"type\":\"invalid\"}", len=27) at cons.c:527
#2  0x00007ffff729edb9 in r_cons_strcat (str=0x7ffff79c18da ",\"size\":1,\"type\":\"invalid\"}") at cons.c:547
#3  0x00007ffff729ec0e in r_cons_printf (format=0x7ffff79c18da ",\"size\":1,\"type\":\"invalid\"}") at cons.c:510
#4  0x00007ffff7999230 in r_core_print_disasm_json (core=0x607980 <r>, addr=4212927, 
    buf=0x6700e0 "1\355I\211\321^H\211\342H\203\344\360PTI\307\300@\"A", nb_bytes=0, nb_opcodes=0) at disasm.c:2453
#5  0x00007ffff794a35c in cmd_pDj (core=0x607980 <r>, arg=0x682803 "") at cmd_print.c:16
#6  0x00007ffff795041a in cmd_print (data=0x607980 <r>, input=0x682801 "Dj") at cmd_print.c:1516
#7  0x00007ffff798100c in r_cmd_call (cmd=0x6ab510, input=0x682800 "pDj") at cmd_api.c:179
#8  0x00007ffff795f618 in r_core_cmd_subst_i (core=0x607980 <r>, cmd=0x682800 "pDj", colon=0x0) at cmd.c:1437
#9  0x00007ffff795dd33 in r_core_cmd_subst (core=0x607980 <r>, cmd=0x682800 "pDj") at cmd.c:981
#10 0x00007ffff7960002 in r_core_cmd (core=0x607980 <r>, cstr=0x6d7680 "pDj", log=1) at cmd.c:1628
#11 0x00007ffff7925cd4 in r_core_prompt_exec (r=0x607980 <r>) at core.c:1015
#12 0x0000000000404f79 in main (argc=2, argv=0x7fffffffebc8, envp=0x7fffffffebe0) at radare2.c:742
```
