### ISSUE TITLE
pf.[junk] /bin/ls

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2160]
morn,

testing pf.* a bit:

```
,r2 -q -c pf.G�Z�z /bin/ls
Warning: G�Z�z is not a valid format name
Segmentation fault (core dumped)
```

```
Core was generated by `r2 -q -c pf.G�Z�z /bin/ls'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4dfa3da866 in r_wstr_clen (s=0x2b13700 <error: Cannot access memory at address 0x2b13700>) at str.c:950
950             if (*s++ == 0) return 0;
(gdb) bt
#0  0x00007f4dfa3da866 in r_wstr_clen (s=0x2b13700 <error: Cannot access memory at address 0x2b13700>) at str.c:950
#1  0x00007f4dfa3f83a8 in r_print_format (p=0x236d3b0, seek=4212927, b=0x23710e0 "1\355I\211\321^H\211\342H\203\344\360PTI\307\300@\"A", 
    len=256, formatname=0x236a030 "G�Z�z", mode=3, setval=0x0, ofield=0x0) at p_format.c:1282
#2  0x00007f4dfdbfead8 in cmd_print_format (core=0x607980 <r>, _input=0x23d9341 "f.G�Z�z", len=256) at cmd_print.c:334
#3  0x00007f4dfdc05dd7 in cmd_print (data=0x607980 <r>, input=0x23d9341 "f.G�Z�z") at cmd_print.c:2127
#4  0x00007f4dfdc3530e in r_cmd_call (cmd=0x23abff0, input=0x23d9340 "pf.G�Z�z") at cmd_api.c:179
#5  0x00007f4dfdc134f3 in r_core_cmd_subst_i (core=0x607980 <r>, cmd=0x23d9340 "pf.G�Z�z", colon=0x0) at cmd.c:1438
#6  0x00007f4dfdc11c0e in r_core_cmd_subst (core=0x607980 <r>, cmd=0x23d9340 "pf.G�Z�z") at cmd.c:982
#7  0x00007f4dfdc13edd in r_core_cmd (core=0x607980 <r>, cstr=0x7fff7b9d8de5 "pf.G�Z�z", log=0) at cmd.c:1629
#8  0x00007f4dfdc1447e in r_core_cmd0 (user=0x607980 <r>, cmd=0x7fff7b9d8de5 "pf.G�Z�z") at cmd.c:1752
#9  0x0000000000404cfe in main (argc=5, argv=0x7fff7b9d7a78, envp=0x7fff7b9d7aa8) at radare2.c:718
(gdb) list
945     }
946
947     // Length in chars of a wide string (find better name?)
948     R_API int r_wstr_clen (const char *s) {
949             int len = 0;
950             if (*s++ == 0) return 0;
951             while (*s++ || *s++)
952                     len++;
953             return len+1;
954     }
(gdb) x/i $pc
=> 0x7f4dfa3da866 <r_wstr_clen+27>:     movzbl (%rax),%eax
(gdb) !uname -srm; r2 -v; dmesg|tail -1
Linux 3.18.6-1-ARCH x86_64
radare2 0.9.9-git 7230 @ linux-little-x86-64 git.0.9.8-882-g45b6f83
commit: 45b6f83d87655d8eb02a9c8e9088b57833b12da3 build: 2015-03-05
3815.823878] r2[1571]: segfault at 2b136ff ip 00007f4dfa3da866 sp 00007fff7b9d60b0 error 4 in libr_util.so.0.9.9-git[7f4dfa3ca000+4a000]
```

Greetings
--zlul

**Comment by zonkzonk** [comment]
still in acce30fc921f804d5f9b5242b15936201b0c30bd

**Comment by crowell** [comment]
can you give repro steps, b64 encode any binary data please.

**Comment by zonkzonk** [comment]
oh. just copy "as is" did work for me on 32bit and 64bit, also in: 56adb2533c84ef8e8093c0b29bcdf885970c8cda
