### ISSUE TITLE
VV fault

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2162]
morrn,

testing the VV,

```
VV
hjkl
p(hit p one or several times)

Segmentation fault (core dumped)$r @ section_end..shstrtab+134512369 # 0x8047fde
zlul@debian:~$  !!#*!de    ff           invalid                                   
           0x08047fdf    ff           invalid                                   
[..]
gdb -q r2 core
Reading symbols from /usr/local/bin/r2...done.
[New LWP 4112]

warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
Core was generated by `r2 /bin/ls'.
Program terminated with signal 11, Segmentation fault.
#0  0xb727ee7f in translateInstruction (mcInst=0xbfbcf974, insn=0xbfbced60)
    at arch/X86/X86Disassembler.c:701
701			if (insn->operands[index].encoding != ENCODING_NONE) {
(gdb) bt
#0  0xb727ee7f in translateInstruction (mcInst=0xbfbcf974, insn=0xbfbced60)
    at arch/X86/X86Disassembler.c:701
#1  0xb727f48b in X86_getInstruction (ud=155817048, 
    code=0x9499270 "\177ELF\001\001\001", code_len=115, instr=0xbfbcf974, 
    size=0xbfbcf972, address=0, _info=0x0) at arch/X86/X86Disassembler.c:830
#2  0xb716e972 in cs_disasm (ud=155817048, 
    buffer=0x9499270 "\177ELF\001\001\001", size=115, offset=0, count=1, 
    insn=0xbfbcfd84) at cs.c:481
#3  0xb7142183 in analop (a=0x91d4ba8, op=0xbfbcfef0, addr=0, 
    buf=0x9499270 "\177ELF\001\001\001", len=115)
    at /home/zlul/radare2/libr/..//libr/anal/p/anal_x86_cs.c:150
#4  0xb7152da1 in r_anal_op (anal=0x91d4ba8, op=0xbfbcfef0, addr=0, 
    data=0x9499270 "\177ELF\001\001\001", len=115) at op.c:46
#5  0xb769217a in num_callback (userptr=0x804e4e0, str=0x91c4cd0 "$$", 
    ok=0xbfbd0070) at core.c:126
#6  0xb6a0ebf4 in r_num_get (num=0x91c4ca0, str=0x91c4cd0 "$$") at num.c:114
#7  0xb6a2775e in prim (num=0x91c4ca0, nc=0x91c4cbc, get=0) at calc.c:107
#8  0xb6a2741d in term (num=0x91c4ca0, nc=0x91c4cbc, get=0) at calc.c:71
#9  0xb6a270e0 in expr (num=0x91c4ca0, nc=0x91c4cbc, get=0) at calc.c:55
#10 0xb6a283ef in r_num_calc (num=0x91c4ca0, str=0x94993c6 "$$-0", 
    err=0xbfbd1334) at calc.c:337
#11 0xb6a0f0c7 in r_num_math (num=0x91c4ca0, str=0x94993c6 "$$-0") at num.c:232
#12 0xb76cfc47 in r_core_cmd_subst_i (core=0x804e4e0, cmd=0x94993c0 "px 64", 
---Type <return> to continue, or q <return> to quit---
    colon=0x94993ca "") at cmd.c:1397
#13 0xb76ce812 in r_core_cmd_subst (core=0x804e4e0, cmd=0x94993c0 "px 64")
    at cmd.c:982
#14 0xb76ce8c1 in r_core_cmd_subst (core=0x804e4e0, cmd=0x9499390 "sr sp")
    at cmd.c:997
#15 0xb76ce8c1 in r_core_cmd_subst (core=0x804e4e0, cmd=0x9499358 "f tmp")
    at cmd.c:997
#16 0xb76d0784 in r_core_cmd (core=0x804e4e0, 
    cstr=0xb7747f80 "f tmp;sr sp;px 64@$$-0;dr=;s-;s tmp;f-tmp;pd $r", log=0)
    at cmd.c:1629
#17 0xb76d0ce5 in r_core_cmd0 (user=0x804e4e0, 
    cmd=0xb7747f80 "f tmp;sr sp;px 64@$$-0;dr=;s-;s tmp;f-tmp;pd $r")
    at cmd.c:1752
#18 0xb76dfd5a in r_core_visual_refresh (core=0x804e4e0) at visual.c:1597
#19 0xb76e022b in r_core_visual (core=0x804e4e0, input=0x9499262 "")
    at visual.c:1692
#20 0xb76cd9aa in cmd_visual (data=0x804e4e0, input=0x9499261 "V") at cmd.c:674
#21 0xb76f2efe in r_cmd_call (cmd=0x91f8318, input=0x9499260 "VV")
    at cmd_api.c:179
#22 0xb76cfe63 in r_core_cmd_subst_i (core=0x804e4e0, cmd=0x9499260 "VV", 
    colon=0x0) at cmd.c:1438
#23 0xb76ce812 in r_core_cmd_subst (core=0x804e4e0, cmd=0x9499260 "VV")
    at cmd.c:982
---Type <return> to continue, or q <return> to quit---
#24 0xb76d0784 in r_core_cmd (core=0x804e4e0, cstr=0x91c6d18 "VV", log=1)
    at cmd.c:1629
#25 0xb7695555 in r_core_prompt_exec (r=0x804e4e0) at core.c:1015
#26 0x0804cb04 in main (argc=2, argv=0xbfbd26a4, envp=0xbfbd26b0)
    at radare2.c:763
(gdb) list
696	#endif
697	
698		insn->numImmediatesTranslated = 0;
699	
700		for (index = 0; index < X86_MAX_OPERANDS; ++index) {
701			if (insn->operands[index].encoding != ENCODING_NONE) {
702				if (translateOperand(mcInst, &insn->operands[index], insn)) {
703					return true;
704				}
705			}

```

Greetings
--zlul

r2 -v
radare2 0.9.9-git 7238 @ linux-little-x86-32 git.0.9.8-890-g5fbd3dd
commit: 5fbd3dd6c1172f105a22ce71333cbf1ea709f7f5 build: 2015-03-06

 3721.502963] r2[4112]: segfault at 30 ip b727ee7f sp bfbcece0 error 4 in libr_anal.so.0.9.9-git[b70ca000+2d1000]

crashes on 32bit, does not want to crash on 64bit!

**Comment by zonkzonk** [comment]
same thing (on 32bit) happens with pd 1 (without and with af)

**Comment by radare** [comment]
Can u show value insn, index, ... And all the offendings vars in there? I cant reproduce this crash but its failing in capstone. Is this with latest git?

**Comment by zonkzonk** [comment]
capstone version was: c488de3926ae3cf5b9255e1ec41addec9112016f

However, thanks for fixing it in 39ead51cd9ae0684cbc67bbc840bcbd8da09b450 with capstone version 8e343885be05b5bf68c067a646874224e7fd9e45. :)

**Comment by radare** [comment]
Cool!
