### ISSUE TITLE
drs munmap_chunk(): invalid pointer: 0x088bd3d0

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2167]
morn,

drs + numeric argument crash.

```
zlul@debian:~$ r2 -d bins/a.out.bak 
Process with PID 12448 started...
PID = 12448
pid = 12448 tid = 12448
r_debug_select: 12448 12448
Using BADDR 0x8048000
Asuming filepath bins/a.out.bak
bits 64
pid = 12448 tid = 12448
 -- Did you ever ordered a pizza using radare2?
[0xb77b5840]> af
dfb77b61e1 > 0xb77b621e
/ (fcn) eip 74pdf
|          ;-- eip:
|          0xb77b5840    89e0         mov eax, esp
|          0xb77b5842    e839020000   call 0xb77b5a80  ; (fcn.b77b5a7c)
|             fcn.b77b5a7c() ; fcn.b77b5a0c+116
|          0xb77b5847    89c7         mov edi, eax
|          0xb77b5849    e8e2ffffff   call 0xb77b5830
|             0xb77b5830() ; map._lib_i386_linux_gnu_ld_2.13.so.r_x+2096
|          0xb77b584e    81c3a6c70100 add ebx, 0x1c7a6
|          0xb77b5854    8b8300ffffff mov eax, dword [rbx - 0x100]
|          0xb77b585a    5a           pop rdx
|          0xb77b585b    8d2484       lea esp, [rsp + rax*4]
|          0xb77b585e    29c2         sub edx, eax
|          0xb77b5860    52           push rdx
|          0xb77b5861    8b832c000000 mov eax, dword [rbx + 0x2c]  ; [0x2c:4]=-1 ; ',' ; 44
|          0xb77b5867    8d749408     lea esi, [rsp + rdx*4 + 8]  ; [0x8:4]=-1 ; 8
|          0xb77b586b    8d4c2404     lea ecx, [rsp + 4]  ; [0x4:4]=-1 ; 4
|          0xb77b586f    89e5         mov ebp, esp
|          0xb77b5871    83e4f0       and esp, 0xfffffff0
|          0xb77b5874    50           push rax
|          0xb77b5875    50           push rax
|          0xb77b5876    55           push rbp
|          0xb77b5877    56           push rsi
|          0xb77b5878    31ed         xor ebp, ebp
|          0xb77b587a    e8e1d90000   call 0xb77c3260
|             0xb77c3260(unk, unk, unk, unk, unk) ; fcn.b77b61e1+53375
|          0xb77b587f    8d939c15ffff lea edx, [rbx - 0xea64]
|          0xb77b5885    8b2424       mov esp, dword [rsp]
\          0xb77b5888    ffe7         jmp rdi
[0xb77b5840]> db
[0xb77b5840]> db main
[0xb77b5840]> dc
bins/a.out.bak: 2: bins/a.out.bak: Syntax error: "(" unexpected
r_debug_select: 12448 1
[0xb77b4424]> drs
2
[0xb77b4424]> drs?
|Usage: drs Register states commands
| drs   List register stack
| drs+  Push register state
| drs-  Pop register state
[0xb77b4424]> drs+
[0xb77b4424]> drs?
|Usage: drs Register states commands
| drs   List register stack
| drs+  Push register state
| drs-  Pop register state
[0xb77b4424]> drs
3
[0xb77b4424]> drs 1
3
^D
Do you want to quit? (Y/n)
^D
Do you want to quit? (Y/n)
Do you want to kill the process? (Y/n)
*** glibc detected *** r2: munmap_chunk(): invalid pointer: 0x088bd3d0 ***
======= Backtrace: =========
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x6feb1)[0xb6832eb1]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x7112e)[0xb683412e]
/usr/local/lib/libr_reg.so(r_reg_arena_free+0x1f)[0xb704debc]
/usr/local/lib/libr_util.so(r_list_delete+0x47)[0xb6952980]
/usr/local/lib/libr_util.so(r_list_purge+0x3d)[0xb6952873]
/usr/local/lib/libr_reg.so(r_reg_free+0x3f)[0xb704c9ed]
/usr/local/lib/libr_anal.so(r_anal_free+0x93)[0xb70e7b82]
/usr/local/lib/libr_core.so(r_core_fini+0xd5)[0xb7673fba]
r2(main+0x2575)[0x804cdb5]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xe6)[0xb67d9e46]
r2[0x804a231]
======= Memory map: ========
08048000-0804e000 r-xp 00000000 08:01 22418890   /usr/local/bin/radare2
0804e000-0804f000 rw-p 00006000 08:01 22418890   /usr/local/bin/radare2
0804f000-080b0000 rw-p 00000000 00:00 0 
08880000-089c4000 rw-p 00000000 00:00 0          [heap]
b6733000-b674f000 r-xp 00000000 08:01 26214404   /lib/i386-linux-gnu/libgcc_s.so.1
b674f000-b6750000 rw-p 0001b000 08:01 26214404   /lib/i386-linux-gnu/libgcc_s.so.1
b6763000-b676a000 r--s 00000000 08:01 24512485   /usr/local/lib/radare2/0.9.9-git/syscall/linux-x86-64.sdb
b676a000-b6771000 r--s 00000000 08:01 24512485   /usr/local/lib/radare2/0.9.9-git/syscall/linux-x86-64.sdb
b6771000-b6772000 r-xp 00000000 08:01 24512467   /usr/local/lib/radare2/0.9.9-git/asm_x86_as.so
b6772000-b6773000 rw-p 00000000 08:01 24512467   /usr/local/lib/radare2/0.9.9-git/asm_x86_as.so
b6773000-b6774000 r-xp 00000000 08:01 24512414   /usr/local/lib/radare2/0.9.9-git/asm_x86_nasm.so
b6774000-b6775000 rw-p 00000000 08:01 24512414   /usr/local/lib/radare2/0.9.9-git/asm_x86_nasm.so
b6775000-b6777000 r-xp 00000000 08:01 24510941   /usr/local/lib/radare2/0.9.9-git/asm_snes.so
b6777000-b6778000 rw-p 00002000 08:01 24510941   /usr/local/lib/radare2/0.9.9-git/asm_snes.so
b6778000-b677b000 r-xp 00000000 08:01 24510940   /usr/local/lib/radare2/0.9.9-git/asm_6502.so
b677b000-b677c000 rw-p 00002000 08:01 24510940   /usr/local/lib/radare2/0.9.9-git/asm_6502.so
b677c000-b6781000 r--s 00000000 08:01 24512484   /usr/local/lib/radare2/0.9.9-git/syscall/linux-x86-32.sdb
b6781000-b6783000 rw-p 00000000 00:00 0 
b6783000-b6798000 r-xp 00000000 08:01 26345500   /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
b6798000-b6799000 r--p 00014000 08:01 26345500   /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
b6799000-b679a000 rw-p 00015000 08:01 26345500   /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
b679a000-b679c000 rw-p 00000000 00:00 0 
b679c000-b67c0000 r-xp 00000000 08:01 26345523   /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
b67c0000-b67c1000 r--p 00023000 08:01 26345523   /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
b67c1000-b67c2000 rw-p 00024000 08:01 26345523   /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
b67c2000-b67c3000 rw-p 00000000 00:00 0 
b67c3000-b6921000 r-xp 00000000 08:01 26345517   /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
b6921000-b6923000 r--p 0015e000 08:01 26345517   /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
b6923000-b6924000 rw-p 00160000 08:01 26345517   /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
b6924000-b6927000 rw-p 00000000 00:00 0 
b6927000-b692a000 r-xp 00000000 08:01 22415279   /usr/local/lib/libr_crypto.so.0.9.9-git
b692a000-b692e000 rw-p 00002000 08:01 22415279   /usr/local/lib/libr_crypto.so.0.9.9-git
b692e000-b693a000 r-xp 00000000 08:01 22415283   /usr/local/lib/libr_egg.so.0.9.9-git
b693a000-b693b000 rw-p 0000c000 08:01 22415283   /usr/local/lib/libr_egg.so.0.9.9-git
b693b000-b693c000 rw-p 00000000 00:00 0 
b693c000-b6982000 r-xp 00000000 08:01 22418888   /usr/local/lib/libr_util.so.0.9.9-git
b6982000-b6984000 rw-p 00045000 08:01 22418888   /usr/local/lib/libr_util.so.0.9.9-git
b6984000-b698d000 rw-p 00000000 00:00 0 
b698d000-b6992000 r-xp 00000000 08:01 22415284   /usr/local/lib/libr_flags.so.0.9.9-git
b6992000-b6993000 rw-p 00004000 08:01 22415284   /usr/local/lib/libr_flags.so.0.9.9-git
b6993000-b699b000 r-xp 00000000 08:01 22418884   /usr/local/lib/libr_socket.so.0.9.9-git
b699b000-b699c000 rw-p 00008000 08:01 22418884   /usr/local/lib/libr_socket.so.0.9.9-git
b699c000-b69ae000 r-xp 00000000 08:01 22418834   /usr/local/lib/libr_magic.so.0.9.9-git
b69ae000-b69af000 rw-p 00011000 08:01 22418834   /usr/local/lib/libr_magic.so.0.9.9-git
b69af000-b69b9000 r-xp 00000000 08:01 22416721   /usr/local/lib/libr_hash.so.0.9.9-git
b69b9000-b69ba000 rw-p 0000a000 08:01 22416721   /usr/local/lib/libr_hash.so.0.9.9-git
b69ba000-b69d3000 r-xp 00000000 08:01 22415280   /usr/local/lib/libr_db.so.0.9.9-git
b69d3000-b69d5000 rw-p 00018000 08:01 22415280   /usr/local/lib/libr_db.so.0.9.9-git
b69d5000-b69f0000 rw-p 00000000 00:00 0 
b69f0000-b69f2000 r-xp 00000000 08:01 22418886   /usr/local/lib/libr_syscall.so.0.9.9-git
b69f2000-b69f3000 rw-p 00002000 08:01 22418886   /usr/local/lib/libr_syscall.so.0.9.9-git
b69f3000-b6d66000 r-xp 00000000 08:01 22415239   /usr/local/lib/libr_asm.so.0.9.9-git
b6d66000-b6fa6000 rw-p 00373000 08:01 22415239   /usr/local/lib/libr_asm.so.0.9.9-git
b6fa6000-b6fba000 rw-p 00000000 00:00 0 
b6fba000-b6fbe000 r-xp 00000000 08:01 22418712   /usr/local/lib/libr_lang.so.0.9.9-git
b6fbe000-b6fbf000 rw-p 00003000 08:01 22418712   /usr/local/lib/libr_lang.so.0.9.9-git
b6fbf000-b6ff0000 r-xp 00000000 08:01 22416609   /usr/local/lib/libr_fs.so.0.9.9-git
b6ff0000-b6ff2000 rw-p 00030000 08:01 22416609   /usr/local/lib/libr_fs.so.0.9.9-git
b6ff2000-b6ff8000 rw-p 00000000 00:00 0 
b6ff8000-b7037000 r-xp 00000000 08:01 22418695   /usr/local/lib/libr_io.so.0.9.9-git
b7037000-b703f000 rw-p 0003e000 08:01 22418695   /usr/local/lib/libr_io.so.0.9.9-git
b703f000-b7046000 rw-p 00000000 00:00 0 
b7046000-b704a000 r-xp 00000000 08:01 22415273   /usr/local/lib/libr_bp.so.0.9.9-git
b704a000-b704b000 rw-p 00003000 08:01 22415273   /usr/local/lib/libr_bp.so.0.9.9-git
b704b000-b7050000 r-xp 00000000 08:01 22418880   /usr/local/lib/libr_reg.so.0.9.9-git
b7050000-b7051000 rw-p 00005000 08:01 22418880   /usr/local/lib/libr_reg.so.0.9.9-git
b7051000-b7054000 r-xp 00000000 08:01 22415282   /usr/local/lib/libr_diff.so.0.9.9-gitAborted
zlul@debian:~$ ^C
Core was generated by `r2 -d bins/a.out.bak'.
Program terminated with signal 6, Aborted.
#0  0xb76f7424 in __kernel_vsyscall ()
(gdb) bt
#0  0xb76f7424 in __kernel_vsyscall ()
#1  0xb67a3661 in *__GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#2  0xb67a6a92 in *__GI_abort () at abort.c:92
#3  0xb67dedc5 in __libc_message (do_abort=2, fmt=0xb68b9b50 "*** glibc detected *** %s: %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:189
#4  0xb67e8eb1 in malloc_printerr (action=<optimized out>, str=0x6 <Address 0x6 out of bounds>, ptr=0x97a9500) at malloc.c:6312
#5  0xb67ea12e in munmap_chunk (p=<optimized out>) at malloc.c:3540
#6  0xb7003ebc in r_reg_arena_free (ra=0x97fb038) at arena.c:176
#7  0xb6908980 in r_list_delete (list=0x97a9348, iter=0x9890758) at list.c:91
#8  0xb6908873 in r_list_purge (list=0x97a9348) at list.c:61
#9  0xb70029ed in r_reg_free (reg=0x97a9280) at reg.c:88
#10 0xb709db82 in r_anal_free (a=0x977fdb8) at anal.c:130
#11 0xb7629fba in r_core_fini (c=0x804e4e0) at core.c:900
#12 0x0804cdb5 in main (argc=3, argv=0xbf9c89d4, envp=0xbf9c89e4) at radare2.c:817
(gdb) i r
eax            0x0	0
ecx            0x34d5	13525
edx            0x6	6
ebx            0x34d5	13525
esp            0xbf9c7ab0	0xbf9c7ab0
ebp            0xbf9c7ac8	0xbf9c7ac8
esi            0x400	1024
edi            0xb68d8ff4	-1232236556
eip            0xb76f7424	0xb76f7424 <__kernel_vsyscall+16>
eflags         0x200202	[ IF ID ]
cs             0x73	115
ss             0x7b	123
ds             0x7b	123
es             0x7b	123
fs             0x0	0
gs             0x33	51


r2 -v
39ead51cd9ae0684cbc67bbc840bcbd8da09b450
``

**Comment by zonkzonk** [comment]
valgrind output here:
http://sprunge.us/IgJR

**Comment by radare** [comment]
yep. im aware of this. drs causes a doublefree when a regstate is dupped.

you can reproduce the issue with just:

	echo q | r2 -cdrs+ -

I have investigated a bit and found the issue, which was pushing an unitialized arena. It’s fixed now in git.

Thanks!
