### ISSUE TITLE
r2 stdin mode prints junk

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2183]
morn,

perl -e "print 'A'x8192"|r2 -
http://radare.tv/a/27

Greetings
--zlul

**Comment by crowell** [comment]
send enough and you get a nice segfault

```
gdb-peda$ bt
#0  0x00007fe1a15486fe in __GI__IO_default_xsputn (
    f=f@entry=0x7fe1a188c400 <_IO_2_1_stdout_>, data=data@entry=0x7fe1a4cf8ec5, 
    n=n@entry=0x13c) at genops.c:480
#1  0x00007fe1a15466e2 in _IO_new_file_xsputn (f=0x7fe1a188c400 <_IO_2_1_stdout_>, 
    data=<optimized out>, n=0x60b2) at fileops.c:1353
#2  0x00007fe1a153be6d in __GI__IO_fwrite (buf=<optimized out>, size=0x1, 
    count=0x60b2, fp=0x7fe1a188c400 <_IO_2_1_stdout_>) at iofwrite.c:43
#3  0x00007fe1a4ae8308 in r_line_readline_cb (cb=0x0, user=0x0) at dietline.c:857
#4  0x00007fe1a4ae6f84 in r_line_readline () at dietline.c:362
#5  0x00007fe1a516d1f5 in r_core_fgets (buf=0x7fffc12fe110 "", len=0x1000)
    at core.c:535
#6  0x00007fe1a4ae9c7a in r_cons_fgets (buf=0x7fffc12fe110 "", len=0x1000, argc=0x0, 
    argv=0x0) at input.c:180
#7  0x00007fe1a516edb3 in r_core_prompt (r=0x6075a0 <r>, sync=0x0) at core.c:1007
#8  0x0000000000405223 in main (argc=0x2, argv=0x7fffc12ff920, envp=0x7fffc12ff930)
    at radare2.c:759
#9  0x00007fe1a14eeec5 in __libc_start_main (main=0x4031cf <main>, argc=0x2, 
    argv=0x7fffc12ff918, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffc12ff908) at libc-start.c:287
#10 0x0000000000402b29 in _start ()
```

**Comment by zonkzonk** [comment]
the problem is, how to implement a better stdin mode? currently it malloc://512
@pancake @condret
