### ISSUE TITLE
 0xb7682764 in unary () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1832

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2212]
morn,

fault in unary() where  buf.core can be found at teh end (base64) or here http://sprunge.us/jIGW.

```
 r2 -q -c "td struct Bar {int`cat /tmp/buf.core` a;char *c;int c;}" -cVt /bin/ls
```

buf.core:
```
W3co3N/+wXE3TmZhDJVmGvs2EYj0hHwft6M8EDuvXgvv4dPMr5fk7BRtsZW2eIauOLNohJze6O/M
jZamMerptQK7VGLZD2c6zFrs7laMs8cAjc+icr8POAfzDjJ26lC5oyKU9yteQPS7bZ3awed9DXuL
XdtunQVuLiNTf7be4WUNxpRZloNvetPfEwpWyehdHT7dvlKX
```

md5sum buf.core
d9a1d8cd0315647dcb8b9399e8fe4677  buf.core

r2 -v 
radare2 0.9.9-git 7314 @ linux-little-x86-32 git.0.9.8-966-g5fa09b3
commit: 5fa09b369e4927278761bf59791a0ef08c8e9a94 build: 2015-03-19

32bit

This coredump dedicated to https://chemnitzer.linux-tage.de/2015/en :)

Greetings
--zlul

**Comment by radare** [comment]
Please paste gdb backtrace, affected variables, register contents, disasm,.. In some cases valgrind would be helpful too.

Btw to run td u have to do -c '"td ..."' Otherwise the ; will split it by commas. So you are actually running plain r2 commands which may be dangerous if not reviewed properly.

**Comment by zonkzonk** [comment]
```
gdb -q /usr/local/bin/r2
Reading symbols from /usr/local/bin/r2...done.
(gdb) set args -q -c "td struct Bar {int`cat /home/zlul/radare-tests/buf.core.2212` a;char *c;int c;}" -cVt /bin/ls
(gdb) r
Starting program: /usr/local/bin/r2 -q -c "td struct Bar {int`cat /home/zlul/radare-tests/buf.core.2212` a;char *c;int c;}" -cVt /bin/ls
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
sh: 1: cannot open : No such file
sh: 1: ��: not found

Program received signal SIGSEGV, Segmentation fault.
0xb7ed3764 in unary () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1832
1832	        if ((s->type.t & (VT_STATIC | VT_INLINE | VT_BTYPE)) ==

(gdb) list
1827	        s = sym_find(t);
1828	        if (!s) {
1829	            if (tok != '(')
1830	                tcc_error("'%s' undeclared", get_tok_str(t, NULL));
1831	        }
1832	        if ((s->type.t & (VT_STATIC | VT_INLINE | VT_BTYPE)) ==
1833	            (VT_STATIC | VT_INLINE | VT_FUNC)) {
1834	            /* if referencing an inline function, then we generate a
1835	               symbol to it if not already done. It will have the
1836	               effect to generate code for it at the end of the
(gdb) bt 
#0  0xb7ed3764 in unary () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1832
#1  0xb7ed39c7 in expr_prod () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1909
#2  0xb7ed3a17 in expr_sum () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1918
#3  0xb7ed3a5a in expr_shift () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1927
#4  0xb7ed3a9d in expr_cmp () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1936
#5  0xb7ed3b02 in expr_cmpeq () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1946
#6  0xb7ed3b49 in expr_and () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1955
#7  0xb7ed3b7f in expr_xor () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1964
#8  0xb7ed3bb5 in expr_or () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1973
#9  0xb7ed3beb in expr_land_const () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1983
#10 0xb7ed3c23 in expr_lor_const () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1993
#11 0xb7ed3cf7 in expr_cond () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:2033
#12 0xb7ed3f02 in expr_const1 () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:2110
#13 0xb7ed3f38 in expr_const () at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:2118
#14 0xb7ed292e in post_type (type=0xbfffc05c, ad=0xbfffc064) at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1370
#15 0xb7ed2c76 in type_decl (type=0xbfffc05c, ad=0xbfffc064, v=0xbfffc070, td=3) at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1481
#16 0xb7ed1b35 in struct_decl (type=0xbfffc0f0, u=7) at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:915
#17 0xb7ed2246 in parse_btype (type=0xbfffc150, ad=0xbfffc148) at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:1134
#18 0xb7ed53e7 in decl0 (l=48, is_for_loop_init=0) at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:2733
#19 0xb7ed5847 in decl (l=48) at /home/zlul/radare2/libr/..//shlr/tcc/tccgen.c:2878
#20 0xb7ec914d in tcc_compile (s1=0x838d508) at /home/zlul/radare2/libr/..//shlr/tcc/libtcc.c:445
#21 0xb7ec9236 in tcc_compile_string (s=0x838d508, str=0xbfffc268 "struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210\364\204;") at /home/zlul/radare2/libr/..//shlr/tcc/libtcc.c:474
#22 0xb7ed59d1 in r_parse_c_string (code=0xbfffc268 "struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210\364\204;") at code.c:38
#23 0xb7f3202b in cmd_type (data=0x804f560, input=0x838b001 "d struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210", <incomplete sequence \364\204>) at cmd_type.c:196
#24 0xb7f703f2 in r_cmd_call (cmd=0x80e86a8, input=0x838b000 "td struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210", <incomplete sequence \364\204>) at cmd_api.c:178
#25 0xb7f4cf42 in r_core_cmd_subst_i (core=0x804f560, cmd=0x838b000 "td struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210", <incomplete sequence \364\204>, colon=0x0) at cmd.c:1442
#26 0xb7f4b8f1 in r_core_cmd_subst (core=0x804f560, cmd=0x838b000 "td struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210", <incomplete sequence \364\204>) at cmd.c:986
#27 0xb7f4d863 in r_core_cmd (core=0x804f560, cstr=0x838af58 "td struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210", <incomplete sequence \364\204>, log=0) at cmd.c:1633
#28 0xb7f4b63b in r_core_cmd_pipe (core=0x804f560, radare_cmd=0x838af58 "td struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210", <incomplete sequence \364\204>, 
    shell_cmd=0x838af81 "\037\267\243<\020") at cmd.c:926
#29 0xb7f4bf61 in r_core_cmd_subst_i (core=0x804f560, cmd=0x838af58 "td struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210", <incomplete sequence \364\204>, colon=0x838af86 "") at cmd.c:1131
#30 0xb7f4b8f1 in r_core_cmd_subst (core=0x804f560, cmd=0x838af58 "td struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210", <incomplete sequence \364\204>) at cmd.c:986
#31 0xb7f4d863 in r_core_cmd (core=0x804f560, 
    cstr=0xbffff68d "td struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210\364\204|\037\267\243<\020;\257^\v\357\341\323̯\227\344\354\024m\261\225\266x\206\256\070\263h\204\234\336\350\357̍\226\246\061\352\351\265\002\273Tb\331\017g:\314Z\354\356V\214\263ǍϢr\277\017\070\a\363\016\062v\352P\271\243\"\224\367+^@\364\273m\235\332\301\347}\r{\213]\333n\235\005n.#S\177\266\336\341e\rƔY\226\203oz\323\337\023\nV\311\350]\035>ݾR\227 a;char *c;int c;}", log=0) at cmd.c:1633
#32 0xb7f4ddc4 in r_core_cmd0 (user=0x804f560, 
    cmd=0xbffff68d "td struct Bar {int[w(\334\337\376\301q7Nfa\f\225f\032\373\066\021\210\364\204|\037\267\243<\020;\257^\v\357\341\323̯\227\344\354\024m\261\225\266x\206\256\070\263h\204\234\336\350\357̍\226\246\061\352\351\265\002\273Tb\331\017g:\314Z\354\356V\214\263ǍϢr\277\017\070\a\363\016\062v\352P\271\243\"\224\367+^@\364\273m\235\332\301\347}\r{\213]\333n\235\005n.#S\177\266\336\341e\rƔY\226\203oz\323\337\023\nV\311\350]\035>ݾR\227 a;char *c;int c;}") at cmd.c:1756
#33 0x0804c86b in main (argc=6, argv=0xbffff524, envp=0xbffff540) at radare2.c:721

```

**Comment by zonkzonk** [comment]
full bt: http://sprunge.us/dPUJ

**Comment by radare** [comment]
print s

**Comment by zonkzonk** [comment]
from full bt you can see that s is 0x00.

**Comment by zonkzonk** [comment]
Thanks! Reproduced as fixed.
