### ISSUE TITLE
EpicScale.exe

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2216]
![epicscale exe](https://cloud.githubusercontent.com/assets/5694980/6744210/9eb5be6e-cea6-11e4-967c-d0175f3602b1.png)

mrnn,

this might be duplicate, looks like capstone bug:

```
Core was generated by `r2 EpicScale.exe'.
Program terminated with signal 11, Segmentation fault.
#0  0xb7208920 in translateInstruction (mcInst=0xbfc5ccf4, insn=0xbfc5c0e8) at arch/X86/X86Disassembler.c:821
821			if (insn->operands[index].encoding != ENCODING_NONE) {
(gdb) bt
#0  0xb7208920 in translateInstruction (mcInst=0xbfc5ccf4, insn=0xbfc5c0e8) at arch/X86/X86Disassembler.c:821
#1  0xb7208f2c in X86_getInstruction (ud=172832800, code=0xa4d27b0 "\350\017s", code_len=632, instr=0xbfc5ccf4, size=0xbfc5ccf2, address=4306445, _info=0x0) at arch/X86/X86Disassembler.c:950
#2  0xb70f0bf6 in cs_disasm (ud=172832800, buffer=0xa4d27b0 "\350\017s", size=632, offset=4306445, count=1, insn=0xbfc5d100) at cs.c:481
#3  0xb70c423b in analop (a=0x9ea2ba8, op=0xbfc5d290, addr=4306445, buf=0xa4d27b0 "\350\017s", len=632) at /home/zlul/radare2/libr/..//libr/anal/p/anal_x86_cs.c:168
#4  0xb70d4b14 in r_anal_op (anal=0x9ea2ba8, op=0xbfc5d290, addr=4306445, data=0xa4d27b0 "\350\017s", len=632) at op.c:46
#5  0xb70d3897 in r_anal_reflines_get (anal=0x9ea2ba8, addr=4306445, buf=0xa4d27b0 "\350\017s", len=640, nlines=63, linesout=1, linescall=0) at reflines.c:44
#6  0xb76df203 in handle_reflines_init (core=0x804f500, ds=0xa4d2a38) at disasm.c:348
#7  0xb76e4ee0 in r_core_print_disasm (p=0x9e92298, core=0x804f500, addr=4306445, buf=0xa4d27b0 "\350\017s", len=640, l=64, invbreak=0, cbytes=0) at disasm.c:2028
#8  0xb7699f4e in cmd_print (data=0x804f500, input=0x9ed7439 "d") at cmd_print.c:1651
#9  0xb76cca62 in r_cmd_call (cmd=0x9ec6688, input=0x9ed7438 "pd") at cmd_api.c:179
#10 0xb76a9613 in r_core_cmd_subst_i (core=0x804f500, cmd=0x9ed7438 "pd", colon=0x0) at cmd.c:1438
#11 0xb76a7fc2 in r_core_cmd_subst (core=0x804f500, cmd=0x9ed7438 "pd") at cmd.c:982
#12 0xb76a9f34 in r_core_cmd (core=0x804f500, cstr=0x9e94d18 "pd", log=1) at cmd.c:1629
#13 0xb766ea48 in r_core_prompt_exec (r=0x804f500) at core.c:1070
#14 0x0804cb22 in main (argc=2, argv=0xbfc5ead4, envp=0xbfc5eae0) at radare2.c:766
(gdb) list
816	#endif
817	
818		insn->numImmediatesTranslated = 0;
819	
820		for (index = 0; index < X86_MAX_OPERANDS; ++index) {
821			if (insn->operands[index].encoding != ENCODING_NONE) {
822				if (translateOperand(mcInst, &insn->operands[index], insn)) {
823					return true;
824				}
825			}
(gdb) !r2 -v
radare2 0.9.9-git 7323 @ linux-little-x86-32 git.0.9.8-974-ge5af653
commit: e5af65394c104fe86053e32d7d1239e8d84e174a build: 2015-03-20
```

just run pd to reproduce.

A Similar bug with different function:
```
zlul@debian:~/.config/libreoffice/3/user/extensions/bundled/registry/com.sun.star.comp.deployment.configuration.PackageRegistryBackend$ r2 -c "pd" backenddb.xml
Segmentation fault (core dumped)
```

Greetings
--zlul

32bit

**Comment by crowell** [comment]
can not repro on linux amd64

**Comment by zonkzonk** [comment]
that xml for the second bug with different function:
```
zlul@debian:~/.config/libreoffice/3/user/extensions/bundled/registry/com.sun.star.comp.deployment.configuration.PackageRegistryBackend$ cat backenddb.xml 
<?xml version="1.0"?>
<conf:configuration-backend-db xmlns:conf="http://openoffice.org/extensionmanager/configuration-registry/2010"/>
zlul@debian:~/.config/libreoffice/3/user/extensions/bundled/registry/com.sun.star.comp.deployment.configuration.PackageRegistryBackend$ 
```

**Comment by crowell** [comment]
cant repro that either linux amd64

**Comment by zonkzonk** [comment]
well, same over here, so this 32bit only

**Comment by radare** [comment]
I have fixed several coverities, and updated capstone, please try again.

**Comment by zonkzonk** [comment]
no change in 285b20ce1ad124d9a7c32220572b73f5e76aaefe

**Comment by zonkzonk** [comment]
2e32d059869b768dbfa4aa9f6d64040ded36d5eb fixes one of the two bugs. (r2 epicscale.exe)
pd still broken with the xml file.

**Comment by radare** [comment]
Cannot reproduce

**Comment by zonkzonk** [comment]
zlul@debian:~$ r2 -c "pd" /bin/ls
Segmentation fault

info provided in http://sprunge.us/TJYC

so the other bug in capstone should fix webfrontend issue

**Comment by radare** [comment]
can anyone reproduce?

are you using capstone from git or the one shipped in your system?

**Comment by radare** [comment]
cant reproduce

**Comment by zonkzonk** [comment]
capstone from git: 6a77cc7463b9ca3cc8e9e3568e8550059965e8a4

**Comment by radare** [comment]
Only happens on 32bit linux that crash? Which version of gcc and which optimization flags are u using?

**Comment by zonkzonk** [comment]
btw: pdj in webfrontend issue should be the same bug  (https://github.com/radare/radare2/issues/2158)

```
 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i486-linux-gnu/4.7/lto-wrapper
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5) 
```

**Comment by zonkzonk** [comment]
```
zlul@debian:~/radare2$ ulimit -c 100000
zlul@debian:~/radare2$ gdb -q r2
Reading symbols from /usr/local/bin/r2...done.
(gdb) set Args -c=H /bin/ls
(gdb) r
Starting program: /usr/local/bin/r2 -c=H /bin/ls
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
Starting http server...
open http://localhost:9090/
r2 -C http://localhost:9090/cmd/
[HTTP] 127.0.0.1:45118 /p
[HTTP] 127.0.0.1:45119 /p/
[HTTP] 127.0.0.1:45120 /p/lib/css/layout-default-latest.css
[HTTP] 127.0.0.1:45121 /p/lib/css/jquery.ui.tabs.css
[HTTP] 127.0.0.1:45122 /p/lib/css/jquery-ui.css
[HTTP] 127.0.0.1:45123 /enyo/disasm.css
[HTTP] 127.0.0.1:45124 /enyo/joint.min.css
[HTTP] 127.0.0.1:45125 /p/lib/css/tree.jquery.css
[HTTP] 127.0.0.1:45126 /p/lib/css/main.css
[HTTP] 127.0.0.1:45127 /p/lib/css/jquery.onoff.css
[HTTP] 127.0.0.1:45128 /enyo/js/joint.js
[HTTP] 127.0.0.1:45129 /enyo/js/joint.layout.DirectedGraph.js
[HTTP] 127.0.0.1:45130 /enyo/js/r2.js
[HTTP] 127.0.0.1:45131 /enyo/js/r2ui.js
[HTTP] 127.0.0.1:45132 /enyo/js/disasm.js
[HTTP] 127.0.0.1:45133 /p/lib/js/jquery-1.9.0.js
[HTTP] 127.0.0.1:45134 /p/lib/js/jquery-ui-latest.js
[HTTP] 127.0.0.1:45135 /p/lib/js/jquery.onoff.js
[HTTP] 127.0.0.1:45136 /p/lib/js/taphold.js
[HTTP] 127.0.0.1:45137 /p/lib/js/jquery.ui-contextmenu.js
[HTTP] 127.0.0.1:45138 /p/lib/js/jquery.layout-latest.js
[HTTP] 127.0.0.1:45139 /p/lib/js/jquery.donetyping.js
[HTTP] 127.0.0.1:45140 /p/lib/js/tree.jquery.js
[HTTP] 127.0.0.1:45141 /p/lib/js/jquery.layout.resizePaneAccordions-latest.js
[HTTP] 127.0.0.1:45142 /p/lib/js/jquery.scrollTo-latest.js
[HTTP] 127.0.0.1:45143 /p/lib/js/disasm_panel.js
[HTTP] 127.0.0.1:45144 /p/lib/js/entropy_panel.js
[HTTP] 127.0.0.1:45145 /p/lib/js/strings_panel.js
[HTTP] 127.0.0.1:45146 /p/lib/js/hex_panel.js
[HTTP] 127.0.0.1:45147 /p/lib/js/settings_panel.js
[HTTP] 127.0.0.1:45148 /p/lib/js/projects_panel.js
[HTTP] 127.0.0.1:45149 /p/lib/js/main.js
[HTTP] 127.0.0.1:45150 /p/rlogo-inv.png
[HTTP] 127.0.0.1:45151 /cmd/fs%20*;fj
[HTTP] 127.0.0.1:45152 /cmd/aa
Cannot find function 'entry0' at 0x0804c1b4

Program received signal SIGSEGV, Segmentation fault.
0xb7aa534f in translateRegister (mcInst=0xbfffb794, reg=28672) at arch/X86/X86Disassembler.c:75
75              uint8_t llvmRegnum = llvmRegnums[reg];
```

**Comment by crowell** [comment]
32 bit ubuntu, can not reproduce.

**Comment by zonkzonk** [comment]
@crowell can you try virtualbox-4.3_4.3.26-98988~Debian~wheezy_i386.deb and run apt-get update to latest before

**Comment by radare** [comment]
Whats the value of reg? Why it is segfaulting? Which is the value of the registers and the affected disasm?, do you have only one install of r2? Why not in /usr? Which bytes are passed to capstone to produce that crash? If u cant reproduce a standalone crash for capstone then it may be an issue in r2. Can u show full backtrace? What do valgrind says? 

Probably knowing the answer to all the previous questions i can make a blind patch and understand the problem.

**Comment by zonkzonk** [comment]
only one install, all current.

```
(gdb) p reg
$1 = 28672
(gdb) x/i $pc
=> 0xb7aa534f <translateRegister+179>:	movzbl (%eax),%eax
(gdb) i f
Stack level 0, frame at 0xbfffaac0:
 eip = 0xb7aa534f in translateRegister (arch/X86/X86Disassembler.c:75); saved eip 0xb7aa8a6f
 called by frame at 0xbfffab10
 source language c.
 Arglist at 0xbfffaab8, args: mcInst=0xbfffb794, reg=28672
 Locals at 0xbfffaab8, Previous frame's sp is 0xbfffaac0
 Saved registers:
  ebx at 0xbfffaaac, ebp at 0xbfffaab8, esi at 0xbfffaab0, edi at 0xbfffaab4, eip at 0xbfffaabc
(gdb) i r
eax            0xc00019c3	-1073735229
ecx            0x2	2
edx            0xbfffa9c3	-1073763901
ebx            0xb7bf0874	-1212217228
esp            0xbfffa9a0	0xbfffa9a0
ebp            0xbfffaab8	0xbfffaab8
esi            0x1	1
edi            0xbfffaa9c	-1073763684
eip            0xb7aa534f	0xb7aa534f <translateRegister+179>
eflags         0x210286	[ PF SF IF RF ID ]
cs             0x73	115
ss             0x7b	123
ds             0x7b	123
es             0x7b	123
fs             0x0	0
gs             0x33	51
(gdb) disas 0xb7aa534f
Dump of assembler code for function translateRegister:
   0xb7aa529c <+0>:	push   %ebp
   0xb7aa529d <+1>:	mov    %esp,%ebp
   0xb7aa529f <+3>:	push   %edi
   0xb7aa52a0 <+4>:	push   %esi
   0xb7aa52a1 <+5>:	push   %ebx
   0xb7aa52a2 <+6>:	sub    $0x10c,%esp
   0xb7aa52a8 <+12>:	call   0xb79278bb <__x86.get_pc_thunk.bx>
   0xb7aa52ad <+17>:	add    $0x14b5c7,%ebx
   0xb7aa52b3 <+23>:	lea    -0xf5(%ebp),%eax
   0xb7aa52b9 <+29>:	lea    -0xbdfd4(%ebx),%edx
   0xb7aa52bf <+35>:	movl   $0xdc,-0xfc(%ebp)
   0xb7aa52c9 <+45>:	mov    %eax,%ecx
   0xb7aa52cb <+47>:	and    $0x1,%ecx
   0xb7aa52ce <+50>:	test   %ecx,%ecx
   0xb7aa52d0 <+52>:	je     0xb7aa52e4 <translateRegister+72>
   0xb7aa52d2 <+54>:	movzbl (%edx),%ecx
   0xb7aa52d5 <+57>:	mov    %cl,(%eax)
   0xb7aa52d7 <+59>:	add    $0x1,%eax
   0xb7aa52da <+62>:	add    $0x1,%edx
   0xb7aa52dd <+65>:	subl   $0x1,-0xfc(%ebp)
   0xb7aa52e4 <+72>:	mov    %eax,%ecx
   0xb7aa52e6 <+74>:	and    $0x2,%ecx
   0xb7aa52e9 <+77>:	test   %ecx,%ecx
   0xb7aa52eb <+79>:	je     0xb7aa5300 <translateRegister+100>
   0xb7aa52ed <+81>:	movzwl (%edx),%ecx
   0xb7aa52f0 <+84>:	mov    %cx,(%eax)
   0xb7aa52f3 <+87>:	add    $0x2,%eax
   0xb7aa52f6 <+90>:	add    $0x2,%edx
   0xb7aa52f9 <+93>:	subl   $0x2,-0xfc(%ebp)
   0xb7aa5300 <+100>:	mov    -0xfc(%ebp),%ecx
   0xb7aa5306 <+106>:	shr    $0x2,%ecx
   0xb7aa5309 <+109>:	mov    %eax,%edi
   0xb7aa530b <+111>:	mov    %edx,%esi
   0xb7aa530d <+113>:	rep movsl %ds:(%esi),%es:(%edi)
   0xb7aa530f <+115>:	mov    %esi,%edx
   0xb7aa5311 <+117>:	mov    %edi,%eax
   0xb7aa5313 <+119>:	mov    $0x0,%ecx
   0xb7aa5318 <+124>:	mov    -0xfc(%ebp),%esi
   0xb7aa531e <+130>:	and    $0x2,%esi
   0xb7aa5321 <+133>:	test   %esi,%esi
   0xb7aa5323 <+135>:	je     0xb7aa5330 <translateRegister+148>
   0xb7aa5325 <+137>:	movzwl (%edx,%ecx,1),%esi
   0xb7aa5329 <+141>:	mov    %si,(%eax,%ecx,1)
   0xb7aa532d <+145>:	add    $0x2,%ecx
   0xb7aa5330 <+148>:	mov    -0xfc(%ebp),%esi
   0xb7aa5336 <+154>:	and    $0x1,%esi
   0xb7aa5339 <+157>:	test   %esi,%esi
   0xb7aa533b <+159>:	je     0xb7aa5344 <translateRegister+168>
   0xb7aa533d <+161>:	movzbl (%edx,%ecx,1),%edx
   0xb7aa5341 <+165>:	mov    %dl,(%eax,%ecx,1)
   0xb7aa5344 <+168>:	lea    -0xf5(%ebp),%edx
   0xb7aa534a <+174>:	mov    0xc(%ebp),%eax
---Type <return> to continue, or q <return> to quit---
   0xb7aa534d <+177>:	add    %edx,%eax
=> 0xb7aa534f <+179>:	movzbl (%eax),%eax
   0xb7aa5352 <+182>:	mov    %al,-0x19(%ebp)
   0xb7aa5355 <+185>:	movzbl -0x19(%ebp),%eax
   0xb7aa5359 <+189>:	mov    %eax,0x4(%esp)
   0xb7aa535d <+193>:	mov    0x8(%ebp),%eax
   0xb7aa5360 <+196>:	mov    %eax,(%esp)
   0xb7aa5363 <+199>:	call   0xb7926720 <MCOperand_CreateReg0@plt>
   0xb7aa5368 <+204>:	add    $0x10c,%esp
   0xb7aa536e <+210>:	pop    %ebx
   0xb7aa536f <+211>:	pop    %esi
   0xb7aa5370 <+212>:	pop    %edi
   0xb7aa5371 <+213>:	pop    %ebp
   0xb7aa5372 <+214>:	ret    
End of assembler dump.
(gdb) 
End of assembler dump.
(gdb) list
70			ALL_REGS
71				0
72		};
73	#undef ENTRY
74	
75		uint8_t llvmRegnum = llvmRegnums[reg];
76		MCOperand_CreateReg0(mcInst, llvmRegnum);
77	}
78	
79	static const uint8_t segmentRegnums[SEG_OVERRIDE_max] = {
```

**Comment by zonkzonk** [comment]
valgrind with selfcrash:

http://sprunge.us/dNMN

bite full:
http://sprunge.us/bSCK

**Comment by zonkzonk** [comment]
epic fail.
