### ISSUE TITLE
oc in sandbox mode

### ISSUE THREAD

**Issue by C-H-A-I-R** [radare/radare2#2273]
using oc in sandbox mode might fuck things up.  

```
[0x0804c1b4]> oc
Cannot disable sandbox
Missing argument
[0x00000000]> pdf
Cannot find function at 0x00000000
[0x00000000]> s 0x0804c1b4
[0x0804c1b4]> pdf
Cannot find function at 0x0804c1b4
```

A pat ch could be to completly disable oc in sandbox mode:

```
diff --git a/libr/core/cmd_open.c b/libr/core/cmd_open.c
index 88da645..bf5c222 100644
--- a/libr/core/cmd_open.c
+++ b/libr/core/cmd_open.c
@@ -378,6 +378,10 @@ static int cmd_open(void *data, const char *input) {
        case 'c':
                // memleak? lose all settings wtf
                // if load fails does not fallbacks to previous file
+               if (r_sandbox_enable (0)) {
+                        eprintf ("This command is disabled in sandbox mode\n");
+                        return 0;
+                }
                r_core_fini (core);
                r_core_init (core);
                if (input[1] && input[2]) {
```

**Comment by radare** [comment]
Agree. This command must be disabled in sandbox mode.

Thanks! Will commit the fix later today.

**Comment by C-H-A-I-R** [comment]
also pd $s segfaults:

```
Core was generated by `r2 -ecfg.sandbox=true ls'.
Program terminated with signal 11, Segmentation fault.
#0  0xb7695a5b in num_callback (userptr=0x804f620, str=0x8a690e8 "$s", 
    ok=0xbf95d500) at core.c:220
220			case 's': return r_io_desc_size (core->io, core->file->desc);
(gdb) bt
#0  0xb7695a5b in num_callback (userptr=0x804f620, str=0x8a690e8 "$s", 
    ok=0xbf95d500) at core.c:220
#1  0xb6822c64 in r_num_get (num=0x8a690b8, str=0x8a690e8 "$s") at num.c:114
#2  0xb683c0d6 in prim (num=0x8a690b8, nc=0x8a690d4, get=0) at calc.c:107
#3  0xb683bd95 in term (num=0x8a690b8, nc=0x8a690d4, get=0) at calc.c:71
#4  0xb683ba58 in expr (num=0x8a690b8, nc=0x8a690d4, get=0) at calc.c:55
#5  0xb683cd67 in r_num_calc (num=0x8a690b8, str=0x8a35223 "$s", 
    err=0xbf95e7c4) at calc.c:337
#6  0xb6823137 in r_num_math (num=0x8a690b8, str=0x8a35223 "$s") at num.c:232
#7  0xb76c1b0a in cmd_print (data=0x804f620, input=0x8a35221 "d $s")
    at cmd_print.c:1223
#8  0xb76f8564 in r_cmd_call (cmd=0x8c67530, input=0x8a35220 "pd $s")
    at cmd_api.c:182
#9  0xb76d4fe8 in r_core_cmd_subst_i (core=0x804f620, cmd=0x8a35220 "pd $s", 
    colon=0x0) at cmd.c:1478
#10 0xb76d3918 in r_core_cmd_subst (core=0x804f620, cmd=0x8a35220 "pd $s")
    at cmd.c:1013
#11 0xb76d5909 in r_core_cmd (core=0x804f620, cstr=0x8a21dc0 "pd $s", log=1)
    at cmd.c:1669
#12 0xb7698ba5 in r_core_prompt_exec (r=0x804f620) at core.c:1072
#13 0x0804cc45 in main (argc=3, argv=0xbf95fb34, envp=0xbf95fb44)
    at radare2.c:771

```
