### ISSUE TITLE
~ crash

### ISSUE THREAD

**Issue by q6r** [radare/radare2#2323]
used version : `d1351cf836df3e2e63043a6dc728e880316f00eb`

Try `r2 -q -c "f ~.." /bin/false`

```
$ bt
#0  0x00007ffff3f13548 in __memcpy_avx_unaligned () from /usr/lib/libc.so.6
#1  0x00007ffff7495efb in r_cons_memcat (str=0x6d30e1 "roject", len=0x656c6966) at cons.c:557
#2  0x00007ffff7498388 in printpage (line=0x6d2ed0 "", index=0x802de0, ms=0x6d3170, from=0xfffffffe, to=0x1) at less.c:16
#3  0x00007ffff7498786 in r_cons_less_str (str=0x676f90 "X\234\030\364\377\177") at less.c:99
#4  0x00007ffff749761b in r_cons_grepbuf (buf=0x676f90 "X\234\030\364\377\177", len=0x0) at grep.c:171
#5  0x00007ffff74955cd in r_cons_filter () at cons.c:344
#6  0x00007ffff74956ec in r_cons_flush () at cons.c:384
#7  0x0000000000404e9e in main (argc=0x5, argv=0x7fffffffd198, envp=0x7fffffffd1c8) at radare2.c:727
#8  0x00007ffff3e0c800 in __libc_start_main () from /usr/lib/libc.so.6
#9  0x0000000000402b79 in _start ()
```

**Comment by jvoisin** [comment]
Reproduced.
