### ISSUE TITLE
Segfault in ragg2

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2382]
How to reproduce:
```
$ ragg2 -i exec -a x86 -b 32 -f elf -k linux -o pouet.bin
zsh: segmentation fault  ragg2 -i exec -a x86 -b 32 -f elf -k linux -o pouet.bin
```

Backtrace:
```
jvoisin@kaa 23:52 ~/prez/SudTelecom gdb ragg2         
Reading symbols from ragg2...done.
gdb-peda$ r -i exec -a x86 -b 32 -f elf -k linux -o pouet.bin
Starting program: /usr/local/bin/ragg2 -i exec -a x86 -b 32 -f elf -k linux -o pouet.bin
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
[----------------------------------registers-----------------------------------]
RAX: 0x0 
RBX: 0x61d910 ("")
RCX: 0x61a1f0 --> 0x61a280 ("-")
RDX: 0x607630 ("")
RSI: 0x61a300 ("{\n")
RDI: 0x607630 ("")
RBP: 0x7fffffffd840 --> 0x7fffffffd880 --> 0x7fffffffd8e0 --> 0x7fffffffd920 --> 0x7fffffffde60 ("")
RSP: 0x7fffffffd818 --> 0x7ffff791fc6a (<r_bin_object_set_sections+112>:	jmp    0x7ffff791fc71 <r_bin_object_set_sections+119>)
RIP: 0x0 
R8 : 0x0 
R9 : 0x2 (b'\x02')
R10: 0x7fffffffd5c0 ("")
R11: 0x7ffff7922a00 (<r_bin_file_find_by_name_n+125>:	mov    eax,DWORD PTR [rbp-0x14])
R12: 0x401610 (<_start>:	xor    ebp,ebp)
R13: 0x7fffffffdf40 ("\r")
R14: 0x0 
R15: 0x0
[-------------------------------------code-------------------------------------]
Invalid $PC address: 0x0
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffd818 --> 0x7ffff791fc6a (<r_bin_object_set_sections+112>:	jmp    0x7ffff791fc71 <r_bin_object_set_sections+119>)
0008| 0x7fffffffd820 --> 0x61a300 ("{\n")
0016| 0x7fffffffd828 --> 0x61a1f0 --> 0x61a280 ("-")
0024| 0x7fffffffd830 ("0v`")
0032| 0x7fffffffd838 --> 0x61a1f0 --> 0x61a280 ("-")
0040| 0x7fffffffd840 --> 0x7fffffffd880 --> 0x7fffffffd8e0 --> 0x7fffffffd920 --> 0x7fffffffde60 ("")
0048| 0x7fffffffd848 --> 0x7ffff7922b38 (<r_bin_file_set_cur_binfile_obj+190>:	mov    eax,0x1)
0056| 0x7fffffffd850 ("")
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x0000000000000000 in ?? ()
gdb-peda$ bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff791fc6a in r_bin_object_set_sections (bf=0x61a1f0, obj=0x61a300) at bin.c:874
#2  0x00007ffff7922b38 in r_bin_file_set_cur_binfile_obj (bin=0x6075d0, bf=0x61a1f0, obj=0x61a300) at bin.c:1805
#3  0x00007ffff79213bb in r_bin_use_arch (bin=0x6075d0, arch=0x7fffffffe40b "x86", bits=0x20, name=0x7fffffffe418 "elf") at bin.c:1337
#4  0x000000000040187a in create (format=0x7fffffffe418 "elf", arch=0x7fffffffe40b "x86", bits=0x20, 
    code=0x6072b0 "1\300Ph//shh/bin\211\343PS\211ᙰ\v̀A", codelen=0x18) at ragg2.c:61
#5  0x0000000000402a7f in main (argc=0xd, argv=0x7fffffffdf48) at ragg2.c:398
#6  0x00007ffff7304ec5 in __libc_start_main (main=0x4019dc <main>, argc=0xd, argv=0x7fffffffdf48, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf38) at libc-start.c:287
#7  0x0000000000401639 in _start ()
gdb-peda$ 
```

**Comment by Maijin** [comment]
Ok this need a test
