### ISSUE TITLE
[zzuf] Elf64_r_bin_elf_get_libs 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2447]
morrn,

```
Core was generated by `r2 -q -c /R/ pop -d ./a.out.bak'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe8ec1151cc in __strncpy_ssse3 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fe8ec1151cc in __strncpy_ssse3 () from /usr/lib/libc.so.6
#1  0x00007fe8ef29a87f in Elf64_r_bin_elf_get_libs (bin=0x18c8690)
    at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1151
#2  0x00007fe8ef294d4f in libs (arch=0x18c7f00) at /home/zlul/src/radare2/libr/..//libr/bin/p/bin_elf.c:380
#3  0x00007fe8ef273836 in r_bin_object_set_items (binfile=0x18c7f00, o=0x18c8460) at bin.c:421
#4  0x00007fe8ef27521c in r_bin_object_new (binfile=0x18c7f00, plugin=0x187ff10, baseaddr=0, loadaddr=0, offset=0, sz=8473)
    at bin.c:943
#5  0x00007fe8ef2757fe in r_bin_file_new_from_bytes (bin=0x187b0c0, file=0x18c0890 "./a.out.bak", 
    bytes=0x18c5dd0 "\177ELF\002\001\001", sz=8473, file_sz=8473, rawstr=0, baseaddr=0, loadaddr=0, fd=1532, 
    pluginname=0x0, xtrname=0x0, offset=0) at bin.c:1054
#6  0x00007fe8ef27452b in r_bin_load_io_at_offset_as_sz (bin=0x187b0c0, desc=0x18ca890, baseaddr=0, loadaddr=0, xtr_idx=0, 
    offset=0, name=0x0, sz=8473) at bin.c:643
#7  0x00007fe8ef2745e0 in r_bin_load_io_at_offset_as (bin=0x187b0c0, desc=0x18ca890, baseaddr=0, loadaddr=0, xtr_idx=0, 
    offset=0, name=0x0) at bin.c:665
#8  0x00007fe8ef274036 in r_bin_load_io (bin=0x187b0c0, desc=0x18ca890, baseaddr=0, loadaddr=0, xtr_idx=0) at bin.c:545
#9  0x00007fe8ef273b1e in r_bin_load (bin=0x187b0c0, file=0x18ca696 "./a.out.bak", baseaddr=0, loadaddr=0, xtr_idx=0, 
    fd=1532, rawstr=0) at bin.c:451
#10 0x00007fe8efdf79bb in r_core_file_do_load_for_debug (r=0x607980 <r>, loadaddr=0, filenameuri=0x18ca696 "./a.out.bak")
    at file.c:301
#11 0x00007fe8efdf8013 in r_core_bin_load (r=0x607980 <r>, filenameuri=0x18ca696 "./a.out.bak", baddr=4194304) at file.c:474
#12 0x00000000004042fd in main (argc=6, argv=0x7ffc2830dc08, envp=0x7ffc2830dc40) at radare2.c:533
(gdb) list
182                                     if (nptr) ptr = nptr+1;
183                                     if (th) r_th_lock_leave(th->user);
184                             } while (nptr);
185                     //r_core_cmd (&r, cmd, 0);
186                     r_str_free (rabin_cmd);
187                     rabin_cmd = NULL;
188             }
189             if (th) eprintf ("rabin2: done\n");
190             return 0;
191     }
(gdb) up
#1  0x00007fe8ef29a87f in Elf64_r_bin_elf_get_libs (bin=0x18c8690)
    at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1151
1151                            strncpy (ret[k].name, bin->strtab + bin->dyn_buf[j].d_un.d_val, ELF_STRING_LENGTH);
(gdb) list
1146                            ret = realloc (ret, (k+1) * sizeof (struct r_bin_elf_lib_t));
1147                            if (ret == NULL) {
1148                                    perror ("realloc (libs)");
1149                                    return NULL;
1150                            }
1151                            strncpy (ret[k].name, bin->strtab + bin->dyn_buf[j].d_un.d_val, ELF_STRING_LENGTH);
1152                            ret[k].last = 0;
1153                            if (ret[k].name[0]) {
1154                                    k++;
1155                            }
```

arch 64bit

fuzzed_file: 
![fuzzed_file](https://cloud.githubusercontent.com/assets/5694980/7352105/e61126dc-ed09-11e4-8280-4d320d354add.png)

a.out.bak:
![a out](https://cloud.githubusercontent.com/assets/5694980/7352147/3135a250-ed0a-11e4-965d-5fc69397e4b6.png)

zzuf args: 
zzuf -s 0:1000000 -r 0.006  -q -c -C 0 -v  -T 5 -M 100 r2 -q -c "/R/ pop" -d ./a.out.bak 2>log

Greetings
--zlul

**Comment by alvarofe** [comment]
I am working on this. But I can't download the fuzzed file.

Can you send it by email ? alvaro.felipe91@gmail.com

**Comment by zonkzonk** [comment]
@alvarofe "save link target as" should work
otherwise try wget https://cloud.githubusercontent.com/assets/5694980/7352105/e61126dc-ed09-11e4-8280-4d320d354add.png

**Comment by alvarofe** [comment]
I was downloading png and I thought that was a mistake

**Comment by zonkzonk** [comment]
no, you have to rename it...

**Comment by alvarofe** [comment]
I downloaded fuzzed_file but after rename it is not a elf-binary. 

```
alvaro_fe@macbook 19:03 /tmp file fuzzed
fuzzed: data
``` 
I will try to run zzuf to see if I get something

**Comment by radare** [comment]
dat elf is so malformed that even the magic is wrong. (ELG vs ELF)

**Comment by radare** [comment]
Looks fixed in latest git
