### ISSUE TITLE
AddressSanitizer format/elf/elf.c

### ISSUE THREAD

**Issue by revskills** [radare/radare2#2454]
```
==19417==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61b00001f7b6 at pc 0x7f5ca4d8d5b5 bp 0x7fff9dca1ea0 sp 0x7fff9dca1e90
READ of size 2 at 0x61b00001f7b6 thread T0
    #0 0x7f5ca4d8d5b4 in Elf64_r_bin_elf_get_symbols /home/revskills/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1462
    #1 0x7f5ca4d792f1 in symbols /home/revskills/radare2/libr/..//libr/bin/p/bin_elf.c:249
    #2 0x7f5ca4d27d2f in r_bin_object_set_items /home/revskills/radare2/libr/bin/bin.c:422
    #3 0x7f5ca4d2b479 in r_bin_object_new /home/revskills/radare2/libr/bin/bin.c:943
    #4 0x7f5ca4d2c178 in r_bin_file_new_from_bytes /home/revskills/radare2/libr/bin/bin.c:1054
    #5 0x7f5ca4d29a96 in r_bin_load_io_at_offset_as_sz /home/revskills/radare2/libr/bin/bin.c:643
    #6 0x7f5ca4d29b91 in r_bin_load_io_at_offset_as /home/revskills/radare2/libr/bin/bin.c:665
    #7 0x7f5ca4d28fc4 in r_bin_load_io /home/revskills/radare2/libr/bin/bin.c:545
    #8 0x7f5ca5b1613c in r_core_file_do_load_for_io_plugin /home/revskills/radare2/libr/core/file.c:344
    #9 0x7f5ca5b16a75 in r_core_bin_load /home/revskills/radare2/libr/core/file.c:476
    #10 0x4061fd in main /home/revskills/radare2/binr/radare2/radare2.c:573
    #11 0x7f5ca0c87ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #12 0x4030f8 (/home/revskills/radare2/binr/radare2/radare2+0x4030f8)

0x61b00001f7b6 is located 107404247299998 bytes to the rightASAN:SIGSEGV
==19417==AddressSanitizer
```

file from radare-regressions: id062 4f902f2b973f32e9935cd774b1543a70
radare2 0.9.9-git 7749 @ linux-little-x86-64 git.0.9.8-1399-g5b4a4b7
commit: 5b4a4b7be0528c11fbe197ee957cd4afbaedb623 build: 2015-04-28

**Comment by alvarofe** [comment]
Thanks @revskills

**Comment by jjdredd** [comment]
```patch
diff --git a/libr/bin/format/elf/elf.c b/libr/bin/format/elf/elf.c
index 7f3a198..9c2edd2 100644
--- a/libr/bin/format/elf/elf.c
+++ b/libr/bin/format/elf/elf.c
@@ -1450,7 +1450,7 @@ if (
 				free (strtab);
 				return NULL;
 			}
-			for (j = k = ret_ctr = 0; j < bin->shdr[i].sh_size; j += sizeof (Elf_(Sym)), k++) {
+			for (j = k = ret_ctr = 0; j < bin->shdr[i].sh_size && k < nsym; j += sizeof (Elf_(Sym)), k++) {
 				if (k == 0)
 					continue;
 				if (type == R_BIN_ELF_IMPORTS && sym[k].st_shndx == STN_UNDEF) {
```

**Comment by radare** [comment]
Fixed by @alvarofe in git. Thanks!
