### ISSUE TITLE
AddressSanitizer libr/bin/dwarf.c

### ISSUE THREAD

**Issue by revskills** [radare/radare2#2457]
```
==27450==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x604000006578 at pc 0x7f6ff7ec542c bp 0x7fff3b65cb30 sp 0x7fff3b65cb20
READ of size 8 at 0x604000006578 thread T0
    #0 0x7f6ff7ec542b in r_bin_dwarf_parse_aranges_raw /home/revskills/radare2/libr/bin/dwarf.c:785
    #1 0x7f6ff7ecb010 in r_bin_dwarf_parse_aranges /home/revskills/radare2/libr/bin/dwarf.c:1588
    #2 0x7f6ff8cd349e in bin_dwarf /home/revskills/radare2/libr/core/bin.c:461
    #3 0x7f6ff8cdd2b3 in r_core_bin_info /home/revskills/radare2/libr/core/bin.c:1617
    #4 0x7f6ff8ccf982 in r_core_bin_set_env /home/revskills/radare2/libr/core/bin.c:94
    #5 0x7f6ff8ca3191 in r_core_file_do_load_for_io_plugin /home/revskills/radare2/libr/core/file.c:349
    #6 0x7f6ff8ca3a75 in r_core_bin_load /home/revskills/radare2/libr/core/file.c:476
    #7 0x4061fd in main /home/revskills/radare2/binr/radare2/radare2.c:573
    #8 0x7f6ff3e14ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #9 0x4030f8 (/home/revskills/radare2/binr/radare2/radare2+0x4030f8)

0x604000006578 is located 101428199816469 bytes insideASAN:SIGSEGV
==27450==AddressSanitizer
```

file: http://revskills.cz/r2/testfile_const_type (feel free to use for regression tests)
radare2 0.9.9-git 7749 @ linux-little-x86-64 git.0.9.8-1399-g5b4a4b7
commit: 5b4a4b7 build: 2015-04-28

**Comment by revskills** [comment]
Grouping results:

==20336==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x604000006580 at pc 0x7f10cc5499ec bp 0x7fff6e163130 sp 0x7fff6e163120
READ of size 1 at 0x604000006580 thread T0
    #0 0x7f10cc5499eb in r_bin_dwarf_parse_opcodes /home/revskills/radare2/libr/bin/dwarf.c:646
    #1 0x7f10cc549fa7 in r_bin_dwarf_parse_line_raw2 /home/revskills/radare2/libr/bin/dwarf.c:698
    #2 0x7f10cc54fb96 in r_bin_dwarf_parse_line /home/revskills/radare2/libr/bin/dwarf.c:1541
    #3 0x7f10cd3584d3 in bin_dwarf /home/revskills/radare2/libr/core/bin.c:462
    #4 0x7f10cd3622b3 in r_core_bin_info /home/revskills/radare2/libr/core/bin.c:1617
    #5 0x7f10cd354982 in r_core_bin_set_env /home/revskills/radare2/libr/core/bin.c:94
    #6 0x7f10cd328191 in r_core_file_do_load_for_io_plugin /home/revskills/radare2/libr/core/file.c:349
    #7 0x7f10cd328a75 in r_core_bin_load /home/revskills/radare2/libr/core/file.c:476
    #8 0x4061fd in main /home/revskills/radare2/binr/radare2/radare2.c:573
    #9 0x7f10c8499ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #10 0x4030f8 (/home/revskills/radare2/binr/radare2/radare2+0x4030f8)

0x604000006580 is located 101428199816477 bytes insideASAN:SIGSEGV
==20336==AddressSanitizer

file: http://revskills.cz/r2/testfile54-32.so.debug (feel free to use for regression tests)
radare2 0.9.9-git 7749 @ linux-little-x86-64 git.0.9.8-1399-g5b4a4b7
commit: 5b4a4b7 build: 2015-04-28
