### ISSUE TITLE
r2 -c "/c", Segfault  in X86_get_insn_id

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2492]
morrn,

```
Core was generated by `r2 -c /c /dev/urandom'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f781874c35f in X86_get_insn_id (h=0x14de720, insn=0x14de8c0, id=2432) at arch/X86/X86Mapping.c:2317
2317                    insn->id = insns[i].mapid;
(gdb) bt
#0  0x00007f781874c35f in X86_get_insn_id (h=0x14de720, insn=0x14de8c0, id=2432) at arch/X86/X86Mapping.c:2317
#1  0x00007f781864c541 in cs_disasm (ud=21882656, buffer=0x14df92e "\362", <incomplete sequence \363>, size=2, offset=111358, count=1, 
    insn=0x7f7817ab2340 <insn>) at cs.c:494
#2  0x00007f78172cd3af in disassemble (a=0x1476170, op=0x7ffc92e98190, buf=0x14df92e "\362", <incomplete sequence \363>, len=2) at p/asm_x86_cs.c:65
#3  0x00007f78172eb262 in r_asm_disassemble (a=0x1476170, op=0x7ffc92e98190, buf=0x14df92e "\362", <incomplete sequence \363>, len=2) at asm.c:321
#4  0x00007f7819b262f3 in r_core_asm_strsearch (core=0x607980 <r>, input=0x14c6c63 "\026x\177", from=0, to=18446744073709551614, maxhits=0) at asm.c:109
#5  0x00007f7819af1cd6 in do_asm_search (core=0x607980 <r>, param=0x7ffc92e98960, input=0x14c6c61 "c") at cmd_search.c:1211
#6  0x00007f7819af3f2d in cmd_search (data=0x607980 <r>, input=0x14c6c61 "c") at cmd_search.c:1827
#7  0x00007f7819b1c71d in r_cmd_call (cmd=0x14a21f0, input=0x14c6c60 "/c") at cmd_api.c:182
#8  0x00007f7819af93fa in r_core_cmd_subst_i (core=0x607980 <r>, cmd=0x14c6c60 "/c", colon=0x0) at cmd.c:1564
#9  0x00007f7819af77d8 in r_core_cmd_subst (core=0x607980 <r>, cmd=0x14c6c60 "/c") at cmd.c:1061
#10 0x00007f7819af9f60 in r_core_cmd (core=0x607980 <r>, cstr=0x7ffc92e99e02 "/c", log=0) at cmd.c:1782
#11 0x00007f7819afa556 in r_core_cmd0 (user=0x607980 <r>, cmd=0x7ffc92e99e02 "/c") at cmd.c:1913
#12 0x0000000000404e99 in main (argc=4, argv=0x7ffc92e99918, envp=0x7ffc92e99940) at radare2.c:726
(gdb) !r2 -v
radare2 0.9.9-git 7780 @ linux-little-x86-64 git.0.9.7-3946-g588bd73
commit: 588bd73b0b3e754fbf70525d96fdbebd392b53e8 build: 2015-05-03
```

Greetings
--zlul

**Comment by zonkzonk** [comment]
can't reproduce in fd7e8000e9146ff642bda38745ad4b314da8b9a0
