### ISSUE TITLE
[zzuf] [i386] r2 -d aas/aac

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2604]
morn,

zzuf args:
zzuf -s 0:10000 -r 0.006  -q -c -C 2 -v -T 5 -M 100 r2 -q -c 'aac $s; aas $v' -d ./a.out.bak >> log 2>&1

![fuzzed_file 25](https://cloud.githubusercontent.com/assets/5694980/7754483/324346ac-ffed-11e4-936e-f8cd94d55a30.png)

![a out bak](https://cloud.githubusercontent.com/assets/5694980/7754988/28b18398-fff1-11e4-8f8c-324520e45d9d.png)

```
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
Core was generated by `r2 -q -c aac $s; aas $v -d ./a.out.bak'.
Program terminated with signal 11, Segmentation fault.
#0  0xb65ca3b7 in _IO_vfprintf_internal (s=0xbf9b5cdc, format=0xb7659f76 "0x%08llx %lld %s\n", ap=0xbf9b5e04 "") at vfprintf.c:1629
1629	vfprintf.c: No such file or directory.
(gdb) bt
#0  0xb65ca3b7 in _IO_vfprintf_internal (s=0xbf9b5cdc, format=0xb7659f76 "0x%08llx %lld %s\n", ap=0xbf9b5e04 "") at vfprintf.c:1629
#1  0xb65edd80 in _IO_vsnprintf (string=0x8e9e08a "0x407c48000 644412735563497488 0\nf ebp 1 0x0\nf esi 1 0x0\nf edi 1 0x0\nf eflags 1 0x200292\nfs-\n", maxlen=32693, format=0xb7659f76 "0x%08llx %lld %s\n", 
    args=0xbf9b5e04 "") at vsnprintf.c:120
#2  0xb7550173 in r_cons_printf (format=0xb7659f76 "0x%08llx %lld %s\n") at cons.c:552
#3  0xb760e3a8 in bin_symbols (r=0x804f740, mode=4, baddr=134512640, laddr=0, va=1, at=0, name=0x0) at bin.c:1031
#4  0xb76114db in r_core_bin_info (core=0x804f740, action=64, mode=4, va=1, filter=0x0, loadaddr=0, chksum=0x0) at bin.c:1655
#5  0xb75d8146 in cmd_info (data=0x804f740, input=0x8ef8131 "sq") at cmd_info.c:256
#6  0xb7617d1c in r_cmd_call (cmd=0x8ecd2c0, input=0x8ef8130 "isq") at cmd_api.c:182
#7  0xb75f34a4 in r_core_cmd_subst_i (core=0x804f740, cmd=0x8ef8130 "isq", colon=0x0) at cmd.c:1583
#8  0xb75f1b52 in r_core_cmd_subst (core=0x804f740, cmd=0x8ef8130 "isq") at cmd.c:1080
#9  0xb75f3f18 in r_core_cmd (core=0x804f740, cstr=0x8eed250 "isq~[0]", log=0) at cmd.c:1801
#10 0xb75f46db in r_core_cmd_str (core=0x804f740, cmd=0x8eed250 "isq~[0]") at cmd.c:1982
#11 0xb75f296c in r_core_cmd_subst_i (core=0x804f740, cmd=0x8eed248 "af @@= ", colon=0x0) at cmd.c:1376
#12 0xb75f1b52 in r_core_cmd_subst (core=0x804f740, cmd=0x8eed248 "af @@= ") at cmd.c:1080
#13 0xb75f3f18 in r_core_cmd (core=0x804f740, cstr=0xb7648f92 "af @@= `isq~[0]`", log=0) at cmd.c:1801
#14 0xb75f44ca in r_core_cmd0 (user=0x804f740, cmd=0xb7648f92 "af @@= `isq~[0]`") at cmd.c:1932
#15 0xb75d29e1 in cmd_anal (data=0x804f740, input=0x8eed209 "as $v") at cmd_anal.c:2467
#16 0xb7617d1c in r_cmd_call (cmd=0x8ecd2c0, input=0x8eed208 "aas $v") at cmd_api.c:182
#17 0xb75f34a4 in r_core_cmd_subst_i (core=0x804f740, cmd=0x8eed208 "aas $v", colon=0x0) at cmd.c:1583
#18 0xb75f1b52 in r_core_cmd_subst (core=0x804f740, cmd=0x8eed208 "aas $v") at cmd.c:1080
#19 0xb75f1c18 in r_core_cmd_subst (core=0x804f740, cmd=0x8f1f7a0 "aac $s") at cmd.c:1098
#20 0xb75f3f18 in r_core_cmd (core=0x804f740, cstr=0xbf9b8696 "aac $s; aas $v", log=0) at cmd.c:1801
#21 0xb75f44ca in r_core_cmd0 (user=0x804f740, cmd=0xbf9b8696 "aac $s; aas $v") at cmd.c:1932
#22 0x0804ca49 in main (argc=6, argv=0xbf9b7d64, envp=0xbf9b7d80) at radare2.c:732
(gdb) x/i $pc
=> 0xb65ca3b7 <_IO_vfprintf_internal+7223>:	repnz scas %es:(%edi),%al
(gdb) l
1624	in vfprintf.c
(gdb) up
#1  0xb65edd80 in _IO_vsnprintf (string=0x8e9e08a "0x407c48000 644412735563497488 0\nf ebp 1 0x0\nf esi 1 0x0\nf edi 1 0x0\nf eflags 1 0x200292\nfs-\n", maxlen=32693, format=0xb7659f76 "0x%08llx %lld %s\n", 
    args=0xbf9b5e04 "") at vsnprintf.c:120
120	vsnprintf.c: No such file or directory.
(gdb) l
115	in vsnprintf.c
(gdb) !r2 -v
radare2 0.9.9-git 7940 @ linux-little-x86-32 git.0.9.8-1584-gbdc2f2e
commit: bdc2f2e661249dd524467042c9e5f05ab34a976f build: 2015-05-21
```

related to #2597 ?

Greetings
--zlul

**Comment by zonkzonk** [comment]
@alvarofe did you test? it still crashes for me with latest r2: frame 0:

```
#0  0xb664d3b7 in _IO_vfprintf_internal (s=0xbf9ef8fc, format=0xb76e024e "0x%08llx %lld %s\n", ap=0xbf9efa24 "") at vfprintf.c:1629
        len = <optimized out>
        string_malloced = <optimized out>
        step0_jumps = {0, -13653, -13579, -13501, -13418, -13344, -13248, -13024, -12733, -12367, -12140, -11875, -11660, -3450, -3880, -3819, -3480, -3465, -9946, -2661, -2926, -11572, -2279, -3349, -2058, 
          -1997, -3269, -3593, -11660, -13100}
        space = 0
        is_short = 0
        use_outdigits = 0
        step1_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, -12367, -12140, -11875, -11660, -3450, -3880, -3819, -3480, -3465, -9946, -2661, -2926, -11572, -2279, -3349, -2058, -1997, -3269, -3593, -11660, 0}
        group = 0
        prec = -1
        step2_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -12140, -11875, -11660, -3450, -3880, -3819, -3480, -3465, -9946, -2661, -2926, -11572, -2279, -3349, -2058, -1997, -3269, -3593, -11660, 0}
        string = 0x4 <Address 0x4 out of bounds>
        left = 0
        is_long_double = -1080100296
        width = <optimized out>
        step3a_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -11961, 0, 0, 0, -3880, -3819, -3480, -3465, -9946, 0, 0, 0, 0, -3349, 0, 0, 0, 0, 0, 0}
        alt = 0
        showsign = 0
        is_long = 0
        is_char = 0
        pad = <optimized out>
        step3b_jumps = {0 <repeats 11 times>, -11660, 0, 0, -3880, -3819, -3480, -3465, -9946, -2661, -2926, -11572, -2279, -3349, -2058, -1997, -3269, 0, 0, 0}
        step4_jumps = {0 <repeats 14 times>, -3880, -3819, -3480, -3465, -9946, -2661, -2926, -11572, -2279, -3349, -2058, -1997, -3269, 0, 0, 0}
        is_negative = -1080100300
        base = 0
        the_arg = {pa_wchar = 0 L'\000', pa_int = 0, pa_long_int = 0, pa_long_long_int = 0, pa_u_int = 0, pa_u_long_int = 0, pa_u_long_long_int = 0, pa_double = 0, pa_long_double = 0, pa_string = 0x0, 
          pa_wstring = 0x0, pa_pointer = 0x0, pa_user = 0x0}
        spec = <optimized out>
        _buffer = {__routine = 0, __arg = 0x0, __canceltype = 0, __prev = 0x0}
        _avail = 0
        thousands_sep = 0x0
        grouping = 0xffffffff <Address 0xffffffff out of bounds>
        f = <optimized out>
        lead_str_end = 0xb76e0250 "%08llx %lld %s\n"
        work_buffer = '\000' <repeats 982 times>, "593208479057969168"
        workstart = 0x0
        workend = 0xbf9ef830 ""
        ap_save = 0xbf9efa24 ""
        nspecs_done = 2
        save_errno = 2
        readonly_format = 0
        args_malloced = 0x0
        specs = <optimized out>
        specs_malloced = false
        jump_table = "\001\000\000\004\000\016\000\006\000\000\a\002\000\003\t\000\005\b\b\b\b\b\b\b\b\b\000\000\000\000\000\000\000\032\000\031\000\023\023\023\000\035\000\000\f\000\000\000\000\000\000\025\000\000\000\000\022\000\r\000\000\000\000\000\000\032\000\024\017\023\023\023\n\017\034\000\v\030\027\021\026\f\000\025\033\020\000\000\022\000\r"
        __PRETTY_FUNCTION__ = "_IO_vfprintf_internal"

```

**Comment by alvarofe** [comment]
With the fuzzed binary I was not getting nothing :S feel free to send a PR to fix it. I will try it again

**Comment by alvarofe** [comment]
I only tested loading the binary not calling with "r2 -d". I will look these days to fix it if I can reproduce it.
