### ISSUE TITLE
AddressSanitizer format/omf/omf.c:338 *WRITE

### ISSUE THREAD

**Issue by revskills** [radare/radare2#2632]
```shell
==15998==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000194cf at pc 0x7f4c6d70207e bp 0x7fff65234fd0 sp 0x7fff65234fc0
WRITE of size 1 at 0x6020000194cf thread T0
    #0 0x7f4c6d70207d in load_omf_content /home/revskills/dev/radare2/libr/..//libr/bin/p/../format/omf/omf.c:338
    #1 0x7f4c6d7022ca in load_record_omf /home/revskills/dev/radare2/libr/..//libr/bin/p/../format/omf/omf.c:358
    #2 0x7f4c6d702446 in load_all_omf_records /home/revskills/dev/radare2/libr/..//libr/bin/p/../format/omf/omf.c:374
    #3 0x7f4c6d704521 in r_bin_internal_omf_load /home/revskills/dev/radare2/libr/..//libr/bin/p/../format/omf/omf.c:614
    #4 0x7f4c6d6fe64a in load_bytes /home/revskills/dev/radare2/libr/..//libr/bin/p/bin_omf.c:11
    #5 0x7f4c6d66268a in r_bin_object_new /home/revskills/dev/radare2/libr/bin/bin.c:911
    #6 0x7f4c6d66373a in r_bin_file_new_from_bytes /home/revskills/dev/radare2/libr/bin/bin.c:1056
    #7 0x7f4c6d661056 in r_bin_load_io_at_offset_as_sz /home/revskills/dev/radare2/libr/bin/bin.c:644
    #8 0x7f4c6d661151 in r_bin_load_io_at_offset_as /home/revskills/dev/radare2/libr/bin/bin.c:666
    #9 0x7f4c6d660584 in r_bin_load_io /home/revskills/dev/radare2/libr/bin/bin.c:546
    #10 0x7f4c6e46922b in r_core_file_do_load_for_io_plugin /home/revskills/dev/radare2/libr/core/file.c:348
    #11 0x7f4c6e469b73 in r_core_bin_load /home/revskills/dev/radare2/libr/core/file.c:485
    #12 0x4062dc in main /home/revskills/dev/radare2/binr/radare2/radare2.c:579
    #13 0x7f4c6959ba3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #14 0x403198 in _start (/home/revskills/dev/radare2/binr/radare2/radare2+0x403198)

0x6020000194cf is located 105686260356247 bytes to the rightASAN:SIGSEGV
==15998==AddressSanitizer
```
file: http://revskills.cz/r2/f486dbe4a04bbc8b87a824429a87b033
radare2 0.9.9-git 7979 @ linux-little-x86-64 git.0.9.8-1627-g4c84b3a
commit: 4c84b3a2d527ae915970ba36fa76de224bc8ac12 build: 2015-05-27

**Comment by revskills** [comment]
@ampotos Can you check this please?

**Comment by ampotos** [comment]
I will check this tomorrow.

**Comment by revskills** [comment]
fixed
