### ISSUE TITLE
anal_mips_cs segfault

### ISSUE THREAD

**Issue by q6r** [radare/radare2#2651]
version : d4fc6d46 ...

# valgrind
```                                                                                                                                                                      
==14876== Memcheck, a memory error detector
==14876== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==14876== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==14876== Command: r2 -a mips -A ./mips.elf
==14876==
Warning: Cannot initialize dynamic section
==14876== Invalid read of size 1
==14876==    at 0x4C2D5F7: strcpy (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14876==    by 0x5EE9B6B: arg (anal_mips_cs.c:24)
==14876==    by 0x5EE9DFC: analop_esil (anal_mips_cs.c:63)
==14876==    by 0x5EEB716: analop (anal_mips_cs.c:500)
==14876==    by 0x5F12BBA: r_anal_op (op.c:54)
==14876==    by 0x5F14C8B: fcn_recurse (fcn.c:287)
==14876==    by 0x5F163C8: r_anal_fcn (fcn.c:637)
==14876==    by 0x4ED0AC8: r_core_anal_fcn (anal.c:815)
==14876==    by 0x4ED10B9: r_core_anal_fcn (anal.c:950)
==14876==    by 0x4ED10B9: r_core_anal_fcn (anal.c:950)
==14876==    by 0x4ED38B6: r_core_anal_all (anal.c:1602)
==14876==    by 0x4E88AFF: cmd_anal (cmd_anal.c:2493)
==14876==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==14876==
==14876==
==14876== Process terminating with default action of signal 11 (SIGSEGV)
==14876==  Access not within mapped region at address 0x0
==14876==    at 0x4C2D5F7: strcpy (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14876==    by 0x5EE9B6B: arg (anal_mips_cs.c:24)
==14876==    by 0x5EE9DFC: analop_esil (anal_mips_cs.c:63)
==14876==    by 0x5EEB716: analop (anal_mips_cs.c:500)
==14876==    by 0x5F12BBA: r_anal_op (op.c:54)
==14876==    by 0x5F14C8B: fcn_recurse (fcn.c:287)
==14876==    by 0x5F163C8: r_anal_fcn (fcn.c:637)
==14876==    by 0x4ED0AC8: r_core_anal_fcn (anal.c:815)
==14876==    by 0x4ED10B9: r_core_anal_fcn (anal.c:950)
==14876==    by 0x4ED10B9: r_core_anal_fcn (anal.c:950)
==14876==    by 0x4ED38B6: r_core_anal_all (anal.c:1602)
==14876==    by 0x4E88AFF: cmd_anal (cmd_anal.c:2493)
==14876==  If you believe this happened as a result of a stack
==14876==  overflow in your program's main thread (unlikely but
==14876==  possible), you can try to increase the size of the
==14876==  main thread stack using the --main-stacksize= flag.
==14876==  The main thread stack size used in this run was 8388608.
==14876==
==14876== HEAP SUMMARY:
==14876==     in use at exit: 4,862,010 bytes in 17,871 blocks
==14876==   total heap usage: 37,844 allocs, 19,973 frees, 14,271,850 bytes allocated
==14876==
==14876== LEAK SUMMARY:
==14876==    definitely lost: 24,024 bytes in 460 blocks
==14876==    indirectly lost: 29,497 bytes in 279 blocks
==14876==      possibly lost: 14,928 bytes in 41 blocks
==14876==    still reachable: 4,793,561 bytes in 17,091 blocks
==14876==         suppressed: 0 bytes in 0 blocks
==14876== Rerun with --leak-check=full to see details of leaked memory
==14876==
==14876== For counts of detected and suppressed errors, rerun with: -v
==14876== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
[1]    14876 segmentation fault  valgrind r2 -a mips -A ./mips.elf
```
# backtrace

```
#0  0x00007ffff45de317 in __strcpy_sse2_unaligned () from /usr/lib/libc.so.6
#1  0x00007ffff6a31b6c in arg (handle=0x7fffffffa698, insn=0xa1cca0, buf=0x7fffffffa1a0 "", n=0x1) at /usr/src/radare2/libr/..//libr/anal/p/anal_mips_cs.c:24
#2  0x00007ffff6a31dfd in analop_esil (a=0x6825d0, op=0x7fffffffa760, addr=0x401c24, buf=0xa1a100 "8B", len=0xd70, handle=0x7fffffffa698, insn=0xa1cca0) at /usr/src/radare2/libr/..//libr/anal/p/anal_mips_cs.c:63
#3  0x00007ffff6a33717 in analop (a=0x6825d0, op=0x7fffffffa760, addr=0x401c24, buf=0xa1a100 "8B", len=0xd70) at /usr/src/radare2/libr/..//libr/anal/p/anal_mips_cs.c:500
#4  0x00007ffff6a5abbb in r_anal_op (anal=0x6825d0, op=0x7fffffffa760, addr=0x401c24, data=0xa1a100 "8B", len=0xd70) at op.c:54
#5  0x00007ffff6a5cc8c in fcn_recurse (anal=0x6825d0, fcn=0xa1c8e0, addr=0x401994, buf=0xa19e70 "\340A", len=0x1000, depth=0x10) at fcn.c:287
#6  0x00007ffff6a5e3c9 in r_anal_fcn (anal=0x6825d0, fcn=0xa1c8e0, addr=0x401994, buf=0xa19e70 "\340A", len=0x1000, reftype=0x0) at fcn.c:637
#7  0x00007ffff7b80ac9 in r_core_anal_fcn (core=0x607920 <r>, at=0x401994, from=0xffffffffffffffff, reftype=0x0, depth=0xe) at anal.c:815
#8  0x00007ffff7b810ba in r_core_anal_fcn (core=0x607920 <r>, at=0x4012fc, from=0xffffffffffffffff, reftype=0x0, depth=0xf) at anal.c:950
#9  0x00007ffff7b810ba in r_core_anal_fcn (core=0x607920 <r>, at=0x400ab0, from=0xffffffffffffffff, reftype=0x0, depth=0x10) at anal.c:950
#10 0x00007ffff7b838b7 in r_core_anal_all (core=0x607920 <r>) at anal.c:1602
#11 0x00007ffff7b38b00 in cmd_anal (data=0x607920 <r>, input=0xa18981 "a") at cmd_anal.c:2493
#12 0x00007ffff7b7ccb6 in r_cmd_call (cmd=0x6acdc0, input=0xa18980 "aa") at cmd_api.c:182
#13 0x00007ffff7b595be in r_core_cmd_subst_i (core=0x607920 <r>, cmd=0xa18980 "aa", colon=0x0) at cmd.c:1583
#14 0x00007ffff7b57994 in r_core_cmd_subst (core=0x607920 <r>, cmd=0xa18980 "aa") at cmd.c:1080
#15 0x00007ffff7b5a132 in r_core_cmd (core=0x607920 <r>, cstr=0x6dcd00 "aa", log=0x1) at cmd.c:1801
#16 0x00007ffff7b1aaaf in r_core_prompt_exec (r=0x607920 <r>) at core.c:1076
#17 0x000000000040518c in main (argc=0x2, argv=0x7fffffffddb8, envp=0x7fffffffddd0) at radare2.c:778
#18 0x00007ffff4569800 in __libc_start_main () from /usr/lib/libc.so.6
#19 0x0000000000402bc9 in _start ()
```

in here

```
anal_mips_cs.c:24
23              case MIPS_OP_REG:
24                      sprintf (buf, "%s",
25                              cs_reg_name (*handle,
26                                      insn->detail->mips.operands[n].reg));
27                      break;
```

**Comment by crowell** [comment]
@q6r can you provide the binary being analyzed here?

**Comment by q6r** [comment]
@crowell get the file 0x80.org/mips.elf

**Comment by radare** [comment]
Are you using system or r2's capstone? can you point out which instruction is producing this? can we include this file in our test suite?

**Comment by q6r** [comment]
@radare I was using system's capstone a newer version than r2's capsone. Using r2's capstone solved the problem no segfault. I don't recommend including this file in the test suite maybe find which instruction caused the segfault and create a binary for that. This file is safe but it's a ctf challenge from HTIB so it's up to you to include it.

**Comment by XVilka** [comment]
Adding a 'question' label, since it is not really a bug, since it was fixed by using the right version of the capstone. But having the test for that would be awesome, thus not closing it.

**Comment by radare** [comment]
Can't reproduce. r2 capstone uses latest commits from git-next branch, so i doubt you have a system wide installation more updated unless you do that by hand. i have been testing it a while with ASAN and valgrind with no crashes at all. so i guess it was a capstone bug which has been fixed recently

**Comment by radare** [comment]
its always nice to have test bins for different archs, thats why im asking. thanks!

**Comment by radare** [comment]
see https://github.com/radare/radare2-regressions/commit/5282bc9823c77ad2836c6f00aecd1379f7c74f71
