### ISSUE TITLE
[zzuf] CL cmd_meta_lineinfo

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2654]
morn,

```
Core was generated by `r2 -q -c aa;CL /dev/:10 0x00 /bin/ls'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7e3303fdc2 in cmd_meta_lineinfo (core=0x607920 <r>, input=0x129b3e2 " /dev/:10 0x00$") at cmd_meta.c:203
203                             ret = cmd_meta_add_fileline (core->bin->cur->sdb_addrinfo,
(gdb) bt
#0  0x00007f7e3303fdc2 in cmd_meta_lineinfo (core=0x607920 <r>, input=0x129b3e2 " /dev/:10 0x00$") at cmd_meta.c:203
#1  0x00007f7e33040b29 in cmd_meta (data=0x607920 <r>, input=0x129b3e1 "L /dev/:10 0x00$") at cmd_meta.c:481
#2  0x00007f7e33081cb6 in r_cmd_call (cmd=0x1259be0, input=0x129b3e0 "CL /dev/:10 0x00$") at cmd_api.c:182
#3  0x00007f7e3305e5be in r_core_cmd_subst_i (core=0x607920 <r>, cmd=0x129b3e0 "CL /dev/:10 0x00$", colon=0x0) at cmd.c:1583
#4  0x00007f7e3305c994 in r_core_cmd_subst (core=0x607920 <r>, cmd=0x129b3e0 "CL /dev/:10 0x00$") at cmd.c:1080
#5  0x00007f7e3305f132 in r_core_cmd (core=0x607920 <r>, cstr=0x129b070 "CL /dev/:10 0x00$", log=0) at cmd.c:1801
#6  0x00007f7e3305c6eb in r_core_cmd_pipe (core=0x607920 <r>, radare_cmd=0x129b070 "CL /dev/:10 0x00$", shell_cmd=0x129b082 "(^") at cmd.c:1019
#7  0x00007f7e3305d0ff in r_core_cmd_subst_i (core=0x607920 <r>, cmd=0x129b070 "CL /dev/:10 0x00$", colon=0x0) at cmd.c:1228
#8  0x00007f7e3305c994 in r_core_cmd_subst (core=0x607920 <r>, cmd=0x129b070 "CL /dev/:10 0x00$") at cmd.c:1080
#9  0x00007f7e3305f132 in r_core_cmd (core=0x607920 <r>, cstr=0x129b320 "CL /dev/:10 0x00$|(^", log=0) at cmd.c:1801
#10 0x00007f7e3305c6eb in r_core_cmd_pipe (core=0x607920 <r>, radare_cmd=0x129b320 "CL /dev/:10 0x00$|(^", 
    shell_cmd=0x129b335 "/)/bin/ls$) ZZUF_DEBUG=0 ZZUF_DEBUGFD=17 ZZUF_MEMORY=100 ZZUF_SEED=1 ZZUF_MINRATIO=0.006 ZZUF_MAXRATIO=0.006 LD_PRELOAD=/usr/local/lib/zzuf/libzzuf.so") at cmd.c:1019
#11 0x00007f7e3305d0ff in r_core_cmd_subst_i (core=0x607920 <r>, cmd=0x129b320 "CL /dev/:10 0x00$|(^", colon=0x0) at cmd.c:1228
#12 0x00007f7e3305c994 in r_core_cmd_subst (core=0x607920 <r>, cmd=0x129b320 "CL /dev/:10 0x00$|(^") at cmd.c:1080
#13 0x00007f7e3305ca64 in r_core_cmd_subst (core=0x607920 <r>, 
    cmd=0x1292420 "#e cfg.sandbox = 1&SHELL=/bin/bash TERM=xterm WINDOWID=16777252 USER=sk XTERM_SHELL=/bin/bash LD_LIBRARY_PATH=:/usr/local/lib:/usr/local/lib MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins PATH=/usr/local/sb"...) at cmd.c:1098
#14 0x00007f7e3305da8f in r_core_cmd_subst_i (core=0x607920 <r>, 
    cmd=0x1292160 "#e cfg.sandbox = 1&SHELL=/bin/bash TERM=xterm WINDOWID=16777252 USER=sk XTERM_SHELL=/bin/bash LD_LIBRARY_PATH=:/usr/local/lib:/usr/local/lib MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins PATH=/usr/local/sb"..., colon=0x0) at cmd.c:1393
#15 0x00007f7e3305c994 in r_core_cmd_subst (core=0x607920 <r>, cmd=0x129b270 "#e cfg.sandbox = 1&") at cmd.c:1080
#16 0x00007f7e3305f132 in r_core_cmd (core=0x607920 <r>, cstr=0x129b5f5 "#e cfg.sandbox = 1&`%08x.%08x.%08x.%08x.%08x\\n`", log=0) at cmd.c:1801
#17 0x00007f7e3305f290 in r_core_cmd_lines (core=0x607920 <r>, 
    lines=0x129b530 "e asm.middle = true\ne scr.color  = 0\n#e cfg.sandbox = 1&`%08x.%08x.%08x.%08x.%08x\\n`\n#e cfg.datefmt = %08x.%08x.%08x.%08x.%08x\\n\n#.:6666 >/dev/null\n") at cmd.c:1833
#18 0x00007f7e3305f3e9 in r_core_cmd_file (core=0x607920 <r>, file=0x129b120 "/home/zlul/.radare2rc") at cmd.c:1864
#19 0x0000000000403c68 in main (argc=5, argv=0x7ffcaaace338, envp=0x7ffcaaace368) at radare2.c:421
(gdb) !r2 -v
radare2 0.9.9-git 8007 @ linux-little-x86-64 git.0.9.8-1653-gd4fc6d4
commit: d4fc6d46f5c1e637af237bb0b1d7094dd11187d6 build: 2015-05-30
```

 r2[1002]: segfault at 78 ip 00007f7e3303fdc2 sp 00007ffcaaacbfa0 error 4 in libr_core.so.0.9.9-git[7f7e32feb000+e8000]

Greetings
--zlul

**Comment by zonkzonk** [comment]
can't reproduce in 5efc92520d9e43e22cd60802e9c70b39cc22ed81
