### ISSUE TITLE
[lulz]  0x00007f96a5669abb in r_core_visual_cmd (core=0x607900 <r>, ch=71) at visual.c:1060

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2722]
morrn

```
  r2 -qc "oc; /e `cat /tmp/buf.core`" -d /tmp/ls
Enter
Shift G
```

```
,gdb -q r2 core
Reading symbols from r2...done.

warning: core file may not match specified executable file.
[New LWP 7858]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
kX��*n�X���57�S'.d by `r2 -qc oc; /e Ă���U�ˁX�(/���l�,H�&!hH:J�M�B�g�c
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1cf8dd1abb in r_core_visual_cmd (core=0x607900 <r>, ch=71) at visual.c:1060
1060                                    offset = r_io_desc_size (core->io, core->file->desc) - core->blocksize;
(gdb) bt
#0  0x00007f1cf8dd1abb in r_core_visual_cmd (core=0x607900 <r>, ch=71) at visual.c:1060
#1  0x00007f1cf8dd45a7 in r_core_visual (core=0x607900 <r>, input=0x21e0b73 "") at visual.c:1770
#2  0x00007f1cf8dc13ca in cmd_visual (data=0x607900 <r>, input=0x21e0b72 "Z") at cmd.c:764
#3  0x00007f1cf8de7ba6 in r_cmd_call (cmd=0x2079fa0, input=0x21e0b71 "VZ") at cmd_api.c:182
#4  0x00007f1cf8dc3f40 in r_core_cmd_subst_i (core=0x607900 <r>, cmd=0x21e0b71 "VZ", colon=0x0) at cmd.c:1589
#5  0x00007f1cf8dc229e in r_core_cmd_subst (core=0x607900 <r>, cmd=0x21e0b71 "VZ") at cmd.c:1080
#6  0x00007f1cf8dc50d8 in r_core_cmd (core=0x607900 <r>, 
    cstr=0x7ffc934cf3ad "oc; /e Ă\330\342\005\263\210U\375\346ˁX\353\333(/\262\357\217\027\362l\372,Hu\b\025\324&!hH:J\311M\020\325B\260g\250c\rkX\226\344\362*n\356X\201\362\300\324\347\065\067\346\221S\353/\366H\375Xc\365m\364\216_\033e#T\310\370\351&\210\034i\204\207\207Џ(#\300\213\016u\273\250\216\f\351\033`\374\235\225ct\241\304D\262\210D`,\236\017\304賈\032\064\034\263\201q\234\317\361(\363R\024]\300\034E\363\005T\326\310\330\356a\023\346Z\233\216\320v\256\225\177\235\327x\252\276\216\340\213\b튠\300?t\246\344\341t(\217\034U2\tp\371\036Է\241\342\033"..., log=0) at cmd.c:1937
#7  0x00007f1cf8dc56cd in r_core_cmd0 (user=0x607900 <r>, 
    cmd=0x7ffc934cf3ad "oc; /e Ă\330\342\005\263\210U\375\346ˁX\353\333(/\262\357\217\027\362l\372,Hu\b\025\324&!hH:J\311M\020\325B\260g\250c\rkX\226\344\362*n\356X\201\362\300\324\347\065\067\346\221S\353/\366H\375Xc\365m\364\216_\033e#T\310\370\351&\210\034i\204\207\207Џ(#\300\213\016u\273\250\216\f\351\033`\374\235\225ct\241\304D\262\210D`,\236\017\304賈\032\064\034\263\201q\234\317\361(\363R\024]\300\034E\363\005T\326\310\330\356a\023\346Z\233\216\320v\256\225\177\235\327x\252\276\216\340\213\b튠\300?t\246\344\341t(\217\034U2\tp\371\036Է\241\342\033"...) at cmd.c:2068
#8  0x0000000000404ee7 in main (argc=5, argv=0x7ffc934cdd68, envp=0x7ffc934cdd98) at radare2.c:738
(gdb) i r
rax            0x0      0
rbx            0x0      0
rcx            0x1300   4864
rdx            0x0      0
rsi            0x0      0
rdi            0x21f9f00        35626752
rbp            0x7ffc934cce60   0x7ffc934cce60
rsp            0x7ffc934cb8e0   0x7ffc934cb8e0
r8             0xffff00000000   281470681743360
r9             0x0      0
r10            0xd2     210
r11            0x7f1cf71d2fa8   139762381696936
r12            0x402b40 4205376
r13            0x7ffc934cdd60   140722779774304
r14            0x0      0
r15            0x0      0
rip            0x7f1cf8dd1abb   0x7f1cf8dd1abb <r_core_visual_cmd+5351>
eflags         0x10246  [ PF ZF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
(gdb) !r2 -v
radare2 0.10.0-git 8111 @ linux-little-x86-64 git.0.9.9-5-g0ce8024
commit: 0ce8024e7f5df615908c16b950761ac7118e9f8f build: 2015-06-06
```

*removed*

 r2[7858]: segfault at 10 ip 00007f1cf8dd1abb sp 00007ffc934cb8e0 error 4 in libr_core.so.0.10.0-git[7f1cf8d50000+ea000]

Greetings
--zlul

**Comment by zonkzonk** [comment]
this can be simplified to: 

  r2 -qc "oc;V" /tmp/ls
Shift G

**Comment by Maijin** [comment]
oh :o:

**Comment by zonkzonk** [comment]
well, uhm :)
