### ISSUE TITLE
gs:  double free or corruption (fasttop): 0x00000000027cb670 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2732]
morrn,

![ls](https://cloud.githubusercontent.com/assets/5694980/8040710/df2d0d34-0e12-11e5-9a30-2f62c2ed7ab8.png)

```
[0x004048d0]> gs exit 
*** Error in `r2': double free or corruption (fasttop): 0x00000000027cb670 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x71bad)[0x7fb874980bad]
/usr/lib/libc.so.6(+0x770fe)[0x7fb8749860fe]
/usr/lib/libc.so.6(+0x778db)[0x7fb8749868db]
/usr/lib/libr_egg.so(+0x6b36)[0x7fb874ebdb36]
/usr/lib/libr_egg.so(r_egg_lang_parsechar+0x3ac)[0x7fb874ebe218]
/usr/lib/libr_egg.so(r_egg_compile+0x61)[0x7fb874ebac18]
/usr/lib/libr_core.so(r_core_syscall+0xcf)[0x7fb878511962]
/usr/lib/libr_core.so(+0x57510)[0x7fb878532510]
/usr/lib/libr_core.so(r_cmd_call+0x156)[0x7fb878572bcf]
/usr/lib/libr_core.so(+0x73f69)[0x7fb87854ef69]
/usr/lib/libr_core.so(+0x722c7)[0x7fb87854d2c7]
/usr/lib/libr_core.so(r_core_cmd+0x26a)[0x7fb878550101]
/usr/lib/libr_core.so(r_core_prompt_exec+0x2b)[0x7fb878510088]
r2(main+0x1f51)[0x40514a]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7fb87492f790]
r2[0x402b69]
======= Memory map: ========
00400000-00407000 r-xp 00000000 08:03 25306773                           /usr/bin/radare2
00607000-00608000 rw-p 00007000 08:03 25306773                           /usr/bin/radare2
00608000-00669000 rw-p 00000000 00:00 0 
02390000-027eb000 rw-p 00000000 00:00 0                                  [heap]
7fb8731b4000-7fb8731ca000 r-xp 00000000 08:03 16819385                   /usr/lib/libgcc_s.so.1
7fb8731ca000-7fb8733c9000 ---p 00016000 08:03 16819385                   /usr/lib/libgcc_s.so.1
7fb8733c9000-7fb8733ca000 rw-p 00015000 08:03 16819385                   /usr/lib/libgcc_s.so.1
7fb8733ca000-7fb8733ce000 r-xp 00000000 08:03 17767182                   /usr/lib/radare2/0.10.0-git/asm_6502.so
7fb8733ce000-7fb8735cd000 ---p 00004000 08:03 17767182                   /usr/lib/radare2/0.10.0-git/asm_6502.so
7fb8735cd000-7fb8735cf000 rw-p 00003000 08:03 17767182                   /usr/lib/radare2/0.10.0-git/asm_6502.so
7fb8735cf000-7fb8735d2000 r-xp 00000000 08:03 17767181                   /usr/lib/radare2/0.10.0-git/asm_snes.so
7fb8735d2000-7fb8737d2000 ---p 00003000 08:03 17767181                   /usr/lib/radare2/0.10.0-git/asm_snes.so
7fb8737d2000-7fb8737d4000 rw-p 00003000 08:03 17767181                   /usr/lib/radare2/0.10.0-git/asm_snes.so
7fb8737d4000-7fb8737d6000 r-xp 00000000 08:03 17767180                   /usr/lib/radare2/0.10.0-git/asm_propeller.so
7fb8737d6000-7fb8739d6000 ---p 00002000 08:03 17767180                   /usr/lib/radare2/0.10.0-git/asm_propeller.so
7fb8739d6000-7fb8739d7000 rw-p 00002000 08:03 17767180                   /usr/lib/radare2/0.10.0-git/asm_propeller.so
7fb8739d7000-7fb8739d8000 r-xp 00000000 08:03 17767179                   /usr/lib/radare2/0.10.0-git/asm_x86_nasm.so
7fb8739d8000-7fb873bd8000 ---p 00001000 08:03 17767179                   /usr/lib/radare2/0.10.0-git/asm_x86_nasm.so
7fb873bd8000-7fb873bd9000 rw-p 00001000 08:03 17767179                   /usr/lib/radare2/0.10.0-git/asm_x86_nasm.so
7fb873bd9000-7fb873bda000 r-xp 00000000 08:03 17767178                   /usr/lib/radare2/0.10.0-git/asm_x86_as.so
7fb873bda000-7fb873dda000 ---p 00001000 08:03 17767178                   /usr/lib/radare2/0.10.0-git/asm_x86_as.so
7fb873dda000-7fb873ddb000 rw-p 00001000 08:03 17767178                   /usr/lib/radare2/0.10.0-git/asm_x86_as.so
7fb873ddb000-7fb873dde000 r-xp 00000000 08:03 17015944                   /usr/lib/libdl-2.21.so
7fb873dde000-7fb873fdd000 ---p 00003000 08:03 17015944                   /usr/lib/libdl-2.21.so
7fb873fdd000-7fb873fde000 r--p 00002000 08:03 17015944                   /usr/lib/libdl-2.21.so
7fb873fde000-7fb873fdf000 rw-p 00003000 08:03 17015944                   /usr/lib/libdl-2.21.so
7fb873fdf000-7fb873ff7000 r-xp 00000000 08:03 17015927                   /usr/lib/libpthread-2.21.so
7fb873ff7000-7fb8741f6000 ---p 00018000 08:03 17015927                   /usr/lib/libpthread-2.21.so
7fb8741f6000-7fb8741f7000 r--p 00017000 08:03 17015927                   /usr/lib/libpthread-2.21.so
7fb8741f7000-7fb8741f8000 rw-p 00018000 08:03 17015927                   /usr/lib/libpthread-2.21.so
7fb8741f8000-7fb8741fc000 rw-p 00000000 00:00 0 
7fb8741fc000-7fb8742ff000 r-xp 00000000 08:03 17036255                   /usr/lib/libm-2.21.so
7fb8742ff000-7fb8744fe000 ---p 00103000 08:03 17036255                   /usr/lib/libm-2.21.so
7fb8744fe000-7fb8744ff000 r--p 00102000 08:03 17036255                   /usr/lib/libm-2.21.so
7fb8744ff000-7fb874500000 rw-p 00103000 08:03 17036255                   /usr/lib/libm-2.21.so
7fb874500000-7fb874509000 r-xp 00000000 08:03 17581594                   /usr/lib/libr_socket.so.0.10.0-git
7fb874509000-7fb874709000 ---p 00009000 08:03 17581594                   /usr/lib/libr_socket.so.0.10.0-git
7fb874709000-7fb87470a000 rw-p 00009000 08:03 17581594                   /usr/lib/libr_socket.so.0.10.0-git
7fb87470a000-7fb87470e000 r-xp 00000000 08:03 17110935                   /usr/lib/libr_lang.so.0.10.0-git
7fb87470e000-7fb87490e000 ---p 00004000 08:03 17110935                   /usr/lib/libr_lang.so.0.10.0-git
7fb87490e000-7fb87490f000 rw-p 00004000 08:03 17110935                   /usr/lib/libr_lang.so.0.10.0-git
7fb87490f000-7fb874aa8000 r-xp 00000000 08:03 16908233                   /usr/lib/libc-2.21.so
7fb874aa8000-7fb874ca7000 ---p 00199000 08:03 16908233                   /usr/lib/libc-2.21.so
7fb874ca7000-7fb874cab000 r--p 00198000 08:03 16908233                   /usr/lib/libc-2.21.so
7fb874cab000-7fb874cad000 rw-p 0019c000 08:03 16908233                   /usr/lib/libc-2.21.so
7fb874cad000-7fb874cb1000 rw-p 00000000 00:00 0 
7fb874cb1000-7fb874cb4000 r-xp 00000000 08:03 17032544                   /usr/lib/libr_crypto.so.0.10.0-git
7fb874cb4000-7fb874eb3000 ---p 00003000 08:03 17032544                   /usr/lib/libr_crypto.so.0.10.0-git
7fb874eb3000-7fb874eb7000 rw-p 00002000 08:03 17032544                   /usr/lib/libr_crypto.so.0.10.0-git
7fb874eb7000-7fb874ec5000 r-xp 00000000 08:03 17032728                   /usr/lib/libr_egg.so.0.10.0-git
7fb874ec5000-7fb8750c4000 ---p 0000e000 08:03 17032728                   /usr/lib/libr_egg.so.0.10.0-git
7fb8750c4000-7fb8750c5000 rw-p 0000d000 08:03 17032728                   /usr/lib/libr_egg.so.0.10.0-git
7fb8750c5000-7fb8750c8000 rw-p 00000000 00:00 0 
7fb8750c8000-7fb875116000 r-xp 00000000 08:03 17581598                   /usr/lib/libr_util.so.0.10.0-git
7fb875116000-7fb875315000 ---p 0004e000 08:03 17581598                   /usr/lib/libr_util.so.0.10.0-git
7fb875315000-7fb875318000 rw-p 0004d000 08:03 17581598                   /usr/lib/libr_util.so.0.10.0-git
7fb875318000-7fb875320000 rw-p 00000000 00:00 0 
7fb875320000-7fb875325000 r-xp 00000000 08:03 17032731                   /usr/lib/libr_flags.so.0.10.0-git
7fb875325000-7fb875524000 ---p 00005000 08:03 17032731                   /usr/lib/libr_flags.so.0.10.0-git
7fb875524000-7fb875525000 rw-p 00004000 08:03 17032731                   /usr/lib/libr_flags.so.0.10.0-git
7fb875525000-7fb875537000 r-xp 00000000 08:03 17391342                   /usr/lib/libr_magic.so.0.10.0-git
7fb875537000-7fb875737000 ---p 00012000 08:03 17391342                   /usr/lib/libr_magic.so.0.10.0-git
7fb875737000-7fb875738000 rw-p 00012000 08:03 17391342                   /usr/lib/libr_magic.so.0.10.0-git
7fb875738000-7fb875742000 r-xp 00000000 08:03 17034048                   /usr/lib/libr_hash.so.0.10.0-git
7fb875742000-7fb875941000 ---p 0000a000 08:03 17034048                   /usr/lib/libr_hash.so.0.10.0-git
7fb875941000-7fb875942000 rw-p 00009000 08:03 17034048                   /usr/lib/libr_hash.so.0.10.0-git
7fb875942000-7fb875963000 r-xp 00000000 08:03 17032547                   /usr/lib/libr_db.so.0.10.0-git
7fb875963000-7fb875b63000 ---p 00021000 08:03 17032547                   /usr/lib/libr_db.so.0.10.0-git
7fb875b63000-7fb875b67000 rw-p 00021000 08:03 17032547                   /usr/lib/libr_db.so.0.10.0-git
7fb875b67000-7fb875b7f000 rw-p 00000000 00:00 0 
7fb875b7f000-7fb875b82000 r-xp 00000000 08:03 17581596                   /usr/lib/libr_syscall.so.0.10.0-git
7fb875b82000-7fb875d82000 ---p 00003000 08:03 17581596                   /usr/lib/libr_syscall.so.0.10.0-git
7fb875d82000-7fb875d83000 rw-p 00003000 08:03 17581596                   /usr/lib/libr_syscall.so.0.10.0-git
7fb875d83000-7fb87618d000 r-xp 00000000 08:03 17029991                   /usr/lib/libr_asm.so.0.10.0-git
7fb87618d000-7fb87638c000 ---p 0040a000 08:03 17029991                   /usr/lib/libr_asm.so.0.10.0-git
7fb87638c000-7fb8766e8000 rw-p 00409000 08:03 17029991                   /usr/lib/libr_asm.so.0.10.0-git
7fb8766e8000-7fb876704000 rw-p 00000000 00:00 0 
7fb876704000-7fb876736000 r-xp 00000000 08:03 17032733                   /usr/lib/libr_fs.so.0.10.0-git
7fb876736000-7fb876935000 ---p 00032000 08:03 17032733                   /usr/lib/libr_fs.so.0.10.0-git
7fb876935000-7fb876937000 rw-p 00031000 08:03 17032733                   /usr/lib/libr_fs.so.0.10.0-git
7fb876937000-7fb876942000 rw-p 00000000 00:00 0 
7fb876942000-7fb876984000 r-xp 00000000 08:03 17069894                   /usr/lib/libr_io.so.0.10.0-git
7fb876984000-7fb876b83000 ---p 00042000 08:03 17069894                   /usr/lib/libr_io.so.0.10.0-git
7fb876b83000-7fb876b8c000 rw-p 00041000 08:03 17069894                   /usr/lib/libr_io.so.0.10.0-git
7fb876b8c000-7fb876b94000 rw-p 00000000 00:00 0 
7fb876b94000-7fb876b98000 r-xp 00000000 08:03 17032513                   /usr/lib/libr_bp.so.0.10.0-git
7fb876b98000-7fb876d98000 ---p 00004000 08:03 17032513                   /usr/lib/libr_bp.so.0.10.0-git
7fb876d98000-7fb876d99000 rw-p 00004000 08:03 17032513                   /usr/lib/libr_bp.so.0.10.0-git
7fb876d99000-7fb876d9f000 r-xp 00000000 08:03 17411094                   /usr/lib/libr_reg.so.0.10.0-git
7fb876d9f000-7fb876f9e000 ---p 00006000 08:03 17411094                   /usr/lib/libr_reg.so.0.10.0-git
7fb876f9e000-7fb876f9f000 rw-p 00005000 08:03 17411094                   /usr/lib/libr_reg.so.0.10.0-git
7fb876f9f000-7fb8772d4000 r-xp 00000000 08:03 17029989                   /usr/lib/libr_anal.so.0.10.0-git
7fb8772d4000-7fb8774d3000 ---p 00335000 08:03 17029989                   /usr/lib/libr_anal.so.0.10.0-git
7fb8774d3000-7fb877786000 rw-p 00334000 08:03 17029989                   /usr/lib/libr_anal.so.0.10.0-git
7fb877786000-7fb87778b000 rw-p 00000000 00:00 0 
7fb87778b000-7fb8777a1000 r-xp 00000000 08:03 17032725                   /usr/lib/libr_debug.so.0.10.0-git
7fb8777a1000-7fb8779a1000 ---p 00016000 08:03 17032725                   /usr/lib/libr_debug.so.0.10.0-git
7fb8779a1000-7fb8779a3000 rw-p 00016000 08:03 17032725                   /usr/lib/libr_debug.so.0.10.0-git
7fb8779a3000-7fb877a73000 r-xp 00000000 08:03 17030190                   /usr/lib/libr_bin.so.0.10.0-git
7fb877a73000-7fb877c72000 ---p 000d0000 08:03 17030190                   /usr/lib/libr_bin.so.0.10.0-git
7fb877c72000-7fb877c7b000 rw-p 000cf000 08:03 17030190                   /usr/lib/libr_bin.so.0.10.0-git
7fb877c7b000-7fb877c7f000 r-xp 00000000 08:03 17032517                   /usr/lib/libr_config.so.0.10.0-git
7fb877c7f000-7fb877e7e000 ---p 00004000 08:03 17032517                   /usr/lib/libr_config.so.0.10.0-git
7fb877e7e000-7fb877e7f000 rw-p 00003000 08:03 17032517                   /usr/lib/libr_config.so.0.10.0-git
7fb877e7f000-7fb877e93000 r-xp 00000000 08:03 17032525                   /usr/lib/libr_cons.so.0.10.0-git
7fb877e93000-7fb878092000 ---p 00014000 08:03 17032525                   /usr/lib/libr_cons.so.0.10.0-git
7fb878092000-7fb878094000 rw-p 00013000 08:03 17032525                   /usr/lib/libr_cons.so.0.10.0-git
7fb878094000-7fb878095000 rw-p 00000000 00:00 0 
7fb878095000-7fb87809a000 r-xp 00000000 08:03 17411096                   /usr/lib/libr_search.so.0.10.0-git
7fb87809a000-7fb878299000 ---p 00005000 08:03 17411096                   /usr/lib/libr_search.so.0.10.0-git
7fb878299000-7fb87829a000 rw-p 00004000 08:03 17411096                   /usr/lib/libr_search.so.0.10.0-git
7fb87829a000-7fb8782b9000 r-xp 00000000 08:03 17391356                   /usr/lib/libr_parse.so.0.10.0-git
7fb8782b9000-7fb8784b9000 ---p 0001f000 08:03 17391356                   /usr/lib/libr_parse.so.0.10.0-git
7fb8784b9000-7fb8784ba000 rw-p 0001f000 08:03 17391356                   /usr/lib/libr_parse.so.0.10.0-git
7fb8784ba000-7fb8784db000 rw-p 00000000 00:00 0 
7fb8784db000-7fb8785c5000 r-xp 00000000 08:03 17032534                   /usr/lib/libr_core.so.0.10.0-git
7fb8785c5000-7fb8787c4000 ---p 000ea000 08:03 17032534                   /usr/lib/libr_core.so.0.10.0-git
7fb8787c4000-7fb8787cf000 rw-p 000e9000 08:03 17032534                   /usr/lib/libr_core.so.0.10.0-git
7fb8787cf000-7fb8787d1000 rw-p 00000000 00:00 0 
7fb8787d1000-7fb8787f3000 r-xp 00000000 08:03 17017529                   /usr/lib/ld-2.21.so
7fb8789a1000-7fb8789be000 r--s 00000000 08:03 25168597                   /usr/bin/ls
7fb8789be000-7fb8789cb000 rw-p 00000000 00:00 0 
7fb8789cd000-7fb8789d4000 r--s 00000000 08:03 25370045                   /usr/lib/radare2/0.10.0-git/syscall/linux-x86-64.sdb
7fb8789d4000-7fb8789db000 r--s 00000000 08:03 25370045                   /usr/lib/radare2/0.10.0-git/syscall/linux-x86-64.sdb
7fb8789db000-7fb8789e2000 r--s 00000000 08:03 25370045                   /usr/lib/radare2/0.10.0-git/syscall/linux-x86-64.sdb
7fb8789e2000-7fb8789ed000 r--s 00000000 08:03 18112086                   /usr/lib/radare2/0.10.0-git/opcodes/x86.sdb
7fb8789f0000-7fb8789f2000 rw-p 00000000 00:00 0 
7fb8789f2000-7fb8789f3000 r--p 00021000 08:03 17017529                   /usr/lib/ld-2.21.so
7fb8789f3000-7fb8789f4000 rw-p 00022000 08:03 17017529                   /usr/lib/ld-2.21.so
7fb8789f4000-7fb8789f5000 rw-p 00000000 00:00 0 
7ffdbdae3000-7ffdbdb04000 rw-p 00000000 00:00 0                          [stack]
7ffdbdb55000-7ffdbdb57000 r--p 00000000 00:00 0                          [vvar]
7ffdbdb57000-7ffdbdb59000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
```

,r2 -v
radare2 0.10.0-git 8104 @ linux-little-x86-64 git.0.9.9-6-g8e3ccab
commit: 8e3ccab7c13266a254b001be27bf5c8bab59eaa2 build: 2015-06-07

Greetings
--zlul

**Comment by zonkzonk** [comment]
valgrind:
==3085== Memcheck, a memory error detector
==3085== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==3085== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==3085== Command: r2 /bin/ls
==3085== Parent PID: 3022
==3085== 
==3085== Invalid read of size 1
==3085==    at 0x89E5DF0: __strcmp_sse2_unaligned (in /usr/lib/libc-2.21.so)
==3085==    by 0x8545758: rcc_next (lang.c:769)
==3085==    by 0x8546217: r_egg_lang_parsechar (lang.c:971)
==3085==    by 0x8542C17: r_egg_compile (egg.c:295)
==3085==    by 0x4E6C961: r_core_syscall (core.c:1608)
==3085==    by 0x4E8D50F: cmd_egg (cmd_egg.c:73)
==3085==    by 0x4ECDBCE: r_cmd_call (cmd_api.c:182)
==3085==    by 0x4EA9F68: r_core_cmd_subst_i (cmd.c:1589)
==3085==    by 0x4EA82C6: r_core_cmd_subst (cmd.c:1080)
==3085==    by 0x4EAB100: r_core_cmd (cmd.c:1937)
==3085==    by 0x4E6B087: r_core_prompt_exec (core.c:1079)
==3085==    by 0x405149: main (radare2.c:783)
==3085==  Address 0xabc6820 is 0 bytes inside a block of size 4 free'd
==3085==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3085==    by 0x8544447: r_egg_mkvar (lang.c:386)
==3085==    by 0x85456E5: rcc_next (lang.c:761)
==3085==    by 0x8546217: r_egg_lang_parsechar (lang.c:971)
==3085==    by 0x8542C17: r_egg_compile (egg.c:295)
==3085==    by 0x4E6C961: r_core_syscall (core.c:1608)
==3085==    by 0x4E8D50F: cmd_egg (cmd_egg.c:73)
==3085==    by 0x4ECDBCE: r_cmd_call (cmd_api.c:182)
==3085==    by 0x4EA9F68: r_core_cmd_subst_i (cmd.c:1589)
==3085==    by 0x4EA82C6: r_core_cmd_subst (cmd.c:1080)
==3085==    by 0x4EAB100: r_core_cmd (cmd.c:1937)
==3085==    by 0x4E6B087: r_core_prompt_exec (core.c:1079)
==3085== 
==3085== Invalid read of size 1
==3085==    at 0x89E5DF0: __strcmp_sse2_unaligned (in /usr/lib/libc-2.21.so)
==3085==    by 0x8545839: rcc_next (lang.c:794)
==3085==    by 0x8546217: r_egg_lang_parsechar (lang.c:971)
==3085==    by 0x8542C17: r_egg_compile (egg.c:295)
==3085==    by 0x4E6C961: r_core_syscall (core.c:1608)
==3085==    by 0x4E8D50F: cmd_egg (cmd_egg.c:73)
==3085==    by 0x4ECDBCE: r_cmd_call (cmd_api.c:182)
==3085==    by 0x4EA9F68: r_core_cmd_subst_i (cmd.c:1589)
==3085==    by 0x4EA82C6: r_core_cmd_subst (cmd.c:1080)
==3085==    by 0x4EAB100: r_core_cmd (cmd.c:1937)
==3085==    by 0x4E6B087: r_core_prompt_exec (core.c:1079)
==3085==    by 0x405149: main (radare2.c:783)
==3085==  Address 0xabc6820 is 0 bytes inside a block of size 4 free'd
==3085==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3085==    by 0x8544447: r_egg_mkvar (lang.c:386)
==3085==    by 0x85456E5: rcc_next (lang.c:761)
==3085==    by 0x8546217: r_egg_lang_parsechar (lang.c:971)
==3085==    by 0x8542C17: r_egg_compile (egg.c:295)
==3085==    by 0x4E6C961: r_core_syscall (core.c:1608)
==3085==    by 0x4E8D50F: cmd_egg (cmd_egg.c:73)
==3085==    by 0x4ECDBCE: r_cmd_call (cmd_api.c:182)
==3085==    by 0x4EA9F68: r_core_cmd_subst_i (cmd.c:1589)
==3085==    by 0x4EA82C6: r_core_cmd_subst (cmd.c:1080)
==3085==    by 0x4EAB100: r_core_cmd (cmd.c:1937)
==3085==    by 0x4E6B087: r_core_prompt_exec (core.c:1079)
==3085== 
==3085== Invalid read of size 1
==3085==    at 0x4C2E558: strcmp (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3085==    by 0x8545839: rcc_next (lang.c:794)
==3085==    by 0x8546217: r_egg_lang_parsechar (lang.c:971)
==3085==    by 0x8542C17: r_egg_compile (egg.c:295)
==3085==    by 0x4E6C961: r_core_syscall (core.c:1608)
==3085==    by 0x4E8D50F: cmd_egg (cmd_egg.c:73)
==3085==    by 0x4ECDBCE: r_cmd_call (cmd_api.c:182)
==3085==    by 0x4EA9F68: r_core_cmd_subst_i (cmd.c:1589)
==3085==    by 0x4EA82C6: r_core_cmd_subst (cmd.c:1080)
==3085==    by 0x4EAB100: r_core_cmd (cmd.c:1937)
==3085==    by 0x4E6B087: r_core_prompt_exec (core.c:1079)
==3085==    by 0x405149: main (radare2.c:783)
==3085==  Address 0xabc6821 is 1 bytes inside a block of size 4 free'd
==3085==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3085==    by 0x8544447: r_egg_mkvar (lang.c:386)
==3085==    by 0x85456E5: rcc_next (lang.c:761)
==3085==    by 0x8546217: r_egg_lang_parsechar (lang.c:971)
==3085==    by 0x8542C17: r_egg_compile (egg.c:295)
==3085==    by 0x4E6C961: r_core_syscall (core.c:1608)
==3085==    by 0x4E8D50F: cmd_egg (cmd_egg.c:73)
==3085==    by 0x4ECDBCE: r_cmd_call (cmd_api.c:182)
==3085==    by 0x4EA9F68: r_core_cmd_subst_i (cmd.c:1589)
==3085==    by 0x4EA82C6: r_core_cmd_subst (cmd.c:1080)
==3085==    by 0x4EAB100: r_core_cmd (cmd.c:1937)
==3085==    by 0x4E6B087: r_core_prompt_exec (core.c:1079)
==3085==    by 0x405149: main (radare2.c:783)
==3085==  Address 0xabc76a0 is 0 bytes inside a block of size 4 free'd
==3085==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3085==    by 0x8544447: r_egg_mkvar (lang.c:386)
==3085==    by 0x8545B54: rcc_next (lang.c:840)
==3085==    by 0x8546217: r_egg_lang_parsechar (lang.c:971)
==3085==    by 0x8542C17: r_egg_compile (egg.c:295)
==3085==    by 0x4E6C961: r_core_syscall (core.c:1608)
==3085==    by 0x4E8D50F: cmd_egg (cmd_egg.c:73)
==3085==    by 0x4ECDBCE: r_cmd_call (cmd_api.c:182)
==3085==    by 0x4EA9F68: r_core_cmd_subst_i (cmd.c:1589)
==3085==    by 0x4EA82C6: r_core_cmd_subst (cmd.c:1080)
==3085==    by 0x4EAB100: r_core_cmd (cmd.c:1937)
==3085==    by 0x4E6B087: r_core_prompt_exec (core.c:1079)
==3085== 
==3085== 
==3085== HEAP SUMMARY:
==3085==     in use at exit: 172,611 bytes in 3,526 blocks
==3085==   total heap usage: 22,635 allocs, 19,111 frees, 8,431,956 bytes allocated
==3085== 
==3085== LEAK SUMMARY:
==3085==    definitely lost: 80,141 bytes in 1,721 blocks
==3085==    indirectly lost: 64,666 bytes in 1,752 blocks
==3085==      possibly lost: 0 bytes in 0 blocks
==3085==    still reachable: 27,804 bytes in 53 blocks
==3085==         suppressed: 0 bytes in 0 blocks
==3085== Rerun with --leak-check=full to see details of leaked memory
==3085== 
==3085== For counts of detected and suppressed errors, rerun with: -v

**Comment by zonkzonk** [comment]
```
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `r2 /bin/ls'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fb874942528 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fb874942528 in raise () from /usr/lib/libc.so.6
#1  0x00007fb87494393a in abort () from /usr/lib/libc.so.6
#2  0x00007fb874980bb2 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007fb8749860fe in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007fb8749868db in _int_free () from /usr/lib/libc.so.6
#5  0x00007fb874ebdb36 in rcc_next (egg=0x2394fc0) at lang.c:839
#6  0x00007fb874ebe218 in r_egg_lang_parsechar (egg=0x2394fc0, c=59 ';') at lang.c:971
#7  0x00007fb874ebac18 in r_egg_compile (egg=0x2394fc0) at egg.c:295
#8  0x00007fb878511962 in r_core_syscall (core=0x607900 <r>, name=0x2390030 "exit", args=0x7fb8785986cb "") at core.c:1608
#9  0x00007fb878532510 in cmd_egg (data=0x607900 <r>, input=0x26576f1 "s exit") at cmd_egg.c:73
#10 0x00007fb878572bcf in r_cmd_call (cmd=0x23daad0, input=0x26576f0 "gs exit") at cmd_api.c:182
#11 0x00007fb87854ef69 in r_core_cmd_subst_i (core=0x607900 <r>, cmd=0x26576f0 "gs exit", colon=0x0) at cmd.c:1589
#12 0x00007fb87854d2c7 in r_core_cmd_subst (core=0x607900 <r>, cmd=0x26576f0 "gs exit") at cmd.c:1080
#13 0x00007fb878550101 in r_core_cmd (core=0x607900 <r>, cstr=0x240ab10 "gs exit ", log=1) at cmd.c:1937
#14 0x00007fb878510088 in r_core_prompt_exec (r=0x607900 <r>) at core.c:1079
#15 0x000000000040514a in main (argc=2, argv=0x7ffdbdb02898, envp=0x7ffdbdb028b0) at radare2.c:783
```

**Comment by crowell** [comment]
96af02492adcae648d00def8a6bcc492c6a2c3f2 is the first bad commit

**Comment by crowell** [comment]
for some reason i don't believe this :-1:

**Comment by crowell** [comment]
yeah disregard what i have said, that was wrong

**Comment by alvarofe** [comment]
I will work on this issue :) thanks for report @zonkzonk
