### ISSUE TITLE
oc and sG segfault

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2753]
morn,

another path to a segfault from oc:

```
r2 -d /bin/ls
[0x00000000]> oc
chair-IT.txt
beer.sqlite
Missing argument
[0x00000000]> sg
[0x00000000]> sG
Segmentation fault
```

gdb:
```
,gdb -q r2 core.17704 
Reading symbols from r2...done.

warning: core file may not match specified executable file.
[New LWP 17704]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `r2 -d /bin/ls'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd4b535a267 in cmd_seek (data=0x607900 <r>, input=0x1b63f01 "G") at cmd_seek.c:262
262                             else r_core_seek (core, r_io_desc_size (core->io, core->file->desc), 1);
(gdb) bt
#0  0x00007fd4b535a267 in cmd_seek (data=0x607900 <r>, input=0x1b63f01 "G") at cmd_seek.c:262
#1  0x00007fd4b53968a5 in r_cmd_call (cmd=0x19fb060, input=0x1b63f00 "sG") at cmd_api.c:182
#2  0x00007fd4b5372fa2 in r_core_cmd_subst_i (core=0x607900 <r>, cmd=0x1b63f00 "sG", colon=0x0) at cmd.c:1590
#3  0x00007fd4b5371300 in r_core_cmd_subst (core=0x607900 <r>, cmd=0x1b63f00 "sG") at cmd.c:1081
#4  0x00007fd4b537413a in r_core_cmd (core=0x607900 <r>, cstr=0x1747010 "sG", log=1) at cmd.c:1938
#5  0x00007fd4b533370e in r_core_prompt_exec (r=0x607900 <r>) at core.c:1084
#6  0x000000000040514a in main (argc=3, argv=0x7ffe045f92f8, envp=0x7ffe045f9318) at radare2.c:783
(gdb) !r2 -v
radare2 0.10.0-git 8141 @ linux-little-x86-64 git.0.9.9-43-gb279f28
commit: b279f282bae6cfc6101c313efcbc2bea19bdaf8b build: 2015-06-14
```

Greetings
--zlul

**Comment by zonkzonk** [comment]
can't reproduce in 5858c2846b8662beb370db69aea6dfa2a13eb9d7

Thank you!
