### ISSUE TITLE
Out of bounds heap read in r_num_calc

### ISSUE THREAD

**Issue by hannob** [radare/radare2#2764]
This file will trigger an out of bounds read in radare2:
https://crashes.fuzzing-project.org/radare2-script-oob-heap-read-r_num_calc

It just contains the command "w0". Test: radare2 -q -i [script] /dev/null

Address Sanitizer trace:
```
==26019==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000168d3 at pc 0x7f9cc6706e0a bp 0x7fff99e9e190 sp 0x7fff99e9e180
READ of size 1 at 0x6020000168d3 thread T0
    #0 0x7f9cc6706e09 in r_num_calc /f/radare2/radare2/libr/util/calc.c:314
    #1 0x7f9cc665e200 in r_num_math /f/radare2/radare2/libr/util/num.c:244
    #2 0x7f9ccb90fd2c in cmd_write /f/radare2/radare2/libr/core/cmd_write.c:239
    #3 0x7f9ccb9870ee in r_core_cmd_subst_i /f/radare2/radare2/libr/core/cmd.c:1590
    #4 0x7f9ccb8eb0c8 in r_core_cmd_subst /f/radare2/radare2/libr/core/cmd.c:1081
    #5 0x7f9ccb8ec35b in r_core_cmd /f/radare2/radare2/libr/core/cmd.c:1938
    #6 0x7f9ccb8ef0bc in r_core_cmd_lines /f/radare2/radare2/libr/core/cmd.c:1989
    #7 0x7f9ccb8ef2f4 in r_core_cmd_file /f/radare2/radare2/libr/core/cmd.c:2001
    #8 0x7f9ccb8f255b in r_core_run_script /f/radare2/radare2/libr/core/cmd.c:373
    #9 0x4054c2 in main /f/radare2/radare2/binr/radare2/radare2.c:729
    #10 0x7f9cc5e6cf9f in __libc_start_main (/lib64/libc.so.6+0x1ff9f)
    #11 0x40a25e (/mnt/ram/radare2/radare2+0x40a25e)

0x6020000168d3 is located 0 bytes to the right of 3-byte region [0x6020000168d0,0x6020000168d3)
allocated by thread T0 here:
    #0 0x7f9ccc0106f7 in malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/libasan.so.1+0x576f7)
    #1 0x7f9cc5ece789 in strdup (/lib64/libc.so.6+0x81789)

SUMMARY: AddressSanitizer: heap-buffer-overflow /f/radare2/radare2/libr/util/calc.c:314 r_num_calc
Shadow bytes around the buggy address:
  0x0c047fffacc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffacd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047ffface0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffacf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffad00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fffad10: fa fa 01 fa fa fa 01 fa fa fa[03]fa fa fa 03 fa
  0x0c047fffad20: fa fa 03 fa fa fa fd fa fa fa fd fd fa fa 06 fa
  0x0c047fffad30: fa fa fd fa fa fa 05 fa fa fa fd fa fa fa 06 fa
  0x0c047fffad40: fa fa fd fa fa fa 03 fa fa fa fd fa fa fa 04 fa
  0x0c047fffad50: fa fa fd fa fa fa fd fa fa fa 04 fa fa fa fd fa
  0x0c047fffad60: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 01 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==26019==ABORTING

**Comment by hannob** [comment]
Seems unfixed to me, get the same address sanitizer error with latest git code.

**Comment by alvarofe** [comment]
Yeah I thought that the command was `w0` reading your comment but looking at the script file is `/V`. I will fix this tonight ;)

**Comment by hannob** [comment]
sorry, must've mixed the bugs after too many bug reports of this kind :-)
