### ISSUE TITLE
out of bounds heap read in core_anal_bytes

### ISSUE THREAD

**Issue by hannob** [radare/radare2#2851]
Sample script:
https://crashes.fuzzing-project.org/radare2-script-oob-heap-read-core_anal_bytes
Contains string "ao@!"

Address Sanitizer:
```
==6280==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000165d2 at pc 0x7f2a8406c6a9 bp 0x7fffbc919d60 sp 0x7fffbc919d50
READ of size 1 at 0x6020000165d2 thread T0
    #0 0x7f2a8406c6a8 in core_anal_bytes /f/radare2/radare2/libr/core/cmd_anal.c:260
    #1 0x7f2a8412e2a9 in cmd_anal_opcode /f/radare2/radare2/libr/core/cmd_anal.c:1794
    #2 0x7f2a8412e2a9 in cmd_anal /f/radare2/radare2/libr/core/cmd_anal.c:2516
    #3 0x7f2a8414c462 in r_core_cmd_subst_i /f/radare2/radare2/libr/core/cmd.c:1574
    #4 0x7f2a840ae499 in r_core_cmd_subst /f/radare2/radare2/libr/core/cmd.c:1081
    #5 0x7f2a840af633 in r_core_cmd /f/radare2/radare2/libr/core/cmd.c:1943
    #6 0x7f2a840b24ec in r_core_cmd_lines /f/radare2/radare2/libr/core/cmd.c:1994
    #7 0x7f2a840b26f4 in r_core_cmd_file /f/radare2/radare2/libr/core/cmd.c:2006
    #8 0x7f2a840b5496 in r_core_run_script /f/radare2/radare2/libr/core/cmd.c:373
    #9 0x4054e3 in main /f/radare2/radare2/binr/radare2/radare2.c:729
    #10 0x7f2a7e610f9f in __libc_start_main (/lib64/libc.so.6+0x1ff9f)
    #11 0x409fae (/mnt/ram/r2/radare2+0x409fae)

0x6020000165d2 is located 0 bytes to the right of 2-byte region [0x6020000165d0,0x6020000165d2)
allocated by thread T0 here:
    #0 0x7f2a847dd9d6 in __interceptor_realloc (/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/libasan.so.1+0x579d6)
    #1 0x7f2a840600b7 in r_core_block_size /f/radare2/radare2/libr/core/core.c:1117

SUMMARY: AddressSanitizer: heap-buffer-overflow /f/radare2/radare2/libr/core/cmd_anal.c:260 core_anal_bytes
Shadow bytes around the buggy address:
  0x0c047fffac60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffac70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffac80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffac90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffaca0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fffacb0: fa fa fa fa fa fa fa fa fa fa[02]fa fa fa 01 fa
  0x0c047fffacc0: fa fa 05 fa fa fa 05 fa fa fa 05 fa fa fa fd fd
  0x0c047fffacd0: fa fa fd fd fa fa fd fa fa fa fd fd fa fa 06 fa
  0x0c047ffface0: fa fa fd fa fa fa 05 fa fa fa fd fa fa fa 06 fa
  0x0c047fffacf0: fa fa fd fa fa fa 06 fa fa fa 03 fa fa fa fd fa
  0x0c047fffad00: fa fa 04 fa fa fa fd fa fa fa fd fa fa fa 04 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==6280==ABORTING

**Comment by alvarofe** [comment]
It's fixed in my latest PR. Will see if I don't break any test and wait for your confirmation to close it.
