### ISSUE TITLE
Out of bounds heap read in radare_compare

### ISSUE THREAD

**Issue by hannob** [radare/radare2#2854]
Script:
https://crashes.fuzzing-project.org/radare2-script-oob-heap-read-radare_compare

Contains these commands:
@i!
c 00

Address Sanitizer:
```
==6329==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000165d2 at pc 0x7fdd74acc969 bp 0x7fff77abd350 sp 0x7fff77abd340
READ of size 1 at 0x6020000165d2 thread T0
    #0 0x7fdd74acc968 in radare_compare /f/radare2/radare2/libr/core/cmd_cmp.c:179
    #1 0x7fdd74acc968 in cmd_cmp /f/radare2/radare2/libr/core/cmd_cmp.c:345
    #2 0x7fdd74b4ea0d in r_core_cmd_subst_i /f/radare2/radare2/libr/core/cmd.c:1595
    #3 0x7fdd74ab1499 in r_core_cmd_subst /f/radare2/radare2/libr/core/cmd.c:1081
    #4 0x7fdd74ab2633 in r_core_cmd /f/radare2/radare2/libr/core/cmd.c:1943
    #5 0x7fdd74ab54ec in r_core_cmd_lines /f/radare2/radare2/libr/core/cmd.c:1994
    #6 0x7fdd74ab56f4 in r_core_cmd_file /f/radare2/radare2/libr/core/cmd.c:2006
    #7 0x7fdd74ab8496 in r_core_run_script /f/radare2/radare2/libr/core/cmd.c:373
    #8 0x4054e3 in main /f/radare2/radare2/binr/radare2/radare2.c:729
    #9 0x7fdd6f013f9f in __libc_start_main (/lib64/libc.so.6+0x1ff9f)
    #10 0x409fae (/mnt/ram/r2/radare2+0x409fae)

0x6020000165d2 is located 0 bytes to the right of 2-byte region [0x6020000165d0,0x6020000165d2)
allocated by thread T0 here:
    #0 0x7fdd751e09d6 in __interceptor_realloc (/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/libasan.so.1+0x579d6)
    #1 0x7fdd74a630b7 in r_core_block_size /f/radare2/radare2/libr/core/core.c:1117

SUMMARY: AddressSanitizer: heap-buffer-overflow /f/radare2/radare2/libr/core/cmd_cmp.c:179 radare_compare
Shadow bytes around the buggy address:
  0x0c047fffac60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffac70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffac80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffac90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffaca0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fffacb0: fa fa 01 fa fa fa 05 fa fa fa[02]fa fa fa fd fa
  0x0c047fffacc0: fa fa fd fa fa fa 00 01 fa fa 00 01 fa fa fd fd
  0x0c047fffacd0: fa fa fd fd fa fa fd fa fa fa fd fd fa fa 06 fa
  0x0c047ffface0: fa fa fd fa fa fa 05 fa fa fa fd fa fa fa 06 fa
  0x0c047fffacf0: fa fa fd fa fa fa 06 fa fa fa 03 fa fa fa fd fa
  0x0c047fffad00: fa fa 04 fa fa fa fd fa fa fa fd fa fa fa 04 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==6329==ABORTING

**Comment by alvarofe** [comment]
Fixed in https://github.com/radare/radare2/pull/2856. Wait to be merged to test

**Comment by alvarofe** [comment]
I close this because I can't reproduce it. @hannob if you see that it's not fixed I will reopen it

**Comment by hannob** [comment]
Can confirm this is fixed in latest git code
