### ISSUE TITLE
lulzfuzz+asan  global-buffer-overflow on address 0x7f348c18f621 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2868]
morrn,

seems, I crashed it. :)

lulzfuzz can be found here:
https://github.com/radare/radare2-regressions/wiki/Crashing-r2-for-fun

```
==16096==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f348c18f621 at pc 0x7f348c0a28f9 bp 0x7ffea07fd620 sp 0x7ffea07fd610
READ of size 1 at 0x7f348c18f621 thread T0
    #0 0x7f348c0a28f8 in cmd_egg_option /home/zlul/src/radare2/libr/core/cmd_egg.c:4
    #1 0x7f348c0a3518 in cmd_egg /home/zlul/src/radare2/libr/core/cmd_egg.c:116
    #2 0x7f348c134156 in r_cmd_call /home/zlul/src/radare2/libr/core/cmd_api.c:185
    #3 0x7f348c0e3c2f in r_core_cmd_subst_i /home/zlul/src/radare2/libr/core/cmd.c:1599
    #4 0x7f348c0dfa5c in r_core_cmd_subst /home/zlul/src/radare2/libr/core/cmd.c:1084
    #5 0x7f348c0e64b5 in r_core_cmd /home/zlul/src/radare2/libr/core/cmd.c:1947
    #6 0x7f348c0540a8 in r_core_prompt_exec /home/zlul/src/radare2/libr/core/core.c:1086
    #7 0x4074f1 in main /home/zlul/src/radare2/binr/radare2/radare2.c:783
    #8 0x7f34873d478f in __libc_start_main (/usr/lib/libc.so.6+0x2078f)
    #9 0x403048 in _start (/usr/bin/radare2+0x403048)

0x7f348c18f621 is located 140048673 bytes inside of global variable '' defined in ':-2084569824:32564' (0x7f3483bffd00) of size 139863523264352
==16096==AddressSanitizer CHECK failed: /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/asan/asan_report.cc:263 "((res)) != (0)" (0x0, 0x0)
    #0 0x7f348c5249f1 in AsanCheckFailed /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/asan/asan_rtl.cc:68
    #1 0x7f348c5299a3 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/sanitizer_common/sanitizer_common.cc:72
    #2 0x7f348c52082c in GlobalFilename /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/asan/asan_report.cc:263
    #3 0x7f348c52082c in PrintGlobalLocation /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/asan/asan_report.cc:269
    #4 0x7f348c520ce5 in __asan::DescribeAddressRelativeToGlobal(unsigned long, unsigned long, __asan_global const&) /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/asan/asan_report.cc:298
    #5 0x7f348c4ace30 in DescribeOrGetInfoIfGlobal /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/asan/asan_globals.cc:101
    #6 0x7f348c522090 in __asan::DescribeAddress(unsigned long, unsigned long) /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/asan/asan_report.cc:553
    #7 0x7f348c5239e4 in __asan_report_error /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/asan/asan_report.cc:1009
    #8 0x7f348c524ed2 in __asan_report_load1 /build/gcc-multilib/src/gcc-5-20150623/libsanitizer/asan/asan_rtl.cc:372
    #9 0x7f348c0a28f8 in cmd_egg_option /home/zlul/src/radare2/libr/core/cmd_egg.c:4
    #10 0x7f348c0a3518 in cmd_egg /home/zlul/src/radare2/libr/core/cmd_egg.c:116
    #11 0x7f348c134156 in r_cmd_call /home/zlul/src/radare2/libr/core/cmd_api.c:185
    #12 0x7f348c0e3c2f in r_core_cmd_subst_i /home/zlul/src/radare2/libr/core/cmd.c:1599
    #13 0x7f348c0dfa5c in r_core_cmd_subst /home/zlul/src/radare2/libr/core/cmd.c:1084
    #14 0x7f348c0e64b5 in r_core_cmd /home/zlul/src/radare2/libr/core/cmd.c:1947
    #15 0x7f348c0540a8 in r_core_prompt_exec /home/zlul/src/radare2/libr/core/core.c:1086
    #16 0x4074f1 in main /home/zlul/src/radare2/binr/radare2/radare2.c:783
    #17 0x7f34873d478f in __libc_start_main (/usr/lib/libc.so.6+0x2078f)
    #18 0x403048 in _start (/usr/bin/radare2+0x403048)

|ERROR| Invalid command 'hra <80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80><80>' (0x68)
```

Greetings
--zlul

should I open issue at asan?

**Comment by alvarofe** [comment]
which was the command that crashed r2?

**Comment by alvarofe** [comment]
I found it

`gra ������������������������������������������`
