### ISSUE TITLE
heap-buffer-overflow on address 0x602000023478

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#2880]
hi,

```
$ r2 -P /home/se/bins/a.out.bak /bin/ls
 -- Too old to crash
=================================================================
==26402==ERROR: AddressSanitizer: heap-buffer-overflow on address 
0x602000023478 at pc 0x7f3322147466 bp 0x7ffed0d98af0 sp 0x7ffed0d98ae0
READ of size 1 at 0x602000023478 thread T0
    #0 0x7f3322147465 in r_core_patch /home/se/src/radare2/libr/core/patch.c:104
    #1 0x407398 in main /home/se/src/radare2/binr/radare2/radare2.c:759
    #2 0x7f331d3fa78f in __libc_start_main (/usr/lib/libc.so.6+0x2078f)
    #3 0x403048 in _start (/home/se/src/radare2/binr/radare2/radare2+0x403048)

ASAN:SIGSEGV
==26402==AddressSanitizer: while reporting a bug found another one. Ignoring.
```

b3589b4a0cd85c94637451f39c3a78be16a595cb

Kind Regards
Susan

**Comment by Susanne588586** [comment]
still in c3346328096fff80f064b970adece6874b452f89

**Comment by jvoisin** [comment]
Care to share the binary and you patch?

**Comment by hannob** [comment]
I can reproduce this issue and it happens with any patch/exec. I can take two zero-byte files and reproduce it:
touch a
touch b
./radare2 -P a b

Same error as original report.

**Comment by hannob** [comment]
In case you don't want to have the trouble recompiling radare2 with asan, valgrind also works:
valgrind radare2 -P a b

Error by valgrind:
```
==17459== Invalid read of size 1
==17459==    at 0x4EA713E: r_core_patch (in /usr/lib64/libr_core.so.0.9.9)
==17459==    by 0x403B05: main (in /usr/bin/radare2)
==17459==  Address 0xa629c51 is 0 bytes after a block of size 1 alloc'd
==17459==    at 0x4C29F80: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==17459==    by 0x8828679: strdup (in /lib64/libc-2.20.so)
==17459==    by 0x4EA6F8E: r_core_patch (in /usr/lib64/libr_core.so.0.9.9)
==17459==    by 0x403B05: main (in /usr/bin/radare2)
