### ISSUE TITLE
pD segfault

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#2886]
```
[0x08048490]> pD 52428800
Segmentation fault (core dumped)
...
Cannot access memory at address 0xb77528f7

r2 -v
radare2 0.10.0-git 8318 @ linux-little-x86-32 git.0.9.9-219-g1f2a63d
commit: 1f2a63ddb54ac9a15cbe3bfec7c7f7078807ccc0 build: 2015-07-04
```

**Comment by radare** [comment]
Can you try again with latest git or provide a backtrace?

**Comment by VisualPrankDude** [comment]
trying with latest git, however it takes some time, and I cannot provide a backtrace. maybe valgrind.

**Comment by VisualPrankDude** [comment]
```
gdb -q r2 core
Reading symbols from /usr/bin/r2...done.
BFD: Warning: /home/sk/core is truncated: expected core file size >= 1730945024, found: 1024000000.
[New LWP 4136]
Cannot access memory at address 0xb77a78f8
Cannot access memory at address 0xb77a78f4
(gdb) bt
#0  0xb66cf3f4 in ?? ()
Cannot access memory at address 0xbfa8002c
(gdb) i s
#0  0xb66cf3f4 in ?? ()
Cannot access memory at address 0xbfa8002c
(gdb) i f
Stack level 0, frame at 0xbfa80030:
 eip = 0xb66cf3f4; saved eip Cannot access memory at address 0xbfa8002c
(gdb) i r
eax            0xb	11
ecx            0xb0117ff5	-1341030411
edx            0x20	32
ebx            0xb67c0ff4	-1233383436
esp            0xbfa8002c	0xbfa8002c
ebp            0xbfa80054	0xbfa80054
esi            0xbfa80788	-1079507064
edi            0xbfa8064c	-1079507380
eip            0xb66cf3f4	0xb66cf3f4
eflags         0x210297	[ CF PF AF SF IF RF ID ]
cs             0x73	115
ss             0x7b	123
ds             0x7b	123
es             0x7b	123
fs             0x0	0
gs             0x33	51
```

**Comment by radare** [comment]
So its an stack exhaustion?

**Comment by VisualPrankDude** [comment]
no OOM. It takes some time to fault.
