### ISSUE TITLE
oc input issue

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#3026]
Hi,

probably related to #2282

```
$ r2 /bin/ls
[0x0804c1b4]> oc /dev/zero
[0x00000000]> pdr
Cannot find function at 0x00000000
[0x00000000]> oc /dev/zero
Segmentation fault (core dumped)
```

```
(gdb) bt
#0  0x00000010 in ?? ()
#1  0xb7552074 in r_bin_object_new (binfile=0x8bee220, plugin=0x88fd6b0,
    baseaddr=0, loadaddr=0, offset=0, sz=0) at bin.c:948
#2  0xb75527b9 in r_bin_file_new_from_bytes (bin=0x8c30120,
    file=0x8becd60 "/dev/zero", bytes=0x0, sz=18446744073709551615,
    file_sz=18446744073709551615, rawstr=0, baseaddr=0, loadaddr=0, fd=8,
    pluginname=0x0, xtrname=0x0, offset=0) at bin.c:1079
#3  0xb7551360 in r_bin_load_io_at_offset_as_sz (bin=0x8c30120,
    desc=0x8becd98, baseaddr=0, loadaddr=0, xtr_idx=0, offset=0, name=0x0,
    sz=18446744073709551615) at bin.c:667
#4  0xb7551462 in r_bin_load_io_at_offset_as (bin=0x8c30120, desc=0x8becd98,
    baseaddr=0, loadaddr=0, xtr_idx=0, offset=0, name=0x0) at bin.c:689
#5  0xb7550d88 in r_bin_load_io (bin=0x8c30120, desc=0x8becd98, baseaddr=0,
    loadaddr=0, xtr_idx=0) at bin.c:569
#6  0xb76c4880 in r_core_file_do_load_for_io_plugin (r=0x804f740, baseaddr=0,
    loadaddr=0) at file.c:352
#7  0xb76c4c9d in r_core_bin_load (r=0x804f740,
    filenameuri=0x8becd60 "/dev/zero", baddr=0) at file.c:489
#8  0xb76a041f in cmd_open (data=0x804f740, input=0x8c03fe1 "c /dev/zero")
    at cmd_open.c:394
#9  0xb76ec4b2 in r_cmd_call (cmd=0x8bc2840, input=0x8c03fe0 "oc /dev/zero")
    at cmd_api.c:185
#10 0xb76c17d6 in r_core_cmd_subst_i (core=0x804f740,
---Type <return> to continue, or q <return> to quit---
    cmd=0x8c03fe0 "oc /dev/zero", colon=0x0) at cmd.c:1655
#11 0xb76bfd3c in r_core_cmd_subst (core=0x804f740,
    cmd=0x8c03fe0 "oc /dev/zero") at cmd.c:1128
#12 0xb76c2884 in r_core_cmd (core=0x804f740,
    cstr=0x8c03fc8 "\217", <incomplete sequence \356\266>, log=1) at cmd.c:2010
#13 0xb767e1b1 in r_core_prompt_exec (r=0x804f740) at core.c:1105
#14 0x0804ccc4 in main (argc=2, argv=0xbf99d964, envp=0xbf99d970)
    at radare2.c:791
```

**Comment by alvarofe** [comment]
I can't reproduce it. What system are you using and what version of r2 ?

**Comment by VisualPrankDude** [comment]
radare2 version is 19bcaffabbca07f999b7d1757c632e113b40dd3b
System is Debian.

**Comment by ret2libc** [comment]
I was able to reproduce it, but it doesn't alway occur. And the segfault doesn't come every time from the same line. I think there's something that is freed and reused...

**Comment by alvarofe** [comment]
In debian i am able to reproduce it. I will look at it then
