### ISSUE TITLE
build with --coverage segfaults on gcov_exit

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3189]
```
<crowell> (gdb) p $r10
<crowell> $1 = 0
<crowell> (gdb) x/i $pc
<crowell> => 0x7ffff2886720 <gcov_exit.part.5+208>:       mov    rdi,QWORD PTR [r10]
```

not sure if this is something we can fix or if it is a bug in gcov, but opening this to track.

**Comment by alvarofe** [comment]
```
[0x100001058]> q
ASAN:DEADLYSIGNAL
=================================================================
==11481==ERROR: AddressSanitizer: SEGV on unknown address 0x0001077c1370 (pc 0x0001077c1370 bp 0x7fff5df3f1e0 sp 0x7fff5df3f1c8 T0)
    #0 0x1077c136f  (/usr/local/lib/radare2/0.10.0-git//asm_ebc.dylib+0xd36f)
    #1 0x7fff8be3171a in __cxa_finalize_ranges (/usr/lib/system/libsystem_c.dylib+0x5e71a)
    #2 0x7fff8be31a2f in exit (/usr/lib/system/libsystem_c.dylib+0x5ea2f)
    #3 0x7fff973585cf in start (/usr/lib/system/libdyld.dylib+0x35cf)
    #4 0x1  (<unknown module>)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/local/lib/radare2/0.10.0-git//asm_ebc.dylib+0xd36f)
```

**Comment by alvarofe** [comment]
```
[0x100001058]> q
==22054== Invalid write of size 8
==22054==    at 0x10287006E: decode_movi (in /usr/local/lib/radare2/0.10.0-git/asm_ebc.dylib)
==22054==    by 0x101D0F71A: __cxa_finalize_ranges (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101D0FA2F: exit (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101C5D5CF: start (in /usr/lib/system/libdyld.dylib)
==22054==    by 0x1: ???
==22054==    by 0x104872402: ???
==22054==    by 0x104872405: ???
==22054==  Address 0x104872090 is on thread 1's stack
==22054==  264 bytes below stack pointer
==22054==
==22054== Invalid read of size 8
==22054==    at 0x102870078: decode_movi (in /usr/local/lib/radare2/0.10.0-git/asm_ebc.dylib)
==22054==    by 0x101D0F71A: __cxa_finalize_ranges (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101D0FA2F: exit (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101C5D5CF: start (in /usr/lib/system/libdyld.dylib)
==22054==    by 0x1: ???
==22054==    by 0x104872402: ???
==22054==    by 0x104872405: ???
==22054==  Address 0x104872090 is on thread 1's stack
==22054==  264 bytes below stack pointer
==22054==
==22054== Invalid write of size 8
==22054==    at 0x10287007F: decode_movi (in /usr/local/lib/radare2/0.10.0-git/asm_ebc.dylib)
==22054==    by 0x101D0F71A: __cxa_finalize_ranges (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101D0FA2F: exit (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101C5D5CF: start (in /usr/lib/system/libdyld.dylib)
==22054==    by 0x1: ???
==22054==    by 0x104872402: ???
==22054==    by 0x104872405: ???
==22054==  Address 0x104872088 is on thread 1's stack
==22054==  272 bytes below stack pointer
==22054==
==22054== Invalid read of size 8
==22054==    at 0x102870089: decode_movi (in /usr/local/lib/radare2/0.10.0-git/asm_ebc.dylib)
==22054==    by 0x101D0F71A: __cxa_finalize_ranges (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101D0FA2F: exit (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101C5D5CF: start (in /usr/lib/system/libdyld.dylib)
==22054==    by 0x1: ???
==22054==    by 0x104872402: ???
==22054==    by 0x104872405: ???
==22054==  Address 0x104872088 is on thread 1's stack
==22054==  272 bytes below stack pointer
==22054==
==22054== Invalid write of size 4
==22054==    at 0x102870099: decode_movi (in /usr/local/lib/radare2/0.10.0-git/asm_ebc.dylib)
==22054==    by 0x101D0F71A: __cxa_finalize_ranges (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101D0FA2F: exit (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101C5D5CF: start (in /usr/lib/system/libdyld.dylib)
==22054==    by 0x1: ???
==22054==    by 0x104872402: ???
==22054==    by 0x104872405: ???
==22054==  Address 0x104872084 is on thread 1's stack
==22054==  276 bytes below stack pointer
==22054==
==22054==
==22054== Process terminating with default action of signal 11 (SIGSEGV)
==22054==  General Protection Fault
==22054==    at 0x101D03DB5: _vsnprintf (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101D04069: vsnprintf (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101D3509C: __snprintf_chk (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x1028700A5: decode_movi (in /usr/local/lib/radare2/0.10.0-git/asm_ebc.dylib)
==22054==    by 0x101D0F71A: __cxa_finalize_ranges (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101D0FA2F: exit (in /usr/lib/system/libsystem_c.dylib)
==22054==    by 0x101C5D5CF: start (in /usr/lib/system/libdyld.dylib)
==22054==    by 0x1: ???
==22054==    by 0x104872402: ???
==22054==    by 0x104872405: ???
==22054==
==22054== HEAP SUMMARY:
==22054==     in use at exit: 184,846 bytes in 3,768 blocks
==22054==   total heap usage: 27,603 allocs, 23,835 frees, 7,536,434 bytes allocated
==22054==
==22054== LEAK SUMMARY:
==22054==    definitely lost: 55,022 bytes in 544 blocks
==22054==    indirectly lost: 47,772 bytes in 2,583 blocks
==22054==      possibly lost: 0 bytes in 0 blocks
==22054==    still reachable: 46,544 bytes in 222 blocks
==22054==         suppressed: 35,508 bytes in 419 blocks
==22054== Rerun with --leak-check=full to see details of leaked memory
==22054==
==22054== For counts of detected and suppressed errors, rerun with: -v
==22054== Use --track-origins=yes to see where uninitialised values come from
==22054== ERROR SUMMARY: 20 errors from 9 contexts (suppressed: 0 from 0)
```

**Comment by alvarofe** [comment]
I get this on linux

```
[0x00005c20]> q
vex amd64->IR: unhandled instruction bytes: 0xFF 0xBF 0x1F 0x0 0x0 0x0 0x89 0xFE
vex amd64->IR:   REX=0 REX.W=0 REX.R=0 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=NONE
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=0
==37945== valgrind: Unrecognised instruction at address 0xad4d300.
==37945==    at 0xAD4D300: decode_ext_cmd (propeller_disas.c:136)
==37945==    by 0x90AFAD3: llvm_writeout_files (in /usr/local/lib/libr_hash.so.0.10.0-git)
==37945==    by 0xA0C02AE: __cxa_finalize (cxa_finalize.c:56)
==37945==    by 0x909D912: ??? (in /usr/local/lib/libr_hash.so.0.10.0-git)
==37945==    by 0x400F846: _dl_fini (dl-fini.c:252)
==37945==    by 0xA0BFF11: __run_exit_handlers (exit.c:82)
==37945==    by 0xA0BFF64: exit (exit.c:104)
==37945==    by 0xA0AA686: (below main) (libc-start.c:323)
==37945== Your program just tried to execute an instruction that Valgrind
==37945== did not recognise.  There are two possible reasons for this.
==37945== 1. Your program has a bug and erroneously jumped to a non-code
==37945==    location.  If you are running Memcheck and you just saw a
==37945==    warning about a bad jump, it's probably your program's fault.
==37945== 2. The instruction is legitimate but Valgrind doesn't handle it,
==37945==    i.e. it's Valgrind's fault.  If you think this is the case or
==37945==    you are not sure, please let us know and we'll try to fix it.
==37945== Either way, Valgrind will now raise a SIGILL signal which will
==37945== probably kill your program.
==37945==
==37945== Process terminating with default action of signal 4 (SIGILL)
==37945==  Illegal opcode at address 0xAD4D300
==37945==    at 0xAD4D300: decode_ext_cmd (propeller_disas.c:136)
==37945==    by 0x90AFAD3: llvm_writeout_files (in /usr/local/lib/libr_hash.so.0.10.0-git)
==37945==    by 0xA0C02AE: __cxa_finalize (cxa_finalize.c:56)
==37945==    by 0x909D912: ??? (in /usr/local/lib/libr_hash.so.0.10.0-git)
==37945==    by 0x400F846: _dl_fini (dl-fini.c:252)
==37945==    by 0xA0BFF11: __run_exit_handlers (exit.c:82)
==37945==    by 0xA0BFF64: exit (exit.c:104)
==37945==    by 0xA0AA686: (below main) (libc-start.c:323)
```

**Comment by alvarofe** [comment]
Adding a simple printf to debug change the error from an invalid instruction to bad access.
```
==39975== Process terminating with default action of signal 11 (SIGSEGV)
==39975==  Access not within mapped region at address 0xFFFFFFFFFFFFFF8B
==39975==    at 0xAD4D300: decode_ext_cmd (propeller_disas.c:133)
==39975==    by 0x90AFAD3: llvm_writeout_files (in /usr/local/lib/libr_hash.so.0.10.0-git)
==39975==    by 0xA0C02AE: __cxa_finalize (cxa_finalize.c:56)
==39975==    by 0x909D912: ??? (in /usr/local/lib/libr_hash.so.0.10.0-git)
==39975==    by 0x400F846: _dl_fini (dl-fini.c:252)
==39975==    by 0xA0BFF11: __run_exit_handlers (exit.c:82)
==39975==    by 0xA0BFF64: exit (exit.c:104)
==39975==    by 0xA0AA686: (below main) (libc-start.c:323)
==39975==  If you believe this happened as a result of a stack
==39975==  overflow in your program's main thread (unlikely but
==39975==  possible), you can try to increase the size of the
==39975==  main thread stack using the --main-stacksize= flag.
==39975==  The main thread stack size used in this run was 8388608.
````

Testing with gcc

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff28f3520 in gcov_exit.part () from /usr/local/lib/radare2/0.10.0-git//bin_dex.so
(gdb) bt
#0  0x00007ffff28f3520 in gcov_exit.part () from /usr/local/lib/radare2/0.10.0-git//bin_dex.so
#1  0x00007ffff304b2af in __cxa_finalize (d=0x7ffff2af6480) at cxa_finalize.c:56
#2  0x00007ffff28ee423 in __do_global_dtors_aux () from /usr/local/lib/radare2/0.10.0-git//bin_dex.so
#3  0x00007fffffffd740 in ?? ()
#4  0x00007ffff7def327 in _dl_close_worker (map=<optimized out>, force=<optimized out>) at dl-close.c:285
Backtrace stopped: frame did not save the PC
```
I would say that is not our problem.

**Comment by radare** [comment]
can we close this?

**Comment by Maijin** [comment]
Something should be done to have coverage of the test if this is not solution then yes it should be closed
