### ISSUE TITLE
"afv-*" and "afv- *" segfaults

### ISSUE THREAD

**Issue by DaniloNC** [radare/radare2#3410]
$ r2 /bin/ls
 -- Check your IO plugins with 'r2 -L'
[0x004048c5]> aaa
[0x004048c5]> afv-*
Segmentation fault

vagrant@kali-mini:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux 2.0
Release:	2.0
Codename:	sana

 r2 -v
WARNING: r2 library versions mismatch! See r2 -V
radare2 0.10.0-git 9165 @ linux-little-x86-64 git.0.9.9-1059-g9b7d06a
commit: 9b7d06aa9955f4506045d265fde2a2b804686cb3 build: 2015-10-03

uname -a
Linux kali-mini 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux

**Comment by Maijin** [comment]
I can reproduce linux x86_64

```
[0x004048c5]> afv-*

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff662aaf6 in r_anal_var_delete (a=0x5555557e01b0, addr=4212933, 
    kind=118 'v', scope=1, delta=0) at var.c:80
80			char *name_key = sdb_fmt (3, "var.0x%"PFMT64x".%c.%d.%s", addr, kind, scope, av->name);
(gdb) bt
#0  0x00007ffff662aaf6 in r_anal_var_delete (a=0x5555557e01b0, addr=4212933, 
    kind=118 'v', scope=1, delta=0) at var.c:80
#1  0x00007ffff7b0de75 in var_cmd (core=0x55555575c640 <r>, 
    str=0x555555c1ad10 "v-*") at cmd_anal.c:97
#2  0x00007ffff7b10970 in cmd_anal_fcn (core=0x55555575c640 <r>, 
    input=0x5555557be011 "fv-*") at cmd_anal.c:691
#3  0x00007ffff7b195a3 in cmd_anal (data=0x55555575c640 <r>, 
    input=0x5555557be011 "fv-*") at cmd_anal.c:3051
#4  0x00007ffff7b6d7b2 in r_cmd_call (cmd=0x5555558162d0, 
    input=0x5555557be010 "afv-*") at cmd_api.c:210
#5  0x00007ffff7b400e1 in r_core_cmd_subst_i (core=0x55555575c640 <r>, 
---Type <return> to continue, or q <return> to quit---
    cmd=0x5555557be010 "afv-*", colon=0x0) at cmd.c:1693
#6  0x00007ffff7b3df89 in r_core_cmd_subst (core=0x55555575c640 <r>, 
    cmd=0x5555557be010 "afv-*") at cmd.c:1158
#7  0x00007ffff7b415d3 in r_core_cmd (core=0x55555575c640 <r>, 
    cstr=0x555555843770 "afv-*", log=1) at cmd.c:2068
#8  0x00007ffff7af40b5 in r_core_prompt_exec (r=0x55555575c640 <r>)
    at core.c:1197
#9  0x00005555555598a6 in main (argc=2, argv=0x7fffffffe348, 
    envp=0x7fffffffe360) at radare2.c:788
(gdb) 
```
