### ISSUE TITLE
fs a<tab> segfault

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3527]
fs a<tab> segfault after opening a binary 

```
[0x00000000]> fs a
Program received signal SIGSEGV, Segmentation fault.
__strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:1739
1739	../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.
(gdb) bt
#0  __strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:1739
#1  0x00007ffff7aea6ea in autocomplete (line=0x7ffff7663200 <r_line_instance>) at core.c:606
#2  0x00007ffff7457705 in r_line_autocomplete () at dietline.c:335
#3  0x00007ffff7458c38 in r_line_readline_cb (cb=0x0, user=0x0) at dietline.c:1224
#4  0x00007ffff7457b42 in r_line_readline () at dietline.c:410
#5  0x00007ffff7aeb2c8 in r_core_fgets (buf=0x7fffffffcb40 "", len=4096) at core.c:718
#6  0x00007ffff745aac1 in r_cons_fgets (buf=0x7fffffffcb40 "", len=4096, argc=0, argv=0x0) at input.c:224
#7  0x00007ffff7aed9c4 in r_core_prompt (r=0x55555575c640 <r>, sync=0) at core.c:1359
#8  0x000055555555986d in main (argc=2, argv=0x7fffffffe320, envp=0x7fffffffe330) at radare2.c:781
(gdb) 
```

**Comment by condret** [comment]
o_O

**Comment by Maijin** [comment]
Open a binary not malloc

**Comment by alvarofe** [comment]
confirmed
