### ISSUE TITLE
`afvn` segfaults

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#3723]
```
jvoisin@kaa 11:18 ~ r2 =ls
Error: provided size must be size > 0
Error: provided size must be size > 0
 -- Use scr.accel to browse the file faster!
[0x00404870]> afvn pif paf
zsh: segmentation fault (core dumped)  r2 =ls
jvoisin@kaa 11:18 ~ 
```

```
gdb-peda$ bt
#0  0x00007ffff7b055f5 in var_cmd (core=0x55555575c5c0 <r>, str=0x55555594a1d3 "pif") at cmd_anal.c:115
#1  0x00007ffff7b083f9 in cmd_anal_fcn (core=0x55555575c5c0 <r>, input=0x55555591b611 "fvn pif paf") at cmd_anal.c:740
#2  0x00007ffff7b113d6 in cmd_anal (data=0x55555575c5c0 <r>, input=0x55555591b611 "fvn pif paf") at cmd_anal.c:3142
#3  0x00007ffff7b69f53 in r_cmd_call (cmd=0x555555816640, input=0x55555591b610 "afvn pif paf") at cmd_api.c:210
#4  0x00007ffff7b393c0 in r_core_cmd_subst_i (core=0x55555575c5c0 <r>, cmd=0x55555591b610 "afvn pif paf", colon=0x0) at cmd.c:1702
#5  0x00007ffff7b37216 in r_core_cmd_subst (core=0x55555575c5c0 <r>, cmd=0x55555591b610 "afvn pif paf") at cmd.c:1164
#6  0x00007ffff7b3aac2 in r_core_cmd (core=0x55555575c5c0 <r>, cstr=0x55555584bbe0 "afvn pif paf", log=0x1) at cmd.c:2111
#7  0x00007ffff7ae9989 in r_core_prompt_exec (r=0x55555575c5c0 <r>) at core.c:1442
#8  0x00005555555599a1 in main (argc=0x2, argv=0x7fffffffe1d8, envp=0x7fffffffe1f0) at radare2.c:795
#9  0x00007ffff3c00a40 in __libc_start_main (main=0x555555557845 <main>, argc=0x2, argv=0x7fffffffe1d8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe1c8) at libc-start.c:289
#10 0x00005555555570f9 in _start ()
gdb-peda$ 
```

**Comment by crowell** [comment]
cant repro, 

i get 

```
Cannot find function here
```

**Comment by alvarofe** [comment]
git pull?

**Comment by Maijin** [comment]
@jvoisin can't reproduce ;)

**Comment by radare** [comment]
If u type bt you can also show the offending instruction, the value of the registers, the affected line of code in r2 codebase and the values of the variables that affect this line.

And you will sudddenly discover that if you do all the previous steps the fix will become obvious and you can directly commit the fix instead of opening an issue ;-)

**Comment by radare** [comment]
no one cant reproduce
