### ISSUE TITLE
Zignature bugs/suggestions

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3800]
- [ ] Bug when using "." (invalid offset detected)
- [ ] "."  is replaced by 0

```
zn bios
zb PCI_WriteWord_SSE 668be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904660fc5e400660f73dc02ffe4
zb PCI_WriteWord_SSE_gen ..8be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904660fc5e400660f73dc02ffe4
zb PCI_WriteWord_SSE_gen2  .8be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904660fc5e400660f73dc02ffe4 # This rule replaced "." by "0" (bug)
zn-
.z/ section..text section..text+1074039
? sign.bios.b.PCI_WriteWord_SSE
#7000:0344  correct
? sign.bios.b.PCI_WriteWord_SSE_gen
#10000:0376 incorrect
```
- [ ] Bug: In previous example, the flirt counter detection still display 1 but actually found 2
- [ ] Bug: bitmask doesn't work `zb blabla 992233 ff00ff`
- [x] Lenght of name is very short 26
- [ ] Add Help/documentation on head signatures
- [ ] Add Help/documentation on func signatures
- [ ] Add a warning when the name is too long
- [x] Add a warning when dup zignatures: same bytes but != name #5685
- [ ] Add help about "." in the rules because it's different from flirt
- [ ] parser should warn about invalid char such as `?` in the signature
- [ ] z/ doesn't restores flag name #728

All those fix should also be joined with tests

**Comment by radare** [comment]
The name and namespace fields are now char*, please confirm that the 26 char limit is no longer an issue

**Comment by Maijin** [comment]
@radare worse, it segfaults now:

# GDB

```
[0x00000000]> zb AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaPCI_WriteWord_SSE 668be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904660fc5e400660f73dc02ffe4

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6500cf8 in r_sign_add (sig=0x55555580d730, anal=0x5555557dfa50, type=98, 
    name=0x555555853d73 'A' <repeats 90 times>, "aPCI_WriteWord_SSE", 
    arg=0x555555853de0 "668be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904"...) at sign.c:40
40		si->name = r_str_newf ("%s.%c.%s", *sig->ns? sig->ns: "sys", type, name);
(gdb) bt
#0  0x00007ffff6500cf8 in r_sign_add (sig=0x55555580d730, anal=0x5555557dfa50, type=98, 
    name=0x555555853d73 'A' <repeats 90 times>, "aPCI_WriteWord_SSE", 
    arg=0x555555853de0 "668be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904"...) at sign.c:40
#1  0x00007ffff7af6256 in cmd_zign (data=0x55555575c5c0 <r>, 
    input=0x555555853d71 "b ", 'A' <repeats 90 times>, "aPCI_WriteWord_SSE") at cmd_zign.c:93
#2  0x00007ffff7b6882d in r_cmd_call (cmd=0x555555815860, 
    input=0x555555853d70 "zb ", 'A' <repeats 90 times>, "aPCI_WriteWord_SSE") at cmd_api.c:210
#3  0x00007ffff7b3721f in r_core_cmd_subst_i (core=0x55555575c5c0 <r>, 
    cmd=0x555555853d70 "zb ", 'A' <repeats 90 times>, "aPCI_WriteWord_SSE", colon=0x0) at cmd.c:1702
#4  0x00007ffff7b35075 in r_core_cmd_subst (core=0x55555575c5c0 <r>, 
    cmd=0x555555853d70 "zb ", 'A' <repeats 90 times>, "aPCI_WriteWord_SSE") at cmd.c:1164
#5  0x00007ffff7b38921 in r_core_cmd (core=0x55555575c5c0 <r>, 
    cstr=0x555555853950 "zb ", 'A' <repeats 90 times>, "aPCI_WriteWord_SSE 668be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400"..., log=1) at cmd.c:2111
#6  0x00007ffff7ae60ea in r_core_prompt_exec (r=0x55555575c5c0 <r>) at core.c:1464
#7  0x0000555555559a30 in main (argc=2, argv=0x7fffffffe3f0, envp=0x7fffffffe400) at radare2.c:818
(gdb) 
```

# ASAN

```

[0x00000000]> zb AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaPCI_WriteWord_SSE 668be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904660fc5e400660f73dc02ffe4
ASAN:SIGSEGV
=================================================================
==27134==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f4379680509 bp 0x7ffd6b14c7b0 sp 0x7ffd6b14c760 T0)
    #0 0x7f4379680508 in r_sign_add /home/maijin/Projects/radare2/libr/anal/sign.c:40
    #1 0x7f437b2959ed in cmd_zign /home/maijin/Projects/radare2/libr/core/cmd_zign.c:93
    #2 0x7f437b38262b in r_cmd_call /home/maijin/Projects/radare2/libr/core/cmd_api.c:210
    #3 0x7f437b3193de in r_core_cmd_subst_i /home/maijin/Projects/radare2/libr/core/cmd.c:1702
    #4 0x7f437b314f7e in r_core_cmd_subst /home/maijin/Projects/radare2/libr/core/cmd.c:1164
    #5 0x7f437b31c5da in r_core_cmd /home/maijin/Projects/radare2/libr/core/cmd.c:2111
    #6 0x7f437b273423 in r_core_prompt_exec /home/maijin/Projects/radare2/libr/core/core.c:1464
    #7 0x56538a0e9ece in main /home/maijin/Projects/radare2/binr/radare2/radare2.c:818
    #8 0x7f4376168a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #9 0x56538a0e5938 in _start (/home/maijin/Projects/radare2/binr/radare2/radare2+0x5938)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/maijin/Projects/radare2/libr/anal/sign.c:40 r_sign_add
==27134==ABORTING



```

**Comment by radare** [comment]
Fixed taht crash. it was a stupid null deref

**Comment by XVilka** [comment]
Please add tests.

**Comment by XVilka** [comment]
- [ ] zF command - FLIRT - add 'scan' command, like in Yara
 - [ ] zF - do not scan by default
 - [ ] zF - show the status of FLIRT signatures in 'z' commands
 - [ ] zb - arguments support + documentation in a book
 - [ ] z/ - search in '[0 ; $s]' range by default

**Comment by radare** [comment]
Do we want to add more features to flirt when it doesnt works with latest signatures? Imho we should go for our own format and not depend on ida's work

**Comment by XVilka** [comment]
@radare imho, FLIRT loading support is very important. And those mostly about user experience/refactoring, figured those after a speaking with @pinkflawd

**Comment by pinkflawd** [comment]
I'd guess sticking to FLIRT format doesn't scale in the long run, enhancing the radare zignatures could, but also I'm quite unaware how much effort that'd require to make them feasible.

**Comment by Maijin** [comment]
Well beginning shipping default one in core repo or via r2pm would at least begin progress for people to contribute to it :P

**Comment by Maijin** [comment]
See 6947

**Comment by radare** [comment]
cc @jroimartin

**Comment by Maijin** [comment]
Closed
