### ISSUE TITLE
ELF oa => double free or corruption

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3858]
Just `oa` and quit
* http://radare.tv/a/126

# GDB

```
[0x00404870]> oa

*** Error in `/usr/bin/r2': double free or corruption (!prev): 0x00005555559af5d0 ***

Program received signal SIGABRT, Aborted.
0x00007ffff3bf7267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff3bf7267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff3bf8eca in __GI_abort () at abort.c:89
#2  0x00007ffff3c3ac53 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff3d531a8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff3c42c69 in malloc_printerr (ptr=<optimized out>, 
    str=0x7ffff3d532d8 "double free or corruption (!prev)", action=1) at malloc.c:4965
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3834
#5  0x00007ffff3c4689c in __GI___libc_free (mem=<optimized out>) at malloc.c:2950
#6  0x00007ffff6f9cdfb in Elf64_r_bin_elf_free (bin=0x555555950670)
    at /home/maijin/Projects/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1697
#7  0x00007ffff6f92a9a in destroy (arch=0x555555950440)
    at /home/maijin/Projects/radare2/libr/..//libr/bin/p/bin_elf.c:59
#8  0x00007ffff6f6bb2d in r_bin_file_free (bf_=0x555555950440) at bin.c:808
#9  0x00007ffff43c1b7c in r_list_delete (list=0x5555557fffe0, iter=0x5555559504f0) at list.c:99
#10 0x00007ffff43c1a4f in r_list_purge (list=0x5555557fffe0) at list.c:68
#11 0x00007ffff43c1a9b in r_list_free (list=0x5555557fffe0) at list.c:78
#12 0x00007ffff6f6cd23 in r_bin_free (bin=0x5555557ffd70) at bin.c:1165
#13 0x00007ffff7ae65d0 in r_core_fini (c=0x55555575c5c0 <r>) at core.c:1281
#14 0x0000555555559cda in main (argc=2, argv=0x7fffffffe3e8, envp=0x7fffffffe400) at radare2.c:874
(gdb) 
```

# ASAN 

```
r2 /bin/ls   
 -- EIP = 0x41414141
[0x00404870]> oa
^D
=================================================================
==11506==ERROR: AddressSanitizer: attempting double-free on 0x625000028100 in thread T0:
    #0 0x7f208a7e86aa in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x986aa)
    #1 0x7f208956175f in Elf64_r_bin_elf_free /home/maijin/Projects/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1697
    #2 0x7f208954a553 in destroy /home/maijin/Projects/radare2/libr/..//libr/bin/p/bin_elf.c:59
    #3 0x7f20894ed9b9 in r_bin_file_free /home/maijin/Projects/radare2/libr/bin/bin.c:808
    #4 0x7f20859d850e in r_list_delete /home/maijin/Projects/radare2/libr/util/list.c:99
    #5 0x7f20859d82de in r_list_purge /home/maijin/Projects/radare2/libr/util/list.c:68
    #6 0x7f20859d8370 in r_list_free /home/maijin/Projects/radare2/libr/util/list.c:78
    #7 0x7f20894effa3 in r_bin_free /home/maijin/Projects/radare2/libr/bin/bin.c:1165
    #8 0x7f208a2be517 in r_core_fini /home/maijin/Projects/radare2/libr/core/core.c:1281
    #9 0x55797cf47219 in main /home/maijin/Projects/radare2/binr/radare2/radare2.c:874
    #10 0x7f20851b8a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #11 0x55797cf42938 in _start (/home/maijin/Projects/radare2/binr/radare2/radare2+0x5938)

0x625000028100 is located 0 bytes inside of 8584-byte region [0x625000028100,0x62500002a288)
freed by thread T0 here:
    #0 0x7f208a7e86aa in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x986aa)
    #1 0x7f208956175f in Elf64_r_bin_elf_free /home/maijin/Projects/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1697
    #2 0x7f208954a553 in destroy /home/maijin/Projects/radare2/libr/..//libr/bin/p/bin_elf.c:59
    #3 0x7f20894ed9b9 in r_bin_file_free /home/maijin/Projects/radare2/libr/bin/bin.c:808
    #4 0x7f20859d850e in r_list_delete /home/maijin/Projects/radare2/libr/util/list.c:99
    #5 0x7f20859d82de in r_list_purge /home/maijin/Projects/radare2/libr/util/list.c:68
    #6 0x7f20859d8370 in r_list_free /home/maijin/Projects/radare2/libr/util/list.c:78
    #7 0x7f20894effa3 in r_bin_free /home/maijin/Projects/radare2/libr/bin/bin.c:1165
    #8 0x7f208a2be517 in r_core_fini /home/maijin/Projects/radare2/libr/core/core.c:1281
    #9 0x55797cf47219 in main /home/maijin/Projects/radare2/binr/radare2/radare2.c:874
    #10 0x7f20851b8a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

previously allocated by thread T0 here:
    #0 0x7f208a7e8b49 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98b49)
    #1 0x7f208955d0df in Elf64_r_bin_elf_get_sections /home/maijin/Projects/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1316
    #2 0x7f2089555a7d in elf_init /home/maijin/Projects/radare2/libr/..//libr/bin/p/../format/elf/elf.c:349
    #3 0x7f2089561a8a in Elf64_r_bin_elf_new_buf /home/maijin/Projects/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1729
    #4 0x7f208954a273 in load_bytes /home/maijin/Projects/radare2/libr/..//libr/bin/p/bin_elf.c:42
    #5 0x7f20894eeb0e in r_bin_object_new /home/maijin/Projects/radare2/libr/bin/bin.c:962
    #6 0x7f20894ef992 in r_bin_file_new_from_bytes /home/maijin/Projects/radare2/libr/bin/bin.c:1110
    #7 0x7f20894ed5f9 in r_bin_load_io_at_offset_as_sz /home/maijin/Projects/radare2/libr/bin/bin.c:735
    #8 0x7f20894ed678 in r_bin_load_io_at_offset_as /home/maijin/Projects/radare2/libr/bin/bin.c:748
    #9 0x7f20894ecb6e in r_bin_load_io /home/maijin/Projects/radare2/libr/bin/bin.c:642
    #10 0x7f208a317205 in cmd_open /home/maijin/Projects/radare2/libr/core/cmd_open.c:339
    #11 0x7f208a3ccfd4 in r_cmd_call /home/maijin/Projects/radare2/libr/core/cmd_api.c:210
    #12 0x7f208a36446b in r_core_cmd_subst_i /home/maijin/Projects/radare2/libr/core/cmd.c:1702
    #13 0x7f208a36000b in r_core_cmd_subst /home/maijin/Projects/radare2/libr/core/cmd.c:1164
    #14 0x7f208a367667 in r_core_cmd /home/maijin/Projects/radare2/libr/core/cmd.c:2111
    #15 0x7f208a2bfbcd in r_core_prompt_exec /home/maijin/Projects/radare2/libr/core/core.c:1462
    #16 0x55797cf46ece in main /home/maijin/Projects/radare2/binr/radare2/radare2.c:818
    #17 0x7f20851b8a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

SUMMARY: AddressSanitizer: double-free ??:0 __interceptor_free
==11506==ABORTING
```

**Comment by alvarofe** [comment]
I can't reproduce it on arch 64 bits and neither i could on mac os x when you first mentioned
```
[alvaro@arch ~]$ r2 -v
radare2 0.10.0-git 9967 @ linux-little-x86-64 git.0.9.8-3606-g530daf5
commit: 530daf5420e84db94245abff9c6c5977c560f792 build: 2015-12-17
```

Which system are you running r2? r2 from git?

**Comment by jjdredd** [comment]
reproduced linux x86 at
radare2 0.10.0-git 9971 @ linux-little-x86-32 git.0.9.9-1854-g530daf5
commit: 530daf5420e84db94245abff9c6c5977c560f792 build: 2015-12-17

**Comment by alvarofe** [comment]
Can you fix it?

**Comment by jjdredd** [comment]
ok, I will see the code and try to fix it today.

**Comment by radare** [comment]
Ping

**Comment by jjdredd** [comment]
I think I have a fix, will make a pr.

**Comment by jjdredd** [comment]
Pls test and close

**Comment by radare** [comment]
Can't reproduce either
