### ISSUE TITLE
[lulzfuzz] ddw 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#3860]
morrn,

running luzzfuzz, there seems to be a problem in ddw:

perl -e 'print "'ddw' ", "\x12"x8192,"\n"' | r2 -qn -

```
#0  __strchr_sse2 () at ../sysdeps/x86_64/multiarch/../strchr.S:32
32	../sysdeps/x86_64/multiarch/../strchr.S: No such file or directory.
(gdb) bt
#0  __strchr_sse2 () at ../sysdeps/x86_64/multiarch/../strchr.S:32
#1  0x00007f2b53fb3eb7 in cmd_debug (data=0x555b0e22b5c0 <r>, input=0x555b0e6b1cd1 "dw") at cmd_debug.c:2861
#2  0x00007f2b5402759d in r_cmd_call (cmd=0x555b0e66b3c0, input=0x555b0e6b1cd0 "ddw") at cmd_api.c:210
#3  0x00007f2b53ff6346 in r_core_cmd_subst_i (core=0x555b0e22b5c0 <r>, cmd=0x555b0e6b1cd0 "ddw", colon=0x0) at cmd.c:1702
#4  0x00007f2b53ff419c in r_core_cmd_subst (core=0x555b0e22b5c0 <r>, cmd=0x555b0e6b1cd0 "ddw") at cmd.c:1164
#5  0x00007f2b53ff7a48 in r_core_cmd (core=0x555b0e22b5c0 <r>, cstr=0x555b0e613030 "ddw ", log=1) at cmd.c:2111
#6  0x00007f2b53fa6019 in r_core_prompt_exec (r=0x555b0e22b5c0 <r>) at core.c:1462
#7  0x0000555b0e028a30 in main (argc=3, argv=0x7fff17a6e088, envp=0x7fff17a6e0a8) at radare2.c:818
(gdb) 

 segfault at 1 ip 00007f2b5010aa73 sp 00007fff17a6bf18 error 4 in libc-2.21.so[7f2b50081000+1c0000] 
```

(gdb) !r2 -v
radare2 0.10.0-git 9973 @ linux-little-x86-64 git.0.9.9-1856-ga991e00
commit: a991e008d19772a0ddbc803fe6eb189035c5f446 build: 2015-12-18

Greetings
--zlul

**Comment by crowell** [comment]
@zonkzonk please provide the input file.

**Comment by zonkzonk** [comment]
@crowell 

perl -e 'print "'ddw' ", "\x12"x8192,"\n"' | r2 -qn -
