### ISSUE TITLE
dct

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#3890]
morrn,

```
r2 -d /bin/ls
dct -1
dct 1
dct 0
SegmentationFault
```

```
 gdb -q r2 core.17880
Core was generated by `r2 -d /bin/ls'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fb06c5be41e in r_bp_traptrace_list (bp=0x555dc6a2ab70)
    at traptrace.c:141
141		r_list_foreach (bp->traces, iter, trace) {
(gdb) bt
#0  0x00007fb06c5be41e in r_bp_traptrace_list (bp=0x555dc6a2ab70) at traptrace.c:141
#1  0x00007fb06e0cfb0f in cmd_debug_backtrace (core=0x555dc663b5c0 <r>, 
input=0x555dc6b571d3 " 0") at cmd_debug.c:487
#2  0x00007fb06e0d7f8a in cmd_debug_continue (core=0x555dc663b5c0 <r>, 
input=0x555dc6b571d1 "ct 0") at cmd_debug.c:2588
#3  0x00007fb06e0d94a4 in cmd_debug (data=0x555dc663b5c0 <r>, 
input=0x555dc6b571d1 "ct 0") at cmd_debug.c:2913
#4  0x00007fb06e14ddb4 in r_cmd_call (cmd=0x555dc6a1bda0, 
input=0x555dc6b571d0 "dct 0") at cmd_api.c:210
#5  0x00007fb06e11c85e in r_core_cmd_subst_i (core=0x555dc663b5c0 <r>, cmd=0x555dc6b571d0 "dct 0", colon=0x0) at cmd.c:1702
#6  0x00007fb06e11a6b4 in r_core_cmd_subst (core=0x555dc663b5c0 <r>, 
cmd=0x555dc6b571d0 "dct 0") at cmd.c:1164
#7  0x00007fb06e11df60 in r_core_cmd (core=0x555dc663b5c0 <r>, 
cstr=0x555dc69c9a70 "dct 0", log=1) at cmd.c:2111
#8  0x00007fb06e0cb2af in r_core_prompt_exec (r=0x555dc663b5c0 <r>) 
at core.c:1465
#9  0x0000555dc6438a30 in main (argc=3, argv=0x7ffc16343418, 
envp=0x7ffc16343438) at radare2.c:818
(gdb) !r2 -v
radare2 0.10.0-git 10007 @ linux-little-x86-64 git.0.9.9-1899-gc916d1c
commit: c916d1ca18bccb18fecae2831302916b09feac20 build: 2015-12-29 
(gdb) dmesg |tail -1 
r2[17880]: segfault at 8 ip 00007fb06c5be41e sp 00007ffc16340f10 error 4 
in libr_bp.so.0.10.0-git[7fb06c5bb000+4000]
```

Greetings
--zlul

**Comment by zonkzonk** [comment]
why fuzzing? see commands above. :)
