### ISSUE TITLE
ESIL bugs append #3621

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#3960]
morrn,

referring to #3621:

```
~$  r2 -e asm.emu=1 -qc'pD -$SS@$S' /bin/ls
*** Error in `r2': malloc(): memory corruption: 0x000055a9e75dd830 ***
Aborted


Core was generated by `r2 -e asm.emu=1 -qcpD -$SS@$S /bin/ls'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f17af9cb267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f17af9cb267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f17af9cceca in __GI_abort () at abort.c:89
#2  0x00007f17afa0ec53 in __libc_message (do_abort=1, fmt=fmt@entry=0x7f17afb271a8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f17afa17e5e in malloc_printerr (ptr=0x55dd09bdc830, str=0x7f17afb2337b "malloc(): memory corruption",
    action=<optimized out>) at malloc.c:4965
#4  _int_malloc (av=av@entry=0x7f17afd5ac00 <main_arena>, bytes=bytes@entry=3824) at malloc.c:3441
#5  0x00007f17afa1b0b5 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3213
#6  0x00007f17b395c34c in handle_init_ds (core=0x55dd089db5c0 <r>) at disasm.c:256
#7  0x00007f17b3965201 in r_core_print_disasm (p=0x55dd09a4e3e0, core=0x55dd089db5c0 <r>, addr=4140151,
    buf=0x55dd09bdc720 '\377' <repeats 200 times>..., len=64553, l=64553, invbreak=0, cbytes=1) at disasm.c:2383
#8  0x00007f17b39012b4 in cmd_print (data=0x55dd089db5c0 <r>, input=0x55dd09ad9e81 "D -$SS") at cmd_print.c:2412
#9  0x00007f17b3947003 in r_cmd_call (cmd=0x55dd09aa2be0, input=0x55dd09ad9e80 "pD -$SS") at cmd_api.c:210
#10 0x00007f17b3915497 in r_core_cmd_subst_i (core=0x55dd089db5c0 <r>, cmd=0x55dd09ad9e80 "pD -$SS", colon=0x0)
    at cmd.c:1717
#11 0x00007f17b3913430 in r_core_cmd_subst (core=0x55dd089db5c0 <r>, cmd=0x55dd09ad9e80 "pD -$SS") at cmd.c:1205
#12 0x00007f17b3916cd2 in r_core_cmd (core=0x55dd089db5c0 <r>, cstr=0x7ffd4b12b84d "pD -$SS@$S", log=0) at cmd.c:2149
#13 0x00007f17b391734a in r_core_cmd0 (user=0x55dd089db5c0 <r>, cmd=0x7ffd4b12b84d "pD -$SS@$S") at cmd.c:2284
#14 0x000055dd087d87e3 in main (argc=5, argv=0x7ffd4b129608, envp=0x7ffd4b129638) at radare2.c:778
(gdb)q

```

Greetings
--zlul

**Comment by zonkzonk** [comment]
radare2 0.10.0-git 10105 @ linux-little-x86-64 git.0.9.9-1996-g3b4fc2c
commit: 3b4fc2cf9a7c0a3ac9650de59e49f9995ec890d1 build: 2016-01-15

**Comment by radare** [comment]
This is not related to esil, its just a bug in pD. FIxed in master, thanks!
