### ISSUE TITLE
radare2 on windows crashes when run with a command to write into a file

### ISSUE THREAD

**Issue by 0xABD** [radare/radare2#4076]
```
radare2 0.10.0 10173 @ windows-little-x86-32 git.0.10.0-6-gd852ed1
commit: d852ed1a2315e889499f995155bb87ad5429b797 build: 2016-01-20
```
Last radare2 win32 build from web site on windows crashes when launched with a command like 
`radare2 -nwq -c "wx DEADBABE @12" file.bin`
Specifying `-e io.cache=true` magically resolves the crash.

**Comment by skuater** [comment]
The problem is when the file already exist, delete file.bin before run the command.

io.cache=true enable all write operations on memory then the file never become create / rewrite this its the reason dont crash with this option enabled.

Looking to solve ... at moment remove the file before launch r2.

**Comment by radare** [comment]
Removing the file doesn't solves the problem because he wants to patch some bytes, not write them on top of nothing. Let me know if you can find the reason. i dont have any windows to test right now

**Comment by 0xABD** [comment]
The use case is that I try to patch the existing file. The actual script is more complex, doing checksums, etc., but the crash happens regardless of the script. 
Anyway, this works in linux on an existing file as intended. 
I will try to get a stacktrace or other crash details and post it here.

**Comment by 0xABD** [comment]
At `\radare2\libr\util\file.c` you are calling WriteFile with `lpNumberOfBytesWritten = NULL` and `lpOverlapped = NULL` at the same time which is prohibited (https://msdn.microsoft.com/en-us/library/windows/desktop/aa365747(v=vs.85).aspx)

```
Program received signal SIGSEGV, Segmentation fault.
0x000007fefd6f1b44 in WriteFile () from C:\WINDOWS\system32\KernelBase.dll
(gdb) bt
#0  0x000007fefd6f1b44 in WriteFile () from C:\WINDOWS\system32\KernelBase.dll
#1  0x0000000077531fd6 in WriteFile () from C:\WINDOWS\system32\kernel32.dll
#2  0x000000007e11229c in WriteProcessed () from C:\Program Files\Far Manager\ConEmu\ConEmuHk64.dll
#3  0x0000000064f4ab0c in r_file_mmap_write (file=0x33d5360 "file.bin", addr=12, buf=0x33d5720 "ABCD\rd-§ÿ˜", '®' <repeats 16 times>, "Œ_Œ_Œ_", len=4) at file.c:515
#4  0x00000000011832b1 in r_io_def_mmap_write (io=0x33750a0, fd=0x33d5470, buf=0x33d5720 "ABCD\rd-§ÿ˜", '®' <repeats 16 times>, "Œ_Œ_Œ_", count=4) at p/io_default.c:251
#5  0x0000000001183730 in __write (io=0x33750a0, fd=0x33d5470, buf=0x33d5720 "ABCD\rd-§ÿ˜", '®' <repeats 16 times>, "Œ_Œ_Œ_", len=4) at p/io_default.c:336
#6  0x000000000118db53 in r_io_write (io=0x33750a0, buf=0x33d5720 "ABCD\rd-§ÿ˜", '®' <repeats 16 times>, "Œ_Œ_Œ_", len=4) at io.c:701
#7  0x000000000118dd8e in r_io_write_at (io=0x33750a0, addr=12, buf=0x33d5720 "ABCD\rd-§ÿ˜", '®' <repeats 16 times>, "Œ_Œ_Œ_", len=4) at io.c:738
#8  0x000000006f9eded4 in r_core_write_at (core=0x40c060 <r>, addr=12, buf=0x33d5720 "ABCD\rd-§ÿ˜", '®' <repeats 16 times>, "Œ_Œ_Œ_", size=4) at io.c:330
#9  0x000000006f99b8fb in cmd_write_hexpair (core=0x40c060 <r>, pairs=0x33cb4c2 " 41424344") at cmd_write.c:12
#10 0x000000006f99e797 in cmd_write (data=0x40c060 <r>, input=0x33cb4c1 "x 41424344") at cmd_write.c:848
#11 0x000000006fa09e12 in r_cmd_call (cmd=0x33820b0, input=0x33cb4c0 "wx 41424344") at cmd_api.c:210
#12 0x000000006f9d827a in r_core_cmd_subst_i (core=0x40c060 <r>, cmd=0x33cb4c0 "wx 41424344", colon=0x0) at cmd.c:1717
#13 0x000000006f9d6267 in r_core_cmd_subst (core=0x40c060 <r>, cmd=0x33cb4c0 "wx 41424344") at cmd.c:1205
#14 0x000000006f9d99fe in r_core_cmd (core=0x40c060 <r>, cstr=0x1346f90 "wx 41424344 @12", log=0) at cmd.c:2149
#15 0x000000006f9d9fef in r_core_cmd0 (user=0x40c060 <r>, cmd=0x1346f90 "wx 41424344 @12") at cmd.c:2284
#16 0x0000000000403a30 in main (argc=5, argv=0x1346e30, envp=0x1342d00) at radare2.c:780
(gdb) frame 3
#3  0x0000000064f4ab0c in r_file_mmap_write (file=0x33d5360 "file.bin", addr=12, buf=0x33d5720 "ABCD\rd-§ÿ˜", '®' <repeats 16 times>, "Œ_Œ_Œ_", len=4) at file.c:515
515             if (!WriteFile (fh, buf, len, NULL, NULL)) {
```

**Comment by 0xABD** [comment]
Made a PR
https://github.com/radare/radare2/pull/4116
