### ISSUE TITLE
cursor + fold = segfault

### ISSUE THREAD

**Issue by q6r** [radare/radare2#4231]
https://asciinema.org/a/aknbxlbfnea04c106pxz4mvhl

bt

```
#0  0x00007ffff640d970 in reader (info=0x7fffffffa450, byte=0x7fffffffa3bf "", 
    address=0x400cc6) at arch/X86/X86Disassembler.c:837
#1  0x00007ffff6423935 in consumeByte (insn=0x7fffffffa470, byte=0x7fffffffa3bf "")
    at arch/X86/X86DisassemblerDecoder.c:283
#2  0x00007ffff6424245 in readPrefixes (insn=0x7fffffffa470)
    at arch/X86/X86DisassemblerDecoder.c:488
#3  0x00007ffff6427c46 in decodeInstruction (insn=0x7fffffffa470, 
    reader=0x7ffff640d921 <reader>, readerArg=0x7fffffffa450, startLoc=0x400cc6, 
    mode=MODE_64BIT) at arch/X86/X86DisassemblerDecoder.c:2344
#4  0x00007ffff640de6c in X86_getInstruction (ud=0x5555558a0320, 
    code=0x5555ab247d40 <error: Cannot access memory at address 0x5555ab247d40>, 
    code_len=0x20, instr=0x7fffffffa830, size=0x7fffffffa82e, address=0x400cc6, _info=0x0)
    at arch/X86/X86Disassembler.c:940
#5  0x00007ffff6310947 in cs_disasm (ud=0x5555558a0320, 
    buffer=0x5555ab247d40 <error: Cannot access memory at address 0x5555ab247d40>, 
    size=0x20, offset=0x400cc6, count=0x1, insn=0x7ffff563a9b8 <insn>) at cs.c:600
#6  0x00007ffff4dbcb0b in disassemble (a=0x5555557c4400, op=0x7fffffffac90, 
    buf=0x5555ab247d40 <error: Cannot access memory at address 0x5555ab247d40>, len=0x20)
    at p/asm_x86_cs.c:72
#7  0x00007ffff4def95e in r_asm_disassemble (a=0x5555557c4400, op=0x7fffffffac90, 
    buf=0x5555ab247d40 <error: Cannot access memory at address 0x5555ab247d40>, len=0x20)
    at asm.c:326
#8  0x00007ffff7943835 in cursor_nextrow (core=0x55555575b8c0 <r>, use_ocur=0x0)
    at visual.c:843
#9  0x00007ffff7945c7d in r_core_visual_cmd (core=0x55555575b8c0 <r>, ch=0x6a)
    at visual.c:1421
#10 0x00007ffff7948713 in r_core_visual (core=0x55555575b8c0 <r>, input=0x5555558aa3e1 "")
    at visual.c:2106
#11 0x00007ffff79312e1 in cmd_visual (data=0x55555575b8c0 <r>, input=0x5555558aa3e1 "")
    at cmd.c:845
#12 0x00007ffff796529f in r_cmd_call (cmd=0x555555812720, input=0x5555558aa3e0 "V")
    at cmd_api.c:210
#13 0x00007ffff79342d3 in r_core_cmd_subst_i (core=0x55555575b8c0 <r>, 
    cmd=0x5555558aa3e0 "V", colon=0x0) at cmd.c:1752
#14 0x00007ffff7932467 in r_core_cmd_subst (core=0x55555575b8c0 <r>, cmd=0x5555558aa3e0 "V")
    at cmd.c:1213
#15 0x00007ffff7935823 in r_core_cmd (core=0x55555575b8c0 <r>, cstr=0x555555848ae0 "V", 
    log=0x1) at cmd.c:2158
#16 0x00007ffff78e6abd in r_core_prompt_exec (r=0x55555575b8c0 <r>) at core.c:1501
#17 0x000055555555940a in main (argc=0x2, argv=0x7fffffffd4f8, envp=0x7fffffffd510)
    at radare2.c:824
#18 0x00007ffff3364710 in __libc_start_main () from /usr/lib/libc.so.6
#19 0x0000555555556cc9 in _start ()
```

**Comment by radare** [comment]
A backtrace would be more helpful. Attach the debugger and type bt when it crashes

**Comment by q6r** [comment]
I included it in the issue ^ :/

**Comment by radare** [comment]
Oh sorry disnt saw that from the mail. Thx

**Comment by radare** [comment]
Please confirm if it is fixed now in master

**Comment by radare** [comment]
Anyway, the z and Z keys in visual mode look pretty broken. Will fill an issue for that
