### ISSUE TITLE
AddressSanitizer WRITE of size 4 set_mem_access arch/AArch64/AArch64InstPrinter.c:73

### ISSUE THREAD

**Issue by revskills** [radare/radare2#4234]
```sh
==1401==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61c000899820 at pc 0x7f624836167a bp 0x7fff4dd59fb0 sp 0x7fff4dd59fa0
WRITE of size 4 at 0x61c000899820 thread T0
    #0 0x7f6248361679 in set_mem_access arch/AArch64/AArch64InstPrinter.c:73
    #1 0x7f624837a027 in printInstruction arch/AArch64/AArch64GenAsmWriter.inc:5743
    #2 0x7f6248369860 in AArch64_printInst arch/AArch64/AArch64InstPrinter.c:448
    #3 0x7f62482ccb23 in cs_disasm /home/fuzzer/R2/radare2/shlr/capstone/cs.c:610
    #4 0x7f62481ad9fe in analop /home/fuzzer/R2/radare2/libr/..//libr/anal/p/anal_arm_cs.c:1184
    #5 0x7f6248275693 in r_anal_op /home/fuzzer/R2/radare2/libr/anal/op.c:89
    #6 0x7f6249fed49e in r_core_anal_search_xrefs /home/fuzzer/R2/radare2/libr/core/anal.c:1699
    #7 0x7f6249f14828 in r_core_anal_refs /home/fuzzer/R2/radare2/libr/core/cmd_anal.c:3497
    #8 0x7f6249f14f40 in cmd_anal_all /home/fuzzer/R2/radare2/libr/core/cmd_anal.c:3554
    #9 0x7f6249f16688 in cmd_anal /home/fuzzer/R2/radare2/libr/core/cmd_anal.c:3778
    #10 0x7f6249fda5fb in r_cmd_call /home/fuzzer/R2/radare2/libr/core/cmd_api.c:210
    #11 0x7f6249f6ab20 in r_core_cmd_subst_i /home/fuzzer/R2/radare2/libr/core/cmd.c:1752
    #12 0x7f6249f6663b in r_core_cmd_subst /home/fuzzer/R2/radare2/libr/core/cmd.c:1213
    #13 0x7f6249f6dd0a in r_core_cmd /home/fuzzer/R2/radare2/libr/core/cmd.c:2158
    #14 0x7f6249f6e873 in r_core_cmd0 /home/fuzzer/R2/radare2/libr/core/cmd.c:2293
    #15 0x55efc187394f in main /home/fuzzer/R2/radare2/binr/radare2/radare2.c:761
    #16 0x7f6244beba3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #17 0x55efc186f978 in _start (/home/fuzzer/R2/radare2/binr/radare2/radare2+0x5978)

ASAN:SIGSEGV
==1401==AddressSanitizer
```
file: http://revskills.cz/r2/3496c4253cd979b4d0018cc5c88f2a08

radare2 0.10.2-git 10495 @ linux-little-x86-64 git.0.10.1-38-gfbb1b1e
commit: fbb1b1e80ff343c14f095a340ef53b977ebfc943 build: 2016-03-06

**Comment by alvarofe** [comment]
to reproduce
```
s 0x100008210
pd 2
```

**Comment by alvarofe** [comment]
the issue is with capstone here a patch. Confirm and i will make a pr to upstream 

```
diff --git a/arch/AArch64/AArch64InstPrinter.c b/arch/AArch64/AArch64InstPrinter.c
index 56b073c..73ca3d6 100644
--- a/arch/AArch64/AArch64InstPrinter.c
+++ b/arch/AArch64/AArch64InstPrinter.c
@@ -70,7 +70,7 @@ static void set_mem_access(MCInst *MI, bool status)
 #ifndef CAPSTONE_DIET
                uint8_t access;
                access = get_op_access(MI->csh, MCInst_getOpcode(MI), MI->ac_idx);
-               MI->flat_insn->detail->arm64.operands[MI->flat_insn->detail->arm.op_count].access = access;
+               MI->flat_insn->detail->arm64.operands[MI->flat_insn->detail->arm64.op_count].access = access;
                MI->ac_idx++;
 #endif
                MI->flat_insn->detail->arm64.operands[MI->flat_insn->detail->arm64.op_count].type = ARM64_OP_MEM;
```

**Comment by revskills** [comment]
Note from radare2-regressions ./mach0/machfuzzed/mach10 also reproduce this issue

**Comment by radare** [comment]
it is fixed now?

**Comment by alvarofe** [comment]
I can make a pr to include the patch inside capstone-patches

**Comment by radare** [comment]
Fixed in master
