### ISSUE TITLE
AddressSanitizer  stack-buffer-overflow READ of size 135 libr/core/anal.c:2283

### ISSUE THREAD

**Issue by revskills** [radare/radare2#4243]
```sh
==8124==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffeb2659e60 at pc 0x7f8879170649 bp 0x7ffeb2659390 sp 0x7ffeb2658b08
READ of size 135 at 0x7ffeb2659e60 thread T0
    #0 0x7f8879170648  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x60648)
    #1 0x7f88791715a5 in __interceptor_vsnprintf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x615a5)
    #2 0x7f8879171811 in snprintf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x61811)
    #3 0x7f8878d99bb9 in esilbreak_mem_read /home/fuzzer/R2/radare2/libr/core/anal.c:2283
    #4 0x7f887703fdd0 in r_anal_esil_mem_read /home/fuzzer/R2/radare2/libr/anal/esil.c:199
    #5 0x7f887704961c in esil_peek_n /home/fuzzer/R2/radare2/libr/anal/esil.c:1470
    #6 0x7f887704986a in esil_peek4 /home/fuzzer/R2/radare2/libr/anal/esil.c:1487
    #7 0x7f887704e076 in runword /home/fuzzer/R2/radare2/libr/anal/esil.c:2135
    #8 0x7f887704ebc5 in r_anal_esil_parse /home/fuzzer/R2/radare2/libr/anal/esil.c:2235
    #9 0x7f8878d9a9ce in r_core_anal_esil /home/fuzzer/R2/radare2/libr/core/anal.c:2389
    #10 0x7f8878cbd457 in cmd_anal_all /home/fuzzer/R2/radare2/libr/core/cmd_anal.c:3590
    #11 0x7f8878cbe688 in cmd_anal /home/fuzzer/R2/radare2/libr/core/cmd_anal.c:3778
    #12 0x7f8878d825fb in r_cmd_call /home/fuzzer/R2/radare2/libr/core/cmd_api.c:210
    #13 0x7f8878d12b20 in r_core_cmd_subst_i /home/fuzzer/R2/radare2/libr/core/cmd.c:1752
    #14 0x7f8878d0e63b in r_core_cmd_subst /home/fuzzer/R2/radare2/libr/core/cmd.c:1213
    #15 0x7f8878d15d0a in r_core_cmd /home/fuzzer/R2/radare2/libr/core/cmd.c:2158
    #16 0x7f8878c65423 in r_core_prompt_exec /home/fuzzer/R2/radare2/libr/core/core.c:1501
    #17 0x5611e838cfb4 in main /home/fuzzer/R2/radare2/binr/radare2/radare2.c:824
    #18 0x7f8873993a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #19 0x5611e8388978 in _start (/home/fuzzer/R2/radare2/binr/radare2/radare2+0x5978)

ASAN:SIGSEGV
==8124==AddressSanitizer
```

Reproduce: aae
file: ./elf/mips.elf

radare2 0.10.2-git 10495 @ linux-little-x86-64 git.0.10.1-38-gfbb1b1e
commit: fbb1b1e build: 2016-03-06

**Comment by radare** [comment]
not fixed acording to revskills. will need to use asan on linux. on mac looks good with valgrind

**Comment by alvarofe** [comment]
I've tried on linux too and valgrind doesn't complain i will compile gcc with asan support and see

**Comment by revskills** [comment]
clang

**Comment by alvarofe** [comment]
neither luck in linux. I just opened the binary and then `aae` but ASAN doesn't complain

```
clang version 3.9.0 (http://llvm.org/git/clang.git dfc9e6a5fb591935d087aea7b63a1fade7ef9e6e) (http://llvm.org/git/llvm.git 5dae3806201cde2ba351cb6bd36d1b6a96b49576)
Target: x86_64-unknown-linux-gnu
```

```
radare2 0.10.2-git 10539 @ linux-little-x86-64 git.0.9.9-2430-g747699f
commit: 747699f712d7cc0402b20c9313a16634e68d7764 build: 2016-03-11
```

**Comment by revskills** [comment]
Wops, it seems fixed already in:

radare2 0.10.2-git 10556 @ linux-little-x86-64 git.0.10.1-99-g747699f
commit: 747699f712d7cc0402b20c9313a16634e68d7764 build: 2016-03-11

Close please

**Comment by crowell** [comment]
wut how did that commit fix anything?
