### ISSUE TITLE
AddressSanitizer rax2 WRITE of size 74801 radare2/binr/rax2/rax2.c:375

### ISSUE THREAD

**Issue by revskills** [radare/radare2#4244]
```sh
=================================================================
==12856==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fc6ddbd1f30 at pc 0x7fc6dcad62a5 bp 0x7ffce8696a30 sp 0x7ffce86961d8
WRITE of size 74801 at 0x7fc6ddbd1f30 thread T0
    #0 0x7fc6dcad62a4  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x462a4)
    #1 0x55961dcc2a03 in use_stdin /home/fuzzer/R2/radare2/binr/rax2/rax2.c:375
    #2 0x55961dcc0d46 in rax /home/fuzzer/R2/radare2/binr/rax2/rax2.c:160
    #3 0x55961dcc2c6a in main /home/fuzzer/R2/radare2/binr/rax2/rax2.c:405
    #4 0x7fc6dc414a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #5 0x55961dcbfeb8 in _start (/home/fuzzer/R2/radare2/binr/rax2/rax2+0x1eb8)

0x7fc6ddbd1f30 is located 0 bytes to the right of 354096-byte region [0x7fc6ddb7b800,0x7fc6ddbd1f30)
ASAN:SIGSEGV
==12856==AddressSanitizer
```

Repro:  rax2 -S < mipsbe-busybox > crash.hex
file: ./bins/elf/mipsbe-busybox

rax2 0.10.2-git 10495 @ linux-little-x86-64 git.0.10.1-38-gfbb1b1e
commit: fbb1b1e80ff343c14f095a340ef53b977ebfc943 build: 2016-03-06

**Comment by alvarofe** [comment]
I can't reproduce this one in Mac 

```
radare2 0.10.2-git 10537 @ darwin-little-x86-64 git.0.9.9-2377-gddde978
commit: ddde978a0e5398a548a3eb73f1e68b93058c08d8 build: 2016-03-07
```

**Comment by revskills** [comment]
I've various samples try this one:

http://revskills.cz/r2/f6183c62ec52da2a3d1d5a8ad4059a9d

```sh
==29664==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fbe90003f30 at pc 0x7fbe8ef14265 bp 0x7ffe8a099760 sp 0x7ffe8a098f08
WRITE of size 9585 at 0x7fbe90003f30 thread T0
    #0 0x7fbe8ef14264  (/lib64/libasan.so.2+0x46264)
    #1 0x55a8870f4941 in use_stdin /home/revskillz/radare2/binr/rax2/rax2.c:375
    #2 0x55a8870f2c98 in rax /home/revskillz/radare2/binr/rax2/rax2.c:160
    #3 0x55a8870f4ba8 in main /home/revskillz/radare2/binr/rax2/rax2.c:405
    #4 0x7fbe8e85c6ff in __libc_start_main (/lib64/libc.so.6+0x206ff)
    #5 0x55a8870f1e48 in _start (/home/revskillz/radare2/binr/rax2/rax2+0x1e48)

```

**Comment by alvarofe** [comment]
confirmed with valgrind

```
==58018== Syscall param read(buf) points to unaddressable byte(s)
==58018==    at 0x10037345E: read (in /usr/lib/system/libsystem_kernel.dylib)
==58018==    by 0x100002F72: use_stdin (in /usr/local/bin/rax2)
==58018==    by 0x100001C23: rax (in /usr/local/bin/rax2)
==58018==    by 0x1000015E8: main (in /usr/local/bin/rax2)
==58018==  Address 0x100b4eee0 is 0 bytes after a block of size 354,096 alloc'd
==58018==    at 0x10000BE3B: malloc (in /usr/local/Cellar/valgrind/HEAD/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==58018==    by 0x100002F13: use_stdin (in /usr/local/bin/rax2)
==58018==    by 0x100001C23: rax (in /usr/local/bin/rax2)
==58018==    by 0x1000015E8: main (in /usr/local/bin/rax2)
==58018==
```

**Comment by alvarofe** [comment]
@revskills https://github.com/radare/radare2/pull/4247
