### ISSUE TITLE
0x00007ff03a193596 in __strcmp_ssse3 () from /usr/lib/libc.so.6

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#4462]
morrn,

![fuzzed_phile](https://cloud.githubusercontent.com/assets/5694980/14157130/fb85273c-f6c9-11e5-828c-fa2d70950003.png)

```
,r2 fuzzed_phile  

Warning: Cannot initialize program headers
Warning: Cannot initialize strings table
Segmentation fault (core dumped)
,gdb -q r2 core.23611 

Core was generated by `r2 fuzzed_phile'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ff03a193596 in __strcmp_ssse3 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ff03a193596 in __strcmp_ssse3 () from /usr/lib/libc.so.6
#1  0x00007ff03dae259a in init_dynstr (bin=0x56080b245380) at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:732
#2  0x00007ff03dae2921 in elf_init (bin=0x56080b245380) at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:776
#3  0x00007ff03dae8a3d in Elf64_r_bin_elf_new_buf (buf=0x56080b245340) at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:2219
#4  0x00007ff03dadc74a in load_bytes (arch=0x56080b247030, buf=0x56080b247470 "\177ELF\002\001\001", sz=126496, loadaddr=0, sdb=0x56080b23f5c0)
    at /home/zlul/src/radare2/libr/..//libr/bin/p/bin_elf.c:42
#5  0x00007ff03dab4128 in r_bin_object_new (binfile=0x56080b247030, plugin=0x56080b1ef820, baseaddr=18446744073709551615, loadaddr=0, offset=0,
    sz=126496) at bin.c:960
#6  0x00007ff03dab4833 in r_bin_file_new_from_bytes (bin=0x56080b1eba10, file=0x56080b246ef0 "fuzzed_phile", 
    bytes=0x56080b247470 "\177ELF\002\001\001", sz=126496, file_sz=126496, rawstr=0, baseaddr=18446744073709551615, loadaddr=0, fd=7, pluginname=0x0,
    xtrname=0x0, offset=0) at bin.c:1109
#7  0x00007ff03dab361c in r_bin_load_io_at_offset_as_sz (bin=0x56080b1eba10, desc=0x56080b246f50, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0,
    offset=0, name=0x0, sz=126496) at bin.c:732
#8  0x00007ff03dab369b in r_bin_load_io_at_offset_as (bin=0x56080b1eba10, desc=0x56080b246f50, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0,
    offset=0, name=0x0) at bin.c:744
#9  0x00007ff03dab30ea in r_bin_load_io (bin=0x56080b1eba10, desc=0x56080b246f50, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0) at bin.c:637
#10 0x00007ff03e681554 in r_core_file_do_load_for_io_plugin (r=0x56080a0c78e0 <r>, baseaddr=18446744073709551615, loadaddr=0) at file.c:383
#11 0x00007ff03e6819e9 in r_core_bin_load (r=0x56080a0c78e0 <r>, filenameuri=0x56080b246ef0 "fuzzed_phile", baddr=18446744073709551615) at file.c:462
#12 0x0000560809ec4ac7 in main (argc=2, argv=0x7fff32257628, envp=0x7fff32257640) at radare2.c:658
(gdb) !r2 -v
radare2 0.10.2-git 10753 @ linux-little-x86-64 git.0.10.1-298-g7a19745
commit: 7a197459326657bd0301fc13c7efe8efb63a79ba build: 2016-03-30
(
```

**Comment by radare** [comment]
thanks!
