### ISSUE TITLE
segfault store_versioninfo_gnu_verdef elf.c

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#4481]
morrn,

![fuzzed_phile](https://cloud.githubusercontent.com/assets/5694980/14195867/bc1cf764-f7be-11e5-8fc8-d8b8d98a6a77.png)

```
,r2 fuzzed_phile
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Segmentation fault (core dumped)
,gdb -q r2 co
color = 1   core.24929  core.25033  
,gdb -q r2 core.25033 
Reading symbols from r2...done.

warning: core file may not match specified executable file.
[New LWP 25033]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `r2 fuzzed_phile'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5cfbae09e5 in store_versioninfo_gnu_verdef (bin=0x55725270c6a0, shdr=0x557252771060, sz=272)
    at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:571
571                     sdb_set (sdb_verdef, "vda_name", &bin->dynstr[aux->vda_name], 0);
(gdb) bt
#0  0x00007f5cfbae09e5 in store_versioninfo_gnu_verdef (bin=0x55725270c6a0, shdr=0x557252771060, sz=272)
    at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:571
#1  0x00007f5cfbae137a in store_versioninfo (bin=0x55725270c6a0) at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:704
#2  0x00007f5cfbae1a4b in elf_init (bin=0x55725270c6a0) at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:791
#3  0x00007f5cfbae7a6b in Elf64_r_bin_elf_new_buf (buf=0x55725270c660) at /home/zlul/src/radare2/libr/..//libr/bin/p/../format/elf/elf.c:2220
#4  0x00007f5cfbadb761 in load_bytes (arch=0x55725270e350, buf=0x55725270e790 "\177ELF\002\001\001", sz=126496, loadaddr=0, sdb=0x5572527068e0)
    at /home/zlul/src/radare2/libr/..//libr/bin/p/bin_elf.c:42
#5  0x00007f5cfbab3128 in r_bin_object_new (binfile=0x55725270e350, plugin=0x5572526b6840, baseaddr=18446744073709551615, loadaddr=0, offset=0, 
    sz=126496) at bin.c:960
#6  0x00007f5cfbab3833 in r_bin_file_new_from_bytes (bin=0x5572526b2a30, file=0x55725270e270 "fuzzed_phile", 
    bytes=0x55725270e790 "\177ELF\002\001\001", sz=126496, file_sz=126496, rawstr=0, baseaddr=18446744073709551615, loadaddr=0, fd=7, pluginname=0x0, 
    xtrname=0x0, offset=0) at bin.c:1109
#7  0x00007f5cfbab261c in r_bin_load_io_at_offset_as_sz (bin=0x5572526b2a30, desc=0x55725270e290, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0, 
    offset=0, name=0x0, sz=126496) at bin.c:732
#8  0x00007f5cfbab269b in r_bin_load_io_at_offset_as (bin=0x5572526b2a30, desc=0x55725270e290, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0, 
    offset=0, name=0x0) at bin.c:744
#9  0x00007f5cfbab20ea in r_bin_load_io (bin=0x5572526b2a30, desc=0x55725270e290, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0) at bin.c:637
#10 0x00007f5cfc680cc7 in r_core_file_do_load_for_io_plugin (r=0x5572510ff8e0 <r>, baseaddr=18446744073709551615, loadaddr=0) at file.c:383
#11 0x00007f5cfc68115c in r_core_bin_load (r=0x5572510ff8e0 <r>, filenameuri=0x55725270e270 "fuzzed_phile", baddr=18446744073709551615) at file.c:462
#12 0x0000557250efcac7 in main (argc=2, argv=0x7ffead15f9f8, envp=0x7ffead15fa10) at radare2.c:658
(gdb) !r2 -v
radare2 0.10.2-git 10777 @ linux-little-x86-64 git.0.10.1-322-gfa4edbf
commit: fa4edbfa452cc9d7514cfeffa91943872c363890 build: 2016-04-01

```

**Comment by zonkzonk** [comment]
Thanks!
