### ISSUE TITLE
e io_cache=true most module - bin_elf.c patch_relocs 

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#4539]
![nls_cp855 ko](https://cloud.githubusercontent.com/assets/6604362/14330197/af804bde-fc3f-11e5-8c7c-b567e5455f6f.png)
![fb_sys_fops ko](https://cloud.githubusercontent.com/assets/6604362/14330243/01e0c2aa-fc40-11e5-966a-4906e5b0893e.png)

r2 -v
radare2 0.10.2-git 10855 @ linux-little-x86-64 git.0.10.1-400-gaee231e
commit: aee231ec04bf072d36c1aa263898c9ef6f136b73 build: 2016-04-06

```
$ locate nls_cp855.ko
/usr/lib/modules/4.4.5-1-ARCH/kernel/fs/nls/nls_cp855.ko.gz
$ cp /usr/lib/modules/4.4.5-1-ARCH/kernel/fs/nls/nls_cp855.ko.gz .
$ gunzip nls_cp855.ko.gz 
$ # r2  -e io.cache=true -d nls_cp855.ko 
$ulimit -c 100000
$ulimit -f 100000
$r2  -e io.cache=true -d nls_cp855.ko 
p/io_debug.c:342 fork_and_attach: execv: Permission denied
Cannot open 'dbg://./nls_cp855.ko' for writing.
$ chmod +x nls_cp855.ko 
$r2  -e io.cache=true -d nls_cp855.ko 
Process with PID 682 started...
attach 682 682
bin.baddr 0x00400000
Assuming filepath ./nls_cp855.ko
Warning: Cannot initialize program headers
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Segmentation fault (core dumped)
$./nls_cp855.ko: ./nls_cp855.ko: cannot execute binary file
gdb -q r2 core.681 
bReading symbols from r2...done.

warning: core file may not match specified executable file.
[New LWP 681]
t
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `r2 -e io.cache=true -d nls_cp855.ko'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f933c6596d7 in patch_relocs (b=0x563e16ca1270) at /home/sk/src/radare2/libr/..//libr/bin/p/bin_elf.c:620
620             if (!b->iob.section_add (io, n_off, n_vaddr, size, size, R_BIN_SCN_READABLE|R_BIN_SCN_MAP, ".got.r2", 0, io->desc->fd))
(gdb) bt
#0  0x00007f933c6596d7 in patch_relocs (b=0x563e16ca1270) at /home/sk/src/radare2/libr/..//libr/bin/p/bin_elf.c:620
#1  0x00007f933c62e253 in r_bin_patch_relocs (bin=0x563e16ca1270) at bin.c:1292
#2  0x00007f933d220f7d in bin_relocs (r=0x563e1543e8e0 <r>, mode=2, va=1) at bin.c:879
#3  0x00007f933d225aed in r_core_bin_info (core=0x563e1543e8e0 <r>, action=20479, mode=2, va=1, filter=0x0, chksum=0x0) at bin.c:2114
#4  0x00007f933d21e11d in r_core_bin_set_env (r=0x563e1543e8e0 <r>, binfile=0x563e16ce2210) at bin.c:106
#5  0x00007f933d1fdf92 in r_core_file_do_load_for_debug (r=0x563e1543e8e0 <r>, baseaddr=4194304, filenameuri=0x563e16cfca86 "./nls_cp855.ko") at file.c:348
#6  0x00007f933d1fe61a in r_core_bin_load (r=0x563e1543e8e0 <r>, filenameuri=0x563e16cfca86 "./nls_cp855.ko", baddr=4194304) at file.c:459
#7  0x0000563e1523b868 in main (argc=5, argv=0x7ffd7bfdcef8, envp=0x7ffd7bfdcf28) at radare2.c:618

```

**Comment by alvarofe** [comment]
can you explain further the issue?

**Comment by VisualPrankDude** [comment]
sorry issues got lost

**Comment by radare** [comment]
You mean that it is not reproducible anymore? Do you use asan?

**Comment by VisualPrankDude** [comment]
still in 8b1d14e3889bb511c640d096e8bc69bcf14636c3

```
valgrind --log-file=/tmp/meh r2  -e io.cache=true -d nls_cp855.ko 
attach 21010 21010
p/debug_native.c:770 Cannot open '/proc/21010/maps': No such file or directory
Assuming filepath ./nls_cp855.ko
Warning: Cannot initialize program headers
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Segmentation fault
,dmesg |tail -2
[  828.214429] r2[10024]: segfault at 0 ip 00007f674cd066d7 sp 00007ffc89567630 error 4 in libr_bin.so.0.10.2-git[7f674ccb6000+f3000]
[ 1113.984078] r2[20977]: segfault at 0 ip 00007fd4272756d7 sp 00007ffd215b2690 error 4 in libr_bin.so.0.10.2-git[7fd427225000+f3000]



```

**Comment by VisualPrankDude** [comment]
```
```

**Comment by alvarofe** [comment]
it should be fixed now reopen if needed. Thx
