### ISSUE TITLE
AddressSanitizer: SEGV format/mach0/dyldcache.c:57

### ISSUE THREAD

**Issue by revskills** [radare/radare2#4568]
```sh
r2 -A aca8ffa33b21ee9a63f61c371e78c7c1                                                                                                                                                                                        
ASAN:SIGSEGV
=================================================================
==10544==ERROR: AddressSanitizer: SEGV on unknown address 0x61800003ec80 (pc 0x7fe619cf8746 bp 0x7ffcf1945b90 sp 0x7ffcf19459d0 T0)
    #0 0x7fe619cf8745 in r_bin_dyldcache_extract /home/fuzzer/radare2/libr/..//libr/bin/p/../format/mach0/dyldcache.c:57
    #1 0x7fe619cf7c03 in oneshot /home/fuzzer/radare2/libr/..//libr/bin/p/bin_xtr_dyldcache.c:90
    #2 0x7fe619cf7e58 in oneshotall /home/fuzzer/radare2/libr/..//libr/bin/p/bin_xtr_dyldcache.c:109
    #3 0x7fe619be13f2 in r_bin_file_xtr_load_bytes /home/fuzzer/radare2/libr/bin/bin.c:864
    #4 0x7fe619be08ff in r_bin_load_io_at_offset_as_sz /home/fuzzer/radare2/libr/bin/bin.c:729
    #5 0x7fe619be0add in r_bin_load_io_at_offset_as /home/fuzzer/radare2/libr/bin/bin.c:753
    #6 0x7fe619bdffcd in r_bin_load_io /home/fuzzer/radare2/libr/bin/bin.c:646
    #7 0x7fe61aa9d1cf in r_core_file_do_load_for_io_plugin /home/fuzzer/radare2/libr/core/file.c:383
    #8 0x7fe61aa9de49 in r_core_bin_load /home/fuzzer/radare2/libr/core/file.c:462
    #9 0x5610f1a740dd in main /home/fuzzer/radare2/binr/radare2/radare2.c:658
    #10 0x7fe6156a5a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #11 0x5610f1a70c68 in _start (/home/fuzzer/radare2/binr/radare2/radare2+0x5c68)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fuzzer/radare2/libr/..//libr/bin/p/../format/mach0/dyldcache.c:57 r_bin_dyldcache_extract
==10544==ABORTING
```

radare2 0.10.2-git 10883 @ linux-little-x86-64 git.0.10.1-429-g4476720
commit: 4476720aa8ce09e2aa13a9d08cc870b2b9886cb9 build: 2016-04-08

file: http://revskills.cz/r2/aca8ffa33b21ee9a63f61c371e78c7c1

**Comment by alvarofe** [comment]
should be fixed now
