### ISSUE TITLE
segfault for wopD with large number and no address

### ISSUE THREAD

**Issue by diouziou** [radare/radare2#4664]
using wopD with a large number and no address like e.g. `wopD 0x41414141` yields a segfault

**Comment by radare** [comment]
cant reproduce. can you confirm this is with git and provide a backtrace?

**Comment by diouziou** [comment]
Here are the infos to reproduce the bug: i use raspbian on an rpi3:
```
pi@raspberrypi:~/info $ uname -a
Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux
pi@raspberrypi:~/info $ r2 -v
radare2 0.10.2 10991 @ linux-little-arm-32 git.0.10.2-47-g1b297b9
commit: 1b297b978446e0910e70c5d565d06699e340514e build: 2016-04-19
```

using `r2` or `r2 -d` on a simple hello world code gives segfault when launching `wopD 0x41414141` (0x41414141=1094795585 is then, e.g., found in argument maxlen of function de_bruijn_seq() ):

```
pi@raspberrypi:~/info $ gdb -q r2
Reading symbols from r2...done.
(gdb) run ./hello
Starting program: /usr/bin/r2 ./hello
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
 -- Bindings are mostly powered by tears.
[0x000102f4]> wopD 0x41414141

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../ports/sysdeps/arm/armv6/strlen.S:26
26	../ports/sysdeps/arm/armv6/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../ports/sysdeps/arm/armv6/strlen.S:26
#1  0x75bb268c in de_bruijn_seq (prenecklace_len_t=1, lyndon_prefix_len_p=1, 
    order=3, maxlen=1094795585, size=62, prenecklace_a=0x54bcf328, 
    sequence=0x0, 
    charset=0x75bc41bc "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890") at debruijn.c:21
#2  0x75bb28f4 in de_bruijn (
    charset=0x75bc41bc "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890", order=3, maxlen=1094795585) at debruijn.c:54
#3  0x75bb2968 in r_debruijn_pattern (size=1094795585, start=0, 
    charset=0x75bc41bc "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890") at debruijn.c:70
#4  0x76eaeb14 in cmd_write_op (core=0x54ac0ec8 <r>, 
    input=0x54bcf1e1 "opD 0x41414141") at cmd_write.c:186
#5  0x76eb1e60 in cmd_write (data=0x54ac0ec8 <r>, 
    input=0x54bcf1e1 "opD 0x41414141") at cmd_write.c:1047
#6  0x76f30ac8 in r_cmd_call (cmd=0x54b646d0, 
    input=0x54bcf1e0 "wopD 0x41414141") at cmd_api.c:210
#7  0x76ef2fe0 in r_core_cmd_subst_i (core=0x54ac0ec8 <r>, 
    cmd=0x54bcf1e0 "wopD 0x41414141", colon=0x0) at cmd.c:1779
#8  0x76ef0ee0 in r_core_cmd_subst (core=0x54ac0ec8 <r>, 
    cmd=0x54bcf1e0 "wopD 0x41414141") at cmd.c:1240
#9  0x76ef4658 in r_core_cmd (core=0x54ac0ec8 <r>, 
    cstr=0x54bc8c40 "wopD 0x41414141", log=1) at cmd.c:2185
#10 0x76e990cc in r_core_prompt_exec (r=0x54ac0ec8 <r>) at core.c:1556
#11 0x54aaf42c in main (argc=2, argv=0x7efff794, envp=0x7efff7a0)
    at radare2.c:879
```
