### ISSUE TITLE
AddressSanitizer: stack-buffer-overflow READ of size 261 /libr/bin/p/bin_xbe.c:146

### ISSUE THREAD

**Issue by zlowram** [radare/radare2#5068]
Command:
```
r2 -A -q -c q samples/4cabafa790019a8859dcc902e69f8be6
```

Stacktrace:
```
==11656==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc4a9ca450 at pc 0x7fd5a2cb7649 bp 0x7ffc4a9c
READ of size 261 at 0x7ffc4a9ca450 thread T0
    #0 0x7fd5a2cb7648  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x60648)
    #1 0x7fd5a2cb85a5 in __interceptor_vsnprintf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x615a5)
    #2 0x7fd5a2cb8811 in snprintf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x61811)
    #3 0x7fd5a1a81e60 in sections /home/z/src/radare2/libr/..//libr/bin/p/bin_xbe.c:146
    #4 0x7fd5a1967fc2 in r_bin_object_set_items /home/z/src/radare2/libr/bin/bin.c:512
    #5 0x7fd5a196bbf2 in r_bin_object_new /home/z/src/radare2/libr/bin/bin.c:1019
    #6 0x7fd5a196c6dd in r_bin_file_new_from_bytes /home/z/src/radare2/libr/bin/bin.c:1129
    #7 0x7fd5a196a267 in r_bin_load_io_at_offset_as_sz /home/z/src/radare2/libr/bin/bin.c:748
    #8 0x7fd5a196a2f2 in r_bin_load_io_at_offset_as /home/z/src/radare2/libr/bin/bin.c:762
    #9 0x7fd5a19697e4 in r_bin_load_io /home/z/src/radare2/libr/bin/bin.c:654
    #10 0x7fd5a2844902 in r_core_file_do_load_for_io_plugin /home/z/src/radare2/libr/core/file.c:387
    #11 0x7fd5a284583b in r_core_bin_load /home/z/src/radare2/libr/core/file.c:508
    #12 0x557bcad6937c in main /home/z/src/radare2/binr/radare2/radare2.c:681
    #13 0x7fd59d3d7a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #14 0x557bcad65e18 in _start (/home/z/src/radare2/binr/radare2/radare2+0x5e18)
```

```
r2 -v
radare2 0.10.4-git 11493 @ linux-x86-64 git.0.10.3-77-g24c0dfc
commit: 24c0dfc961234e9e831efdff80ea0eb982d7da8f build: 2016-06-02
```

Sample: `bins/fuzzed/4cabafa790019a8859dcc902e69f8be6`

Greetings: @revskills

**Comment by radare** [comment]
please confirm
