### ISSUE TITLE
ELF fuzzing

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#5138]
```bash
(gdb) r findings_dir/fuzzer03/crashes/id:000001,sig:11,src:000000,op:havoc,rep:16 -A
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/r2 findings_dir/fuzzer03/crashes/id:000001,sig:11,src:000000,op:havoc,rep:16 -A
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: Cannot initialize program headers
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Cannot find NOTE section
LEN = 21845

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3a6c218 in r_hex_bin2strdup (in=<optimized out>, len=<optimized out>) at hex.c:174
174			snprintf (tmp, sizeof (tmp), "%02x", in[i]);
(gdb) bt
#0  0x00007ffff3a6c218 in r_hex_bin2strdup (in=<optimized out>, len=<optimized out>) at hex.c:174
#1  0x00007ffff6c52d9d in load_bytes (arch=<optimized out>, buf=0x55555585acf0 "\177ELF\001\001\001", sz=<optimized out>, loadaddr=93824995465904, sdb=<optimized out>)
    at /opt/radare2/libr/..//libr/bin/p/bin_elf.c:55
#2  0x00007ffff6bed458 in r_bin_object_new (binfile=<optimized out>, plugin=<optimized out>, baseaddr=<optimized out>, loadaddr=<optimized out>, offset=0, sz=3693) at bin.c:984
#3  0x00007ffff6be4bb3 in r_bin_file_new_from_bytes (offset=0, bin=<optimized out>, file=<optimized out>, bytes=<optimized out>, sz=<optimized out>, file_sz=<optimized out>, rawstr=<optimized out>, 
    baseaddr=<optimized out>, loadaddr=<optimized out>, fd=<optimized out>, pluginname=<optimized out>, xtrname=<optimized out>) at bin.c:1129
#4  r_bin_load_io_at_offset_as_sz (bin=<optimized out>, desc=<optimized out>, baseaddr=<optimized out>, loadaddr=0, xtr_idx=<optimized out>, offset=<optimized out>, name=<optimized out>, sz=<optimized out>)
    at bin.c:748
#5  0x00007ffff6be0579 in r_bin_load_io_at_offset_as (bin=0x5555557fc2a0, desc=0x5555558522f0, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0, offset=0, name=<optimized out>) at bin.c:762
#6  r_bin_load_io (bin=0x5555557fc2a0, desc=0x5555558522f0, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0) at bin.c:654
#7  0x00007ffff7a8c741 in r_core_file_do_load_for_io_plugin (r=<optimized out>, baseaddr=<optimized out>, loadaddr=<optimized out>) at file.c:392
#8  r_core_bin_load (r=0x555555762390 <r>, filenameuri=0x555555852260 "findings_dir/fuzzer03/crashes/id:000001,sig:11,src:000000,op:havoc,rep:16", baddr=<optimized out>) at file.c:512
#9  0x000055555555bba9 in main (argc=2, argv=<optimized out>, envp=<optimized out>) at radare2.c:681
(gdb) 
```

[zipped file](https://github.com/radare/radare2/files/316147/id.000001.sig.11.src.000000.op.havoc.rep.16.zip)

**Comment by jvoisin** [comment]
```bash
(gdb) r -A id:000009,sig:11,src:000000,op:havoc,rep:8
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/r2 -A id:000009,sig:11,src:000000,op:havoc,rep:8
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6c6cd10 in Elf32_r_bin_elf_get_relocs (bin=<optimized out>) at /opt/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1781
1781						ret[rel].rva = bin->shdr[g_sections[i].info].sh_offset + ret[rel].offset;
(gdb) bt
#0  0x00007ffff6c6cd10 in Elf32_r_bin_elf_get_relocs (bin=<optimized out>) at /opt/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1781
#1  0x00007ffff6c57838 in relocs (arch=0x5555558523e0) at /opt/radare2/libr/..//libr/bin/p/bin_elf.c:536
#2  0x00007ffff6bee885 in r_bin_object_set_items (binfile=<optimized out>, o=<optimized out>) at bin.c:519
#3  r_bin_object_new (binfile=<optimized out>, plugin=<optimized out>, baseaddr=<optimized out>, loadaddr=<optimized out>, offset=<optimized out>, 
    sz=<optimized out>) at bin.c:1019
#4  0x00007ffff6be4bb3 in r_bin_file_new_from_bytes (offset=0, bin=<optimized out>, file=<optimized out>, bytes=<optimized out>, 
    sz=<optimized out>, file_sz=<optimized out>, rawstr=<optimized out>, baseaddr=<optimized out>, loadaddr=<optimized out>, fd=<optimized out>, 
    pluginname=<optimized out>, xtrname=<optimized out>) at bin.c:1129
#5  r_bin_load_io_at_offset_as_sz (bin=<optimized out>, desc=<optimized out>, baseaddr=<optimized out>, loadaddr=0, xtr_idx=<optimized out>, 
    offset=<optimized out>, name=<optimized out>, sz=<optimized out>) at bin.c:748
#6  0x00007ffff6be0579 in r_bin_load_io_at_offset_as (bin=0x5555557fc2a0, desc=0x555555852270, baseaddr=18446744073709551615, loadaddr=0, 
    xtr_idx=0, offset=0, name=<optimized out>) at bin.c:762
#7  r_bin_load_io (bin=0x5555557fc2a0, desc=0x555555852270, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0) at bin.c:654
#8  0x00007ffff7a8c741 in r_core_file_do_load_for_io_plugin (r=<optimized out>, baseaddr=<optimized out>, loadaddr=<optimized out>) at file.c:392
#9  r_core_bin_load (r=0x555555762390 <r>, filenameuri=0x555555852230 "id:000009,sig:11,src:000000,op:havoc,rep:8", baddr=<optimized out>)
    at file.c:512
#10 0x000055555555bba9 in main (argc=2, argv=<optimized out>, envp=<optimized out>) at radare2.c:681
(gdb) 
```
[zipped file](https://github.com/radare/radare2/files/316160/id.000009.sig.11.src.000000.op.havoc.rep.8.zip)

**Comment by jvoisin** [comment]
This one makes `r2 -AA` hang.

[zipped sample](https://github.com/radare/radare2/files/316186/id.000000.sig.11.src.000000.op.havoc.rep.8.zip)

**Comment by jvoisin** [comment]
```bash
(gdb) r -AA id:000000,sig:11,src:001374,op:havoc,rep:16
Starting program: /usr/bin/r2 -AA id:000000,sig:11,src:001374,op:havoc,rep:16
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: Cannot initialize program headers
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Warning: read (init_offset)
Cannot set bits 64 to 'vax'
Cannot set bits 64 to 'vax'
Cannot set bits 64 to 'vax'
Cannot set bits 64 to 'vax'
Cannot set bits 64 to 'vax'
Cannot set bits 64 to 'vax'
Cannot set bits 64 to 'vax'
Cannot set bits 64 to 'vax'
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] Emulate code to find computed references (aae)
Program received signal SIGSEGV, Segmentation fault.
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:163
163	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:163
#1  0x00007ffff52e5368 in vax_buffer_read_memory (memaddr=<optimized out>, myaddr=0x7fffffffb3cb "", length=<optimized out>, info=<optimized out>) at p/asm_vax.c:28
#2  0x00007ffff52e6302 in fetch_data (info=<optimized out>, addr=<optimized out>) at p/../arch/vax/vax-dis.c:100
#3  print_insn_mode (d=0x7ffff53b0304 "wf", size=4, p0=<optimized out>, addr=65731, info=0x7fffffffb4e0) at p/../arch/vax/vax-dis.c:146
#4  0x00007ffff52e5ebf in print_insn_arg (d=<optimized out>, p0=<optimized out>, addr=65731, info=0x66) at p/../arch/vax/vax-dis.c:286
#5  print_insn_vax (memaddr=<optimized out>, info=<optimized out>) at p/../arch/vax/vax-dis.c:356
#6  0x00007ffff52e524b in disassemble (a=0x5555557d7630, op=0x7fffffffb8f0, buf=0x555555876a20 'C' <repeats 31 times>, "\306\306", <incomplete sequence \306>, len=180) at p/asm_vax.c:89
#7  0x00007ffff5358ad5 in r_asm_disassemble (a=<optimized out>, op=0x7fffffffb8f0, buf=<optimized out>, len=180) at asm.c:357
#8  0x00007ffff7b4e187 in r_core_anal_esil (core=<optimized out>, str=<optimized out>, target=<optimized out>) at anal.c:2890
#9  0x00007ffff7a554c3 in cmd_anal_all (core=<optimized out>, input=<optimized out>) at ./cmd_anal.c:4223
#10 cmd_anal (data=0x5555557603c8 <r>, input=<optimized out>) at ./cmd_anal.c:4423
#11 0x00007ffff7b3673c in r_cmd_call (cmd=<optimized out>, input=<optimized out>) at cmd_api.c:210
#12 0x00007ffff7ab55e2 in r_core_cmd_subst_i (core=<optimized out>, cmd=<optimized out>, colon=<optimized out>) at cmd.c:1800
#13 0x00007ffff7a4e9d4 in r_core_cmd_subst (core=<optimized out>, cmd=<optimized out>) at cmd.c:1245
#14 0x00007ffff7a4bbe9 in r_core_cmd (core=<optimized out>, cstr=<optimized out>, log=<optimized out>) at cmd.c:2245
#15 0x00007ffff7a57845 in r_core_cmd0 (cmd=0x555555e93069 <error: Cannot access memory at address 0x555555e93069>, user=<optimized out>) at cmd.c:2382
#16 cmd_anal_all (core=<optimized out>, input=<optimized out>) at ./cmd_anal.c:4170
#17 cmd_anal (data=<optimized out>, input=<optimized out>) at ./cmd_anal.c:4423
#18 0x00007ffff7b3673c in r_cmd_call (cmd=<optimized out>, input=<optimized out>) at cmd_api.c:210
#19 0x00007ffff7ab3e08 in r_core_cmd_subst_i (core=<optimized out>, cmd=<optimized out>, colon=<optimized out>) at cmd.c:1838
#20 0x00007ffff7a4e9d4 in r_core_cmd_subst (core=<optimized out>, cmd=<optimized out>) at cmd.c:1245
#21 0x00007ffff7a4bbe9 in r_core_cmd (core=<optimized out>, cstr=<optimized out>, log=<optimized out>) at cmd.c:2245
#22 0x000055555555bcc6 in main (argc=2, argv=<optimized out>, envp=<optimized out>) at radare2.c:838
(gdb) ```

[zipped sample](https://github.com/radare/radare2/files/317897/id.000000.sig.11.src.001374.op.havoc.rep.16.zip)

**Comment by radare** [comment]
that's a bug in the GNU VAX disassembler. looking at it

**Comment by radare** [comment]
it also shows a bug in the @oddcoder callconv implementation

**Comment by jvoisin** [comment]
Those samples are making radare2 hang.

[zipped samples](https://github.com/radare/radare2/files/320265/hang.zip)

**Comment by jvoisin** [comment]
This one too.
[hang.zip](https://github.com/radare/radare2/files/320270/hang.zip)

**Comment by jvoisin** [comment]
```bash
(gdb) r findings_dir/fuzzer03/crashes/id:000000,sig:11,src:000000,op:havoc,rep:16
Starting program: /usr/bin/r2 findings_dir/fuzzer03/crashes/id:000000,sig:11,src:000000,op:havoc,rep:16
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: Cannot initialize dynamic strings

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6dc501f in store_versioninfo_gnu_verdef (sz=0, bin=<optimized out>, shdr=<optimized out>)
    at /opt/radare2/libr/..//libr/bin/p/../format/elf/elf.c:559
559		if (bin->shstrtab && link_shdr->sh_name < bin->shstrtab_size) {
(gdb) bt
#0  0x00007ffff6dc501f in store_versioninfo_gnu_verdef (sz=0, bin=<optimized out>, shdr=<optimized out>)
    at /opt/radare2/libr/..//libr/bin/p/../format/elf/elf.c:559
#1  store_versioninfo (bin=<optimized out>) at /opt/radare2/libr/..//libr/bin/p/../format/elf/elf.c:765
#2  elf_init (bin=<optimized out>) at /opt/radare2/libr/..//libr/bin/p/../format/elf/elf.c:852
#3  0x00007ffff6dc8308 in Elf32_r_bin_elf_new_buf (buf=0x555555860620)
    at /opt/radare2/libr/..//libr/bin/p/../format/elf/elf.c:2356
#4  0x00007ffff6da9c9b in load_bytes (arch=<optimized out>, buf=0x555555868880 "\177ELF\001\001\001", 
    sz=2324, loadaddr=<optimized out>, sdb=0x5555558691a0)
    at /opt/radare2/libr/..//libr/bin/p/bin_elf.c:48
#5  0x00007ffff6d623b6 in r_bin_object_new (binfile=<optimized out>, plugin=<optimized out>, 
    baseaddr=<optimized out>, loadaddr=<optimized out>, offset=0, sz=<optimized out>) at bin.c:984
#6  0x00007ffff6d5bfe7 in r_bin_file_new_from_bytes (offset=0, bin=<optimized out>, 
    file=<optimized out>, bytes=<optimized out>, sz=<optimized out>, file_sz=<optimized out>, 
    rawstr=<optimized out>, baseaddr=<optimized out>, loadaddr=<optimized out>, fd=<optimized out>, 
---Type <return> to continue, or q <return> to quit---
    pluginname=<optimized out>, xtrname=<optimized out>) at bin.c:1129
#7  r_bin_load_io_at_offset_as_sz (bin=<optimized out>, desc=<optimized out>, baseaddr=<optimized out>, 
    loadaddr=0, xtr_idx=<optimized out>, offset=<optimized out>, name=<optimized out>, 
    sz=<optimized out>) at bin.c:748
#8  0x00007ffff6d58c1f in r_bin_load_io_at_offset_as (bin=0x55555580a2a0, desc=0x55555585fd90, 
    baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0, offset=0, name=<optimized out>) at bin.c:762
#9  r_bin_load_io (bin=0x55555580a2a0, desc=0x55555585fd90, baseaddr=18446744073709551615, loadaddr=0, 
    xtr_idx=0) at bin.c:654
#10 0x00007ffff7ad9116 in r_core_file_do_load_for_io_plugin (r=<optimized out>, 
    baseaddr=<optimized out>, loadaddr=<optimized out>) at file.c:392
#11 r_core_bin_load (r=0x5555557603c8 <r>, 
    filenameuri=0x55555585fd00 "findings_dir/fuzzer03/crashes/id:000000,sig:11,src:000000,op:havoc,rep:16", baddr=<optimized out>) at file.c:512
#12 0x000055555555ab29 in main (argc=2, argv=<optimized out>, envp=<optimized out>) at radare2.c:681
(gdb) 
```
[zipped sample](https://github.com/radare/radare2/files/320500/id.000000.sig.11.src.000000.op.havoc.rep.16.zip)

**Comment by radare** [comment]
Everything should be fixed again, please confirm and update tests

**Comment by jvoisin** [comment]
This one is taking ages with `r2 -AA`, and also, funny thing, it also takes ages to quit radare2 :)
[zipped sample](https://github.com/radare/radare2/files/325011/id.000001.sig.11.src.000000.op.havoc.rep.8.zip)

**Comment by jvoisin** [comment]
Another `r2 -AA` hang
[zipped.zip](https://github.com/radare/radare2/files/325127/zipped.zip)

**Comment by radare** [comment]
cant reproduce

**Comment by alvarofe** [comment]
Fixed in master

**Comment by jvoisin** [comment]
```nasm
$ r2 -AA id:000013,sig:11,src:001710,op:havoc,rep:32
Warning: Cannot initialize dynamic section
Warning: Too big version info field 5 (16777216)
Warning: read (init_offset)
[Cannot find function 'entry0' at 0x08040010 entry0 (aa)
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[Oops invalid rangen calls (aac)
[x] Analyze function calls (aac)
[0x00000021 esil_eq: invalid parametersences (aae)
0x000001dc esil_eq: invalid parameters
0x0000028c esil_eq: invalid parameters
0x00000375 ESIL infinite loop detected

0x000003b4 ESIL infinite loop detected

0x0000045d ESIL infinite loop detected

0x00000612 ESIL infinite loop detected

0x00000633 esil_eq: invalid parameters
0x00000820 esil_eq: invalid parameters
0x00000848 esil_eq: invalid parameters
0x000008fb ESIL infinite loop detected

0x00000a37 ESIL infinite loop detected

0x00000cfa esil_eq: invalid parameters
0x00000de1 ESIL infinite loop detected

0x00000e02 esil_eq: invalid parameters
0x00000ec0 esil_mem_addeq_n: invalid parameters
0x00000f6f esil_eq: invalid parameters
[x] Emulate code to find computed references (aae)
[Cannot find section boundaries in here
[x] Analyze consecutive function (aat)
[aav: Cannot find section at this address
aav: Cannot find section at this address
[x] Analyze value pointers (aav)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
 -- Print the contents of the current block with the 'p' command
[0x08040010]> 
```

[zipped sample.zip](https://github.com/radare/radare2/files/325808/zipped.sample.zip)

**Comment by Maijin** [comment]
There are tons of opened ESIL issues:
https://github.com/radare/radare2/issues?q=is%3Aopen+is%3Aissue+label%3Aesil
https://github.com/radare/radare2/issues/4952
...

**Comment by jvoisin** [comment]
Ok, so here you go with a crash then ;)

```nasm
(gdb) r -AA id:000000,sig:11,src:001940,op:havoc,rep:4
Starting program: /usr/bin/r2 -AA id:000000,sig:11,src:001940,op:havoc,rep:4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Warning: run r2 with -e io.cache=true to fix relocations in disassembly

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6e8715e in resolve (t=<optimized out>, foo=<optimized out>, bar=<optimized out>) at mangling/swift-sd.c:97
97		if (!t || !foo || !*foo) {
(gdb) bt
#0  0x00007ffff6e8715e in resolve (t=<optimized out>, foo=<optimized out>, bar=<optimized out>) at mangling/swift-sd.c:97
#1  r_bin_demangle_swift (s=<optimized out>, syscmd=<optimized out>) at mangling/swift-sd.c:312
#2  0x00007ffff6d6a6b2 in r_bin_demangle (binfile=0x55555585ff40, def=0x555555844070 "c", str=<optimized out>) at demangle.c:376
#3  0x00007ffff7b2719f in snInit (r=0x5555557603d8 <r>, sym=0x55555588c0b0, sn=<optimized out>, lang=<optimized out>) at bin.c:1191
#4  bin_symbols_internal (r=<optimized out>, mode=<optimized out>, laddr=0, va=<optimized out>, at=<optimized out>, name=<optimized out>, exponly=<optimized out>) at bin.c:1253
#5  0x00007ffff7b20f06 in bin_symbols (laddr=0, r=<optimized out>, mode=<optimized out>, va=<optimized out>, at=<optimized out>, name=<optimized out>) at bin.c:1418
#6  r_core_bin_info (core=<optimized out>, action=<optimized out>, mode=<optimized out>, va=<optimized out>, filter=<optimized out>, chksum=<optimized out>) at bin.c:2159
#7  0x00007ffff7b15350 in r_core_bin_set_env (r=0x5555557603d8 <r>, binfile=0x55555585ff40) at bin.c:107
#8  0x00007ffff7ad89fc in r_core_file_do_load_for_io_plugin (r=<optimized out>, baseaddr=<optimized out>, loadaddr=<optimized out>) at file.c:397
#9  r_core_bin_load (r=0x5555557603d8 <r>, filenameuri=0x55555585fd80 "id:000000,sig:11,src:001940,op:havoc,rep:4", baddr=<optimized out>) at file.c:512
#10 0x000055555555aa0c in main (argc=2, argv=<optimized out>, envp=<optimized out>) at radare2.c:733
(gdb) 

```

[crash.zip](https://github.com/radare/radare2/files/327009/crash.zip)

**Comment by jvoisin** [comment]
I fuzzed r2 over the week-end with `r2 -AA`, it was awfully slow (10 exec/s), but didn't find any crashes, congratz.
