### ISSUE TITLE
r2 crash due to out-of-bounds read in dex_loadcode()

### ISSUE THREAD

**Issue by ekse** [radare/radare2#5187]
Sample: https://drive.google.com/open?id=0B9u4BZE06xNIc0F2SzFIUG9HXzg

```
$ r2 sample.dex
r2 SIGSEGV.PC.7ffff6f3e889.STAC…” terminated by signal SIGSEGV (Address boundary error)
```

__Initial analysis:__

In dex_loadcode() bin_dex.c line 563,  the value of `i` in the header is larger than the number of classes.
```
		for (i = 0; i < bin->header.method_size; i++) {
			//RBinDexMethod *method = &bin->methods[i];
			if (!methods[i]) {
				struct dex_class_t *c = &bin->classes[i];
				char *class_name = dex_class_name (bin, c);

dex_class_name() is called with an invalid value for `c`, the program crashes at line 316.

```c
312	static char *dex_class_name (RBinDexObj *bin, RBinDexClass *c) {
313		int cid, tid;
314		if (!bin || !c || !bin->types)
315			return NULL;
316		cid = c->class_id;
```

Using rr, we can see that the classes buffer is allocated in r_bin_dex_new_buf(), libr/bin/format/dex/dex.c line 55.

```c
	int classes_size = bin->header.class_size * sizeof (struct dex_class_t);
	if (bin->header.class_offset + classes_size >= bin->size) {
		classes_size = bin->size - bin->header.class_offset;
	}
	if (classes_size<0) {
		classes_size = 0;
	}
	bin->header.class_size = classes_size / sizeof (struct dex_class_t);
	bin->classes = (struct dex_class_t *) malloc (classes_size);
```

```
rr) p bin->header.class_size
$30 = 0x1
``` 

Backtrace:
```
#0  0x00007ffff6f4c438 in dex_class_name (bin=0x55555585c4c0, c=0x55555589c010)
    at /home/ekse/git/radare2/libr/..//libr/bin/p/bin_dex.c:316
#1  0x00007ffff6f4cf5b in dex_loadcode (arch=0x55555584bca0, bin=0x55555585c4c0)
    at /home/ekse/git/radare2/libr/..//libr/bin/p/bin_dex.c:567
#2  0x00007ffff6f4d66a in entries (arch=0x55555584bca0) at /home/ekse/git/radare2/libr/..//libr/bin/p/bin_dex.c:779
#3  0x00007ffff6f30b2e in r_bin_object_set_items (binfile=0x55555584bca0, o=0x55555584c230) at bin.c:480
#4  0x00007ffff6f32a40 in r_bin_object_new (binfile=0x55555584bca0, plugin=0x5555557fac90, baseaddr=0xffffffffffffffff, 
    loadaddr=0x0, offset=0x0, sz=0x3dd88) at bin.c:1019
#5  0x00007ffff6f32fed in r_bin_file_new_from_bytes (bin=0x5555557f6070, 
    file=0x55555584baa0 "SIGSEGV.PC.7ffff6f3e889.STACK.106778f28.CODE.1.ADDR.0x5555558a3000.INSTR.mov____(%rax),%ecx.fuzz", bytes=0x7ffff7f16010 "dex\n035", sz=0x3dd88, file_sz=0x3dd88, rawstr=0x0, baseaddr=0xffffffffffffffff, loadaddr=0x0, 
    fd=0x7, pluginname=0x0, xtrname=0x0, offset=0x0) at bin.c:1129
#6  0x00007ffff6f31d64 in r_bin_load_io_at_offset_as_sz (bin=0x5555557f6070, desc=0x55555584bb50, 
    baseaddr=0xffffffffffffffff, loadaddr=0x0, xtr_idx=0x0, offset=0x0, name=0x0, sz=0x3dd88) at bin.c:748
#7  0x00007ffff6f31def in r_bin_load_io_at_offset_as (bin=0x5555557f6070, desc=0x55555584bb50, 
    baseaddr=0xffffffffffffffff, loadaddr=0x0, xtr_idx=0x0, offset=0x0, name=0x0) at bin.c:762
#8  0x00007ffff6f31857 in r_bin_load_io (bin=0x5555557f6070, desc=0x55555584bb50, baseaddr=0xffffffffffffffff, 
    loadaddr=0x0, xtr_idx=0x0) at bin.c:654
#9  0x00007ffff7b27622 in r_core_file_do_load_for_io_plugin (r=0x55555575c500 <r>, baseaddr=0xffffffffffffffff, 
    loadaddr=0x0) at file.c:392
#10 0x00007ffff7b27c5a in r_core_bin_load (r=0x55555575c500 <r>, 
    filenameuri=0x55555584baa0 "SIGSEGV.PC.7ffff6f3e889.STACK.106778f28.CODE.1.ADDR.0x5555558a3000.INSTR.mov____(%rax),%ecx.fuzz", baddr=0xffffffffffffffff) at file.c:512
#11 0x0000555555558f68 in main (argc=0x2, argv=0x7fffffffdc18, envp=0x7fffffffdc30) at radare2.c:733
```

**Comment by radare** [comment]
I can reproduce it, didnt had time to fix it yesterday

**Comment by Maijin** [comment]
Fixed

**Comment by Maijin** [comment]
I put the bin in r2r
