### ISSUE TITLE
Deleted comments reappear on project open and automatic comments not deleted by CC- and 

### ISSUE THREAD

**Issue by Jaguar83** [radare/radare2#5445]
I'm working with a PSX mips file and radare2 keeps marking sections of code as strings. So far, the only way I can disable this is to add "f- ..." and "Cs- ..." commands to my project file. Furthermore, if I type "CC", there is a huge list and typing "CC- @address" does not remove it from this list.

I'm using version 0.10.5-git

**Comment by radare** [comment]
What about CC-0x628633?

**Comment by Jaguar83** [comment]
No, CC- doesn't work with or without a space and/or @.

The main problem is that radare seems to find and mark strings in the every time it starts up, and loading a project is the only way to remove them. After that, saving the project puts all of the strings into the saved project file, meaning they reappear.

**Comment by Jaguar83** [comment]
Here's a trace to demonstrate.
There are no CC commands in the "dc" project and the section definitions are:
```
S 0x00000800 0x80010000 0x00003e4c 0x00003e4c DATA mrw-
S 0x0000464c 0x80013e4c 0x00056a48 0x00056a48 TEXT m--x
S 0x0005b094 0x8006a894 0x0000d76c 0x0000d76c DATA1 mrw-
```

And yet, the section comment "_[0] va=0x80010000 pa=0x00000800 sz=425984 vsz=425984 rwx=m---x TEXT_" reappears whenever the project is loaded. See the attachment.

[CC issue.txt](https://github.com/radare/radare2/files/407923/CC.issue.txt)

**Comment by Jaguar83** [comment]
I've used gdb to trace the issue, and it appears to be here:

#0  r_meta_add (a=0x7fbef9d24a70, type=115, from=2147549184, to=2147549191, str=0x7fbef9f036c0 ".DRV;1") at meta.c:249
#1  0x00007fbef814c84b in bin_strings (r=0x7fbef8809640 <r>, mode=2, va=1) at bin.c:336
#2  0x00007fbef8154400 in r_core_bin_info (core=0x7fbef8809640 <r>, action=20479, mode=2, va=1, filter=0x0, chksum=0x0) at bin.c:2183
#3  0x00007fbef814bbfc in r_core_bin_set_env (r=0x7fbef8809640 <r>, binfile=0x7fbefa1e0270) at bin.c:107
#4  0x00007fbef812997e in r_core_file_do_load_for_io_plugin (r=0x7fbef8809640 <r>, baseaddr=18446744073709551615, loadaddr=0) at file.c:397
#5  0x00007fbef8129f45 in r_core_bin_load (r=0x7fbef8809640 <r>, filenameuri=0x7fbef9f27830 "/mnt/disk/slus_013.28", baddr=18446744073709551615) at file.c:512
#6  0x00007fbef816958a in r_core_project_open (core=0x7fbef8809640 <r>, prjfile=0x7fbefa186303 "dc") at project.c:224
#7  0x00007fbef80df2b9 in cmd_project (data=0x7fbef8809640 <r>, input=0x7fbefa186301 "o dc") at cmd_project.c:27
#8  0x00007fbef815c0cd in r_cmd_call (cmd=0x7fbef9d56720, input=0x7fbefa186300 "Po dc") at cmd_api.c:210
#9  0x00007fbef8125e54 in r_core_cmd_subst_i (core=0x7fbef8809640 <r>, cmd=0x7fbefa186300 "Po dc", colon=0x0) at cmd.c:1853
#10 0x00007fbef81237e2 in r_core_cmd_subst (core=0x7fbef8809640 <r>, cmd=0x7fbefa186300 "Po dc") at cmd.c:1249
#11 0x00007fbef812756c in r_core_cmd (core=0x7fbef8809640 <r>, cstr=0x7fbef9f80b00 "Po dc", log=1) at cmd.c:2260
#12 0x00007fbef80c8a63 in r_core_prompt_exec (r=0x7fbef8809640 <r>) at core.c:1626
#13 0x00007fbef8606fbe in main (argc=5, argv=0x7fff3dc58c28, envp=0x7fff3dc58c58) at radare2.c:943

In /usr/src/radare2/libr/core/project.c:r_core_project_open, the sequence is as follows:

```
		r_core_bin_load (core, filepath, UT64_MAX);
	}
	// FIXME: If r_anal_project_load is not called before r_core_cmd_file, xrefs are not loaded correctly
	r_anal_project_load (core->anal, prjfile);
	ret = r_core_cmd_file (core, prj);

```
From the trace it appears that r_core_bin_info (called from `r_core_bin_load`) is filling in all of the extra data BEFORE the project script is executed. This means that there is no way to stop it from happening by putting commands in the project script.

With a further trace, it appears that r_core_bin_set_env (which calls r_core_bin_info), is run 4 times.
From r_core_file_do_load_for_io_plugin, r_core_bin_set_arch_bits (within r_core_file_do_load_for_io_plugin), r_core_bin_load, r_core_bin_set_arch_bits (within r_core_bin_load).

**Comment by radare** [comment]
a string data type is not a comment
