### ISSUE TITLE
Fuzzing elf, once again :)

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#5485]
```C
(gdb) r -AA id:000004,sig:11,src:003295+016016,op:splice,rep:4
Starting program: /usr/bin/r2 -AA id:000004,sig:11,src:003295+016016,op:splice,rep:4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: Cannot initialize program headers
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Warning: read (init_offset)
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] Emulate code to find computed references (aae)
Program received signal SIGSEGV, Segmentation fault.
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:163
163	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:163
#1  0x00007ffff52a4478 in vax_buffer_read_memory (memaddr=<optimized out>, myaddr=0x7fffffffb48c "", length=<optimized out>, info=<optimized out>) at p/asm_vax.c:28
#2  0x00007ffff52a5412 in fetch_data (info=<optimized out>, addr=<optimized out>) at p/../arch/vax/vax-dis.c:100
#3  print_insn_mode (d=0x7ffff536d1df "rwab", size=2, p0=<optimized out>, addr=65682, info=0x7fffffffb5a0) at p/../arch/vax/vax-dis.c:146
#4  0x00007ffff52a4fcf in print_insn_arg (d=<optimized out>, p0=<optimized out>, addr=65682, info=0x77) at p/../arch/vax/vax-dis.c:286
#5  print_insn_vax (memaddr=<optimized out>, info=<optimized out>) at p/../arch/vax/vax-dis.c:356
#6  0x00007ffff52a435b in disassemble (a=0x5555557d8750, op=0x7fffffffb9a0, buf=0x55555587a54e "!", len=52) at p/asm_vax.c:89
#7  0x00007ffff5315695 in r_asm_disassemble (a=<optimized out>, op=0x7fffffffb9a0, buf=<optimized out>, len=52) at asm.c:359
#8  0x00007ffff7b497f6 in r_core_anal_esil (core=<optimized out>, str=<optimized out>, target=<optimized out>) at anal.c:2957
#9  0x00007ffff7a4250c in cmd_anal_all (core=<optimized out>, input=<optimized out>) at ./cmd_anal.c:4402
#10 cmd_anal (data=0x5555557613d8 <r>, input=<optimized out>) at ./cmd_anal.c:4603
#11 0x00007ffff7b31b7c in r_cmd_call (cmd=<optimized out>, input=<optimized out>) at cmd_api.c:210
#12 0x00007ffff7aa6412 in r_core_cmd_subst_i (core=<optimized out>, cmd=<optimized out>, colon=<optimized out>) at cmd.c:1812
#13 0x00007ffff7a3b4b4 in r_core_cmd_subst (core=<optimized out>, cmd=<optimized out>) at cmd.c:1249
#14 0x00007ffff7a386c9 in r_core_cmd (core=<optimized out>, cstr=<optimized out>, log=<optimized out>) at cmd.c:2260
#15 0x00007ffff7a44999 in r_core_cmd0 (cmd=0x5555c8fa1893 <error: Cannot access memory at address 0x5555c8fa1893>, user=<optimized out>) at cmd.c:2397
#16 cmd_anal_all (core=<optimized out>, input=<optimized out>) at ./cmd_anal.c:4349
#17 cmd_anal (data=<optimized out>, input=<optimized out>) at ./cmd_anal.c:4603
#18 0x00007ffff7b31b7c in r_cmd_call (cmd=<optimized out>, input=<optimized out>) at cmd_api.c:210
#19 0x00007ffff7aa47ee in r_core_cmd_subst_i (core=<optimized out>, cmd=<optimized out>, colon=<optimized out>) at cmd.c:1853
#20 0x00007ffff7a3b4b4 in r_core_cmd_subst (core=<optimized out>, cmd=<optimized out>) at cmd.c:1249
#21 0x00007ffff7a386c9 in r_core_cmd (core=<optimized out>, cstr=<optimized out>, log=<optimized out>) at cmd.c:2260
#22 0x000055555555c1a5 in main (argc=2, argv=<optimized out>, envp=<optimized out>) at radare2.c:891
(gdb) 
```

[id:000004,sig:11,src:003295+016016,op:splice,rep:4.zip](https://github.com/radare/radare2/files/415272/id.000004.sig.11.src.003295.016016.op.splice.rep.4.zip)

**Comment by jvoisin** [comment]
```C
(gdb) r -AA  id:000008,sig:11,src:003828+020487,op:splice,rep:32
Starting program: /usr/bin/r2 -AA  id:000008,sig:11,src:003828+020487,op:splice,rep:32
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: Cannot initialize program headers
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Warning: read (init_offset)
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] Emulate code to find computed references (aae)
Program received signal SIGSEGV, Segmentation fault.
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:163
163	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:163
#1  0x00007ffff52a4478 in vax_buffer_read_memory (memaddr=<optimized out>, myaddr=0x7fffffffb48b "", length=<optimized out>, info=<optimized out>) at p/asm_vax.c:28
#2  0x00007ffff52a5412 in fetch_data (info=<optimized out>, addr=<optimized out>) at p/../arch/vax/vax-dis.c:100
#3  print_insn_mode (d=0x7ffff536d1df "rwab", size=2, p0=<optimized out>, addr=65623, info=0x7fffffffb5a0) at p/../arch/vax/vax-dis.c:146
#4  0x00007ffff52a4fcf in print_insn_arg (d=<optimized out>, p0=<optimized out>, addr=65623, info=0x77) at p/../arch/vax/vax-dis.c:286
#5  print_insn_vax (memaddr=<optimized out>, info=<optimized out>) at p/../arch/vax/vax-dis.c:356
#6  0x00007ffff52a435b in disassemble (a=0x5555557d8770, op=0x7fffffffb9a0, buf=0x555555879f74 "\"\367\367", 'C' <repeats 27 times>, "\367\367\367\367\367\377\377\377\377\377\377\017\377\036", len=76)
    at p/asm_vax.c:89
#7  0x00007ffff5315695 in r_asm_disassemble (a=<optimized out>, op=0x7fffffffb9a0, buf=<optimized out>, len=76) at asm.c:359
#8  0x00007ffff7b497f6 in r_core_anal_esil (core=<optimized out>, str=<optimized out>, target=<optimized out>) at anal.c:2957
#9  0x00007ffff7a4250c in cmd_anal_all (core=<optimized out>, input=<optimized out>) at ./cmd_anal.c:4402
#10 cmd_anal (data=0x5555557613d8 <r>, input=<optimized out>) at ./cmd_anal.c:4603
#11 0x00007ffff7b31b7c in r_cmd_call (cmd=<optimized out>, input=<optimized out>) at cmd_api.c:210
#12 0x00007ffff7aa6412 in r_core_cmd_subst_i (core=<optimized out>, cmd=<optimized out>, colon=<optimized out>) at cmd.c:1812
#13 0x00007ffff7a3b4b4 in r_core_cmd_subst (core=<optimized out>, cmd=<optimized out>) at cmd.c:1249
#14 0x00007ffff7a386c9 in r_core_cmd (core=<optimized out>, cstr=<optimized out>, log=<optimized out>) at cmd.c:2260
#15 0x00007ffff7a44999 in r_core_cmd0 (cmd=0x5555567e975a <error: Cannot access memory at address 0x5555567e975a>, user=<optimized out>) at cmd.c:2397
#16 cmd_anal_all (core=<optimized out>, input=<optimized out>) at ./cmd_anal.c:4349
#17 cmd_anal (data=<optimized out>, input=<optimized out>) at ./cmd_anal.c:4603
#18 0x00007ffff7b31b7c in r_cmd_call (cmd=<optimized out>, input=<optimized out>) at cmd_api.c:210
#19 0x00007ffff7aa47ee in r_core_cmd_subst_i (core=<optimized out>, cmd=<optimized out>, colon=<optimized out>) at cmd.c:1853
#20 0x00007ffff7a3b4b4 in r_core_cmd_subst (core=<optimized out>, cmd=<optimized out>) at cmd.c:1249
#21 0x00007ffff7a386c9 in r_core_cmd (core=<optimized out>, cstr=<optimized out>, log=<optimized out>) at cmd.c:2260
#22 0x000055555555c1a5 in main (argc=2, argv=<optimized out>, envp=<optimized out>) at radare2.c:891
```

[id:000008,sig:11,src:003828+020487,op:splice,rep:32.zip](https://github.com/radare/radare2/files/415282/id.000008.sig.11.src.003828.020487.op.splice.rep.32.zip)

**Comment by XVilka** [comment]
@jvoisin when you push those files to regression-tests, please remove ':' and ',' characters from the name, it really troubles Windows systems, lol.

**Comment by radare** [comment]
this is a problem in the vax disassembler

**Comment by radare** [comment]
i fixed it in master
