### ISSUE TITLE
The ownership of RBinObject is unclear

### ISSUE THREAD

**Issue by dequis** [radare/radare2#5517]
`r_bin_object_free` currently doesn't free the object itself because otherwise it would be freed twice sometimes.

The function that calls it doesn't own it (even though it receives the newly created object, this should be documented), instead it seems to be added to the RBinFile->objs linked list and also the RBinFile->o attribute.

```
Breakpoint 1, r_bin_object_new (binfile=0x55fe297991f0, plugin=0x55fe29748070, baseaddr=18446744073709551615, loadaddr=0, offset=0, sz=126552) at bin.c:971
971             const ut8 *bytes = binfile? r_buf_buffer (binfile->buf): NULL;
(rr) bt
#0  r_bin_object_new (binfile=0x55fe297991f0, plugin=0x55fe29748070, baseaddr=18446744073709551615, loadaddr=0, offset=0, sz=126552) at bin.c:971
#1  0x00007fad26a8ec6c in r_bin_file_new_from_bytes (bin=0x55fe29742e30, file=0x55fe29799b30 "/bin/ls", bytes=0x55fe2979f630 "\177ELF\002\001\001", sz=126552, file_sz=126552, rawstr=0, baseaddr=18446744073709551615, loadaddr=0, fd=7,
    pluginname=0x0, xtrname=0x0, offset=0) at bin.c:1165
#2  0x00007fad26a8d76c in r_bin_load_io_at_offset_as_sz (bin=0x55fe29742e30, desc=0x55fe29799b90, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0, offset=0, name=0x0, sz=126552) at bin.c:758
#3  0x00007fad26a8d807 in r_bin_load_io_at_offset_as (bin=0x55fe29742e30, desc=0x55fe29799b90, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0, offset=0, name=0x0) at bin.c:772
#4  0x00007fad26a8d251 in r_bin_load_io (bin=0x55fe29742e30, desc=0x55fe29799b90, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0) at bin.c:664
#5  0x00007fad2769f6d4 in r_core_file_do_load_for_io_plugin (r=0x55fe2916e500 <r>, baseaddr=18446744073709551615, loadaddr=0) at file.c:392
#6  0x00007fad2769fd3c in r_core_bin_load (r=0x55fe2916e500 <r>, filenameuri=0x55fe29799b30 "/bin/ls", baddr=18446744073709551615) at file.c:512
#7  0x000055fe28f6afeb in main (argc=4, argv=0x7ffc554aef88, envp=0x7ffc554aefb0) at radare2.c:734
(rr) n
972             ut64 bytes_sz = binfile? r_buf_size (binfile->buf): 0;
(rr)
973             Sdb *sdb = binfile? binfile->sdb: NULL;
(rr)
974             RBinObject *o = R_NEW0 (RBinObject);
(rr) p o
$8 = (RBinObject *) 0x55fe29799880
(rr) c
Continuing.
```

The first free (when freeing the objs list of RBinFile)

```
Breakpoint 2, r_bin_object_free (o_=0x55fe297e2d10) at bin.c:441
441             RBinObject *o = o_;
(rr) bt
#0  r_bin_object_free (o_=0x55fe297e2d10) at bin.c:441
#1  0x00007fad240e4d2f in r_list_delete (list=0x55fe297998e0, iter=0x55fe29836a50) at list.c:98
#2  0x00007fad240e4bc7 in r_list_purge (list=0x55fe297998e0) at list.c:67
#3  0x00007fad240e4c24 in r_list_free (list=0x55fe297998e0) at list.c:77
#4  0x00007fad26a8db1b in r_bin_file_free (bf_=0x55fe297991f0) at bin.c:844
#5  0x00007fad240e4d2f in r_list_delete (list=0x55fe297430b0, iter=0x55fe297997f0) at list.c:98
#6  0x00007fad240e4bc7 in r_list_purge (list=0x55fe297430b0) at list.c:67
#7  0x00007fad240e4c24 in r_list_free (list=0x55fe297430b0) at list.c:77
#8  0x00007fad26a8ef5a in r_bin_free (bin=0x55fe29742e30) at bin.c:1226
#9  0x00007fad27633cf0 in r_core_fini (c=0x55fe2916e500 <r>) at core.c:1465
#10 0x000055fe28f6c01b in main (argc=4, argv=0x7ffc554aef88, envp=0x7ffc554aefb0) at radare2.c:1027
(rr) frame 4
#4  0x00007fad26a8db1b in r_bin_file_free (bf_=0x55fe297991f0) at bin.c:844
844             r_list_free (a->objs);
(rr) c
Continuing.
```

The second free (when freeing the o attribute of RBinFile)

```
Breakpoint 2, r_bin_object_free (o_=0x55fe297e2d10) at bin.c:441
441             RBinObject *o = o_;
(rr) bt
#0  r_bin_object_free (o_=0x55fe297e2d10) at bin.c:441
#1  0x00007fad26a8db3b in r_bin_file_free (bf_=0x55fe297991f0) at bin.c:846
#2  0x00007fad240e4d2f in r_list_delete (list=0x55fe297430b0, iter=0x55fe297997f0) at list.c:98
#3  0x00007fad240e4bc7 in r_list_purge (list=0x55fe297430b0) at list.c:67
#4  0x00007fad240e4c24 in r_list_free (list=0x55fe297430b0) at list.c:77
#5  0x00007fad26a8ef5a in r_bin_free (bin=0x55fe29742e30) at bin.c:1226
#6  0x00007fad27633cf0 in r_core_fini (c=0x55fe2916e500 <r>) at core.c:1465
#7  0x000055fe28f6c01b in main (argc=4, argv=0x7ffc554aef88, envp=0x7ffc554aefb0) at radare2.c:1027
(rr) up
#1  0x00007fad26a8db3b in r_bin_file_free (bf_=0x55fe297991f0) at bin.c:846
846             r_bin_object_free (a->o);
```

`binfile->o` is set by `r_bin_file_set_cur_binfile_obj`, which is called by `r_bin_file_object_add`, the same function that adds it to `binfile->objs`

```
(rr) frame
#0  0x00007fad26a91fcc in r_bin_file_set_cur_binfile_obj (bin=0x55fe29742e30, bf=0x55fe297991f0, obj=0x55fe297e2d10) at bin.c:2080
2080            bf->o = obj;
(rr) up
#1  0x00007fad26a8dbc6 in r_bin_file_object_add (binfile=0x55fe297991f0, o=0x55fe297e2d10) at bin.c:854
854             r_bin_file_set_cur_binfile_obj (binfile->rbin, binfile, o);
(rr) l
849     }
850
851     static int r_bin_file_object_add(RBinFile *binfile, RBinObject *o) {
852             if (!o) return false;
853             r_list_append (binfile->objs, o);
854             r_bin_file_set_cur_binfile_obj (binfile->rbin, binfile, o);
855             return true;
856     }
857
858     static RBinFile *r_bin_file_create_append(RBin *bin, const char *file, const ut8 *bytes, ut64 sz, ut64 file_sz, int rawstr, int fd, const char *xtrname) {
```

Judging by this, `binfile->o` should be considered an alias of one of the items of the list, and shouldn't be freed. So maybe drop that free, make `r_bin_object_free` free itself, and everything is ok? Or would that blow up elsewhere?

**Comment by radare** [comment]
I think this is something that came after the last refactor of that code to speedup rabin-x of dyldcaches

**Comment by radare** [comment]
i dont think this is an issue still
