### ISSUE TITLE
having phun on -p

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#5708]
morrn,

```r2 -p "`bash genchars 8192 %%f`"  /bin/ls```
then hit q

```
Core was generated by `r2 -p %f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f57f93099c3 in _IO_vfprintf_internal (s=<optimized out>, format=<optimized out>, ap=<optimized out>) at vfprintf.c:1641
1641    vfprintf.c: No such file or directory.
(gdb) bt
#0  0x00007f57f93099c3 in _IO_vfprintf_internal (s=<optimized out>, format=<optimized out>, ap=<optimized out>) at vfprintf.c:1641
#1  0x00007f57f930a121 in buffered_vfprintf (s=0x7f57f9680640 <_IO_2_1_stderr_>, format=<optimized out>, args=<optimized out>) at vfprintf.c:2348
#2  0x00007f57f9304d95 in _IO_vfprintf_internal (s=0x7f57f9680640 <_IO_2_1_stderr_>, 
    format=0x55598968c2d0 "Do you want to save the '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%"..., ap=0x7ffe908af920) at vfprintf.c:1296
#3  0x00007f57fcae1fb0 in r_cons_yesno (def=121, 
    fmt=0x55598968c2d0 "Do you want to save the '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%"...) at input.c:466
#4  0x0000555988f8f1f9 in main (argc=4, argv=0x7ffe908b00e8, envp=0x7ffe908b0110) at radare2.c:1015


```

,r2 -v
radare2 0.10.6-git 12310 @ linux-x86-64 git.0.10.5-179-gd250d21
commit: d250d21385c608a46ce7e09670ce46c0ae85f4db build: 2016-09-06

**Comment by radare** [comment]
nice catch, fixed in 618ac8ad03b0239c0fa2358597d8a16dd0cec0c5
