### ISSUE TITLE
lulzfuzz: avb faulting 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#5766]
```
 Core was generated by `r2 -e asm.arch=arm -e asm.bits=32 -qn -'.
Program terminated with signal SIGSEGV, Segmentation fault.
 #0  0x00007f98f85f36d8 in r_anal_virtual_functions (core=0x560f232015c0 <r>, input=0x560f239affb2 "b  %1269168516 %1073741824\\n") at cmd_anal.c:4645
 4645            const char *curArch = ((RCore *)core)->bin->cur->o->info->arch;
 (gdb) bt
 #0  0x00007f98f85f36d8 in r_anal_virtual_functions (core=0x560f232015c0 <r>, input=0x560f239affb2 "b  %1269168516 %1073741824\\n") at cmd_anal.c:4645
 #1  0x00007f98f85f3d54 in cmd_anal (data=0x560f232015c0 <r>, input=0x560f239affb1 "vb  %1269168516 %1073741824\\n") at cmd_anal.c:4770
 #2  0x00007f98f865dbe2 in r_cmd_call (cmd=0x560f2396cc70, input=0x560f239affb0 "avb  %1269168516 %1073741824\\n") at cmd_api.c:210
 #3  0x00007f98f8626189 in r_core_cmd_subst_i (core=0x560f232015c0 <r>, cmd=0x560f239affb0 "avb  %1269168516 %1073741824\\n", colon=0x0) at cmd.c:1863
 #4  0x00007f98f8623aff in r_core_cmd_subst (core=0x560f232015c0 <r>, cmd=0x560f239affb0 "avb  %1269168516 %1073741824\\n") at cmd.c:1255
 #5  0x00007f98f8627cff in r_core_cmd (core=0x560f232015c0 <r>, cstr=0x560f2399a540 "avb  %1269168516 %1073741824\\n", log=1) at cmd.c:2337
 #6  0x00007f98f85bab70 in r_core_prompt_exec (r=0x560f232015c0 <r>) at core.c:1651
 #7  0x0000560f22ffef69 in main (argc=7, argv=0x7ffcae6a40e8, envp=0x7ffcae6a4128) at radare2.c:989
 (gdb) l
 4640            }
 4641            return true;
 4642    }
 4643
 4644    static void r_anal_virtual_functions(void *core, const char* input) {
 4645            const char *curArch = ((RCore *)core)->bin->cur->o->info->arch;
 4646            if (!strcmp (curArch, "x86")) {
 4647                    const char * help_msg[] = {
 4648                            "Usage:", "av ", "analyze the .rodata section and list virtual function present",
 4649                            NULL};
 (gdb) i r
 rax            0x0      0
 rbx            0x0      0
 rcx            0x7f98f4727351   140294912897873
 rdx            0x560f239affb2   94623021858738
 rsi            0x560f239affb2   94623021858738
 rdi            0x560f232015c0   94623013803456
 rbp            0x7ffcae6a2ec0   0x7ffcae6a2ec0
 rsp            0x7ffcae6a2e70   0x7ffcae6a2e70
 r8             0x7ffcae6a2e00   140723234680320
 r9             0x7ffcae6a2c10   140723234679824
 r10            0x8      8
 r11            0x206    518
 r12            0x560f22ffc160   94623011684704
 r13            0x7ffcae6a40e0   140723234685152
 r14            0x0      0
 r15            0x0      0
 rip            0x7f98f85f36d8   0x7f98f85f36d8 <r_anal_virtual_functions+42>
 eflags         0x10246  [ PF ZF IF RF ]
 cs             0x33     51
 ss             0x2b     43
 ds             0x0      0
 es             0x0      0
 fs             0x0      0
 gs             0x0      0
 (gdb) 
 ```
 r2 -v:
 bc16525860b6efc7f42775d74b727cbff5f6fb05
 
 Greetings
 --zlul
 
 Greetings to c-base; I had my ordinateur missing :p

**Comment by zonkzonk** [comment]
meh

**Comment by radare** [comment]
avb is not a command. the command is av. this is clearly a null deref.
