### ISSUE TITLE
aggi coredump

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#6209]
```
Wed Nov 16 23:27:23 CET 2016
Reading symbols from r2...done.

warning: core file may not match specified executable file.
[New LWP 1035]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `r2 /bin/ls'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc65365df34 in get_bbnodes (g=0x56164fadf7e0, core=0x56164dc83640 <r>, fcn=0x0) at graph.c:1690
1690            r_list_sort (fcn->bbs, (RListComparator)bbcmp);
(gdb) bt
#0  0x00007fc65365df34 in get_bbnodes (g=0x56164fadf7e0, core=0x56164dc83640 <r>, fcn=0x0) at graph.c:1690
#1  0x00007fc65365e57f in reload_nodes (g=0x56164fadf7e0, core=0x56164dc83640 <r>, fcn=0x0) at graph.c:1819
#2  0x00007fc65365f67e in agraph_reload_nodes (g=0x56164fadf7e0, core=0x56164dc83640 <r>, fcn=0x0) at graph.c:2140
#3  0x00007fc65365fa29 in check_changes (g=0x56164fadf7e0, is_interactive=1, core=0x56164dc83640 <r>, fcn=0x0) at graph.c:2191
#4  0x00007fc65365fd21 in agraph_print (g=0x56164fadf7e0, is_interactive=1, core=0x56164dc83640 <r>, fcn=0x0) at graph.c:2239
#5  0x00007fc653660120 in agraph_refresh (grd=0x56164fa96070) at graph.c:2320
#6  0x00007fc6536618e7 in r_core_visual_graph (core=0x56164dc83640 <r>, g=0x56164fadf7e0, _fcn=0x0, is_interactive=1) at graph.c:2706
#7  0x00007fc653604d88 in cmd_agraph_print (core=0x56164dc83640 <r>, input=0x56164fca4e33 "i") at cmd_anal.c:4110
#8  0x00007fc65360505a in cmd_anal_graph (core=0x56164dc83640 <r>, input=0x56164fca4e32 "gi") at cmd_anal.c:4177
#9  0x00007fc653608054 in cmd_anal (data=0x56164dc83640 <r>, input=0x56164fca4e31 "ggi") at cmd_anal.c:5002
#10 0x00007fc653675aac in r_cmd_call (cmd=0x56164fae5a80, input=0x56164fca4e30 "aggi") at cmd_api.c:213
#11 0x00007fc65363c45a in r_core_cmd_subst_i (core=0x56164dc83640 <r>, cmd=0x56164fca4e30 "aggi", colon=0x0) at cmd.c:1992
#12 0x00007fc653639bca in r_core_cmd_subst (core=0x56164dc83640 <r>, cmd=0x56164fca4e30 "aggi") at cmd.c:1318
#13 0x00007fc65363e299 in r_core_cmd (core=0x56164dc83640 <r>, cstr=0x56164fc92fc0 "aggi", log=1) at cmd.c:2530
#14 0x00007fc6535cccd6 in r_core_prompt_exec (r=0x56164dc83640 <r>) at core.c:1776
#15 0x000056164da81134 in main (argc=2, argv=0x7fff8eade4a8, envp=0x7fff8eade4c0) at radare2.c:1031
(gdb) 
```

**Comment by VisualPrankDude** [comment]
hit aggi, then hit a and then random keys

**Comment by VisualPrankDude** [comment]
```
(gdb) list 
1685            core->keep_asmqjmps = false;
1686
1687            if (emu) {
1688                    saved_arena = r_reg_arena_peek (core->anal->reg);
1689            }
1690            r_list_sort (fcn->bbs, (RListComparator)bbcmp);
1691
1692            core->keep_asmqjmps = false;
1693            r_list_foreach (fcn->bbs, iter, bb) {
1694                    RANode *node;
```

**Comment by radare** [comment]
confirmed
