### ISSUE TITLE
Out of bounds read in in r_bin_dwarf_parse_attr_value()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#6273]
**Out of bounds read in in r_bin_dwarf_parse_attr_value()**

Tested on Git HEAD: 5463ce49342067005d38dd0ecefe144c0b74623e

Payload (bins/fuzzed/r2_oobr_r_bin_dwarf_parse_attr_value) in https://github.com/radare/radare2-regressions/pull/639

To reproduce: `r2 -A r2_oobr_r_bin_dwarf_parse_attr_value 2>&1 | asan_symbolize-3.8`

ASAN Output:

```
==22523==ERROR: AddressSanitizer: SEGV on unknown address 0x61f084a0f69a (pc 0x7f49f82fbe11 bp 0x7ffc585b6b80 sp 0x7ffc585b6b20 T0)
==22523==The signal is caused by a READ memory access.
==22523==WARNING: failed to fork (errno 12)
==22523==WARNING: failed to fork (errno 12)
==22523==WARNING: failed to fork (errno 12)
==22523==WARNING: failed to fork (errno 12)
==22523==WARNING: failed to fork (errno 12)
==22523==WARNING: Failed to use and restart external symbolizer!
    #0 0x7f49f82fbe10 in r_bin_dwarf_parse_attr_value XYZ/radare2/libr/bin/dwarf.c:1184:26
    #1 0x7f49f82f8ac7 in r_bin_dwarf_parse_comp_unit XYZ/radare2/libr/bin/dwarf.c:1290:10
    #2 0x7f49f82f818c in r_bin_dwarf_parse_info_raw XYZ/radare2/libr/bin/dwarf.c:1354:9
    #3 0x7f49f82f92ae in r_bin_dwarf_parse_info XYZ/radare2/libr/bin/dwarf.c:1480:9
    #4 0x7f49f925cf1f in bin_dwarf XYZ/radare2/libr/core/cbin.c:737:4
    #5 0x7f49f925a07a in r_core_bin_info XYZ/radare2/libr/core/cbin.c:2558:46
    #6 0x7f49f9259e7d in r_core_bin_set_env XYZ/radare2/libr/core/cbin.c:107:3
    #7 0x7f49f9220915 in r_core_file_do_load_for_io_plugin XYZ/radare2/libr/core/file.c:407:2
    #8 0x7f49f921ebbf in r_core_bin_load XYZ/radare2/libr/core/file.c:521:4
    #9 0x562806083fe9 in main XYZ/radare2/binr/radare2/radare2.c:818:14
    #10 0x7f49f2b4a82f in __libc_start_main ??:0:0
    #11 0x562805fb6e58 in _start ??:0:0

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/local/lib/libr_bin.so+0xc5e10)
==22523==ABORTING
```

**Comment by alvarofe** [comment]
should be fixed in master now.
