### ISSUE TITLE
rarun2 config omitting `program=...` causes SEGFAULT

### ISSUE THREAD

**Issue by TobalJackson** [radare/radare2#6298]
Hello,

I'm running `r2 -R <config>.rr2 -d <program>` in order to specify the output terminal that the program should tie its STDIN/OUT to using the config:

```bash
-> % cat fork1.rr2
#!/usr/bin/rarun2
stdio=/dev/pts/17
bits=32
```
and running r2 with the command:

```bash
r2 -R fork1.rr2 -d fork1
```

which produces a segfault:

```bash
tobaljackson@b14ckb0x [02:45:10 PM] [~/programming/c/forking] 
-> % r2 -R fork1.rr2 -d fork1 2>error2.log
tobaljackson@b14ckb0x [02:45:25 PM] [~/programming/c/forking] 
-> % cat error2.log 
ASAN:DEADLYSIGNAL
=================================================================
==5233==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fc917850446 bp 0x7ffe7adda700 sp 0x7ffe7add9e88 T0)
    #0 0x7fc917850445 in strlen (/usr/lib/libc.so.6+0x80445)
    #1 0x7fc91d07c04e in __interceptor_strdup /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_interceptors.cc:556
    #2 0x561fc35027ee in main /home/tobaljackson/AUR/radare2/radare2.main/binr/radare2/radare2.c:606
    #3 0x7fc9177f0290 in __libc_start_main (/usr/lib/libc.so.6+0x20290)
    #4 0x561fc3500079 in _start (/home/tobaljackson/AUR/radare2/radare2.main/binr/radare2/radare2+0x6079)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/libc.so.6+0x80445) in strlen
==5233==ABORTING
```

adding in the line `program=fork1` to fork1.rr2 will alleviate this issue, but seems redundant to specify the program in the rr2 config as well as on `-d` option, but I could be thinking about this wrong:

```bash
-> % cat fork1.rr2 
#!/usr/bin/rarun2
program=fork1
stdio=/dev/pts/17
bits=32
tobaljackson@b14ckb0x [02:55:29 PM] [~/programming/c/forking]
-> % r2 -R fork1.rr2 -d fork1 
Process with PID 5528 started...
= attach 5528 5528
bin.baddr 0x08048000
USING 8048000
Assuming filepath /home/tobaljackson/programming/c/forking/fork1
asm.bits 32
 -- It's not a bug, it's a work in progress
[0xf771eba0]> 
```

**Comment by TobalJackson** [comment]
forgot to add my r2 version:
-> % r2 -v
radare2 1.1.0-git 13166 @ linux-x86-64 git.1.0.2-221-g07819e2
commit: 07819e2f3659af4b43f21df58428eca392190a30 build: 2016-12-09

**Comment by radare** [comment]
You missed the program= directive
