### ISSUE TITLE
SIGSEGV when using command aaaa on AVR binary

### ISSUE THREAD

**Issue by ImanolBarba** [radare/radare2#6307]
I recently updated my r2 version and a certain AVR binary I was analyzing makes r2 segfault (which it didn't before) when I run aaaa or invoke r2 with `-AA` flag.

I first analyzed the binary successfully on Tuesday December 6th and I updated r2 today (December 10th) around 1 AM, something in between should be the cause.

It doesn't consistently happen with all AVR binaries, I tried with an AVR ELF executable and it doesn't crash, but this one (which I believe it's a flash dump) crashes

The binary is the "Jumpy" challenge from riscure (attached)
[binary.zip](https://github.com/radare/radare2/files/643757/binary.zip)

NOTE: r2 has to be invoked with `-a avr` otherwise it doesn't detect it correctly

Host system is Debian testing amd64

Backtrace below:

```
Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x00007ffff60e4f0e in r_reg_get (reg=0x7ffff3fc3b98 <main_arena+152>, name=0x7ffff6593a48 "_prog", type=-1) at reg.c:262
#2  0x00007ffff642cf42 in internal_esil_reg_write (esil=0x5555557cd4b0, regname=0x7ffff6593a48 "_prog", num=0) at esil.c:304
#3  0x00007ffff642dabb in r_anal_esil_reg_write (esil=0x5555557cd4b0, dst=0x7ffff6593a48 "_prog", num=0) at esil.c:562
#4  0x00007ffff63cfba4 in avr_op (anal=0x5555557d9ee0, op=0x7fffffff9a90, addr=0, buf=0x5555557be0d0 "\f\224E", len=256) at /home/imanol/devel/radare2/libr/..//libr/anal/p/anal_avr.c:1627
#5  0x00007ffff6419783 in r_anal_op (anal=0x5555557d9ee0, op=0x7fffffff9a90, addr=0, data=0x5555557be0d0 "\f\224E", len=256) at op.c:98
#6  0x00007ffff7aaa758 in num_callback (userptr=0x55555575c580 <r>, str=0x5555557c1dc8 "$$", ok=0x7fffffff9cd0) at core.c:377
#7  0x00007ffff3fe3e4b in r_num_get (num=0x5555557c1d80, str=0x5555557c1dc8 "$$") at num.c:109
#8  0x00007ffff4003207 in prim (num=0x5555557c1d80, nc=0x5555557c1db0, get=0) at calc.c:114
#9  0x00007ffff4002f5b in term (num=0x5555557c1d80, nc=0x5555557c1db0, get=0) at calc.c:78
#10 0x00007ffff4002ba0 in expr (num=0x5555557c1d80, nc=0x5555557c1db0, get=0) at calc.c:60
#11 0x00007ffff4003f4c in r_num_calc (num=0x5555557c1d80, str=0x5555557c9d06 "$$", err=0x7fffffffa2a0) at calc.c:348
#12 0x00007ffff3fe4324 in r_num_math (num=0x5555557c1d80, str=0x5555557c9d06 "$$") at num.c:238
#13 0x00007ffff7adf0ca in cmd_anal_reg (core=0x55555575c580 <r>, str=0x5555557c9d02 " PC") at cmd_anal.c:2042
#14 0x00007ffff7ae99c2 in cmd_anal (data=0x55555575c580 <r>, input=0x5555557c9d01 "r PC") at cmd_anal.c:5162
#15 0x00007ffff7b52096 in r_cmd_call (cmd=0x55555580d350, input=0x5555557c9d00 "ar PC") at cmd_api.c:213
#16 0x00007ffff7b1a69d in r_core_cmd_subst_i (core=0x55555575c580 <r>, cmd=0x5555557c9d00 "ar PC", colon=0x0) at cmd.c:2001
#17 0x00007ffff7b181f9 in r_core_cmd_subst (core=0x55555575c580 <r>, cmd=0x5555557c9d00 "ar PC") at cmd.c:1324
#18 0x00007ffff7b1c3b7 in r_core_cmd (core=0x55555575c580 <r>, cstr=0x7ffff7b96a96 "ar PC=$$", log=0) at cmd.c:2557
#19 0x00007ffff7b1ca15 in r_core_cmd0 (user=0x55555575c580 <r>, cmd=0x7ffff7b96a96 "ar PC=$$") at cmd.c:2703
#20 0x00007ffff7ae1fd5 in cmd_anal_esil (core=0x55555575c580 <r>, input=0x5555557c9cc2 "i") at cmd_anal.c:2858
#21 0x00007ffff7ae99e1 in cmd_anal (data=0x55555575c580 <r>, input=0x5555557c9cc1 "ei") at cmd_anal.c:5163
#22 0x00007ffff7b52096 in r_cmd_call (cmd=0x55555580d350, input=0x5555557c9cc0 "aei") at cmd_api.c:213
#23 0x00007ffff7b1a69d in r_core_cmd_subst_i (core=0x55555575c580 <r>, cmd=0x5555557c9cc0 "aei", colon=0x0) at cmd.c:2001
#24 0x00007ffff7b181f9 in r_core_cmd_subst (core=0x55555575c580 <r>, cmd=0x5555557c9cc0 "aei") at cmd.c:1324
#25 0x00007ffff7b1c3b7 in r_core_cmd (core=0x55555575c580 <r>, cstr=0x7ffff7b8d4d2 "aei", log=0) at cmd.c:2557
#26 0x00007ffff7b1ca15 in r_core_cmd0 (user=0x55555575c580 <r>, cmd=0x7ffff7b8d4d2 "aei") at cmd.c:2703
#27 0x00007ffff7ad8048 in type_cmd (core=0x55555575c580 <r>, input=0x555555887bc3 "a") at cmd_anal.c:67
#28 0x00007ffff7adc84c in cmd_anal_fcn (core=0x55555575c580 <r>, input=0x555555887bc1 "fta") at cmd_anal.c:1273
#29 0x00007ffff7ae9a65 in cmd_anal (data=0x55555575c580 <r>, input=0x555555887bc1 "fta") at cmd_anal.c:5170
#30 0x00007ffff7b52096 in r_cmd_call (cmd=0x55555580d350, input=0x555555887bc0 "afta") at cmd_api.c:213
#31 0x00007ffff7b1a69d in r_core_cmd_subst_i (core=0x55555575c580 <r>, cmd=0x555555887bc0 "afta", colon=0x0) at cmd.c:2001
#32 0x00007ffff7b181f9 in r_core_cmd_subst (core=0x55555575c580 <r>, cmd=0x555555887bc0 "afta") at cmd.c:1324
#33 0x00007ffff7b1c3b7 in r_core_cmd (core=0x55555575c580 <r>, cstr=0x7ffff7b94222 "afta", log=0) at cmd.c:2557
#34 0x00007ffff7b1ca15 in r_core_cmd0 (user=0x55555575c580 <r>, cmd=0x7ffff7b94222 "afta") at cmd.c:2703
#35 0x00007ffff7ae8e91 in cmd_anal_all (core=0x55555575c580 <r>, input=0x555555823402 "aa") at cmd_anal.c:4924
#36 0x00007ffff7ae9b3c in cmd_anal (data=0x55555575c580 <r>, input=0x555555823401 "aaa") at cmd_anal.c:5192
#37 0x00007ffff7b52096 in r_cmd_call (cmd=0x55555580d350, input=0x555555823400 "aaaa") at cmd_api.c:213
#38 0x00007ffff7b1a69d in r_core_cmd_subst_i (core=0x55555575c580 <r>, cmd=0x555555823400 "aaaa", colon=0x0) at cmd.c:2001
#39 0x00007ffff7b181f9 in r_core_cmd_subst (core=0x55555575c580 <r>, cmd=0x555555823400 "aaaa") at cmd.c:1324
#40 0x00007ffff7b1c3b7 in r_core_cmd (core=0x55555575c580 <r>, cstr=0x55555555b3ec "aaaa", log=0) at cmd.c:2557
#41 0x00007ffff7b1ca15 in r_core_cmd0 (user=0x55555575c580 <r>, cmd=0x55555555b3ec "aaaa") at cmd.c:2703
#42 0x0000555555559b21 in main (argc=5, argv=0x7fffffffe278, envp=0x7fffffffe2a8) at radare2.c:1025
```
Thanks for your help

**Comment by Maijin** [comment]
Paste output of r2 -v

**Comment by ImanolBarba** [comment]
radare2 1.1.0-git 13170 @ linux-x86-64 git.1.0.2-225-g8d02b7f
commit: 8d02b7fececfc98090d4da1b26b780c63ae06dc8 build: 2016-12-10

I also want to add that  I just dumped a blink led example from an arduino uno and it also crashes, so it's not specifically tied to the binary per se

**Comment by killabytenow** [comment]
I am checking it and it seems a bug when managing the reg profile. I don't know why neither when this bug appeared. I have to travel this week I am not sure when I will have time to debug this, so please be patient.

**Comment by radare** [comment]
There was some changes in the regprofiles 2 or 3 weeks ago with skuater. But it shouldnt segfault :) may be related to this

**Comment by radare** [comment]
valgrind logs:
```
==31297== Invalid read of size 4ll functionsd sym.func.* functions (aan)
==31297==    at 0x100497C9F: r_anal_esil_reg_write (esil.c:554)
==31297==    by 0x10041C1E7: avr_op (anal_avr.c:1627)
==31297==    by 0x10047FE87: r_anal_op (op.c:98)
==31297==    by 0x100082C10: num_callback (core.c:377)
==31297==    by 0x10169470B: r_num_get (num.c:109)
==31297==    by 0x1016BC3AE: prim (calc.c:114)
==31297==    by 0x1016BBE95: term (calc.c:78)
==31297==    by 0x1016BB6B5: expr (calc.c:60)
==31297==    by 0x1016BADA4: r_num_calc (calc.c:348)
==31297==    by 0x101694D36: r_num_math (num.c:238)
==31297==    by 0x100089D73: cmd_anal_reg (cmd_anal.c:2043)
==31297==    by 0x100096FD5: cmd_anal (cmd_anal.c:5162)
==31297==  Address 0x1114dc058 is 56 bytes inside a block of size 304 free'd
==31297==    at 0x100072EF7: free (in /usr/local/Cellar/valgrind/3.11.0_1/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==31297==    by 0x100496E90: r_anal_esil_free (esil.c:190)
==31297==    by 0x1000C497C: cmd_anal_esil (cmd_anal.c:2853)
==31297==    by 0x100096FF4: cmd_anal (cmd_anal.c:5163)
==31297==    by 0x10013F216: r_cmd_call (cmd_api.c:213)
==31297==    by 0x1000C1F47: r_core_cmd_subst_i (cmd.c:2001)
==31297==    by 0x1000948A4: r_core_cmd_subst (cmd.c:1324)
==31297==    by 0x1000923F6: r_core_cmd (cmd.c:2557)
==31297==    by 0x100087C69: r_core_cmd0 (cmd.c:2703)
==31297==    by 0x1000D0861: type_cmd (cmd_anal.c:67)
==31297==    by 0x1000C6D01: cmd_anal_fcn (cmd_anal.c:1273)
==31297==    by 0x10009707B: cmd_anal (cmd_anal.c:5170)
==31297==  Block was alloc'd at
==31297==    at 0x1000731B9: calloc (in /usr/local/Cellar/valgrind/3.11.0_1/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==31297==    by 0x100496666: r_anal_esil_new (esil.c:65)
==31297==    by 0x1000C49F1: cmd_anal_esil (cmd_anal.c:2861)
==31297==    by 0x100096FF4: cmd_anal (cmd_anal.c:5163)
==31297==    by 0x10013F216: r_cmd_call (cmd_api.c:213)
==31297==    by 0x1000C1F47: r_core_cmd_subst_i (cmd.c:2001)
==31297==    by 0x1000948A4: r_core_cmd_subst (cmd.c:1324)
==31297==    by 0x1000923F6: r_core_cmd (cmd.c:2557)
==31297==    by 0x100087C69: r_core_cmd0 (cmd.c:2703)
==31297==    by 0x10014AA82: r_core_anal_esil (anal.c:3291)
==31297==    by 0x1000CC6C3: cmd_anal_all (cmd_anal.c:4961)
==31297==    by 0x100097167: cmd_anal (cmd_anal.c:5192)
==31297==
```

**Comment by ImanolBarba** [comment]
Thanks for looking into this issue :)

Unfortunately, I just did a sys/install.sh and it seems to be failing still (using the same binary), I checked and the last commit was this one.

radare2 1.1.0-git 13180 @ linux-x86-64 git.1.0.2-235-g4598fc3
commit: 4598fc34ca8bd2f6eb5d842f7cc0b363481b198e build: 2016-12-12

```
Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x00007ffff60e3f0e in r_reg_get (reg=0x7ffff3fc2b98 <main_arena+152>, name=0x7ffff6592a48 "_prog", type=-1) at reg.c:262
#2  0x00007ffff642bf51 in internal_esil_reg_write (esil=0x5555557cd4b0, regname=0x7ffff6592a48 "_prog", num=0) at esil.c:305
#3  0x00007ffff642caca in r_anal_esil_reg_write (esil=0x5555557cd4b0, dst=0x7ffff6592a48 "_prog", num=0) at esil.c:564
#4  0x00007ffff63ceba4 in avr_op (anal=0x5555557da480, op=0x7fffffffa010, addr=0, buf=0x5555557be0d0 "\f\224E", len=256) at /home/imanol/devel/radare2/libr/..//libr/anal/p/anal_avr.c:1627
#5  0x00007ffff641877f in r_anal_op (anal=0x5555557da480, op=0x7fffffffa010, addr=0, data=0x5555557be0d0 "\f\224E", len=256) at op.c:98
#6  0x00007ffff7aa9798 in num_callback (userptr=0x55555575c580 <r>, str=0x5555557c1dc8 "$$", ok=0x7fffffffa250) at core.c:377
#7  0x00007ffff3fe2e4b in r_num_get (num=0x5555557c1d80, str=0x5555557c1dc8 "$$") at num.c:109
#8  0x00007ffff4002207 in prim (num=0x5555557c1d80, nc=0x5555557c1db0, get=0) at calc.c:114
#9  0x00007ffff4001f5b in term (num=0x5555557c1d80, nc=0x5555557c1db0, get=0) at calc.c:78
#10 0x00007ffff4001ba0 in expr (num=0x5555557c1d80, nc=0x5555557c1db0, get=0) at calc.c:60
#11 0x00007ffff4002f4c in r_num_calc (num=0x5555557c1d80, str=0x5555557c9d06 "$$", err=0x7fffffffa820) at calc.c:348
#12 0x00007ffff3fe3324 in r_num_math (num=0x5555557c1d80, str=0x5555557c9d06 "$$") at num.c:238
#13 0x00007ffff7ade10a in cmd_anal_reg (core=0x55555575c580 <r>, str=0x5555557c9d02 " PC") at cmd_anal.c:2042
#14 0x00007ffff7ae8a02 in cmd_anal (data=0x55555575c580 <r>, input=0x5555557c9d01 "r PC") at cmd_anal.c:5162
#15 0x00007ffff7b511de in r_cmd_call (cmd=0x55555580dcc0, input=0x5555557c9d00 "ar PC") at cmd_api.c:213
#16 0x00007ffff7b197e5 in r_core_cmd_subst_i (core=0x55555575c580 <r>, cmd=0x5555557c9d00 "ar PC", colon=0x0) at cmd.c:2003
#17 0x00007ffff7b17341 in r_core_cmd_subst (core=0x55555575c580 <r>, cmd=0x5555557c9d00 "ar PC") at cmd.c:1326
#18 0x00007ffff7b1b4ff in r_core_cmd (core=0x55555575c580 <r>, cstr=0x7ffff7b95c16 "ar PC=$$", log=0) at cmd.c:2559
#19 0x00007ffff7b1bb5d in r_core_cmd0 (user=0x55555575c580 <r>, cmd=0x7ffff7b95c16 "ar PC=$$") at cmd.c:2705
#20 0x00007ffff7ae1015 in cmd_anal_esil (core=0x55555575c580 <r>, input=0x5555557c9cc2 "i") at cmd_anal.c:2858
#21 0x00007ffff7ae8a21 in cmd_anal (data=0x55555575c580 <r>, input=0x5555557c9cc1 "ei") at cmd_anal.c:5163
#22 0x00007ffff7b511de in r_cmd_call (cmd=0x55555580dcc0, input=0x5555557c9cc0 "aei") at cmd_api.c:213
#23 0x00007ffff7b197e5 in r_core_cmd_subst_i (core=0x55555575c580 <r>, cmd=0x5555557c9cc0 "aei", colon=0x0) at cmd.c:2003
#24 0x00007ffff7b17341 in r_core_cmd_subst (core=0x55555575c580 <r>, cmd=0x5555557c9cc0 "aei") at cmd.c:1326
#25 0x00007ffff7b1b4ff in r_core_cmd (core=0x55555575c580 <r>, cstr=0x7ffff7b8c612 "aei", log=0) at cmd.c:2559
#26 0x00007ffff7b1bb5d in r_core_cmd0 (user=0x55555575c580 <r>, cmd=0x7ffff7b8c612 "aei") at cmd.c:2705
#27 0x00007ffff7ad7088 in type_cmd (core=0x55555575c580 <r>, input=0x555555888533 "a") at cmd_anal.c:67
#28 0x00007ffff7adb88c in cmd_anal_fcn (core=0x55555575c580 <r>, input=0x555555888531 "fta") at cmd_anal.c:1273
#29 0x00007ffff7ae8aa5 in cmd_anal (data=0x55555575c580 <r>, input=0x555555888531 "fta") at cmd_anal.c:5170
#30 0x00007ffff7b511de in r_cmd_call (cmd=0x55555580dcc0, input=0x555555888530 "afta") at cmd_api.c:213
#31 0x00007ffff7b197e5 in r_core_cmd_subst_i (core=0x55555575c580 <r>, cmd=0x555555888530 "afta", colon=0x0) at cmd.c:2003
#32 0x00007ffff7b17341 in r_core_cmd_subst (core=0x55555575c580 <r>, cmd=0x555555888530 "afta") at cmd.c:1326
#33 0x00007ffff7b1b4ff in r_core_cmd (core=0x55555575c580 <r>, cstr=0x7ffff7b933a2 "afta", log=0) at cmd.c:2559
#34 0x00007ffff7b1bb5d in r_core_cmd0 (user=0x55555575c580 <r>, cmd=0x7ffff7b933a2 "afta") at cmd.c:2705
#35 0x00007ffff7ae7ed1 in cmd_anal_all (core=0x55555575c580 <r>, input=0x555555823d72 "aa") at cmd_anal.c:4924
#36 0x00007ffff7ae8b7c in cmd_anal (data=0x55555575c580 <r>, input=0x555555823d71 "aaa") at cmd_anal.c:5192
#37 0x00007ffff7b511de in r_cmd_call (cmd=0x55555580dcc0, input=0x555555823d70 "aaaa") at cmd_api.c:213
#38 0x00007ffff7b197e5 in r_core_cmd_subst_i (core=0x55555575c580 <r>, cmd=0x555555823d70 "aaaa", colon=0x0) at cmd.c:2003
#39 0x00007ffff7b17341 in r_core_cmd_subst (core=0x55555575c580 <r>, cmd=0x555555823d70 "aaaa") at cmd.c:1326
#40 0x00007ffff7b1b4ff in r_core_cmd (core=0x55555575c580 <r>, cstr=0x55555555b3ec "aaaa", log=0) at cmd.c:2559
#41 0x00007ffff7b1bb5d in r_core_cmd0 (user=0x55555575c580 <r>, cmd=0x55555555b3ec "aaaa") at cmd.c:2705
#42 0x0000555555559b21 in main (argc=5, argv=0x7fffffffe7f8, envp=0x7fffffffe828) at radare2.c:1025
```

**Comment by ImanolBarba** [comment]
Works like a charm, thanks guys!
