### ISSUE TITLE
/P fault

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6308]
https://asciinema.org/a/85pgispqmnkbtchszm2r6n83n

**Comment by Maijin** [comment]
No asan, no gdb, no valgrind logs?

**Comment by radare** [comment]
U see it you fix it

**Comment by zonkzonk** [comment]
No asan, no gdb, no valgrind logs!
but, teh vid :p

```
,gdb r2 core
Sat Dec 10 16:09:02 CET 2016
Reading symbols from r2...done.

warning: core file may not match specified executable file.
[New LWP 1542]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `r2 -d bin/russia'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f6ae2c30d43 in r_core_get_boundaries_prot (core=0x555ec7fa6640 <r>, protection=1, mode=0x555ec80855f0 "dbg.map", from=0x0, to=0x0) at cmd_search.c:662
662                                     *from = *to = core->offset;
(gdb) bt
#0  0x00007f6ae2c30d43 in r_core_get_boundaries_prot (core=0x555ec7fa6640 <r>, protection=1, mode=0x555ec80855f0 "dbg.map", from=0x0, to=0x0) at cmd_search.c:662
#1  0x00007f6ae2c362cf in search_similar_pattern (core=0x555ec7fa6640 <r>, count=0) at cmd_search.c:2060
#2  0x00007f6ae2c371e8 in cmd_search (data=0x555ec7fa6640 <r>, input=0x555ec807c3d1 "P") at cmd_search.c:2348
#3  0x00007f6ae2c79b50 in r_cmd_call (cmd=0x555ec805e6e0, input=0x555ec807c3d0 "/P") at cmd_api.c:213
#4  0x00007f6ae2c3f69b in r_core_cmd_subst_i (core=0x555ec7fa6640 <r>, cmd=0x555ec807c3d0 "/P", colon=0x0) at cmd.c:2001
#5  0x00007f6ae2c3ce0b in r_core_cmd_subst (core=0x555ec7fa6640 <r>, cmd=0x555ec807c3d0 "/P") at cmd.c:1324
#6  0x00007f6ae2c41554 in r_core_cmd (core=0x555ec7fa6640 <r>, cstr=0x555ec80b8950 "/P", log=1) at cmd.c:2557
#7  0x00007f6ae2bce48e in r_core_prompt_exec (r=0x555ec7fa6640 <r>) at core.c:1782
#8  0x0000555ec7da3468 in main (argc=3, argv=0x7ffd577ec088, envp=0x7ffd577ec0a8) at radare2.c:1091
(gdb) l
657
658                             r_debug_map_sync (core->dbg);
659
660                             if (!strcmp (mode, "dbg.map")) {
661                                     int perm = 0;
662                                     *from = *to = core->offset;
663                                     list = r_list_newf (free);
664                                     r_list_foreach (core->dbg->maps, iter, map) {
665                                             if (*from >= map->addr && *from < map->addr_end) {
666                                                     *from = map->addr;
```
