### ISSUE TITLE
Analysis isn't finished

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#6322]
Try to analyse library:

```
$ r2 /usr/lib/firefox/libxul.so
 — All your base are belong to r2
[0x009df2d0]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[ ] Analyze function calls (aac)
```

I were waiting about 14 hours... And analysis wasn't finished

Env: r2 from git, Mint 17.3 x64, firefox from apt-get

**Comment by radare** [comment]
Why you have so much patience? There are sevwral issues for the same thing. Yes. R2 analysis is slow for big binaries. Thats a known issue and will be solved next year but required some heavy refactoring and more tests that are delicate to do

**Comment by enovella** [comment]
Find the same issue here with an ARM shared object.

**Comment by radare** [comment]
Do u think its an infinite loop? Can you add some printfs to confirm this theory?

**Comment by alvarofe** [comment]
I think the issue is aac

**Comment by enovella** [comment]
Sure that I can add printfs to it, the only problem is that I do not remember which binary I was radare'ing with. It could be a binary of the SECCON 2016 CTF or another one.  Let me see if I am able to reproduce the infinite loop with one the binaries of this CTF and can print out where the issue is.

**Comment by radare** [comment]
can you proove that "infinite analysis" theory with a small binary?

**Comment by enovella** [comment]
Hi r2,

Sorry but I did not find yet the binary that hung me r2 in that occasion. As soon as I am able to reproduce the "infinite analysis" again,  will share the binary over here.

Cheers

**Comment by dukebarman** [comment]
I've created profiler logs of my case for kcachegrind:
- only open binary
[callgrind.out.42046.zip](https://github.com/radare/radare2/files/1770178/callgrind.out.42046.zip)
- open and command `aaa` 
[callgrind.out.42070.zip](https://github.com/radare/radare2/files/1770179/callgrind.out.42070.zip)

Binary file: /usr/lib64/firefox/libxul.so
r2: from git
OS: Fedora x64

**Comment by dukebarman** [comment]
In last versions, besides no finished analysis, have another errors:
```
$ r2 -v
radare2 2.5.0-git 17803 @ linux-x86-64 git.2.4.0-282-g43af9e3
commit: 43af9e3bb2ac50cd755d0ee89aca33bd3607e0ff build: 2018-04-06__08:20:44
$ r2 /usr/lib/firefox/libxul.so 
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Warning: read (init_offset)
 -- Coffee time!
[0x00949bc0]>
```

**Comment by Maijin** [comment]
Those are not errors but warnings

**Comment by dukebarman** [comment]
sry, mistypes. Warnings of course

**Comment by dukebarman** [comment]
Is it related bug https://github.com/radare/radare2/issues/6642?

**Comment by radare** [comment]
is this bug still there?

**Comment by radare** [comment]
because i fixed an infinite loop in analysis in 3.2

**Comment by dukebarman** [comment]
Now, it's crashing:

```
$ r2 /usr/lib/firefox/libxul.so 
WARNING: bin_strings buffer is too big (0x012596f7). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)
 -- Everybody hates warnings. Mr. Pancake, tear down this -Wall
[0x00805080]> aaa
[[anal.jmptbl] Missing cjmp bb in predecessor at 0x0212e5e3
Invalid instruction of 1005 bytes at 0x2b
[anal.jmptbl] Missing cjmp bb in predecessor at 0x035e3367
[anal.jmptbl] Missing cjmp bb in predecessor at 0x0362f727
Invalid instruction of 972 bytes at 0x3c
Invalid instruction of 16383 bytes at 0x4832f9c
Invalid instruction of 16373 bytes at 0x4832f35
Invalid instruction of 16384 bytes at 0x4833c7e
[anal.jmptbl] Missing cjmp bb in predecessor at 0x04836d6d
Invalid instruction of 16384 bytes at 0x4833101
Invalid instruction of 16384 bytes at 0x4838325
Invalid instruction of 16384 bytes at 0x4832fa6
...
Invalid instruction of 1024 bytes at 0x64f3531
Invalid instruction of 1024 bytes at 0x65040a1
Invalid instruction of 1024 bytes at 0x65069ba
Invalid instruction of 1024 bytes at 0x6507325
Invalid instruction of 1024 bytes at 0x6537c7e
Invalid instruction of 1024 bytes at 0x653c766
Invalid instruction of 1024 bytes at 0x653c806
Invalid instruction of 1024 bytes at 0x6545581
Invalid instruction of 1024 bytes at 0x6548d2e
Invalid instruction of 1024 bytes at 0x654ee65
Invalid instruction of 1024 bytes at 0x656a201
Invalid instruction of 1024 bytes at 0x657358d
Invalid instruction of 1024 bytes at 0x6599cf5
[x] Analyze function calls (aac)
[Segmentation fault (core dumped)ions for references (aar)
```

OS: Ubuntu 18 with last updates
r2 from git

**Comment by radare** [comment]
pls try again

**Comment by dukebarman** [comment]
Another error - Killed

```
$ r2 -v
radare2 3.3.0-git 20866 @ linux-x86-64 git.3.2.1-253-g36f677eb7
commit: 36f677eb7bc43c4232e5776f4538c8dd239f5235 build: 2019-02-05__02:34:18
```

Output:
```
$ r2 /usr/lib/firefox/libxul.so
WARNING: bin_strings buffer is too big (0x012ad527). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)
Cannot compute hash
 -- Use rarun2 to launch your programs with a predefined environment.
[0x0081ac20]> aaa
[[anal.jmptbl] Missing predecesessor cjmp bb at 0x011bec83
Invalid instruction of 5 bytes at 0x81bbe2
Invalid instruction of 6 bytes at 0x8783c0
[anal.jmptbl] Missing predecesessor cjmp bb at 0x03622647
...
Truncated instruction of 3 bytes at 0x492ca4d
Invalid instruction of 4 bytes at 0x492cb7c
Invalid instruction of 7 bytes at 0x859803
Invalid instruction of 4 bytes at 0x85d890
Truncated instruction of 1 bytes at 0x873cd3
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[Killede matching analysis for all functions (aaft)
$
```

**Comment by radare** [comment]
Can you strace this and see why the kernel kills r2?

**Comment by dukebarman** [comment]
```
...
brk(0x5608dadf0000)                     = 0x5608dadf0000
brk(0x5608dae11000)                     = 0x5608dae11000
brk(0x5608dae32000)                     = 0x5608dae32000
brk(0x5608dae53000)                     = 0x5608dae53000
write(2, "Invalid asr shift of 65 at 0x3c8"..., 37Invalid asr shift of 65 at 0x3c88c4a
) = 37
write(2, "Invalid asr shift of 65 at 0x3c8"..., 37Invalid asr shift of 65 at 0x3c88eba
) = 37
write(2, "Invalid asr shift of 56 at 0x3c8"..., 37Invalid asr shift of 56 at 0x3c8aa85
) = 37
brk(0x5608dccfe000)                     = 0x5608dae53000
mmap(NULL, 32284672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGKILL +++
Killed
```

**Comment by radare** [comment]
Can you get a backtrace in gdb of that malloc of 32284672 bytes plz? To identify who is doing that?

**Comment by radare** [comment]
ping? i was thinking that maybe wrapping all the malloc calls via r_malloc we can do if (allocSize > X) r_sys_breakpoint() in there.

**Comment by radare** [comment]
hello?

**Comment by ret2libc** [comment]
@dukebarman Do we have a binary for this issue? Have you tried with ASAN enabled?

Without these info, I doubt we can fix this (in particular for next release 3.3.0)

**Comment by dukebarman** [comment]
@radare sry, for delay:
```
...
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6635bf6 in reserve_kv (ht=0x0, key=0x55565132ea30, key_len=15, update=false) at ht_inc.c:178
178		HT_(Bucket) *bt = &ht->table[bucketfn (ht, key)];
(gdb) bt
#0  0x00007ffff6635bf6 in reserve_kv (ht=0x0, key=0x55565132ea30, key_len=15, update=false) at ht_inc.c:178
#1  0x00007ffff6635d72 in ht_pp_insert_kv (ht=0x0, kv=0x5556608be360, update=false) at ht_inc.c:204
#2  0x00007ffff6635a1e in internal_ht_grow (ht=0x55555566ec60) at ht_inc.c:159
#3  0x00007ffff6635bd6 in check_growing (ht=0x55555566ec60) at ht_inc.c:173
#4  0x00007ffff6635dab in ht_pp_insert_kv (ht=0x55555566ec60, kv=0x55566498f420, update=true) at ht_inc.c:210
#5  0x00007ffff66367bf in sdb_ht_insert_kvp (ht=0x55555566ec60, kvp=0x55566498f420, update=true) at sdbht.c:46
#6  0x00007ffff663ffcc in sdb_set_internal (s=0x55555566bee0, key=0x7ffff669fb80 <Key.4426+2560> "trace.0.3ea5499", val=0x7fffffffc390 "0x555667457550", owned=0, cas=0) at sdb.c:619
#7  0x00007ffff664007d in sdb_set (s=0x55555566bee0, key=0x7ffff669fb80 <Key.4426+2560> "trace.0.3ea5499", val=0x7fffffffc390 "0x555667457550", cas=0) at sdb.c:633
#8  0x00007ffff6646996 in sdb_num_set (s=0x55555566bee0, key=0x7ffff669fb80 <Key.4426+2560> "trace.0.3ea5499", v=93829588153680, cas=0) at num.c:28
#9  0x00007ffff7b28192 in r_debug_trace_add (dbg=0x555555659ea0, addr=65688729, size=4) at trace.c:154
#10 0x00007ffff7b27d76 in r_debug_trace_pc (dbg=0x555555659ea0, pc=65688738) at trace.c:68
#11 0x00007ffff7e115e4 in r_core_esil_step (core=0x5555555611c0 <r>, until_addr=18446744073709551615, until_expr=0x0, prev_addr=0x0) at cmd_anal.c:3687
Backtrace stopped: Cannot access memory at address 0x7fffffffcb18
```

@ret2libc I sent a binary to @radare, hash: 8d2d117370df1280d315d80d6d377eff55ff904480c01d6562a293dcb2037a78 (and it's library from standard firefox for ubuntu).
I haven't tried with ASAN build yet

**Comment by radare** [comment]
These two clusterfuzz bins can be related (big allocations during analysis or rbin parsing)

[clusterfuzz-testcase-minimized-ia_fuzz-5634910105108480.dms.zip](https://github.com/radare/radare2/files/2862751/clusterfuzz-testcase-minimized-ia_fuzz-5634910105108480.dms.zip)
[clusterfuzz-testcase-minimized-ia_fuzz-5752811923439616.dms.zip](https://github.com/radare/radare2/files/2862752/clusterfuzz-testcase-minimized-ia_fuzz-5752811923439616.dms.zip)

**Comment by radare** [comment]
fwd the bin to ret2libc

**Comment by radare** [comment]
Maybe this is the fix https://github.com/radare/radare2/pull/13094

**Comment by radare** [comment]
Please try again

**Comment by dukebarman** [comment]
`Killed` again :(

**Comment by radare** [comment]
Can you pls tell me which is the malloc causing this?

**Comment by ret2libc** [comment]
I think I found the issue in sdb ht implementation. I'm fixing it at https://github.com/radare/sdb/pull/187

This fix seems to be consistent with the report you gave us before. Indeed the hashtable was growing too much because the size was computed in a wrong way. 

Please consider that it still uses ~6GB of memory to do all the analysis, but it is able to finish on my machine (it's slow, but it finishes). Once that's merged, please @dukebarman try again. However, I think we should close this issue and create another one if there are other (maybe) related issues, this issue has started with one problem and is now shifting towards others.

**Comment by dukebarman** [comment]
Okay. My testing VM has 4 Gb RAM, but I'll increase to 6 and try both variants

**Comment by ret2libc** [comment]
Given you received the message in https://github.com/radare/radare2/issues/6322#issuecomment-463223216 I guess you can reproduce on your current environment.

**Comment by ret2libc** [comment]
@dukebarman if you want, you can test my patch by using https://github.com/ret2libc/radare2/tree/dukebar

**Comment by radare** [comment]
Woah nice catch

**Comment by radare** [comment]
I bet this will be the reason why loading a kernel was taking 3gb of ram?

**Comment by ret2libc** [comment]
I’m not sure. Consider that even with this patch it takes 6gb of memory to analyze things. I will check it out but I’m not sure it will be better.

**Comment by radare** [comment]
please update sdb in r2

**Comment by radare** [comment]
is this issue fixed now?

**Comment by dukebarman** [comment]
Killed again, but now another errors:
```
$ r2 -A /usr/lib/firefox/libxul.so
WARNING: bin_strings buffer is too big (0x012ad527). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)
Cannot compute hash
Cannot compute hash
oops
[[anal.jmptbl] Missing predecesessor cjmp bb at 0x011bec83
[anal.jmptbl] Missing predecesessor cjmp bb at 0x03622647
[anal.jmptbl] Missing predecesessor cjmp bb at 0x036725b7
[anal.jmptbl] Missing predecesessor cjmp bb at 0x022d0557
[anal.jmptbl] Missing predecesessor cjmp bb at 0x03622637
[anal.jmptbl] Missing predecesessor cjmp bb at 0x04905255
[anal.jmptbl] Missing predecesessor cjmp bb at 0x037af4b7
[anal.jmptbl] Missing predecesessor cjmp bb at 0x022d0547
[x] Analyze all flags starting with sym. and entry0 (aa)
...
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[Invalid asr shift of 58 at 0x3bc3d5bnctions (aaft)
Invalid asr shift of 58 at 0x3bc3e25
Invalid asr shift of 58 at 0x3bc3ebf
Invalid asr shift of 58 at 0x3bc3f61
Invalid asr shift of 58 at 0x3bc3ffb
Invalid asr shift of 58 at 0x3bc40aa
Invalid asr shift of 58 at 0x3bc375c
Invalid asr shift of 58 at 0x3bc3889
Invalid asr shift of 58 at 0x3bc390f
Invalid asr shift of 58 at 0x3bc397c
Invalid asr shift of 58 at 0x3bc3a59
Invalid asr shift of 58 at 0x3bc3ac6
Invalid asr shift of 58 at 0x3bc3b80
Invalid asr shift of 58 at 0x3bc3bed
Invalid asr shift of 58 at 0x3bc44e1
Invalid asr shift of 58 at 0x3bc4bd4
Invalid asr shift of 32 at 0x371cfa4
Invalid asr shift of 46 at 0x371e281
Invalid asr shift of 46 at 0x371e2df
Invalid asr shift of 33 at 0x370511d
Invalid asr shift of 35 at 0x36dfd1b
Invalid asr shift of 46 at 0x36e2068
Invalid asr shift of 32 at 0x36dbcf3
Invalid asr shift of 36 at 0x36dbdb6
Killed
```

**Comment by Maijin** [comment]
As already said before please do again:

Can you strace this and see why the kernel kills r2?

**Comment by dukebarman** [comment]
```
write(2, "Invalid asr shift of 32 at 0x371"..., 37Invalid asr shift of 32 at 0x371cfa4
) = 37
write(2, "Invalid asr shift of 46 at 0x371"..., 37Invalid asr shift of 46 at 0x371e281
) = 37
write(2, "Invalid asr shift of 46 at 0x371"..., 37Invalid asr shift of 46 at 0x371e2df
) = 37
write(2, "Invalid asr shift of 33 at 0x370"..., 37Invalid asr shift of 33 at 0x370511d
) = 37
write(2, "Invalid asr shift of 35 at 0x36d"..., 37Invalid asr shift of 35 at 0x36dfd1b
) = 37
write(2, "Invalid asr shift of 46 at 0x36e"..., 37Invalid asr shift of 46 at 0x36e2068
) = 37
write(2, "Invalid asr shift of 32 at 0x36d"..., 37Invalid asr shift of 32 at 0x36dbcf3
) = 37
write(2, "Invalid asr shift of 36 at 0x36d"..., 37Invalid asr shift of 36 at 0x36dbdb6
) = 37
mmap(NULL, 46292992, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9573fbe000
brk(0x55ad1fd68000)                     = 0x55ad1fd68000
brk(0x55ad1fd89000)                     = 0x55ad1fd89000
brk(0x55ad1fdaa000)                     = 0x55ad1fdaa000
brk(0x55ad1fdcb000)                     = 0x55ad1fdcb000
brk(0x55ad1fdec000)                     = 0x55ad1fdec000
brk(0x55ad1fe0d000)                     = 0x55ad1fe0d000
brk(0x55ad1fe2e000)                     = 0x55ad1fe2e000
brk(0x55ad1fe4f000)                     = 0x55ad1fe4f000
...
brk(0x55ad21b2f000)                     = 0x55ad21b2f000
brk(0x55ad21b50000)                     = 0x55ad21b50000
brk(0x55ad21b71000)                     = 0x55ad21b71000
brk(0x55ad21b92000 <unfinished ...>
+++ killed by SIGKILL +++
Killed
```

**Comment by radare** [comment]
And the line doing the big malloc is...

**Comment by ret2libc** [comment]
I think there isn't any "big malloc", but there are many objects allocated on the heap. As said, on my machine it doesn't get killed so probably there isn't a lot of memory on the VM you are using for testing.

Analysis of libxul still requires ~6GB of memory, so it's not light. However there is no single/easy-fix for this IMHO.

**Comment by dukebarman** [comment]
@radare I've tried wrapper for mmap in gdb session, but it's very long process...

@ret2libc I think you're right. It works after I've increased RAM from 4Gb to 7Gb

**Comment by ret2libc** [comment]
@dukebarman I think we can close this issue. That said, there are many places we should improve to use less memory, but it's not likely this is going to be in one shot. Are you ok with it?

**Comment by dukebarman** [comment]
Ok. Should I open another issue?

**Comment by ret2libc** [comment]
Yes please, do so.
