### ISSUE TITLE
FPE (modulo by zero) in grub_ext2_read_inode()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#6327]
**FPE (modulo by zero) in grub_ext2_read_inode()**

Tested on Git HEAD: 4ae632133ed34c7f80949a8a705635608a4ac45d

Payload (bins/fuzzed/r2_fpe_grub_ext2_read_inode) in https://github.com/radare/radare2-regressions/pull/641

To reproduce: `r2 -A r2_fpe_grub_ext2_read_inode `

ASAN Output:

```
==1943==ERROR: AddressSanitizer: FPE on unknown address 0x7f5778308fd5 (pc 0x7f5778308fd5 bp 0x7fff9b7706a0 sp 0x7fff9b7705a0 T0)
    #0 0x7f5778308fd4 in grub_ext2_read_inode XYZ/radare2/shlr/grub/fs/ext2.c:530:5
    #1 0x7f5778307eb8 in grub_ext2_mount XYZ/radare2/shlr/grub/fs/ext2.c:582:3
    #2 0x7f577830718f in grub_ext2_dir XYZ/radare2/shlr/grub/fs/ext2.c:848:10
    #3 0x7f57782f55d8 in ext2__mount XYZ/radare2/libr/fs/p/fs_grub_base.c:74:8
    #4 0x7f57782fd357 in r_fs_mount XYZ/radare2/libr/fs/fs.c:141:7
    #5 0x7f577af9af12 in cmd_mount XYZ/radare2/libr/core/./cmd_mount.c:57:9
    #6 0x7f577b0801fc in r_cmd_call XYZ/radare2/libr/core/cmd_api.c:213:10
    #7 0x7f577afccbea in r_core_cmd_subst_i XYZ/radare2/libr/core/cmd.c:2039:16
    #8 0x7f577af98f67 in r_core_cmd_subst XYZ/radare2/libr/core/cmd.c:1332:9
    #9 0x7f577af95f85 in r_core_cmd XYZ/radare2/libr/core/cmd.c:2595:9
    #10 0x7f577af8b538 in r_core_cmdf XYZ/radare2/libr/core/cmd.c:2735:8
    #11 0x7f577b069581 in bin_info XYZ/radare2/libr/core/cbin.c:593:4
    #12 0x7f577b066f0e in r_core_bin_info XYZ/radare2/libr/core/cbin.c:2610:45
    #13 0x7f577b066d3d in r_core_bin_set_env XYZ/radare2/libr/core/cbin.c:109:3
    #14 0x7f577b02d645 in r_core_file_do_load_for_io_plugin XYZ/radare2/libr/core/file.c:409:2
    #15 0x7f577b02b8ef in r_core_bin_load XYZ/radare2/libr/core/file.c:527:4
    #16 0x5586a8089593 in main XYZ/radare2/binr/radare2/radare2.c:822:14
    #17 0x7f57748fe82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #18 0x5586a7fbbe58 in _start (/usr/local/bin/radare2+0x20e58)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE XYZ/radare2/shlr/grub/fs/ext2.c:530:5 in grub_ext2_read_inode
==1943==ABORTING
```

**Comment by radare** [comment]
grub is a pile of crap. i already fixed many overflows in there.. thanks for reporting this. im gonna fix it now
