### ISSUE TITLE
SEGFAULT in some commands on dex

### ISSUE THREAD

**Issue by h4ng3r** [radare/radare2#6333]
I am using r2 from git, this is the last commit now:
```
r2 -v
radare2 1.1.0-git 13240 @ darwin-x86-64 git.0.10.6-709-g8505294
commit: 85052941cfe088fa381152aba519aaa458e222c3 build: 2016-12-16
```

If I open a simple dex file "pi" command will always SEGFAULT.

```
r2 ../radare2-regressions/bins/dex/HelloWorld.dex
 -- Ilo ni li pona li pali e lipu. mi wile e ni: sina kama jo e musi
[0x0000025c]> pi
Segmentation fault: 11
```
pd1 for example will produce the same SEGFAULT.

```
r2 ../radare2-regressions/bins/dex/HelloWorld.dex
 -- Check your IO plugins with 'r2 -L'
[0x0000025c]> pd1
Segmentation fault: 11
```

This is the backtrace for the "pi" example:
```
Process 75339 launched: '/usr/local/bin/r2' (x86_64)
 -- For a full list of commands see `strings /dev/urandom`
Process 75339 stopped
* thread #1: tid = 0xef284, 0x00000001004ff18b libr_anal.dylib`r_anal_var_free(av=0xffffffffffffffff) + 27 at var.c:339, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffffffffffff)
    frame #0: 0x00000001004ff18b libr_anal.dylib`r_anal_var_free(av=0xffffffffffffffff) + 27 at var.c:339
   336
   337 	R_API void r_anal_var_free(RAnalVar *av) {
   338 		if (av) {
-> 339 			free (av->name);
   340 			free (av->type);
   341 			R_FREE (av);
   342 		}
(lldb) bt
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/buffer.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/cdb.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/cdb_make.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/ht.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/json.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/lock.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/ls.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/ns.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/query.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/sdb.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/base64.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/disk.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/array.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/fmt.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/match.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/num.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/util.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
error: libr_util.dylib debug map object file '/Users/wsg-ms/radare2-dev/libr/util/../../shlr/sdb/src/journal.o' has changed (actual time is 0x58531949, debug map time is 0x58531944) since this executable was linked, file will be ignored
* thread #1: tid = 0xef284, 0x00000001004ff18b libr_anal.dylib`r_anal_var_free(av=0xffffffffffffffff) + 27 at var.c:339, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffffffffffff)
  * frame #0: 0x00000001004ff18b libr_anal.dylib`r_anal_var_free(av=0xffffffffffffffff) + 27 at var.c:339
    frame #1: 0x00000001004f3480 libr_anal.dylib`r_anal_op_fini(op=0x0000000102005fa0) + 48 at op.c:41
    frame #2: 0x00000001001e96d5 libr_core.dylib`r_core_print_disasm_instructions(core=0x0000000100007520, nb_bytes=256, nb_opcodes=256) + 1381 at disasm.c:3860
    frame #3: 0x00000001001280d7 libr_core.dylib`cmd_print(data=0x0000000100007520, input="i") + 9671 at cmd_print.c:2930
    frame #4: 0x00000001001bd047 libr_core.dylib`r_cmd_call(cmd=0x000000010283f600, input="pi") + 503 at cmd_api.c:213
    frame #5: 0x000000010013f900 libr_core.dylib`r_core_cmd_subst_i(core=0x0000000100007520, cmd="pi", colon=0x0000000000000000) + 11104 at cmd.c:2039
    frame #6: 0x0000000100111de5 libr_core.dylib`r_core_cmd_subst(core=0x0000000100007520, cmd="pi") + 917 at cmd.c:1332
    frame #7: 0x000000010010f937 libr_core.dylib`r_core_cmd(core=0x0000000100007520, cstr="pi", log=1) + 1031 at cmd.c:2595
    frame #8: 0x0000000100101c65 libr_core.dylib`r_core_prompt_exec(r=0x0000000100007520) + 37 at core.c:1796
    frame #9: 0x00000001000042d2 r2`main(argc=2, argv=0x00007fff5fbff948, envp=0x00007fff5fbff960) + 11042 at radare2.c:1091
    frame #10: 0x00007fffdeba5255 libdyld.dylib`start + 1
    frame #11: 0x00007fffdeba5255 libdyld.dylib`start + 1
(lldb)
```

More information from asan:
```
==12865==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62000001cfa0 at pc 0x000113111bbe bp 0x7fff50011940 sp 0x7fff50011100
WRITE of size 1370 at 0x62000001cfa0 thread T0
    #0 0x113111bbd in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib+0x41bbd)
    #1 0x111c2b89f in r_asm_disassemble asm.c:409
    #2 0x10ff084e7 in r_core_print_disasm_instructions disasm.c:3859
    #3 0x10fcf2c6b in cmd_print .cmd_print.c:2930
    #4 0x10fe83e85 in r_cmd_call cmd_api.c:213
    #5 0x10fd2f150 in r_core_cmd_subst_i cmd.c:2039
    #6 0x10fcbb8d0 in r_core_cmd_subst cmd.c:1332
    #7 0x10fcb540b in r_core_cmd cmd.c:2595
    #8 0x10fc8d1ec in r_core_prompt_exec core.c:1796
    #9 0x10fbebdaf in main radare2.c:1091
    #10 0x7fffdeba5254 in start (libdyld.dylib+0x5254)

ASAN:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

**Comment by radare** [comment]
For this kind of errors use valgrind

**Comment by radare** [comment]
PING

**Comment by h4ng3r** [comment]
@radare, I reproduced the error in Linux with the the last version from git.

Valgrind backtrace:
```
vagrant@vagrant-ubuntu-trusty-64:~/radare2-regressions$ valgrind --tool=memcheck r2 -qc "pi" bins/dex/HelloWorld.dex
==25179== Memcheck, a memory error detector
==25179== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==25179== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==25179== Command: r2 -qc pi bins/dex/HelloWorld.dex
==25179==
==25179== Invalid write of size 2
==25179==    at 0x4C2F7E3: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25179==    by 0x7422154: r_asm_disassemble (asm.c:409)
==25179==    by 0x4F53B72: r_core_print_disasm_instructions (disasm.c:3859)
==25179==    by 0x4ED461F: cmd_print (cmd_print.c:2930)
==25179==    by 0x4F2AAAD: r_cmd_call (cmd_api.c:223)
==25179==    by 0x4EF0494: r_core_cmd_subst_i (cmd.c:2039)
==25179==    by 0x4EEDBFB: r_core_cmd_subst (cmd.c:1332)
==25179==    by 0x4EF2341: r_core_cmd (cmd.c:2595)
==25179==    by 0x4EF29D5: r_core_cmd0 (cmd.c:2741)
==25179==    by 0x10BCCE: run_commands (radare2.c:328)
==25179==    by 0x10E184: main (radare2.c:1040)
==25179==  Address 0xb097030 is 0 bytes after a block of size 3,872 alloc'd
==25179==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25179==    by 0x4F460FF: ds_init (disasm.c:335)
==25179==    by 0x4F53822: r_core_print_disasm_instructions (disasm.c:3804)
==25179==    by 0x4ED461F: cmd_print (cmd_print.c:2930)
==25179==    by 0x4F2AAAD: r_cmd_call (cmd_api.c:223)
==25179==    by 0x4EF0494: r_core_cmd_subst_i (cmd.c:2039)
==25179==    by 0x4EEDBFB: r_core_cmd_subst (cmd.c:1332)
==25179==    by 0x4EF2341: r_core_cmd (cmd.c:2595)
==25179==    by 0x4EF29D5: r_core_cmd0 (cmd.c:2741)
==25179==    by 0x10BCCE: run_commands (radare2.c:328)
==25179==    by 0x10E184: main (radare2.c:1040)
==25179==
==25179== Invalid read of size 8
==25179==    at 0x60AD2B0: r_anal_var_free (var.c:339)
==25179==    by 0x60A342D: r_anal_op_fini (op.c:41)
==25179==    by 0x4F53B87: r_core_print_disasm_instructions (disasm.c:3860)
==25179==    by 0x4ED461F: cmd_print (cmd_print.c:2930)
==25179==    by 0x4F2AAAD: r_cmd_call (cmd_api.c:223)
==25179==    by 0x4EF0494: r_core_cmd_subst_i (cmd.c:2039)
==25179==    by 0x4EEDBFB: r_core_cmd_subst (cmd.c:1332)
==25179==    by 0x4EF2341: r_core_cmd (cmd.c:2595)
==25179==    by 0x4EF29D5: r_core_cmd0 (cmd.c:2741)
==25179==    by 0x10BCCE: run_commands (radare2.c:328)
==25179==    by 0x10E184: main (radare2.c:1040)
==25179==  Address 0xffffffffffffffff is not stack'd, malloc'd or (recently) free'd
==25179==
==25179==
==25179== Process terminating with default action of signal 11 (SIGSEGV)
==25179==  Access not within mapped region at address 0xFFFFFFFFFFFFFFFF
==25179==    at 0x60AD2B0: r_anal_var_free (var.c:339)
==25179==    by 0x60A342D: r_anal_op_fini (op.c:41)
==25179==    by 0x4F53B87: r_core_print_disasm_instructions (disasm.c:3860)
==25179==    by 0x4ED461F: cmd_print (cmd_print.c:2930)
==25179==    by 0x4F2AAAD: r_cmd_call (cmd_api.c:223)
==25179==    by 0x4EF0494: r_core_cmd_subst_i (cmd.c:2039)
==25179==    by 0x4EEDBFB: r_core_cmd_subst (cmd.c:1332)
==25179==    by 0x4EF2341: r_core_cmd (cmd.c:2595)
==25179==    by 0x4EF29D5: r_core_cmd0 (cmd.c:2741)
==25179==    by 0x10BCCE: run_commands (radare2.c:328)
==25179==    by 0x10E184: main (radare2.c:1040)
==25179==  If you believe this happened as a result of a stack
==25179==  overflow in your program's main thread (unlikely but
==25179==  possible), you can try to increase the size of the
==25179==  main thread stack using the --main-stacksize= flag.
==25179==  The main thread stack size used in this run was 8388608.
==25179==
==25179== HEAP SUMMARY:
==25179==     in use at exit: 870,764 bytes in 12,977 blocks
==25179==   total heap usage: 241,584 allocs, 228,607 frees, 29,104,161 bytes allocated
==25179==
==25179== LEAK SUMMARY:
==25179==    definitely lost: 1,965 bytes in 82 blocks
==25179==    indirectly lost: 1,524 bytes in 3 blocks
==25179==      possibly lost: 0 bytes in 0 blocks
==25179==    still reachable: 867,275 bytes in 12,892 blocks
==25179==         suppressed: 0 bytes in 0 blocks
==25179== Rerun with --leak-check=full to see details of leaked memory
==25179==
==25179== For counts of detected and suppressed errors, rerun with: -v
==25179== ERROR SUMMARY: 143 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
vagrant@vagrant-ubuntu-trusty-64:~/radare2-regressions$
```

**Comment by alvarofe** [comment]
are you working on it??

**Comment by h4ng3r** [comment]
Nop, I'm at work :(.

**Comment by alvarofe** [comment]
ok, will look at it after fix all coverities

**Comment by alvarofe** [comment]
i can't reproduce neither in mac os x nor linux, check again since lately there has been fixes in dex as well as other places

**Comment by alvarofe** [comment]
ok fixed and pushed in master, it would be great if you could create a test for this
