### ISSUE TITLE
izz crash with bigger file

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6401]
morrn,

r2 crashing with segmentation fault, when analysing a bigger file:

,r2  -e 'io.va=true' American_Beauty.avi
aaaa
pd 10
izz~'8'

```
,gdb -q r2 core.5521
Thu Dec 29 21:50:00 CET 2016
Cannot access memory at address 0x7f61b1b22168
Cannot access memory at address 0x7f61b1b22160
Failed to read a valid object file image from memory.
Core was generated by `r2 -e io.va=true American_Beauty.avi'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f61ad8297b4 in ?? ()
(gdb) bt
#0  0x00007f61ad8297b4 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7ffe60741298
(gdb) i r
rax            0x0      0
rbx            0x0      0
rcx            0x7f6087b1606f   140052570136687
rdx            0x5f     95
rsi            0x7f6087b16010   140052570136592
rdi            0x0      0
rbp            0x7ffe60741330   0x7ffe60741330
rsp            0x7ffe60741298   0x7ffe60741298
r8             0x800000000000   140737488355328
r9             0x0      0
r10            0x22     34
r11            0x246    582
r12            0x560756a692f0   94589518516976
r13            0x7ffe60741ad0   140730516642512
r14            0x0      0
r15            0x0      0
rip            0x7f61ad8297b4   0x7f61ad8297b4
eflags         0x10202  [ IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
(gdb) i f
Stack level 0, frame at 0x7ffe607412a0:
 rip = 0x7f61ad8297b4; saved rip = <error: Cannot access memory at address 0x7ffe60741298>
 Outermost frame: Cannot access memory at address 0x7ffe60741298
 Arglist at 0x7ffe60741290, args: 
 Locals at 0x7ffe60741290, Previous frame's sp is 0x7ffe607412a0
Cannot access memory at address 0x7ffe60741298
```

Greetings
--zlul

ps, no valgrind on this machine

**Comment by zonkzonk** [comment]
forgot list:
```
(gdb) list 
328                     r_core_cmd0 (&r, cmdn);
329                     r_cons_flush ();
330             }
331             if (quiet) {
332                     if (cmds && !r_list_empty (cmds)) {
333                             return true;
334                     }
335                     if (!r_list_empty (files)) {
336                             return true;
337                     }

```

**Comment by radare** [comment]
SeeMs like an stack exhaustion

**Comment by radare** [comment]
Can't reproduce, can you show regions or hexdump of contents pointed by $rsp ?

are you sure you are using latest r2 from git? :P

**Comment by zonkzonk** [comment]
now yes :P but this core dump seems screwed (wrong ulimit)
nothing useful:

(gdb) i r rsp
rsp            0x7ffe60741298   0x7ffe60741298
(gdb) x/40i $rsp
   0x7ffe60741298:      Cannot access memory at address 0x7ffe60741298
(gdb) x/40i $rsp+40
   0x7ffe607412c0:      Cannot access memory at address 0x7ffe607412c0
(gdb) x/40i $rsp-40
   0x7ffe60741270:      Cannot access memory at address 0x7ffe60741270
