### ISSUE TITLE
dg heap-buffer-overflow after writing core on purpose

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6616]
morrn,

running dg

```
> r2 -d /bin/ls
Process with PID 8469 started...
= attach 8469 8469
bin.baddr 0x00400000
USING 400000
Assuming filepath /bin/ls
asm.bits 64
 -- prove you are a robot to continue ...
[0x7f51da4c8cd0]> dg
Writing to file 'core.8469'
=================================================================
==8468==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000120158 at pc 0x7f2076a91d95 bp 0x7ffed7cbb6f0 sp 0x7ffed7cbae98
READ of size 80 at 0x602000120158 thread T0
    #0 0x7f2076a91d94 in __asan_memcpy (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8cd94)
    #1 0x7f20714f7f2a in r_mem_dup /home/sk/radare2/libr/util/mem.c:285
    #2 0x7f2075337ce4 in prpsinfo_get_psargs p/native/linux/linux_coredump.c:63
    #3 0x7f2075338339 in linux_get_prpsinfo p/native/linux/linux_coredump.c:111
    #4 0x7f2075342b7b in linux_generate_corefile p/native/linux/linux_coredump.c:1540
    #5 0x7f207532fd9d in r_debug_gcore p/debug_native.c:1517
    #6 0x7f20764eb004 in cmd_debug /home/sk/radare2/libr/core/cmd_debug.c:3731
    #7 0x7f20766206fb in r_cmd_call /home/sk/radare2/libr/core/cmd_api.c:226
    #8 0x7f20765a167b in r_core_cmd_subst_i /home/sk/radare2/libr/core/cmd.c:2082
    #9 0x7f207659befe in r_core_cmd_subst /home/sk/radare2/libr/core/cmd.c:1359
    #10 0x7f20765a584d in r_core_cmd /home/sk/radare2/libr/core/cmd.c:2638
    #11 0x7f20764b697f in r_core_prompt_exec /home/sk/radare2/libr/core/core.c:1871
    #12 0x55f632503606 in main /home/sk/radare2/binr/radare2/radare2.c:1145
    #13 0x7f207111cabf in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20abf)
    #14 0x55f6324fe308 in _start (/usr/bin/radare2+0x6308)

0x602000120158 is located 0 bytes to the right of 8-byte region [0x602000120150,0x602000120158)
allocated by thread T0 here:
    #0 0x7f2076a6776f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6276f)
    #1 0x7f2075338272 in linux_get_prpsinfo p/native/linux/linux_coredump.c:104
    #2 0x7f2075342b7b in linux_generate_corefile p/native/linux/linux_coredump.c:1540
    #3 0x7f207532fd9d in r_debug_gcore p/debug_native.c:1517
    #4 0x7f20764eb004 in cmd_debug /home/sk/radare2/libr/core/cmd_debug.c:3731
    #5 0x7f20766206fb in r_cmd_call /home/sk/radare2/libr/core/cmd_api.c:226
    #6 0x7f20765a167b in r_core_cmd_subst_i /home/sk/radare2/libr/core/cmd.c:2082
    #7 0x7f207659befe in r_core_cmd_subst /home/sk/radare2/libr/core/cmd.c:1359
    #8 0x7f20765a584d in r_core_cmd /home/sk/radare2/libr/core/cmd.c:2638
    #9 0x7f20764b697f in r_core_prompt_exec /home/sk/radare2/libr/core/core.c:1871
    #10 0x55f632503606 in main /home/sk/radare2/binr/radare2/radare2.c:1145
    #11 0x7f207111cabf in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20abf)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 __asan_memcpy
Shadow bytes around the buggy address:
  0x0c048001bfd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048001bfe0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048001bff0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048001c000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048001c010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c048001c020: fa fa fa fa fa fa fa fa fa fa 00[fa]fa fa 00 01
  0x0c048001c030: fa fa fd fd fa fa fd fd fa fa 00 00 fa fa 00 02
  0x0c048001c040: fa fa 01 fa fa fa 03 fa fa fa 03 fa fa fa 03 fa
  0x0c048001c050: fa fa 03 fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c048001c060: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c048001c070: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
 Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==8468==ABORTING
```

**Comment by radare** [comment]
Its ironic

**Comment by alvarofe** [comment]
I reviewed the code and is full of vulnerabilities due to bad practices, I fixed some in local but I prefer to hand it out to Oscar who was who made it.

**Comment by leberus** [comment]
Soz :(, I'll take a look tomorrow ;)!
