### ISSUE TITLE
r2 on empty files SIGBUS

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#6673]
```
,touch bitch
,zzuf -s 0:1000000 -r 0.06 -q -c -C 1 -v r2 acid bitch
zzuf[s=0,r=0.06]: launched `r2'
zzuf[s=0,r=0.06]: signal 7 (SIGBUS)
zzuf: maximum crash count reached, exiting
,ls -l bitch 
-rw------- 1 sk sk 0 Feb  3 18:47 bitch
,ls
bitch  serverauth.QBWU890vbK
,ulimit -c 1000000
,ulimit -c 1000000
,ulimit -f 1000000
,ulimit 
1000000
,zzuf -s 0:1000000 -r 0.06 -q -c -C 1 -v r2 acid bitch
zzuf[s=0,r=0.06]: launched `r2'
zzuf[s=0,r=0.06]: signal 7 (SIGBUS)
zzuf: maximum crash count reached, exiting
,gdb -q r2 core 
Fri Feb  3 18:47:44 CET 2017
Reading symbols from r2...done.

warning: core file may not match specified executable file.
[New LWP 1035]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `r2 acid bitch'.
Program terminated with signal SIGBUS, Bus error.
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:181
181     ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) x/i $pc
=> 0x7f5e31ef1897 <__memcpy_avx_unaligned+487>: vmovdqu -0x80(%rcx),%xmm5
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:181
#1  0x00007f5e35fdbd68 in mmap () from /usr/lib/zzuf/libzzuf.so
#2  0x00007f5e321953af in r_file_mmap_unix (m=0x556f463c36c0, fd=5) at file.c:688
#3  0x00007f5e3219555e in r_file_mmap (file=0x556f463c1810 "bitch", rw=false, base=0) at file.c:770
#4  0x00007f5e3516244f in check (bin=0x556f4636cd10) at /home/sk/radare2/libr/..//libr/bin/p/bin_xtr_fatmach0.c:36
#5  0x00007f5e350ce8b8 in r_bin_load_io_at_offset_as_sz (bin=0x556f4636cd10, desc=0x556f463c35e0, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0, offset=0, name=0x0, 
    sz=0) at bin.c:957
#6  0x00007f5e350ceba9 in r_bin_load_io_at_offset_as (bin=0x556f4636cd10, desc=0x556f463c35e0, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0, offset=0, name=0x0)
    at bin.c:1010
#7  0x00007f5e350ce3ba in r_bin_load_io (bin=0x556f4636cd10, desc=0x556f463c35e0, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0) at bin.c:836
#8  0x00007f5e35d0f3e4 in r_core_file_do_load_for_io_plugin (r=0x556f45f245a0 <r>, baseaddr=18446744073709551615, loadaddr=0) at file.c:414
#9  0x00007f5e35d0fa1c in r_core_bin_load (r=0x556f45f245a0 <r>, filenameuri=0x556f463c1810 "bitch", baddr=18446744073709551615) at file.c:537
#10 0x0000556f45d20568 in main (argc=3, argv=0x7ffd35e4f2f8, envp=0x7ffd35e4f318) at radare2.c:874
(gdb) i f 0
Stack frame at 0x7ffd35e4e800:
 rip = 0x7f5e31ef1897 in __memcpy_avx_unaligned (../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:181); saved rip = 0x7f5e35fdbd68
 called by frame at 0x7ffd35e4e8a0
 source language asm.
 Arglist at 0x7ffd35e4e7f0, args: 
 Locals at 0x7ffd35e4e7f0, Previous frame's sp is 0x7ffd35e4e800
 Saved registers:
  rip at 0x7ffd35e4e7f8
```

**Comment by condret** [comment]
try with siol, and tell me what happens

**Comment by Susanne588586** [comment]
@condret it is not in siol branch, can you check difference?

**Comment by condret** [comment]
i can try

**Comment by alvarofe** [comment]
How can I reproduce this?

**Comment by radare** [comment]
: > empty
valgrind r2 empty


==66193== Conditional jump or move depends on uninitialised value(s)
==66193==    at 0x100320F54: check_bytes (bin_omf.c:37)
==66193==    by 0x1002A16FC: r_bin_get_binplugin_by_bytes (bin.c:1156)
==66193==    by 0x1002A1216: r_bin_file_new_from_bytes (bin.c:1427)
==66193==    by 0x1002A0C9A: r_bin_load_io_at_offset_as_sz (bin.c:980)
==66193==    by 0x10029FC67: r_bin_load_io_at_offset_as (bin.c:994)
==66193==    by 0x10029FAA1: r_bin_load_io (in /Users/pancake/prg/radare2/libr/bin/libr_bin.dylib)
==66193==    by 0x10010815A: r_core_file_do_load_for_io_plugin (file.c:419)
==66193==    by 0x100107008: r_core_bin_load (file.c:542)
==66193==    by 0x100003049: main (in /usr/local/bin/r2)
==66193==
==66193== Conditional jump or move depends on uninitialised value(s)
==66193==    at 0x100320F67: check_bytes (bin_omf.c:37)
==66193==    by 0x1002A16FC: r_bin_get_binplugin_by_bytes (bin.c:1156)
==66193==    by 0x1002A1216: r_bin_file_new_from_bytes (bin.c:1427)
==66193==    by 0x1002A0C9A: r_bin_load_io_at_offset_as_sz (bin.c:980)
==66193==    by 0x10029FC67: r_bin_load_io_at_offset_as (bin.c:994)
==66193==    by 0x10029FAA1: r_bin_load_io (in /Users/pancake/prg/radare2/libr/bin/libr_bin.dylib)
==66193==    by 0x10010815A: r_core_file_do_load_for_io_plugin (file.c:419)
==66193==    by 0x100107008: r_core_bin_load (file.c:542)
==66193==    by 0x100003049: main (in /usr/local/bin/r2)
==66193==
 -- Mind that the 'g' in radare is silent
