### ISSUE TITLE
Visual assembler hang on some instruction

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6696]
Repro:
`VppA`
enter 'mov eax,[`

```
(gdb) bt
#0  0x00007f8a1ccbffec in parseOperand (a=a@entry=0x55ea25fca1e0, str=0x7fff72faad28 "[", op=op@entry=0x7fff72faacf0)
    at p/asm_x86_nz.c:2294
#1  0x00007f8a1ccc0274 in parseOpcode (a=a@entry=0x55ea25fca1e0, op=op@entry=0x7fff72faad20 "mov eax,[", 
    out=out@entry=0x7fff72faaca0) at p/asm_x86_nz.c:2373
#2  0x00007f8a1ccc0306 in assemble (a=0x55ea25fca1e0, ao=0x7fff72faae80, str=<optimized out>) at p/asm_x86_nz.c:2420
<...>
```

#6689

**Comment by radare** [comment]
@unlogic

**Comment by radare** [comment]
@Svenito
