### ISSUE TITLE
drp load SEGV

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6716]
``` 
,r2  -c "`cat /tmp/rtdsc`;drp /tmp/rtdsc" -d /bin/ls
Process with PID 15033 started...
= attach 15033 15033
bin.baddr 0x00400000
USING 400000
Assuming filepath /bin/ls
asm.bits 64
r_reg_set_profile_string: Parse error @ line 1 (Invalid syntax)
 -- The unix-like reverse engineering framework.
ASAN:SIGSEGV
=================================================================
==15032==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x7f026b0e3b05 bp 0x7ffcaf0825b0 sp 0x7ffcaf0824f0 T0)
    #0 0x7f026b0e3b04 in r_debug_reg_sync /home/sk/radare2/libr/debug/dreg.c:28
    #1 0x7f026c29ffcf in cmd_debug_reg /home/sk/radare2/libr/core/cmd_debug.c:1938
    #2 0x7f026c2ad7b1 in cmd_debug /home/sk/radare2/libr/core/cmd_debug.c:3587
    #3 0x7f026c3e6496 in r_cmd_call /home/sk/radare2/libr/core/cmd_api.c:226
    #4 0x7f026c366cf1 in r_core_cmd_subst_i /home/sk/radare2/libr/core/cmd.c:2082
    #5 0x7f026c361574 in r_core_cmd_subst /home/sk/radare2/libr/core/cmd.c:1359
    #6 0x7f026c36aec3 in r_core_cmd /home/sk/radare2/libr/core/cmd.c:2638
    #7 0x7f026c36be93 in r_core_cmd_str /home/sk/radare2/libr/core/cmd.c:2834
    #8 0x7f026c35cdc4 in cmd_interpret /home/sk/radare2/libr/core/cmd.c:651
    #9 0x7f026c3e6496 in r_cmd_call /home/sk/radare2/libr/core/cmd_api.c:226
    #10 0x7f026c366cf1 in r_core_cmd_subst_i /home/sk/radare2/libr/core/cmd.c:2082
    #11 0x7f026c361574 in r_core_cmd_subst /home/sk/radare2/libr/core/cmd.c:1359
    #12 0x7f026c36aec3 in r_core_cmd /home/sk/radare2/libr/core/cmd.c:2638
    #13 0x7f026c27ac34 in set_prompt /home/sk/radare2/libr/core/core.c:1794
    #14 0x7f026c27b398 in r_core_prompt /home/sk/radare2/libr/core/core.c:1852
    #15 0x5607163725ce in main /home/sk/radare2/binr/radare2/radare2.c:1141
    #16 0x7f0266edfabf in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20abf)
    #17 0x56071636d308 in _start (/usr/bin/radare2+0x6308)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/sk/radare2/libr/debug/dreg.c:28 r_debug_reg_sync
==15032==ABORTING

```

**Comment by zonkzonk** [comment]
@radare /tmp/rtdsc contains an =

**Comment by zonkzonk** [comment]
@pancake 

```
Core was generated by `r2 -c =;drp /tmp/rtdsc -d /bin/ls'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2fa87a2177 in r_debug_reg_sync (dbg=0x55ecec708360, type=0, write=0) at dreg.c:28
28              if (i >= R_REG_TYPE_GPR && dbg->reg->regset[i].regs->length == 0) {
(gdb) bt
#0  0x00007f2fa87a2177 in r_debug_reg_sync (dbg=0x55ecec708360, type=0, write=0) at dreg.c:28
#1  0x00007f2fa95bdc66 in cmd_debug_reg (core=0x55eceb2455a0 <r>, str=0x55ecec712502 "*") at cmd_debug.c:1938
#2  0x00007f2fa95c422e in cmd_debug (data=0x55eceb2455a0 <r>, input=0x55ecec712501 "r*") at cmd_debug.c:3587
#3  0x00007f2fa965b8e4 in r_cmd_call (cmd=0x55ecec705030, input=0x55ecec712500 "dr*") at cmd_api.c:226
#4  0x00007f2fa962047f in r_core_cmd_subst_i (core=0x55eceb2455a0 <r>, cmd=0x55ecec712500 "dr*", colon=0x0) at cmd.c:2082
#5  0x00007f2fa961da69 in r_core_cmd_subst (core=0x55eceb2455a0 <r>, cmd=0x55ecec712500 "dr*") at cmd.c:1359
#6  0x00007f2fa9622338 in r_core_cmd (core=0x55eceb2455a0 <r>, cstr=0x55ecec712680 "dr*", log=0) at cmd.c:2638
#7  0x00007f2fa9622c8a in r_core_cmd_str (core=0x55eceb2455a0 <r>, cmd=0x55ecec712680 "dr*") at cmd.c:2834
#8  0x00007f2fa961b606 in cmd_interpret (data=0x55eceb2455a0 <r>, input=0x55ecec90fce1 "dr*") at cmd.c:651
#9  0x00007f2fa965b8e4 in r_cmd_call (cmd=0x55ecec705030, input=0x55ecec90fce0 ".dr*") at cmd_api.c:226
#10 0x00007f2fa962047f in r_core_cmd_subst_i (core=0x55eceb2455a0 <r>, cmd=0x55ecec90fce0 ".dr*", colon=0x0) at cmd.c:2082
#11 0x00007f2fa961da69 in r_core_cmd_subst (core=0x55eceb2455a0 <r>, cmd=0x55ecec90fce0 ".dr*") at cmd.c:1359
#12 0x00007f2fa9622338 in r_core_cmd (core=0x55eceb2455a0 <r>, cstr=0x55ecec72f1d0 ".dr*", log=0) at cmd.c:2638
#13 0x00007f2fa95ab77d in set_prompt (r=0x55eceb2455a0 <r>) at core.c:1799
#14 0x00007f2fa95abb31 in r_core_prompt (r=0x55eceb2455a0 <r>, sync=0) at core.c:1857
#15 0x000055eceb0423c6 in main (argc=5, argv=0x7ffcdceff4a8, envp=0x7ffcdceff4d8) at radare2.c:1141


(gdb) bt f
#0  0x00007f2fa87a2177 in r_debug_reg_sync (dbg=0x55ecec708360, type=0, write=0) at dreg.c:28
        i = 0
        n = -588260240
        size = -588269792

```
