### ISSUE TITLE
pi *** Error in `r2': realloc(): invalid next size: 0x0000561470b981a0 ***

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#6764]
```
,r2 /bin/ls
 -- Get a free shell with 'ragg2 -i exec -x'
[0x00404870]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x00404870]> pi 1
xor ebp, ebp
[0x00404870]> pif -100
xor ebp, ebp
mov r9, rdx
pop rsi
mov rdx, rsp
and rsp, 0xfffffffffffffff0
push rax
push rsp
mov r8, 0x412490
mov rcx, 0x412420
mov rdi, main
call sym.imp.__libc_start_main
hlt
pi -100
*** Error in `r2': realloc(): invalid next size: 0x0000561470b981a0 ***
Aborted
```

**Comment by Susanne588586** [comment]
```
[0x00404870]> pi 1
xor ebp, ebp
[0x00404870]> pi -100
=================================================================
==16131==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61200000bfc1 at pc 0x7f2bb9c7904c bp 0x7ffce8098fd0 sp 0x7ffce8098778
WRITE of size 438 at 0x61200000bfc1 thread T0
    #0 0x7f2bb9c7904b in __asan_memset (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8d04b)
    #1 0x7f2bb6de4f32 in r_io_read_at /home/sk/radare2/libr/io/io.c:420
    #2 0x7f2bb97bd39b in r_core_read_at /home/sk/radare2/libr/core/cio.c:490
    #3 0x7f2bb985f912 in r_core_print_disasm_instructions /home/sk/radare2/libr/core/disasm.c:3734
    #4 0x7f2bb9749774 in cmd_print /home/sk/radare2/libr/core/cmd_print.c:3026
    #5 0x7f2bb9802504 in r_cmd_call /home/sk/radare2/libr/core/cmd_api.c:226
    #6 0x7f2bb9782db0 in r_core_cmd_subst_i /home/sk/radare2/libr/core/cmd.c:2082
    #7 0x7f2bb977d633 in r_core_cmd_subst /home/sk/radare2/libr/core/cmd.c:1359
    #8 0x7f2bb97870db in r_core_cmd /home/sk/radare2/libr/core/cmd.c:2656
    #9 0x7f2bb96971ec in r_core_prompt_exec /home/sk/radare2/libr/core/core.c:1875
    #10 0x55c2a2d16637 in main /home/sk/radare2/binr/radare2/radare2.c:1149
    #11 0x7f2bb42f3abf in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20abf)
    #12 0x55c2a2d11308 in _start (/usr/bin/radare2+0x6308)

0x61200000bfc1 is located 0 bytes to the right of 257-byte region [0x61200000bec0,0x61200000bfc1)
allocated by thread T0 here:
    #0 0x7f2bb9c84b49 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98b49)
    #1 0x7f2bb96932ed in r_core_init /home/sk/radare2/libr/core/core.c:1488
    #2 0x55c2a2d12d1d in main /home/sk/radare2/binr/radare2/radare2.c:442
    #3 0x7f2bb42f3abf in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20abf)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 __asan_memset
Shadow bytes around the buggy address:
  0x0c247fff97a0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c247fff97b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c247fff97c0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa
  0x0c247fff97d0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c247fff97e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c247fff97f0: 00 00 00 00 00 00 00 00[01]fa fa fa fa fa fa fa
  0x0c247fff9800: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c247fff9810: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c247fff9820: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa
  0x0c247fff9830: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c247fff9840: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==16131==ABORTING

```

**Comment by radare** [comment]
thanks!!

**Comment by zonkzonk** [comment]
pr for #6764
