### ISSUE TITLE
heap-buffer-overflow on address 0x61200000bfc1 at pc 0x7f9f0bd1904c bp 0x7ffd7c958510 sp 0x7ffd7c957cb8

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#6769]
similar to #6764

r2  -c "aa; pi 1; pid -100" /bin/ls

```
[x] Analyze all flags starting with sym. and entry0 (aa)
=================================================================
==5774==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61200000bfc1 at pc 0x7f0567dcc04c bp 0x7fff12993bf0 sp 0x7fff12993398
WRITE of size 438 at 0x61200000bfc1 thread T0
    #0 0x7f0567dcc04b in __asan_memset (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8d04b)
    #1 0x7f0564f37f32 in r_io_read_at /home/sk/radare2/libr/io/io.c:420
    #2 0x7f05679102e6 in r_core_read_at /home/sk/radare2/libr/core/cio.c:490
    #3 0x7f056788ed80 in pdi /home/sk/radare2/libr/core/cmd_print.c:1224
    #4 0x7f056789c2fd in cmd_print /home/sk/radare2/libr/core/cmd_print.c:2987
    #5 0x7f056795544f in r_cmd_call /home/sk/radare2/libr/core/cmd_api.c:226
    #6 0x7f05678d5cfb in r_core_cmd_subst_i /home/sk/radare2/libr/core/cmd.c:2082
    #7 0x7f05678d057e in r_core_cmd_subst /home/sk/radare2/libr/core/cmd.c:1359
    #8 0x7f05678d081b in r_core_cmd_subst /home/sk/radare2/libr/core/cmd.c:1381
    #9 0x7f05678d081b in r_core_cmd_subst /home/sk/radare2/libr/core/cmd.c:1381
    #10 0x7f05678da026 in r_core_cmd /home/sk/radare2/libr/core/cmd.c:2656
    #11 0x7f05678dab64 in r_core_cmd0 /home/sk/radare2/libr/core/cmd.c:2802
    #12 0x564d7f9308ec in run_commands /home/sk/radare2/binr/radare2/radare2.c:332
    #13 0x564d7f93431f in main /home/sk/radare2/binr/radare2/radare2.c:1096
    #14 0x7f0562446abf in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20abf)
    #15 0x564d7f92f308 in _start (/usr/bin/radare2+0x6308)

0x61200000bfc1 is located 0 bytes to the right of 257-byte region [0x61200000bec0,0x61200000bfc1)
allocated by thread T0 here:
    #0 0x7f0567dd7b49 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98b49)
    #1 0x7f05677e62ed in r_core_init /home/sk/radare2/libr/core/core.c:1488
    #2 0x564d7f930d1d in main /home/sk/radare2/binr/radare2/radare2.c:442
    #3 0x7f0562446abf in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20abf)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 __asan_memset
Shadow bytes around the buggy address:
  0x0c247fff97a0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c247fff97b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c247fff97c0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa
  0x0c247fff97d0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c247fff97e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c247fff97f0: 00 00 00 00 00 00 00 00[01]fa fa fa fa fa fa fa
  0x0c247fff9800: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c247fff9810: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c247fff9820: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa
  0x0c247fff9830: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c247fff9840: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==5774==ABORTING

,r2 -v 2>/dev/null 
radare2 1.3.0-git 13792 @ linux-x86-64 git.1.2.0-145-gea5740d
commit: ea5740da573bc4b1f2a0e9a3a6b80e1d6b6632a9 build: 2017-02-13__01:30:12
```

**Comment by condret** [comment]
does it overflow on siol, too?

**Comment by radare** [comment]
the bug was not in IO, so it will crash in siol too :P its fixed now
