### ISSUE TITLE
Cf segfault

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#6846]
```
,echo "Cf -1 %1$*269168" | r2 -qn  -
Segmentation fault
,echo "Cf" | r2 -qn  -
Usage: Cf [size] [pf-format-string]






,gdb -q r2 core
Fri Feb 24 21:38:21 CET 2017
Reading symbols from r2...done.

warning: core file may not match specified executable file.
[New LWP 1351]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `r2 -qn -'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:238
238     ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:238
#1  0x00007f01ddce3c70 in r_print_format (p=0x562a3b7a10c0, seek=0, b=0x562a3b79c0d0 "", len=1265391, formatname=0x562a3b79c073 "%1269168", mode=0, setval=0x0, ofield=0x0)
    at p_format.c:1495
#2  0x00007f01e18339b2 in cmd_meta_hsdmf (core=0x562a3a5d65a0 <r>, input=0x562a3b79c031 "f -1 %1269168") at cmd_meta.c:502
#3  0x00007f01e1834707 in cmd_meta (data=0x562a3a5d65a0 <r>, input=0x562a3b79c031 "f -1 %1269168") at cmd_meta.c:780
#4  0x00007f01e18a1d05 in r_cmd_call (cmd=0x562a3b80cb40, input=0x562a3b79c030 "Cf -1 %1269168") at cmd_api.c:226
#5  0x00007f01e1865f28 in r_core_cmd_subst_i (core=0x562a3a5d65a0 <r>, cmd=0x562a3b79c030 "Cf -1 %1269168", colon=0x0) at cmd.c:2082
#6  0x00007f01e1863517 in r_core_cmd_subst (core=0x562a3a5d65a0 <r>, cmd=0x562a3b79c030 "Cf -1 %1269168") at cmd.c:1359
#7  0x00007f01e1867e7f in r_core_cmd (core=0x562a3a5d65a0 <r>, cstr=0x562a3b84b2b0 "Cf -1 %1269168", log=1) at cmd.c:2656
#8  0x00007f01e17f1142 in r_core_prompt_exec (r=0x562a3a5d65a0 <r>) at core.c:1876
#9  0x0000562a3a3d33ef in main (argc=3, argv=0x7ffff9985858, envp=0x7ffff9985878) at radare2.c:1165
(gdb) l
233     in ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S


```

**Comment by VisualPrankDude** [comment]
```
#0  0x00007f801fe6a978 in ?? ()
(gdb) l
386             r_core_cmdf (core, "o %s", f);
387     }
388
389     void r2_asmjs_openurl(void *kore, const char *url) {
390             const char *file = r_str_lchr (url, '/');
391             if (kore) {
392                     core = kore;
393             }
394             if (file) {
395                     emscripten_async_wget (url, file + 1, wget_cb, NULL);
```

**Comment by VisualPrankDude** [comment]
> r2 -v
radare2 1.3.0-git 13882 @ linux-x86-64 git.1.2.0-216-g20c079d
commit: 20c079d5b3d8a08f95caf3d76ca9ead9acc37519 build: 2017-02-24__20:38:48

**Comment by radare** [comment]
cant reproduce

**Comment by VisualPrankDude** [comment]
@radare echo "Cf -1 %1$*269168" | r2 -qn  - on Linux  with current r2?

**Comment by Maijin** [comment]
can't reproduce on OSX so maybe linux only?

**Comment by VisualPrankDude** [comment]
might be, it is somehow ironic

**Comment by alvarofe** [comment]
I could, let see if I can fix it before going to bed

```
air:r2 alvaro$ echo "Cf -1 %1$*269168" | r2 -qn -
=================================================================
==83361==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61200000be41 at pc 0x000112b089eb bp 0x7fff5077e610 sp 0x7fff5077ddd0
READ of size 1265391 at 0x61200000be41 thread T0
    #0 0x112b089ea in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib+0x419ea)
    #1 0x1128a4ecf in r_print_format p_format.c:1495
    #2 0x10f655924 in cmd_meta_hsdmf .cmd_meta.c:502
    #3 0x10f5a9745 in cmd_meta .cmd_meta.c:780
    #4 0x10f72d995 in r_cmd_call cmd_api.c:226
    #5 0x10f5cdda8 in r_core_cmd_subst_i cmd.c:2082
    #6 0x10f5571e0 in r_core_cmd_subst cmd.c:1359
    #7 0x10f550bbb in r_core_cmd cmd.c:2656
    #8 0x10f52892c in r_core_prompt_exec core.c:1878
    #9 0x10f4839d5 in main radare2.c:1165
    #10 0x7fff9a6c15ac in start (libdyld.dylib+0x35ac)

ASAN:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

**Comment by alvarofe** [comment]
Would be nice to add this as test on r2r
