### ISSUE TITLE
Null pointer dereference in dex_parse_debug_item()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#6872]
**Null pointer dereference in dex_parse_debug_item()**

Tested on Git HEAD: 0744e334429cc00cef937a87f89b8c3429152d11

Payload (bins/fuzzed/r2_nullptr_dex_parse_debug_item) in https://github.com/radare/radare2-regressions/pull/719

To reproduce: `r2 -A r2_nullptr_dex_parse_debug_item`

```
==2753==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f223d2c1756 bp 0x7ffd259196c0 sp 0x7ffd25820d60 T0)
==2753==The signal is caused by a READ memory access.
==2753==Hint: address points to the zero page.
    #0 0x7f223d2c1755 in dex_parse_debug_item XYZ/radare2/libr/..//libr/bin/p/bin_dex.c:380:15
    #1 0x7f223d2c062b in parse_dex_class_method XYZ/radare2/libr/..//libr/bin/p/bin_dex.c:1255:5
    #2 0x7f223d2bc6c4 in parse_class XYZ/radare2/libr/..//libr/bin/p/bin_dex.c:1387:7
    #3 0x7f223d2baa89 in dex_loadcode XYZ/radare2/libr/..//libr/bin/p/bin_dex.c:1483:4
    #4 0x7f223d2b6d27 in entries XYZ/radare2/libr/..//libr/bin/p/bin_dex.c:1610:3
    #5 0x7f223d2898da in r_bin_object_set_items XYZ/radare2/libr/bin/bin.c:617:16
    #6 0x7f223d28206c in r_bin_object_new XYZ/radare2/libr/bin/bin.c:1240:2
    #7 0x7f223d28104c in r_bin_file_new_from_bytes XYZ/radare2/libr/bin/bin.c:1428:6
    #8 0x7f223d280a77 in r_bin_load_io_at_offset_as_sz XYZ/radare2/libr/bin/bin.c:974:13
    #9 0x7f223d27f536 in r_bin_load_io_at_offset_as XYZ/radare2/libr/bin/bin.c:988:12
    #10 0x7f223d27f3f7 in r_bin_load_io XYZ/radare2/libr/bin/bin.c:831:9
    #11 0x7f223e24cb98 in r_core_file_do_load_for_io_plugin XYZ/radare2/libr/core/file.c:429:7
    #12 0x7f223e24ae2f in r_core_bin_load XYZ/radare2/libr/core/file.c:552:4
    #13 0x557585b4e46e in main XYZ/radare2/binr/radare2/radare2.c:898:14
    #14 0x7f223793b82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #15 0x557585a80cb8 in _start (/usr/local/bin/radare2+0x20cb8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV XYZ/radare2/libr/..//libr/bin/p/bin_dex.c:380:15 in dex_parse_debug_item
==2753==ABORTING
```

**Comment by Maijin** [comment]
Merge the test too @h4ng3r

**Comment by Maijin** [comment]
Could you write an article on radare.today or something about the process of findings and reporting those CVE (purpose, how to find etc.)
