### ISSUE TITLE
iI command on elfs results in segfault on Windows

### ISSUE THREAD

**Issue by wargio** [radare/radare2#6935]
```
(gdb) r
Starting program: radare2 -c iI -q radare2-regressions/bins/elf/true32
[New Thread 1856.0xaf0]
[New Thread 1856.0x1d90]

Program received signal SIGSEGV, Segmentation fault.
0x000000006fa1c938 in pair (a=0x6faa6df1 "intrp", b=0xabababababababab <error: Cannot access memory at address 0xabababababababab>, mode=0, last=false) at cbin.c:22
22              if (!b || !(*b)) {
(gdb) bt
#0  0x000000006fa1c938 in pair (a=0x6faa6df1 "intrp", b=0xabababababababab <error: Cannot access memory at address 0xabababababababab>, mode=0, last=false) at cbin.c:22
#1  0x000000006fa1cb30 in pair_str (a=0x6faa6df1 "intrp", b=0xabababababababab <error: Cannot access memory at address 0xabababababababab>, mode=0, last=0) at cbin.c:54
#2  0x000000006fa1edcc in bin_info (r=0x40d060 <r>, mode=0) at cbin.c:682
#3  0x000000006fa26859 in r_core_bin_info (core=0x40d060 <r>, action=2, mode=0, va=1, filter=0x0, chksum=0x0) at cbin.c:2728
#4  0x000000006f9c7aba in cmd_info (data=0x40d060 <r>, input=0x333bca1 "I") at cmd_info.c:422
#5  0x000000006fa2ded4 in r_cmd_call (cmd=0x32cd010, input=0x333bca0 "iI") at cmd_api.c:226
#6  0x000000006f9f3173 in r_core_cmd_subst_i (core=0x40d060 <r>, cmd=0x333bca0 "iI", colon=0x0) at cmd.c:2066
#7  0x000000006f9f0818 in r_core_cmd_subst (core=0x40d060 <r>, cmd=0x333bca0 "iI") at cmd.c:1341
#8  0x000000006f9f4f82 in r_core_cmd (core=0x40d060 <r>, cstr=0x2e6480 "iI", log=0) at cmd.c:2622
#9  0x000000006f9f5596 in r_core_cmd0 (user=0x40d060 <r>, cmd=0x2e6480 "iI") at cmd.c:2768
#10 0x0000000000401f12 in run_commands (cmds=0x2e6540, files=0x2e65e0, quiet=true) at radare2.c:333
#11 0x00000000004043a6 in main (argc=5, argv=0x2e2940, envp=0x2e2c20) at radare2.c:1111
(gdb)

```

**Comment by wargio** [comment]
this needs to be checked on linux/osx
