### ISSUE TITLE
Segmentation fault on /c/ with a regexp ending with \

### ISSUE THREAD

**Issue by Gophys** [radare/radare2#7150]
When using r2, if you try to launch the /c/ command and that your regexp end with a trailing \ r2 crashes into a segfault.

Maybe other regexp based command are impacted with the same issue?

GDB backtrace:

``` 
[0x00003000]> /c/ \

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3f77892 in r_regex_fini (preg=0x0) at regex/regcomp.c:187
187		if (preg->re_magic != MAGIC1)	/* oops */
(gdb) bt
#0  0x00007ffff3f77892 in r_regex_fini (preg=0x0) at regex/regcomp.c:187
#1  0x00007ffff3f77942 in r_regex_free (preg=0x0) at regex/regcomp.c:204
#2  0x00007ffff7b55410 in r_core_asm_strsearch (core=0x7ffff81ff900, 
    input=0x7ffff8305143 " \\", from=2129920, to=2530456, maxhits=0, regexp=1)
    at asm.c:132
#3  0x00007ffff7afe6e6 in do_asm_search (core=0x7ffff81ff900, 
    param=0x7fffffffd0c0, input=0x7ffff8305141 "c/ \\") at cmd_search.c:1861
#4  0x00007ffff7b02234 in cmd_search (data=0x7ffff81ff900, 
    input=0x7ffff8305141 "c/ \\") at cmd_search.c:2900
#5  0x00007ffff7b43d83 in r_cmd_call (cmd=0x7ffff82e7e90, 
    input=0x7ffff8305140 "/c/ \\") at cmd_api.c:226
#6  0x00007ffff7b092a3 in r_core_cmd_subst_i (core=0x7ffff81ff900, 
    cmd=0x7ffff8305140 "/c/ \\", colon=0x0) at cmd.c:2149
#7  0x00007ffff7b067df in r_core_cmd_subst (core=0x7ffff81ff900, 
    cmd=0x7ffff8305140 "/c/ \\") at cmd.c:1342
#8  0x00007ffff7b0b37d in r_core_cmd (core=0x7ffff81ff900, 
    cstr=0x7ffff832e040 "/c/ \\", log=1) at cmd.c:2727
#9  0x00007ffff7a955f0 in r_core_prompt_exec (r=0x7ffff81ff900) at core.c:1909
#10 0x00007ffff7ffd380 in main (argc=2, argv=0x7fffffffde18, 
    envp=0x7fffffffde30) at radare2.c:1192
```

**Comment by Maijin** [comment]
Use markdown formatting:

```
CODE
```

![image](https://cloud.githubusercontent.com/assets/1408600/24345759/e0ef883e-12d1-11e7-9fa3-2b7dac5045f9.png)

**Comment by alvarofe** [comment]
You can edit his message, I added it

**Comment by Maijin** [comment]
This is for next time :P
