### ISSUE TITLE
can provoke a segfault

### ISSUE THREAD

**Issue by holgerschurig** [radare/radare2#7151]
I can provoke a segfault easily:

````
wget ftp://ftp.elecraft.com/KX3/firmware/fmcu0270.hex 
r2 -a pic18c fmcu0270.hex -c pd
r2 -a pic18c ihex://fmcu0270.hex -c pd
````

* radare is from git 1.3.0-188-g2ce093b (today's top-of-tree)
* my `.radare2rc` is empty
* the microcontroller for this firmware file is actually a PIC 18**F**87K22, but this shouldn't create a segfault

This is the backtrace:

```
schurig@xps15:~/a/kx3fw$ gdb --args /usr/src/radare2/dist/bin/r2 -a pic18c ihex://fmcu0270.hex -c pd
Reading symbols from /usr/src/radare2/dist/bin/r2...done.
(gdb) r
Starting program: /usr/src/radare2/dist/bin/r2 -a pic18c ihex://fmcu0270.hex -c pd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0xf6b66b86 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
(gdb) bt
#0  0xf6b66b86 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#1  0xf6cf4bc8 in ht_find_kv (ht=0x56618820, key=0x0, found=0xffffc1ab) at ht.c:248
#2  0xf6cf4cc6 in ht_find (ht=0x56618820, key=0x0, found=0xffffc1ab) at ht.c:280
#3  0xf6d7f3f1 in r_flag_get (f=0x566181a0, name=0x0) at flag.c:319
#4  0xf7f7463b in r_core_print_disasm (p=0x565c2018, core=0x5655d200 <r>, addr=0, 
    buf=0x566543c0 "\222\357\001\360\022", len=70, l=7, invbreak=0, cbytes=0) at disasm.c:3478
#5  0xf7f010c7 in cmd_print (data=0x5655d200 <r>, input=0x56652189 "d") at cmd_print.c:3692
#6  0xf7f4ec26 in r_cmd_call (cmd=0x56622760, input=0x56652188 "pd") at cmd_api.c:226
#7  0xf7f195a2 in r_core_cmd_subst_i (core=0x5655d200 <r>, cmd=0x56652188 "pd", colon=0x0) at cmd.c:2149
#8  0xf7f1736e in r_core_cmd_subst (core=0x5655d200 <r>, cmd=0x56652188 "pd") at cmd.c:1342
#9  0xf7f1af70 in r_core_cmd (core=0x5655d200 <r>, cstr=0xffffd7fa "pd", log=0) at cmd.c:2727
#10 0xf7f1b50e in r_core_cmd0 (user=0x5655d200 <r>, cmd=0xffffd7fa "pd") at cmd.c:2873
#11 0x56557bde in run_commands (cmds=0x565be008, files=0x565be038, quiet=false) at radare2.c:348
#12 0x56559ed0 in main (argc=6, argv=0xffffd664, envp=0xffffd680) at radare2.c:1139
```

**Comment by alvarofe** [comment]
```
[alvaro@alvaro tmp]$ valgrind r2 -a pic18c fmcu0270.hex -c pd                                                                                                                 
==29173== Memcheck, a memory error detector                                                                                                                                   
==29173== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.                                                                                                     
==29173== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info                                                                                              
==29173== Command: r2 -a pic18c fmcu0270.hex -c pd                                                                                                                            
==29173==                                                                                                                                                                     
==29173== Invalid read of size 1                                                                                                                                              
==29173==    at 0x4C2FD32: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)                                                                                    
==29173==    by 0x8AAF2C6: ht_find_kv (ht.c:248)                                                                                                                              
==29173==    by 0x8AAF3FE: ht_find (ht.c:280)                                                                                                                                 
==29173==    by 0x83F2B2D: r_flag_get (flag.c:319)                                                                                                                            
==29173==    by 0x4F62718: r_core_print_disasm (disasm.c:3519)                                                                                                                
==29173==    by 0x4EDFC3D: cmd_print (cmd_print.c:3692)                                                                                                                       
==29173==    by 0x4F38134: r_cmd_call (cmd_api.c:226)
==29173==    by 0x4EFBBD3: r_core_cmd_subst_i (cmd.c:2149)
==29173==    by 0x4EF90FC: r_core_cmd_subst (cmd.c:1342)
==29173==    by 0x4EFDD62: r_core_cmd (cmd.c:2727)
==29173==    by 0x4EFE3FD: r_core_cmd0 (cmd.c:2873)
==29173==    by 0x10B676: run_commands (radare2.c:348)
==29173==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==29173==
==29173==
==29173== Process terminating with default action of signal 11 (SIGSEGV)
==29173==  Access not within mapped region at address 0x0
==29173==    at 0x4C2FD32: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29173==    by 0x8AAF2C6: ht_find_kv (ht.c:248)
==29173==    by 0x8AAF3FE: ht_find (ht.c:280)
==29173==    by 0x83F2B2D: r_flag_get (flag.c:319)
==29173==    by 0x4F62718: r_core_print_disasm (disasm.c:3519)
==29173==    by 0x4EDFC3D: cmd_print (cmd_print.c:3692)
==29173==    by 0x4F38134: r_cmd_call (cmd_api.c:226)
==29173==    by 0x4EFBBD3: r_core_cmd_subst_i (cmd.c:2149)
==29173==    by 0x4EF90FC: r_core_cmd_subst (cmd.c:1342)
==29173==    by 0x4EFDD62: r_core_cmd (cmd.c:2727)
==29173==    by 0x4EFE3FD: r_core_cmd0 (cmd.c:2873)
==29173==    by 0x10B676: run_commands (radare2.c:348)
==29173==  If you believe this happened as a result of a stack
==29173==  overflow in your program's main thread (unlikely but
==29173==  possible), you can try to increase the size of the
==29173==  main thread stack using the --main-stacksize= flag.
==29173==  The main thread stack size used in this run was 8388608.
```

Will dump sdb tonight I have some fixes in local iirc but left my dev laptop at home.

**Comment by alvarofe** [comment]
Fixed. Test again please
