### ISSUE TITLE
debug and agv

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#7270]
@pancake morrn,

```
[0x7f79c60ddcd0]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x7f79c60ddcd0]> agv
No function in current seek
[0x7f79c60ddcd0]> af
[0x7f79c60ddcd0]> agv
pid 13794: killed by signal 11
> core  serverauth.xO2AL8gMiz

> q
q: No such file or directory

> gdb -q r2 core
Fri Apr 14 09:15:57 CEST 2017
Reading symbols from r2...done.

warning: core file may not match specified executable file.
[New LWP 13786]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `r2 -d /bin/ls'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
40      ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
#1  0x00007efc5d3cfb66 in ds_print_ptr (ds=0x557cc9955c70, len=327, idx=47) at disasm.c:2685
#2  0x00007efc5d3d3e95 in r_core_print_disasm (p=0x557cc9475140, core=0x557cc871e5a0 <r>, addr=139904657067216, buf=0x557cc9470160 "H\211\347\350h?", len=71, l=71, 
    invbreak=0, cbytes=1) at disasm.c:3691
#3  0x00007efc5d34fe92 in cmd_print (data=0x557cc871e5a0 <r>, input=0x557cc9943301 "D 71") at cmd_print.c:3839
#4  0x00007efc5d3a89c7 in r_cmd_call (cmd=0x557cc94f85a0, input=0x557cc9943300 "pD 71") at cmd_api.c:226
#5  0x00007efc5d36b79a in r_core_cmd_subst_i (core=0x557cc871e5a0 <r>, cmd=0x557cc9943300 "pD 71", colon=0x0) at cmd.c:2108
#6  0x00007efc5d368efe in r_core_cmd_subst (core=0x557cc871e5a0 <r>, cmd=0x557cc9943300 "pD 71") at cmd.c:1342
#7  0x00007efc5d36db5b in r_core_cmd (core=0x557cc871e5a0 <r>, cstr=0x7ffcf27d86d0 "pD 71 @ 0x7f3e17630cd0", log=0) at cmd.c:2730
#8  0x00007efc5d36e4b2 in r_core_cmd_str (core=0x557cc871e5a0 <r>, cmd=0x7ffcf27d86d0 "pD 71 @ 0x7f3e17630cd0") at cmd.c:2928
#9  0x00007efc5d36e456 in r_core_cmd_strf (core=0x557cc871e5a0 <r>, fmt=0x7efc5d412237 "%s %d @ 0x%08llx") at cmd.c:2918
#10 0x00007efc5d38f36c in get_body (core=0x557cc871e5a0 <r>, addr=139904657067216, size=71, opts=0) at graph.c:1770
#11 0x00007efc5d38f4e2 in get_bb_body (core=0x557cc871e5a0 <r>, b=0x557cc98d9c70, opts=0, fcn=0x557cc98c69b0, emu=false, saved_gp=0, saved_arena=0x0) at graph.c:1797
#12 0x00007efc5d38fb5c in get_bbnodes (g=0x557cc9903270, core=0x557cc871e5a0 <r>, fcn=0x557cc98c69b0) at graph.c:1919
#13 0x00007efc5d3901d2 in reload_nodes (g=0x557cc9903270, core=0x557cc871e5a0 <r>, fcn=0x557cc98c69b0) at graph.c:2057
#14 0x00007efc5d3915a3 in agraph_reload_nodes (g=0x557cc9903270, core=0x557cc871e5a0 <r>, fcn=0x557cc98c69b0) at graph.c:2456
#15 0x00007efc5d391a52 in check_changes (g=0x557cc9903270, is_interactive=0, core=0x557cc871e5a0 <r>, fcn=0x557cc98c69b0) at graph.c:2556
#16 0x00007efc5d391d47 in agraph_print (g=0x557cc9903270, is_interactive=0, core=0x557cc871e5a0 <r>, fcn=0x557cc98c69b0) at graph.c:2607
#17 0x00007efc5d392158 in agraph_refresh (grd=0x557cc9943040) at graph.c:2692
#18 0x00007efc5d393bc3 in r_core_visual_graph (core=0x557cc871e5a0 <r>, g=0x557cc9903270, _fcn=0x0, is_interactive=0) at graph.c:3145
#19 0x00007efc5d32ff0c in cmd_anal_graph (core=0x557cc871e5a0 <r>, input=0x557cc9903152 "f") at cmd_anal.c:4672
#20 0x00007efc5d33352d in cmd_anal (data=0x557cc871e5a0 <r>, input=0x557cc9903151 "gf") at cmd_anal.c:5609
#21 0x00007efc5d3a89c7 in r_cmd_call (cmd=0x557cc94f85a0, input=0x557cc9903150 "agf") at cmd_api.c:226
#22 0x00007efc5d36b9d5 in r_core_cmd_subst_i (core=0x557cc871e5a0 <r>, cmd=0x557cc9903150 "agf", colon=0x0) at cmd.c:2149
#23 0x00007efc5d368efe in r_core_cmd_subst (core=0x557cc871e5a0 <r>, cmd=0x557cc9903150 "agf") at cmd.c:1342
#24 0x00007efc5d36db5b in r_core_cmd (core=0x557cc871e5a0 <r>, cstr=0x557cc9531860 "agf", log=0) at cmd.c:2730
#25 0x00007efc5d36e20f in r_core_cmd0 (user=0x557cc871e5a0 <r>, cmd=0x557cc9531860 "agf") at cmd.c:2878
#26 0x00007efc5d3304ac in cmd_anal_graph (core=0x557cc871e5a0 <r>, input=0x557cc9904942 "v") at cmd_anal.c:4744
#27 0x00007efc5d33352d in cmd_anal (data=0x557cc871e5a0 <r>, input=0x557cc9904941 "gv") at cmd_anal.c:5609
#28 0x00007efc5d3a89c7 in r_cmd_call (cmd=0x557cc94f85a0, input=0x557cc9904940 "agv") at cmd_api.c:226
#29 0x00007efc5d36b9d5 in r_core_cmd_subst_i (core=0x557cc871e5a0 <r>, cmd=0x557cc9904940 "agv", colon=0x0) at cmd.c:2149
#30 0x00007efc5d368efe in r_core_cmd_subst (core=0x557cc871e5a0 <r>, cmd=0x557cc9904940 "agv") at cmd.c:1342
#31 0x00007efc5d36db5b in r_core_cmd (core=0x557cc871e5a0 <r>, cstr=0x557cc9487d40 "agv", log=1) at cmd.c:2730
#32 0x00007efc5d2f2706 in r_core_prompt_exec (r=0x557cc871e5a0 <r>) at core.c:1910
#33 0x0000557cc851b5a9 in main (argc=3, argv=0x7ffcf27db798, envp=0x7ffcf27db7b8) at radare2.c:1198
(gdb) !r2 -v
radare2 1.4.0-git 14474 @ linux-x86-64 git.1.3.0-370-gc6049ab
commit: c6049ab42d8705da9c4bec7d229fd1940413c524 build: 2017-04-14__08:57:12
```

valgrind: 

http://sprunge.us/ENWH

======

=954== Process terminating with default action of signal 11 (SIGSEGV)
==954==  Access not within mapped region at address 0x0
==954==    at 0x4C33544: strstr (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==954==    by 0x4F60B65: ds_print_ptr (disasm.c:2685)
==954==    by 0x4F64E94: r_core_print_disasm (disasm.c:3691)
==954==    by 0x4EE0E91: cmd_print (cmd_print.c:3839)
==954==    by 0x4F399C6: r_cmd_call (cmd_api.c:226)
==954==    by 0x4EFC799: r_core_cmd_subst_i (cmd.c:2108)
==954==    by 0x4EF9EFD: r_core_cmd_subst (cmd.c:1342)
==954==    by 0x4EFEB5A: r_core_cmd (cmd.c:2730)
==954==    by 0x4EFF4B1: r_core_cmd_str (cmd.c:2928)
==954==    by 0x4EFF455: r_core_cmd_strf (cmd.c:2918)
==954==    by 0x4F2036B: get_body (graph.c:1770)
==954==    by 0x4F204E1: get_bb_body (graph.c:1797)
==954==  If you believe this happened as a result of a stack
==954==  overflow in your program's main thread (unlikely but
==954==  possible), you can try to increase the size of the
==954==  main thread stack using the --main-stacksize= flag.
==954==  The main thread stack size used in this run was 8388608.
==954== 
==954== HEAP SUMMARY:
==954==     in use at exit: 5,001,005 bytes in 77,930 blocks
==954==   total heap usage: 397,650 allocs, 319,720 frees, 334
...

**Comment by radare** [comment]
should be fixed in master
