### ISSUE TITLE
Null pointer dereference - Missing string check and in dex_method_fullname()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#8049]
**Null pointer dereference - Missing string check and in dex_method_fullname()**

Git HEAD: 933c6737fe8b93033443fa4b51b1f22718b7e588

Payload (bins/fuzzed/r2_nullptr_string_dex_method_fullname) in https://github.com/radare/radare2-regressions/pull/932

To reproduce: `r2 -A r2_nullptr_string_dex_method_fullname`

ASAN:

```
==19266==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fdb4f14f8c6 bp 0x7ffdec8ea300 sp 0x7ffdec8e9a88 T0)
==19266==The signal is caused by a READ memory access.
==19266==Hint: address points to the zero page.
    #0 0x7fdb4f14f8c5 in __GI_strlen (/usr/lib/libc.so.6+0x828c5)
    #1 0x55a6d1e4781f in __strdup (/usr/local/bin/radare2+0x7781f)
    #2 0x7fdb54f539ce in dex_method_fullname XYZ/radare2/libr/..//libr/bin/p/bin_dex.c:935:21
    #3 0x7fdb51b27728 in dalvik_disassemble XYZ/radare2/libr/asm/p/asm_dalvik.c:407:16
    #4 0x7fdb51bce250 in r_asm_disassemble XYZ/radare2/libr/asm/asm.c:389:9
    #5 0x7fdb55fb9068 in r_core_anal_op XYZ/radare2/libr/core/canal.c:774:6
    #6 0x7fdb55fbef02 in fcn_callconv XYZ/radare2/libr/core/canal.c:2289:9
    #7 0x7fdb55fc3676 in r_core_anal_all XYZ/radare2/libr/core/canal.c:2868:5
    #8 0x7fdb55eff273 in cmd_anal_all XYZ/radare2/libr/core/./cmd_anal.c:5387:4
    #9 0x7fdb55eb98c8 in cmd_anal XYZ/radare2/libr/core/./cmd_anal.c:5705:8
    #10 0x7fdb55fb54d5 in r_cmd_call XYZ/radare2/libr/core/cmd_api.c:226:10
    #11 0x7fdb55ef180d in r_core_cmd_subst_i XYZ/radare2/libr/core/cmd.c:2198:12
    #12 0x7fdb55eb64b7 in r_core_cmd_subst XYZ/radare2/libr/core/cmd.c:1396:9
    #13 0x7fdb55eb30d6 in r_core_cmd XYZ/radare2/libr/core/cmd.c:2806:9
    #14 0x55a6d1ee70f9 in main XYZ/radare2/binr/radare2/radare2.c
    #15 0x7fdb4f0ed4c9 in __libc_start_main (/usr/lib/libc.so.6+0x204c9)
    #16 0x55a6d1df0d09 in _start (/usr/local/bin/radare2+0x20d09)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/libc.so.6+0x828c5) in __GI_strlen
==19266==ABORTING
```

**Comment by radare** [comment]
Fixed in 60d062286be629531aeae135697d816021152771

this bug shouldnt be in 1.6, this change was introduced recently on a wip refactoring. thanks for reporting
