### ISSUE TITLE
Null pointer dereference in sdb_set_internal()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#8059]
**Null pointer dereference in sdb_set_internal()**

Git HEAD: 054d35b57039480ba76fb6aac4e6c0cc75652c4d

Payload (bins/fuzzed/r2_nullptr_sdb_set_internal) in https://github.com/radare/radare2-regressions/pull/934

To reproduce: `r2 -A r2_nullptr_sdb_set_internal`

ASAN:

```
==1075==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x7f272e0868c6 bp 0x7fff07992e90 sp 0x7fff07992618 T0)
==1075==The signal is caused by a READ memory access.
==1075==Hint: address points to the zero page.
    #0 0x7f272e0868c5 in __GI_strlen (/usr/lib/libc.so.6+0x828c5)
    #1 0x55b9735b4f4c in __interceptor_strlen.part.30 (/usr/local/bin/radare2+0x52f4c)
    #2 0x7f272f0748a4 in sdb_set_internal XYZradare2/shlr/sdb/src/sdb.c:562:9
    #3 0x7f272f072c0f in sdb_set XYZradare2/shlr/sdb/src/sdb.c:631:9
    #4 0x7f2733e56744 in r_bin_dwarf_parse_comp_unit XYZradare2/libr/bin/dwarf.c:1339:5
    #5 0x7f2733e55d2b in r_bin_dwarf_parse_info_raw XYZradare2/libr/bin/dwarf.c:1398:9
    #6 0x7f2733e56e9e in r_bin_dwarf_parse_info XYZradare2/libr/bin/dwarf.c:1526:9
    #7 0x7f2734ed5a68 in bin_dwarf XYZradare2/libr/core/cbin.c:810:3
    #8 0x7f2734ed24fe in r_core_bin_info XYZradare2/libr/core/cbin.c:2898:46
    #9 0x7f2734ed22ba in r_core_bin_set_env XYZradare2/libr/core/cbin.c:118:3
    #10 0x7f2734e92785 in r_core_file_do_load_for_io_plugin XYZradare2/libr/core/file.c:437:2
    #11 0x7f2734e90870 in r_core_bin_load XYZradare2/libr/core/file.c:591:4
    #12 0x55b973678385 in main XYZradare2/binr/radare2/radare2.c:951:14
    #13 0x7f272e0244c9 in __libc_start_main (/usr/lib/libc.so.6+0x204c9)
    #14 0x55b973582d09 in _start (/usr/local/bin/radare2+0x20d09)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/libc.so.6+0x828c5) in __GI_strlen
==1075==ABORTING
```

**Comment by radare** [comment]
this is not a null deref, and the bug is not in sdb_set.

the problem was because an union was initialized incorrectly when handling unknown DW_FORM types, this caused the union to contain a pointer to a string at address 0x30. Which make sdb crash when trying to unboxing that pointer as a string.

The fix implied adding an error checking returning null instead of the wrong Form, and handling that null case at time before the disaster happens later.

thanks for reporting
