### ISSUE TITLE
r2 crashes on trying to attach to qemu-arm gdb stub

### ISSUE THREAD

**Issue by extremecoders-re** [radare/radare2#8083]
Radare version:
```
$ r2 -version
radare2 1.7.0-git 270 @ linux-x86-32 git.1.6.0-198-g5da2238
commit: 5da2238b7bbf880aafdc8d72935481b034b3f1d0 build: 2017-08-01__14:06:28
```

I am debugging an arm binary using `qemu-arm` gdb stub. It's invoked as:
```
$ file ./example
./example: ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=05ce81d7ab5ca4c68fe32cefca7a92a3813cad43, not stripped

$ qemu-arm-static -g 23946 ./example
```

Now, trying to connect `r2` to the port results in a crash while on the other terminal `qemu` segfaults.
```
$ r2 -a arm -b 32 -D gdb gdb://127.0.0.1:23946
= attach 1 1
Floating point exception (core dumped)
```

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
```

If instead of `r2` I use `gdb-multiarch`, I can debug normally
```
$ gdb-multiarch -q
Loaded 108 commands. Type pwndbg [filter] for a list.
pwndbg> set arch arm
The target architecture is assumed to be arm
pwndbg> file example
Reading symbols from example...(no debugging symbols found)...done.
pwndbg> target remote :23946
Remote debugging using :23946
0x00008b98 in _start ()
```

### example.c
```c
$ cat ./example.c 
#include <string.h>
#include <stdio.h>

void main()
{
	char buffer[10];
	gets("Enter something");
	gets(buffer);
	puts("----");
	puts(buffer);
}
```

This was compiled using
```
$ arm-linux-gnueabi-gcc -static -fno-stack-protector example.c -o example
```

**Comment by radare** [comment]
i dont see any backtrace or crashlog here

**Comment by extremecoders-re** [comment]
I recompiled r2 with debugging symbols.

Here is the backtrace.
```
(gdb)  bt
#0  0xb6c208f4 in __udivdi3 () from /home/ec/bin/prefix/radare2/lib/libr_io.so
#1  0xb6c159e9 in gdbr_read_memory (g=0xb87fb208, address=0x8b98, len=0x100) at src/gdbclient/core.c:505
#2  0xb6be648b in debug_gdb_read_at (buf=0xb8745068 '\377' <repeats 256 times>, sz=0x100, addr=0x8b98) at p/io_gdb.c:43
#3  0xb6be6bb0 in __read (io=0xb87a23b0, fd=0xb87fcd88, buf=0xb8745068 '\377' <repeats 256 times>, count=0x100) at p/io_gdb.c:185
#4  0xb6bf5923 in r_io_read_internal (io=0xb87a23b0, buf=0xb8745068 '\377' <repeats 256 times>, len=0x100) at io.c:311
#5  0xb6bf6589 in r_io_read_at (io=0xb87a23b0, addr=0x8b98, buf=0xb8745068 '\377' <repeats 256 times>, len=0x100) at io.c:509
#6  0xb7625ce6 in r_core_block_read (core=0xb7716320 <r>) at cio.c:453
#7  0xb762544d in r_core_seek (core=0xb7716320 <r>, addr=0x8b98, rb=0x1) at cio.c:294
#8  0xb75da7ba in seek_to_register (core=0xb7716320 <r>, input=0xb87f9c0b "PC", is_silent=0x0) at cmd_seek.c:208
#9  0xb75dab2f in cmd_seek (data=0xb7716320 <r>, input=0xb87f9c09 "r PC") at cmd_seek.c:270
#10 0xb764975a in r_cmd_call (cmd=0xb87b1d08, input=0xb87f9c08 "sr PC") at cmd_api.c:226
#11 0xb7606edb in r_core_cmd_subst_i (core=0xb7716320 <r>, cmd=0xb87f9c08 "sr PC", colon=0x0) at cmd.c:2223
#12 0xb7604619 in r_core_cmd_subst (core=0xb7716320 <r>, cmd=0xb87f9c08 "sr PC") at cmd.c:1421
#13 0xb7608f5a in r_core_cmd (core=0xb7716320 <r>, cstr=0xb76bb292 "sr PC", log=0x0) at cmd.c:2831
#14 0xb762469d in r_core_setup_debugger (r=0xb7716320 <r>, debugbackend=0xbfea110e "gdb", attach=0x1) at cio.c:43
#15 0xb7712346 in main (argc=0x8, argv=0xbfe9f3b4, envp=0xbfe9f3d8) at radare2.c:1072
```

```
(gdb)  bt full
#0  0xb6c208f4 in __udivdi3 () from /home/ec/bin/prefix/radare2/lib/libr_io.so
No symbol table info available.
#1  0xb6c159e9 in gdbr_read_memory (g=0xb87fb208, address=0x8b98, len=0x100) at src/gdbclient/core.c:505
        command = '\000' <repeats 63 times>
        ret = 0x0
        num_pkts = 0xb738ca48
        last = 0x100000001
        data_sz = 0x0
        ret_len = 0x1b738c890
        pkt = 0xb770c000
        __func__ = "gdbr_read_memory"
#2  0xb6be648b in debug_gdb_read_at (buf=0xb8745068 '\377' <repeats 256 times>, sz=0x100, addr=0x8b98) at p/io_gdb.c:43
        size_max = 0x800
        packets = 0x0
        last = 0x100
        x = 0x0
        ret = 0x0
---------------------------SNIP---------------------
```

Judging from the dump the crash is on **[this](https://github.com/radare/radare2/blob/5da2238b7bbf880aafdc8d72935481b034b3f1d0/shlr/gdb/src/gdbclient/core.c#L505)** line.

```c
data_sz = g->stub_features.pkt_sz / 2;
num_pkts = len / data_sz;
last = len % data_sz;
```
Looks like `data_sz` is `0` causing a division by zero exception.

**Comment by extremecoders-re** [comment]
Unfortunately the issue persists at the exact same location, `data_sz` is still zero.
```c
data_sz = g->stub_features.pkt_sz / 2;
num_pkts = len / data_sz;
last = len % data_sz;
```

```
Core was generated by `radare2 -a arm -b 32 -D gdb gdb://127.0.0.1:23946'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0xb6cafa34 in __udivdi3 () from /home/ec/bin/prefix/radare2/lib/libr_io.so
(gdb)  bt
#0  0xb6cafa34 in __udivdi3 () from /home/ec/bin/prefix/radare2/lib/libr_io.so
#1  0xb6ca4b26 in gdbr_read_memory (g=0xb81ef728, address=0x8b98, len=0x100) at src/gdbclient/core.c:511
#2  0xb6c7548b in debug_gdb_read_at (buf=0xb813b068 '\377' <repeats 256 times>, sz=0x100, addr=0x8b98) at p/io_gdb.c:43
#3  0xb6c75bb0 in __read (io=0xb81983b0, fd=0xb81fc4d8, buf=0xb813b068 '\377' <repeats 256 times>, count=0x100) at p/io_gdb.c:185
#4  0xb6c8495c in r_io_read_internal (io=0xb81983b0, buf=0xb813b068 '\377' <repeats 256 times>, len=0x100) at io.c:311
#5  0xb6c855c2 in r_io_read_at (io=0xb81983b0, addr=0x8b98, buf=0xb813b068 '\377' <repeats 256 times>, len=0x100) at io.c:509
#6  0xb76b7d67 in r_core_block_read (core=0xb77a8320 <r>) at cio.c:453
#7  0xb76b74ce in r_core_seek (core=0xb77a8320 <r>, addr=0x8b98, rb=0x1) at cio.c:294
#8  0xb766c7ba in seek_to_register (core=0xb77a8320 <r>, input=0xb81f2ccb "PC", is_silent=0x0) at cmd_seek.c:208
#9  0xb766cb2f in cmd_seek (data=0xb77a8320 <r>, input=0xb81f2cc9 "r PC") at cmd_seek.c:270
#10 0xb76db7db in r_cmd_call (cmd=0xb81a7d08, input=0xb81f2cc8 "sr PC") at cmd_api.c:226
#11 0xb7698f5c in r_core_cmd_subst_i (core=0xb77a8320 <r>, cmd=0xb81f2cc8 "sr PC", colon=0x0) at cmd.c:2223
#12 0xb769669a in r_core_cmd_subst (core=0xb77a8320 <r>, cmd=0xb81f2cc8 "sr PC") at cmd.c:1421
#13 0xb769afdb in r_core_cmd (core=0xb77a8320 <r>, cstr=0xb774d3d2 "sr PC", log=0x0) at cmd.c:2831
#14 0xb76b671e in r_core_setup_debugger (r=0xb77a8320 <r>, debugbackend=0xbfb1710e "gdb", attach=0x1) at cio.c:43
#15 0xb77a4346 in main (argc=0x8, argv=0xbfb15064, envp=0xbfb15088) at radare2.c:1072


gef➤  bt full 3
#0  0xb6cafa34 in __udivdi3 () from /home/ec/bin/prefix/radare2/lib/libr_io.so
No symbol table info available.
#1  0xb6ca4b26 in gdbr_read_memory (g=0xb81ef728, address=0x8b98, len=0x100) at src/gdbclient/core.c:511
        command = '\000' <repeats 63 times>
        ret = 0x0
        num_pkts = 0xb741ea48
        last = 0x100000001
        data_sz = 0x0
        ret_len = 0x1b741e890
        pkt = 0xb779e000
        __func__ = "gdbr_read_memory"
#2  0xb6c7548b in debug_gdb_read_at (buf=0xb813b068 '\377' <repeats 256 times>, sz=0x100, addr=0x8b98) at p/io_gdb.c:43
        size_max = 0x800
        packets = 0x0
        last = 0x100
        x = 0x0
        ret = 0x0
(More stack frames follow...)
```
The issue occurs both for `qemu` gdb stub as well as `gdbserver` on any architecture (tested with x86 and ARM)

## Steps to reproduce

1.  Run `gdbserver`

	```
    $ gdbserver --once :23946 /bin/ls
    Process /bin/ls created; pid = 28615
    Listening on port 23946
	```

2. On another terminal try to connect by `r2`

    ```
    $ r2 -a x86 -b 32 -D gdb gdb://127.0.0.1:23946
    = attach 28615 28615
    Floating point exception (core dumped)
    ```

**Comment by SrimantaBarua** [comment]
I'm unable to reproduce. Could you upload a pcap?

**Comment by extremecoders-re** [comment]
@SrimantaBarua @radare The issue has been fixed with the recent commits. Thanks again.

**Comment by extremecoders-re** [comment]
@SrimantaBarua The division by zero exception has been fixed. Thanks for that. However I feel there are rough edges here and there in the gdb remote client. 
For example, r2 can attach to a remote gdb instance but the debugging is not as smooth as the native implementation.

**Comment by radare** [comment]
local native debugging will be always faster than remote debugging, and also, gdb protocol is crap, so dont expect it to be as fast as any local debugger

**Comment by extremecoders-re** [comment]
@radare Sure. Now r2 can attach to qemu-arm gdb stub, but analysis is failing. Do you have any tips on how to do this ? Much appreciated.

```
$ r2 -a arm -b 32 -D gdb gdb://localhost:23946
= attach 1 1
 -- Press 'c' in visual mode to toggle the cursor mode
[0x00008b98]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
TODO: esil-vm not initialized
[ ] 
[aav: using from to 0x8b98 0x8b98
Using vmin 0x8b98 and vmax 0x8b98
Error: from must be lower than to
aav: using from to 0x8b98 0x8b98
Using vmin 0x8b98 and vmax 0x8b98
Error: from must be lower than to
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[x] Emulate code to find computed references (aae)
[Cannot find section boundaries in here
[x] Analyze consecutive function (aat)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Type matching analysis for all functions (afta)
[0x00008b98]> afl
0x00008b98    1 140          fcn.r15
[0x00008b98]> 
```

**Comment by SrimantaBarua** [comment]
Try `r2 -e dbg.exe.path=<path_to_binary> -a arm ....`.
Also speed will be improved once caching is implemented.
