### ISSUE TITLE
 rabin2 -rP ntkrnlmp.pdb

### ISSUE THREAD

**Issue by K2** [radare/radare2#8260]
I was checking out symbol support in radare2 and found a crash (feel free to use my [JSON symsrv](https://github.com/ShaneK2/inVtero.net/wiki/Linux-support) (I want to try add radare2 support for JSON symbol srv also))

From this version of nt kernel symbols => ntkrnlmp.pdb/DDA812F4AC284269AB8073D8423801A41

rabin2 -rP ntkrnlmp.pdb 

```
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff6c9a47e in __GI___strdup (s=0x0) at strdup.c:41
#2  0x00007ffff77b694a in parse_microsoft_mangled_name (sym=0x55555766eea1 "StDmRegionGetKeys@?$ST_STORE@USM_TRAITS@@@@SAJPEAU_ST_DATA_MGR@1@PEAU_STDM_SEARCH_RESULTS@1@KKKPEAT_SM_PAGE_KEY@@PEAK@Z",
    demangled_name=0x7ffffff9c9e8) at mangling/microsoft_demangle.c:1407
#3  0x00007ffff77b6a34 in microsoft_demangle (demangler=0x5555574ae0c0, demangled_name=0x7ffffff9c9e8) at mangling/microsoft_demangle.c:1431
#4  0x00007ffff7712638 in r_bin_demangle_msvc (str=0x555556fa20c0 "?StDmRegionGetKeys@?$ST_STORE@USM_TRAITS@@@@SAJPEAU_ST_DATA_MGR@1@PEAU_STDM_SEARCH_RESULTS@1@KKKPEAT_SM_PAGE_KEY@@PEAK@Z") at demangle.c:114
#5  0x00007ffff77c445b in print_gvars (pdb=0x7ffffff9caf0, img_base=0, format=114) at pdb/pdb.c:1116
#6  0x00007ffff7b22103 in bin_pdb (core=0x7ffffff9cd00, mode=114) at cbin.c:1033
#7  0x00007ffff7b29cf9 in r_core_bin_info (core=0x7ffffff9cd00, action=8192, mode=1, va=1, filter=0x7ffffff9ccd0, chksum=0x0) at cbin.c:3039
#8  0x0000555555559f59 in main (argc=3, argv=0x7fffffffe5c8) at rabin2.c:1042
(gdb) frame 2
#2  0x00007ffff77b694a in parse_microsoft_mangled_name (sym=0x55555766eea1 "StDmRegionGetKeys@?$ST_STORE@USM_TRAITS@@@@SAJPEAU_ST_DATA_MGR@1@PEAU_STDM_SEARCH_RESULTS@1@KKKPEAT_SM_PAGE_KEY@@PEAK@Z",
    demangled_name=0x7ffffff9c9e8) at mangling/microsoft_demangle.c:1407
1407            *demangled_name = strdup (func_str.type_str);
(gdb) L
1402                    copy_string (&func_str, " ", 0);
1403                    copy_string (&func_str, __64ptr, 0);
1404            }
1405
1406            // need to be free by user
1407            *demangled_name = strdup (func_str.type_str);
1408
1409    parse_microsoft_mangled_name_err:
1410            R_FREE (ret_type);
1411            free_type_code_str_struct (&type_code_str);
(gdb) print func_str
$1 = {type_str = 0x0, type_str_len = -2107568035, curr_pos = 263}
(gdb) print func_str.type_str

```

**Comment by XVilka** [comment]
@xarkes can you please have a look?

**Comment by radare** [comment]
can you share the bin?

**Comment by radare** [comment]
pls confirm

**Comment by K2** [comment]
confirmed no crashes
