### ISSUE TITLE
 SIGSEGV in check_bytes aka "radare2 meme" (https://twitter.com/radareorg/status/902092932064448517)

### ISSUE THREAD

**Issue by ret5et** [radare/radare2#8366]
```
:radare2$ LD_LIBRARY_PATH=./lib/ gdb bin/radare2  
(gdb) r
Starting program: /home/thistle/bin/prefix/radare2/bin/radare2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Usage: r2 [-ACdfLMnNqStuvwzX] [-P patch] [-p prj] [-a arch] [-b bits] [-i file]
          [-s addr] [-B baddr] [-M maddr] [-c cmd] [-e k=v] file|pid|-|--|=
[Inferior 1 (process 15807) exited normally]
(gdb) r gdb://192.168.56.101:9090
Starting program: /home/thistle/bin/prefix/radare2/bin/radare2 gdb://192.168.56.101:9090
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
= attach 14539 0

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6eb5257 in check_bytes (buf=0x5555558cbb80 "", length=18446744073709551615) at /home/thistle/src/radare2/libr/..//libr/bin/p/bin_bios.c:17
17			if ((buf[ep] == 0xea) || (buf[ep] == 0xe9)) {
(gdb) bt
#0  0x00007ffff6eb5257 in check_bytes (buf=0x5555558cbb80 "", length=18446744073709551615) at /home/thistle/src/radare2/libr/..//libr/bin/p/bin_bios.c:17
#1  0x00007ffff6e9d499 in r_bin_get_binplugin_by_bytes (bin=0x55555582b5b0, bytes=0x5555558cbb80 "", sz=18446744073709551615) at bin.c:1269
#2  0x00007ffff6e9e037 in r_bin_file_new_from_bytes (bin=0x55555582b5b0, file=0x5555558cba30 "", bytes=0x5555558cbb80 "", sz=18446744073709551615, file_sz=18446744073709551615, rawstr=0, 
    baseaddr=18446744073709551615, loadaddr=0, fd=3, pluginname=0x0, xtrname=0x0, offset=0, steal_ptr=true) at bin.c:1539
#3  0x00007ffff6e9cdf6 in r_bin_load_io_at_offset_as_sz (bin=0x55555582b5b0, fd=3, baseaddr=18446744073709551615, loadaddr=0, xtr_idx=0, offset=0, name=0x0, sz=18446744073709551615) at bin.c:1100
#4  0x00007ffff6e9ce72 in r_bin_load_io_at_offset_as (bin=0x55555582b5b0, fd=3, baseaddr=18446744073709551615, loadaddr=18446744073709551615, xtr_idx=0, offset=0, name=0x0) at bin.c:1114
#5  0x00007ffff6e9c965 in r_bin_load_io (bin=0x55555582b5b0, fd=3, baseaddr=18446744073709551615, loadaddr=18446744073709551615, xtr_idx=0) at bin.c:1007
#6  0x00007ffff6e9c42e in r_bin_load (bin=0x55555582b5b0, file=0x5555558cba30 "", baseaddr=18446744073709551615, loadaddr=18446744073709551615, xtr_idx=0, fd=3, rawstr=0) at bin.c:898
#7  0x00007ffff7afe30a in r_core_file_do_load_for_debug (r=0x55555575d520 <r>, baseaddr=18446744073709551615, filenameuri=0x5555558cba30 "") at file.c:352
#8  0x00007ffff7afeda4 in r_core_bin_load (r=0x55555575d520 <r>, filenameuri=0x5555558cba30 "", baddr=18446744073709551615) at file.c:562
#9  0x00005555555598b7 in main (argc=2, argv=0x7fffffffe068, envp=0x7fffffffe080) at radare2.c:965
(gdb) quit
A debugging session is active.

	Inferior 1 [process 15920] will be killed.

Quit anyway? (y or n) y

```
Version
```
 LD_LIBRARY_PATH=./lib/ radare2 -v
radare2 1.7.0-git 15891 @ linux-x86-64 git.1.6.0-618-g17995ab46
commit: 17995ab4620292fd12ab01d83843a64d47db8d8e build: 2017-08-28__18:27:12
thistle@desertwitch:radare2$ LD_LIBRARY_PATH=./lib/ radare2 -V
1.6.0-618-g17995ab46  r2
1.6.0-618-g17995ab46  r_anal
1.6.0-618-g17995ab46  r_lib
1.6.0-618-g17995ab46  r_egg
1.6.0-618-g17995ab46  r_asm
1.6.0-618-g17995ab46  r_bin
1.6.0-618-g17995ab46  r_cons
1.6.0-618-g17995ab46  r_flag
1.6.0-618-g17995ab46  r_core
1.6.0-618-g17995ab46  r_crypto
1.6.0-618-g17995ab46  r_bp
1.6.0-618-g17995ab46  r_debug
1.6.0-618-g17995ab46  r_hash
1.6.0-618-g17995ab46  r_fs
1.6.0-618-g17995ab46  r_io
1.6.0-618-g17995ab46  r_magic
1.6.0-618-g17995ab46  r_parse
1.6.0-618-g17995ab46  r_reg
1.6.0-618-g17995ab46  r_sign
1.6.0-618-g17995ab46  r_search
1.6.0-618-g17995ab46  r_syscall
1.6.0-618-g17995ab46  r_util
```

**Comment by ret5et** [comment]
fixed (#d4c258a )
