### ISSUE TITLE
Invalid write in r_read_le16()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#8685]
**Invalid write in r_read_le16()**

Git HEAD: d0b1e63e33b363c03fcfc8a780890ebf475ae91b

Faulting file in https://github.com/radare/radare2-regressions/pull/1056

Command: `r2 -A r2_iw_r_read_le16`

ASAN:

```
==3764==ERROR: AddressSanitizer: SEGV on unknown address 0x7f588beec830 (pc 0x7f59464ec419 bp 0x7ffdf4d82140 sp 0x7ffdf4d81b60 T0)
==3764==The signal is caused by a WRITE memory access.
    #0 0x7f59464ec418 in r_read_le16 XYZ/radare2/libr/include/r_endian.h:143:29
    #1 0x7f59464ec418 in r_read_ble16 XYZ/radare2/libr/include/r_endian.h:317
    #2 0x7f59464ec418 in store_versioninfo_gnu_verdef XYZ/radare2/libr/..//libr/bin/p/../format/elf/elf.c:744
    #3 0x7f59464ec418 in store_versioninfo XYZ/radare2/libr/..//libr/bin/p/../format/elf/elf.c:983
    #4 0x7f59464ec418 in elf_init XYZ/radare2/libr/..//libr/bin/p/../format/elf/elf.c:1084
    #5 0x7f59464f5a18 in Elf32_r_bin_elf_new_buf XYZ/radare2/libr/..//libr/bin/p/../format/elf/elf.c:3065:7
    #6 0x7f59464bbfa6 in load_bytes XYZ/radare2/libr/..//libr/bin/p/bin_elf.c:53:8
    #7 0x7f59463fab3d in r_bin_object_new XYZ/radare2/libr/bin/bin.c:1321:16
    #8 0x7f59463f83d3 in r_bin_file_new_from_bytes XYZ/radare2/libr/bin/bin.c:1548:6
    #9 0x7f59463f83d3 in r_bin_load_io_at_offset_as_sz XYZ/radare2/libr/bin/bin.c:1099
    #10 0x7f59463f5819 in r_bin_load_io_at_offset_as XYZ/radare2/libr/bin/bin.c:1113:12
    #11 0x7f59463f5819 in r_bin_load_io XYZ/radare2/libr/bin/bin.c:1006
    #12 0x7f594777b5e0 in r_core_file_do_load_for_io_plugin XYZ/radare2/libr/core/file.c:406:7
    #13 0x7f594777b5e0 in r_core_bin_load XYZ/radare2/libr/core/file.c:563
    #14 0x556985267f9a in main XYZ/radare2/binr/radare2/radare2.c:995:15
    #15 0x7f593fdb282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #16 0x55698516a1a8 in _start (/usr/local/bin/radare2+0x221a8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV XYZ/radare2/libr/include/r_endian.h:143:29 in r_read_le16
==3764==ABORTING
```

**Comment by radare** [comment]
Fixed in fd947ec9316bc3a72502afb7ee24812cbd275cde
