### ISSUE TITLE
Starting rap server from command line causes crash

### ISSUE THREAD

**Issue by rot256** [radare/radare2#9015]
When attempting to start a rap server in the background I experience a segfault.

How to reproduce, run: r2 "-qc=&:7777" -

This causes a segfault. GDB backtrace:

```
#0  0x00007f1978db0d0b in r_cmd_alias_get (cmd=0x0, k=0x7f196c0018d0 "o rap://", remote=1) at cmd_api.c:138
#1  0x00007f1978db0f8f in r_cmd_call (cmd=0x0, input=0x7f196c0018d0 "o rap://") at cmd_api.c:209
#2  0x00007f1978d6fd6a in r_core_cmd_subst_i (core=0x556a3fe38780 <r>, cmd=0x7f196c0018d0 "o rap://", colon=0x0) at cmd.c:2458
#3  0x00007f1978d6d3ba in r_core_cmd_subst (core=0x556a3fe38780 <r>, cmd=0x7f196c0018d0 "o rap://") at cmd.c:1610
#4  0x00007f1978d71ec3 in r_core_cmd (core=0x556a3fe38780 <r>, cstr=0x7f1973e71e10 "o rap://", log=0) at cmd.c:3090
#5  0x00007f1978d725cc in r_core_cmdf (user=0x556a3fe38780 <r>, fmt=0x7f1978e265bc "o rap://%s") at cmd.c:3251
#6  0x00007f1978dafa24 in r_core_rtr_rap_run (core=0x556a3fe38780 <r>, input=0x556a40890e42 "") at rtr.c:1658
#7  0x00007f1978dafa80 in r_core_rtr_rap_thread (th=0x556a40890f30) at rtr.c:1669
#8  0x00007f1974ba3704 in _r_th_launcher (_th=0x556a40890f30) at thread.c:29
#9  0x00007f197492e064 in start_thread (arg=0x7f1973e73700) at pthread_create.c:309
#10 0x00007f197446062d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

I have tested against newest release radare2-2.1.0 and current git version.

**Comment by Maijin** [comment]
No need to mention the release.

**Comment by radare** [comment]
thanks for pointing out, it should be good now. that was tricky
