### ISSUE TITLE
Infinite loop on 'CATCH' sigint after using 'dmh' command

### ISSUE THREAD

**Issue by 0x3f97** [radare/radare2#9318]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04 64bit
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0 17188 @ linux-x86-64 git.2.2.0-379-gfe194d2    commit: fe194d205ae2c396e8d31660f5e68707bb5477bd build: 2018-02-04__23:13:01

When I run `sudo r2 -d [pid]`, enter visual mode, `:dm` command is normal,

```
...
0x088b0000 # 0x088d1000 - usr   132K s -rw- [heap] [heap] ; map.heap_._rw
...
```
but when I execute `:dmh` command, radare2 goes in an infinite loop with 'CATCH' output

**Comment by radare** [comment]
can you ^C within gdb and paste the backtrace here? you can probably see why and wher eis hanging and fix it directly in a PR

**Comment by 0x3f97** [comment]
I don't know if my approach is correct, I use gdb to attach radare2 when radare2 infinite loop output 'CATCH'.

```
Stopped reason: SIGINT
0x00007fae1ff28ced in _IO_vfprintf_internal (s=s@entry=0x7ffc5c9e1090, format=<optimized out>, format@entry=0x7fae234b1864 "0x%08llx", 
    ap=ap@entry=0x7ffc5c9e11f8) at vfprintf.c:1631
1631	vfprintf.c: No such file or directory.
gdb-peda$ bt
#0  0x00007fae1ff28ced in _IO_vfprintf_internal (s=s@entry=0x7ffc5c9e1090, format=<optimized out>, format@entry=0x7fae234b1864 "0x%08llx", 
    ap=ap@entry=0x7ffc5c9e11f8) at vfprintf.c:1631
#1  0x00007fae1ff51a49 in _IO_vsnprintf (string=0x7ffc5c9e13f0 "0xf7f8d5a0", maxlen=<optimized out>, format=0x7fae234b1864 "0x%08llx", 
    args=args@entry=0x7ffc5c9e11f8) at vsnprintf.c:114
#2  0x00007fae1ff30932 in __snprintf (s=<optimized out>, maxlen=<optimized out>, format=<optimized out>) at snprintf.c:33
#3  0x00007fae2349e842 in r_debug_reg_list (dbg=0x55c149a1ede0, type=0x0, size=0x20, rad=0x2a, use_color=0x7fae23c4cc26 "\033[36m")
    at dreg.c:159
#4  0x00007fae24331468 in cmd_debug_reg (core=0x55c149361540 <r>, str=0x55c149bf7c52 "*") at cmd_debug.c:2476
#5  0x00007fae24338866 in cmd_debug (data=0x55c149361540 <r>, input=0x55c149bf7c51 "r*") at cmd_debug.c:4332
#6  0x00007fae243eb33a in r_cmd_call (cmd=0x55c1499eea80, input=0x55c149bf7c50 "dr*") at cmd_api.c:233
#7  0x00007fae243a4766 in r_core_cmd_subst_i (core=0x55c149361540 <r>, cmd=0x55c149bf7c50 "dr*", colon=0x0) at cmd.c:2493
#8  0x00007fae243a1883 in r_core_cmd_subst (core=0x55c149361540 <r>, cmd=0x55c149bf7c50 "dr*") at cmd.c:1620
#9  0x00007fae243a6ca4 in r_core_cmd (core=0x55c149361540 <r>, cstr=0x55c149b9f120 "dr*", log=0x0) at cmd.c:3142
#10 0x00007fae243a78d7 in r_core_cmd_str (core=0x55c149361540 <r>, cmd=0x55c149b9f120 "dr*") at cmd.c:3394
#11 0x00007fae2439f728 in cmd_interpret (data=0x55c149361540 <r>, input=0x55c149b628c1 "dr*") at cmd.c:838
#12 0x00007fae243eb33a in r_cmd_call (cmd=0x55c1499eea80, input=0x55c149b628c0 ".dr*") at cmd_api.c:233
#13 0x00007fae243a4766 in r_core_cmd_subst_i (core=0x55c149361540 <r>, cmd=0x55c149b628c0 ".dr*", colon=0x0) at cmd.c:2493
#14 0x00007fae243a1883 in r_core_cmd_subst (core=0x55c149361540 <r>, cmd=0x55c149b628c0 ".dr*") at cmd.c:1620
#15 0x00007fae243a6ca4 in r_core_cmd (core=0x55c149361540 <r>, cstr=0x55c149a75c40 ".dr*", log=0x0) at cmd.c:3142
#16 0x00007fae24319aa9 in set_prompt (r=0x55c149361540 <r>) at core.c:2001
#17 0x00007fae24319e63 in r_core_prompt (r=0x55c149361540 <r>, sync=0x0) at core.c:2059
#18 0x000055c14915e1c7 in main (argc=0x3, argv=0x7ffc5c9e48e8, envp=0x7ffc5c9e4908) at radare2.c:1322
#19 0x00007fae1fefb830 in __libc_start_main (main=0x55c14915adb6 <main>, argc=0x3, argv=0x7ffc5c9e48e8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc5c9e48d8) at ../csu/libc-start.c:291
#20 0x000055c14915a0f9 in _start ()
```

**Comment by zadlg** [comment]
I'm not able to reproduce the issue. Does this bug occur with any binary ?

**Comment by Maijin** [comment]
Probably not, as written in the issue template, please provide the binary.

**Comment by 0x3f97** [comment]
I test again with this simple program on ubuntu 16.04 64bit:
```c
#include <stdlib.h>

void main() {

    malloc(0x100);

}
```
r2 -v:
radare2 2.4.0-git 17324 @ linux-x86-64 git.2.2.0-512-g2232190
commit: 223219039f0ccab73c8a53b345d3d9b132b74f43 build: 2018-02-20__13:16:42

r2 -V:
https://pastebin.com/XkrbuJZe

after malloc, use dmh command and radare2 goes in infinite loop...

**Comment by zadlg** [comment]
Okay, I can reproduce the bug too.
I'm on it

**Comment by zadlg** [comment]
I can't reproduce the bug now, however I have the same behavior by hinting CTRL-C during fgets (or scanf or whatever similar), after doing aaaa.
