### ISSUE TITLE
Heap out of bounds read in avr_op_analyze()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#9901]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04 x64
| File format of the file you reverse (mandatory)      | Generic
| Architecture/bits of the file (mandatory)            | AVR
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 17928 @ linux-x86-64 git.2.5.0-73-g8f209fa commit: 8f209fade29b3c5c1f4eae931c0bd04c237a669c build: 2018-04-16__13:52:25

### Expected behavior

Display dissaslembly of file or error message.

### Actual behavior

Heap out of bounds read in ASAN build.

### Steps to reproduce the behavior 
- Download: https://github.com/radare/radare2-regressions/pull/1271
- Run `r2 -A r2_hoobr_avr_op_analyze`

### Additional Logs, screenshots, source-code,  configuration dump, ...

ASAN log:

```
==13011==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x611000004881 at pc 0x7f1abdacdcf1 bp 0x7fff388e9f70 sp 0x7fff388e9f60
READ of size 1 at 0x611000004881 thread T0
    #0 0x7f1abdacdcf0 in avr_op_analyze XYZ/radare2/libr/..//libr/anal/p/anal_avr.c:1529
    #1 0x7f1abdace804 in _inst__sbrx XYZ/radare2/libr/..//libr/anal/p/anal_avr.c:1294
    #2 0x7f1abdacd734 in avr_op_analyze XYZ/radare2/libr/..//libr/anal/p/anal_avr.c:1558
    #3 0x7f1abdad943b in avr_op XYZ/radare2/libr/..//libr/anal/p/anal_avr.c:1636
    #4 0x7f1abdd0a634 in r_anal_op XYZ/radare2/libr/anal/op.c:104
    #5 0x7f1ac04c4ba1 in r_core_anal_search_xrefs XYZ/radare2/libr/core/canal.c:2825
    #6 0x7f1ac0220bd4 in r_core_anal_refs XYZ/radare2/libr/core/cmd_anal.c:5938
    #7 0x7f1ac0301733 in cmd_anal_all XYZ/radare2/libr/core/cmd_anal.c:6323
    #8 0x7f1ac0301733 in cmd_anal XYZ/radare2/libr/core/cmd_anal.c:6667
    #9 0x7f1ac048fa3a in r_cmd_call XYZ/radare2/libr/core/cmd_api.c:233
    #10 0x7f1ac037e180 in r_core_cmd_subst_i XYZ/radare2/libr/core/cmd.c:2686
    #11 0x7f1ac0244c7c in r_core_cmd_subst XYZ/radare2/libr/core/cmd.c:1733
    #12 0x7f1ac02467c3 in r_core_cmd XYZ/radare2/libr/core/cmd.c:3368
    #13 0x5603c9276e9e in main XYZ/radare2/binr/radare2/radare2.c:1286
    #14 0x7f1ab9b8782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #15 0x5603c927ba48 in _start (/usr/local/bin/radare2+0x10a48)

0x611000004881 is located 1 bytes to the right of 256-byte region [0x611000004780,0x611000004880)
allocated by thread T0 here:
    #0 0x7f1ac0a0a602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f1ac04c44d9 in r_core_anal_search_xrefs XYZ/radare2/libr/core/canal.c:2788

SUMMARY: AddressSanitizer: heap-buffer-overflow XYZ/radare2/libr/..//libr/anal/p/anal_avr.c:1529 avr_op_analyze
Shadow bytes around the buggy address:
  0x0c227fff88c0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c227fff88d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fff88e0: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
  0x0c227fff88f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fff8900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c227fff8910:[fa]fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c227fff8920: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fff8930: 00 00 00 00 00 00 fa fa fa fa fa fa fa fa fa fa
  0x0c227fff8940: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c227fff8950: fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa fa
  0x0c227fff8960: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==13011==ABORTING
```

**Comment by radare** [comment]
Fixed in b35530fa0681b27eba084de5527037ebfb397422 and 25a3703ef2e015bbe1d1f16f6b2f63bb10dd34f4
