### ISSUE TITLE
Heap out of bounds read in get_debug_info()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#9926]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04 x86/64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64 
| r2 -v full output, **not truncated** (mandatory)     |radare2 2.6.0-git 17962 @ linux-x86-64 git.2.5.0-91-g880dfca commit: 880dfca21755b0068fd0c3007c4d2637a0aff8a3 build: 2018-04-19__10:19:56

### Expected behavior

Display dissaslembly of file or error message.

### Actual behavior

Heap out of bounds read in ASAN build.

### Steps to reproduce the behavior 

- Download: https://github.com/radare/radare2-regressions/pull/1280
- Run `r2 -A r2_hoobr_get_debug_info`

### Additional Logs, screenshots, source-code,  configuration dump, ...

ASAN log:

```
==20808==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000027e10 at pc 0x7ff6b2a41756 bp 0x7ffcdfded500 sp 0x7ffcdfded4f0
READ of size 16 at 0x602000027e10 thread T0
    #0 0x7ff6b2a41755 in get_debug_info XYZ/radare2/libr/..//libr/bin/p/../format/pe/pe.c:2752
    #1 0x7ff6b2a41755 in Pe32_r_bin_pe_get_debug_data XYZ/radare2/libr/..//libr/bin/p/../format/pe/pe.c:2832
    #2 0x7ff6b2a23fe7 in info XYZ/radare2/libr/..//libr/bin/p/bin_pe.c:543
    #3 0x7ff6b278de91 in r_bin_object_set_items XYZ/radare2/libr/bin/obj.c:182
    #4 0x7ff6b279032e in r_bin_object_new XYZ/radare2/libr/bin/obj.c:94
    #5 0x7ff6b2787ff0 in r_bin_file_new_from_bytes XYZ/radare2/libr/bin/file.c:495
    #6 0x7ff6b275879d in r_bin_load_io_at_offset_as_sz XYZ/radare2/libr/bin/bin.c:486
    #7 0x7ff6b2758c31 in r_bin_load_io_at_offset_as XYZ/radare2/libr/bin/bin.c:503
    #8 0x7ff6b27596a5 in r_bin_load_io XYZ/radare2/libr/bin/bin.c:361
    #9 0x7ff6b3b9a8be in r_core_file_do_load_for_io_plugin XYZ/radare2/libr/core/file.c:410
    #10 0x7ff6b3b9a8be in r_core_bin_load XYZ/radare2/libr/core/file.c:567
    #11 0x555e2f472a90 in main XYZ/radare2/binr/radare2/radare2.c:1064
    #12 0x7ff6ad39082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x555e2f478788 in _start (XYZ/radare2/binr/radare2/radare2+0x10788)

0x602000027e15 is located 0 bytes to the right of 5-byte region [0x602000027e10,0x602000027e15)
allocated by thread T0 here:
    #0 0x7ff6b421579a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7ff6b2a40cec in Pe32_r_bin_pe_get_debug_data XYZ/radare2/libr/..//libr/bin/p/../format/pe/pe.c:2829
    #2 0x7ff6b2bf6ee7  (/usr/local/lib/libr_bin.so+0x539ee7)

SUMMARY: AddressSanitizer: heap-buffer-overflow XYZ/radare2/libr/..//libr/bin/p/../format/pe/pe.c:2752 get_debug_info
Shadow bytes around the buggy address:
  0x0c047fffcf70: fa fa 04 fa fa fa 00 06 fa fa 06 fa fa fa 04 fa
  0x0c047fffcf80: fa fa 00 06 fa fa 06 fa fa fa 04 fa fa fa 00 06
  0x0c047fffcf90: fa fa 00 fa fa fa 04 fa fa fa 00 06 fa fa 05 fa
  0x0c047fffcfa0: fa fa 06 fa fa fa 00 06 fa fa 00 03 fa fa 03 fa
  0x0c047fffcfb0: fa fa 06 fa fa fa 00 03 fa fa 04 fa fa fa 00 02
=>0x0c047fffcfc0: fa fa[05]fa fa fa 06 fa fa fa 00 03 fa fa fa fa
  0x0c047fffcfd0: fa fa fa fa fa fa 03 fa fa fa 00 03 fa fa fa fa
  0x0c047fffcfe0: fa fa 04 fa fa fa 00 03 fa fa fa fa fa fa 04 fa
  0x0c047fffcff0: fa fa 00 03 fa fa fa fa fa fa 03 fa fa fa 00 03
  0x0c047fffd000: fa fa fa fa fa fa 03 fa fa fa 03 fa fa fa fa fa
  0x0c047fffd010: fa fa 06 fa fa fa 00 03 fa fa fa fa fa fa 05 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==20808==ABORTING
```

**Comment by radare** [comment]
fixed

**Comment by attritionorg** [comment]
Can you link to the fixing commit please?

**Comment by radare** [comment]
4e1cf0d3e6f6fe2552a269def0af1cd2403e266c
https://github.com/radare/radare2/commit/4e1cf0d3e6f6fe2552a269def0af1cd2403e266c

**Comment by attritionorg** [comment]
Thanks!
